>gnl|BL_ORD_ID|1598 @Brassica_rapa@_022170|PACid:22685108
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------GED
GRQEVYSVGLQEYEVSDVQIVRRKNDDANELPGKV--VGKSTFIDLAGSEIGADTTDNDR
QTSFGSLNAEYECKLGIFLTILVNCAYLARICFRACMEEKKLADDRVIDDQVEKIELVVS
DVDARDTED---EEAIDSS---KPESLQAD----DLP---SEEVKDPKEI----------
----------IGESHG------------EANLQHITTGEAVPGFGTSRMNG-DEGEAGAE
------------------------------NVHETATHS---------------------
-FSENGTVSL-EKKQPVADVIG------ETRNGGIEEEIKEEIVDVSGA----QRNGER-
--------ASGERSFNDSIQVASAGT----SSPLEKSSSEENGETEGHISREHDTVQNGG
LGVEHTSQPNKEFEKQRGSRVNMSPEIK-----ERKSEVASSVSPTES------------
-TSNIAASPPPARPA-GHGRDASLLEPTPRVPHQPR-VNGNASQNQSE------------
------------------------------QA-EDPTPAETDEHDETREKLQLIRVKFLR
LSHRLGQTP-HNVV----------------------------------------------
----------VAQVLYRLGLAEQLRGRNGS-RVGAFSFDRASS-----------------
----------------------------------------MAEQL-------EAAGQDPL
DF---------------------------------------------------S-CTVMV
LGKSGVGKSATINSIFDE----VKIC-TD---------------------AFQM------
----GTKRVQEV--EGF-------------------------------------------
---V--QGIKVRV-IDT----PGL-LPSW-SD-QHKNE-KMLKSV---------------
-----------------KVFIKKNPPDIVLYLDRLDMQSRDS-----GD--TPL--LRTI
TDVFGPSIWFNAIVGLTHAASAP-----------------------------PDGPNGTA
SSYDMFVTQRS---------------HVIQQ-----------------------------
------------------------AIRQA--AGDMR-----LMNPV-------------S
LVENH-------------SACRTNRAGQRVLPNGQVWKPHLL------------------
LLSFASKILAEAN-----ALLKLQDN-NTPGRPF-VARSKAPPLPLLLSSFLQSRPQAKL
PEEQYGDEEDED-DLDESSGSDE----ESEYDQLPP-FKRLTKAEMARLSKSQKKQYLDE
MEYREKLFMKRQMKEERKRRKMMKKFAA--------------------EIKDMAEEH-SE
NVEEERSEPAS----------------------VPVPMPDLSLPASFDSDNPTHRYRSLD
SSNQWLVRPVLETQGWDHDVGYEGVNAERLFVVKEKIPISFSGQ----------------
-----------------VTKDK----KDANVQLEMAGSVKHGE--GRST-SL--------
---------------------------------------------------------VED
KLIANKRFRMVMC-GGAMTSRGDVAYGGSLEAQLRDKDYPLGR-FLSTLGLSVMDWH-GD
LAIGGNIQSQVPIGRSSNLIARANLNNRGAGQVSVRVNSSEQLQLAMVALVPLFKKL---
--F--SYYSPQQMQ----------------------------------------------
------------------------------------------------Y--
>gnl|BL_ORD_ID|25364 @Brassica_rapa@_006330|PACid:22708874
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------EEKKNADDRIINDNI--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------LIPPAAPVLGLGRGAPLLKPTPR-----RRVNGNVSQHPTT------------
----------------------------------------------TTAEIDETRVKFLR
LSHRLGQTPRNNVV----------------------------------------------
----------VAQFL----------SRGSS-RVGG----AAIS-----------------
----------------------------------------MAEQL-------EGQNH-PL
DF---------------------------------------------------S-CTIML
LGKSGVGKSATINSIFDDDHAVKKMCTTD---------------------AFQM------
----GTKRVQLV--EGF-------------------------------------------
---V--QGIKVRA-IDT----PGL-SPSW-FD-QHKNV-KTLKSI---------------
-----------------RAFIKKSPPDVVLYLDRLDTQTQSS-----IDEEMLL--LRTI
TQFLGPSIWFNAIVGLTHAASAP-----------------------------PD---GAA
SSYGMFVTQRC---------------LAIQQ-----------------------------
------------------------DIRRA--ARDLR-----LVSPV-------------S
LVENH-------------PACRTNRAGQRVLPNGQAWKPHLL------------------
LLSFASKILAQEN-----AYDRNYNSRPL------VVESTAQPLSLFLSSLLESH---QL
PPPFLSSLLESH--------------------ELPPRCKRLTEAEISRLSKSQKEQY--P
VEFQAEL----EMEEERR------------------------------------------
------------------------------------PHIDLSNPS---------------
----LLVTPVLVVPRWDHDIGYDGLSAKGTL-VKEKIHMSYSGK----------------
-----------------VTKNNLMKMKGADVQLEMASLVVHGEEGNRST-SVGFEMQKKT
WDELSCALRSDS---NFMKHKAAA-----------------GLAITLLGDSVSAGVKAER
KLVANKRFGIDVCGGGAMTCRGDAAYGGSLEAHL------LGSFFLSTLGLSVVDGH-RG
LAIGGNIQTQVHIGRSSDLTARANLDSSGAGQVSIRANIFELLEHAMAVLVPLFKKL---
----LSYYSPN-------------------------------------------------
---------------------------------------------------
