>gnl|BL_ORD_ID|26953 @Citrus_clementina@_0.9_001850m|PACid:19278112
-M----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------ENGVNKPVV
DAFVDEKVEEKVMVSSDEPKDVE--------DVFE-EAVDTPDHLNDEGT----------
KDESG----------DDASVGD---------------------------LGSVVVDGGSN
VGGEMDSFD---ETEGVPSEGGNDVVGEGEGKVGDLAGAESVIEVVLCWKRSSTQVTGEC
NVQPLPQPA---------SSAAKSTMPVNPPARPAGLGRAAPLLEPAPRVVQHPRVNGAI
SHTQTQPIEDPGNGEAEEYDETREKLQMIRVKFLRLAHRLGQTPHNVVVAQVLYRLGLAE
QLR-GRNGGRVGAFSFDRA--SAMAEQ---------------------------------
---------------------------------------------------------LEA
AGQEPLD-------------------FSCTIMVLGKTG---------VGKSATINS----
------------------------------------------------------------
---------------------------------------I------FD----------EV
KFGTDA-----FQMGTKKVQDVV-----GTV--QG--IKV--------------------
--RVIDTP---GLLPSWS-----------DQRQNEK-------------------ILHSV
KRFIKKTPPDIVLY--------------------------------LDRLD---------
---------MQNRDFSDMPLL-RTITD---------------------------------
-------------------IFGPSIWFNAIVVLTHAASAPP-------------------
-------------------------------DGPNGTASSYDMFVTQRSHVVQQ------
-----------------AIRQAAGDMRLMN-----PVSLVENHSACRTNRAGQRVLPNGQ
VWKPHLL--------------------------------------LLSFASKILAEANTL
LKLQDTPP-GKPFSARSRAPPLPFLLSSLLQ-----------------------------
------SRPQVKLPEEQFGDEDS-------------------------------------
-------LDDD---------------------LDDSSES---EDESEFDELPPFKRLTKA
QVAK---LTKAQKRAYFDELEYREKLFMKKQLKEEKKRR---------------------
-------------------------------------------KMMKK------------
---------MAAAAKDLPSDNSENVEEESGGAASVPVPMPDLALPASFDSDNPTHRYRYL
DSSNQWLVRPVLETHGWDHDVGYEGINAERLF----------------------------
--VVKNKIPISFSGQVTKDKKDANVQMEVVSSLKHGEGKATSLGFDMQTVGKDLAYTLRS
ETRFSNFRKNKAMAGLSVTHLGDSLSAGVKVEDK------LIVNKRFRV-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------VMTGGAMTSRSDVAYGGSLEAQLRDADYPL
GRSLTTLGLSVMDWHGDLAIGCNIQSQVPIGRSTNMIGRANLNNRGAG------------
------------------------------------------------------------
-----------------QVSIRVNSSEQLQLALIGLIPLLKKLLGY--SQQM--QL--GQ
