>gnl|BL_ORD_ID|3128 Cyanidioschyzon_merolae_cds_gnl|CMER|CMP284C similar to chloroplast outer membrane protein Toc34
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DSETPTKNEAEQRASPD
RTGQVTQRPVSLFRKNGTFAYPLEDSDVYEEQ----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------VLALEDVP---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------EPTAQAILRLALA
AERQG------------------------------VPRLRFLVVG---------------
---------------------------APGVGK---------------------------
-----SSLINTLLNENLCSVS---------------AWERGTK-NAQVCARQVD------
-----------------------SVVIEFIDTPG----IAPCRRSGLEASRRQV---QR-
-------LRKLLDARGA-------------------------------------------
-----------------------------------------------------------D
EHPYLRSFHAILYVMRLDDTRPDLVDYHNWKVLMEFFGAEVLRHMMVVFTHGQSLPPDSL
SYPEYVRGRR-------DYVYLLIERL---------------------------------
------TGPLKAVRFPVFVAENSSKCPVI-------------EETGERKLPDDTPWITQL
YDGIRRFVFPLEADLFGMETGPEDTQVLVYIYDKRRSRADERYPRSPLQALIRNPWFLRA
VQFCGAMLLRS-----YMIRQEHERFNPKPHHPEPIIRDANNAFAVASRRANDHRLFTPS
IDEDEESFFRMNGNDDFVSRLRNRPGEVDLDELDVERIESPDGRFVEYWYTEKD------
--------------------------------NPEMVRMYRLEIRDDPNEERESRQDRIP
ISKDQH------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>gnl|BL_ORD_ID|3286 Cyanidioschyzon_merolae_cds_gnl|CMER|CMQ137C similar to chloroplast outer membrane protein Toc34
M-----------------------------------------------------------
------------------------------------------------------------
-------------------------TESFTSPQTREQVRLDFAERVEPRGDDAAERRDVS
GRRTADSDKTTRGSRPSTGRTRSRRRQLFRRNLLPGVLSQSRKGTESEG-----------
------------HGAENAADGEFFISDERHLYNMGIHVKQELNLSRLAALVVT-------
---------------------------------------SPAPYSKDLKESGSSWQQGPS
PTLSDKPSLSEVCGEQPWGAIPDATEKALERLCLLWIARKTGASESSSNGLRAVLSDPNV
-------------------------------FLHIAGIDAPCSGDARN--LDSMRR----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-CIQLFLDSARNAGLDANALFEPEDVIEGKNLHLACKVLCAYAEKTDSEAFTACMKQVGL
QRRNYEEIIRGFGNDSRPGCATVNQLVDVVRAHSPFRDATILFAG---------------
---------------------------TIGAGK---------------------------
-----SATINRILGSPVARTNHTMALILSDDEILERDPEHGLE-VIEERSYEREREQRAH
PNRKTEFVPSPNENVLIYPVEKEGMSLRLIEIPSSEKYFYDEAGEDSKKWSRAGTC-ES-
-------VAAALRGLEIDIVCIIERLDSYR------------------------------
------------------------------------------------------------
----------------------SHCFRLVLEELKSLFDGGVWERCILVFTHGYALPPEGL
TFEEN-----------------LARRMHLAQEE---------------------------
---VHRVSGRRDIFIPVCVVENSESCPR--------------DSAGNLILPN--------
---------------------GISFLDRFVTIGENVFLRNRDRPRLKVRSLVPSHVRVRH
IGFILSSVLILQMLRNGPQDGRANPLARDKAFLPAF------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
