>gnl|BL_ORD_ID|516 @Cyanophora_paradoxa@_ConsensusfromContig10710-snap_masked-ConsensusfromContig10710-abinit-gene-0.1-mRNA-1:cds:3832/1722-1917:0:+
MPLRT-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------PRYLDPVESMWDRLCTSAKLERAEVLTV-----
----------------------------------LVIGRSGVGKTALVNTLFADEPSK--
-IKPTSPFEHKPSEGFARVRSAYH-GVSIQFVEETL------------------------
--------------------------------------------------------PMGE
PGDPQEEAMARRVQKLYRRAGAEGEIFLLVFVDRLDGARELNSALAVVTDTLGTAAWARS
MVV---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------LTHGQTLPPPD-----STFADFVKQRRETAT-------------------
-------LALRRAARNKQLSVNVVVVDNAREGLRSAEGHRVLPFG---------------
----------------------------------VPAWANIGPCVPALLEAAAESVANSM
PE----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------A
>gnl|BL_ORD_ID|6430 @Cyanophora_paradoxa@_ConsensusfromContig37641-snap_masked-ConsensusfromContig37641-abinit-gene-0.1-mRNA-1:cds:7602/5125-5160:0:+
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------RRVP
RTYLPSASRWERQLNERGSGTESTDGG---------------------------------
----------------------VAASSESLGAVHMQELWGTVVAVQANFYQPSLSGDSLA
APLE--------------------------------------------------------
------------------------------ILCTRRARLKKIDQSVMVGDRVRITGDRPR
PVEYVPVGGVMMPRATELDRPPVANAFQALVVISIADPPI---------------DPDQA
TRFIVACEAAGLRSDLVSEHVRTAWTVRIRDWGYEPLFV---------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------SAEKDSIERVVDFLREGAPPGAIT---------
----------------------------------VVVGPSGVGKSSILNRLVPD------
-------LNLRTGEVSGKLRRGRHTTRHVQLFELPG-------------GSSGLKAAPLL
ADTPGF------------------------------------------------NRPDVT
CAPEEVAAYFPEVARQFAVAGGR----------------------CAFSDCLH-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------RDEEGCVVRGDWERYPHYVSMLAEAEERAEQ-------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------GYGVLTGGQLRTRETAGATPKTERRRGVKAVAGKG
GRVTYEPKLDARKYRSESRKSATQRL----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------R
>gnl|BL_ORD_ID|5720 @Cyanophora_paradoxa@_ConsensusfromContig36989-maker-ConsensusfromContig36989-snap-gene-0.1-mRNA-1:cds:4839/4192-4222:0:+
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------NPEYDYLFKL-----------------------
----------------------------------LLIGDSGVGKSCLLLRFADDTYTESY
ISTIGVDFKIRTIELDGK-------TIKLQIWDTAGQERFRTITSSYYRGAHGIIIVYDV
TDQESF--------------------------------------------------NNVK
QWLQEIDRYACEGVSKLLVGNKSDLTTKKVVQYEVA---------KEFADSLG-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------IPFLETSAKNSTNVEAAFMTMAAEIKAMTKN-------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------DVTAGGDKKKGVELGKSKPVEKGGPLAVFCAYC
ILQDYALLSRDLRIRTWLHRVISI------------------------------------
------------------------------------------------------------
------------------------------IQSYIAKLPVKFRTSAKALMSSLLASSRPA
DWRHASIP----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------E
>atToc120_gi|332642323|gb|AEE75844.1| translocase of chloroplast 120 [Arabidopsis thaliana]
M--------------GDGAEIVTRLYGDEKKLAEDGRISELVGSDEVKDNEEEVFEEAIG
SQEGLKPESLKTDVLQEDFPLASNDEVCDLEETSRNERGVEN------------------
------------------------------------------------------------
------------------------------------------------------------
-------LKVNYSEIGESHGEVNEQCITTKEADSDLVTLKMNDYDHGEVADADISYGKMA
SSLDVVENSEKATSNLATEDVNLENGNTHSSSENGVVSPDENKELVAEVISVSACSVETG
SNGIDDEKWEEEIDVSAGMVTEQRNGK---------------------------------
----------------------TGAEFNSVKIVSGDKSLNDSIEVAAGTLSPLEKSSSEE
KGETESQNSNGGH-----------------------------------------------
------------------------------DIQSNKEIVKQQDSSVNIGPEIKESQHMER
ESEVLSSVSPTESRSDTAALPPARPAGLGRAAPLLEPAPRVTQQPRVN-GNVSHNQPQQA
EDSTTAETDEHDETREKLQFIRVKFLRLSHRLGQTPHNVVVAQVLYRLGLAEQLRGRNGS
RVG---------------------------------------------------------
------------------------------------------------------------
---------------------------AFSFDRASAMAEQLEAAAQDPLDFSCTI-----
----------------------------------MVLGKSGVGKSATINSIFDELKISTD
AFQVGTK-KVQDIEGFVQ-------GIKVRVIDTPG------------------------
-------------------------------------LLPSWSDQHKNEKILKSVRAFIK
KSPPDIVLYLDRLDMQSRDSGDM-------------------PLLRTITDVFGPSIWFNA
IVG---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------LTHAASAPPDGPNGTASSYDMFVTQRSHVIQ-------------------
-------QAIRQAAGDMRLMNPVSLVENHSACRTNRAGQRVLPNGQVWKPHLLLLSFASK
ILAEANALLKLQDNIPGGQFATRSK----------------APPLPLLLSSLLQSRPQAK
LPEQQYDDEDDEDDLDESSDSEEESEYDELPPFKRLTKAEMTKLSKSQKKEYLDEMEYRE
KLFMKRQMKEERKRRKLLKKFAAEIKDMPNGYSENVEEERSEPASVPVP-----MPDLSL
PASFDSDNPTHRYRYLDTSNQWLVRPVLETHGWDHDIGYEGVNAERLFVVKDKIPVSFSG
QVTKDKKDAHVQLELASSVKHGEGRSTSLGFDMQNAGKELAYTIRSETRFNKFRKNKAAA
GLSVTLL-----------------------------------------------------
------------------------------------------------------------
---------------------GDSVSAGLKVEDKLIANKRFRMVMSGGAMTSRGDVAYGG
TLEAQFRDKDYPLGRFLSTLGLSVMDWHGDLAIGGNIQSQVPIGRSSNLIARANLNNRGA
GQVSIRVNSSEQLQLAVVALVPLFKKLLTYYSPEQMQYGH
>gnl|BL_ORD_ID|26088 @Cyanophora_paradoxa@_ConsensusfromContig52771-maker-ConsensusfromContig52771-snap-gene-0.0-mRNA-1:cds:9969/25287-25526:2:-
MTLGTFNYAAEMPSDGRPLEIVVETLSVIDTTWNYTVIILPVGSPAVTYPPWTASQTAIA
DVLTYVTVNAAVPYFRVWFGTSASNEAYVQRSSNNTILWAHNGAIAQYDIVIPSANGFGE
RNLVFDFLTPQGKIPVLVKVKGLDAFACFPSSGRVAAGRQIFARVSGATGSERLVFSSDL
QTLSDSSVVTQANPVDTSPSGGVTDLTYTTSSGKDSLVVTYRLLPSVDFSATPLTVGTCS
YAVLAADVQCSPARIRKSFAASNTTCVITKPSGSGLADLQTSDFGAGDVVDASIGSLSAV
FLGSAAGATSFGPTWSPAQSQNLIPASRYAVDVLAVASVVYSKYRVALGQLIQVTVQSAA
GIAIHASDFAGDIDLAVASPTASADTVQFFVNQTKLISKPSPLAKLRWATEFGSSDIVAP
NGTVIAFGSGSYVQTADASVCCAATRFFSVLVNYLPDSTGAYPTFLASDLTSSVSGATTT
IAEERAPAASGNAYGVTFRVPVQAPLTYSLSWNPSTILASGVVYSFTPTIIMLQLTCPAN
AAKGTTPYVLYPDEGTFSPYTLVSPGVYSFTFTKTDLGTSASAIRIDFASSYLQTLSTSG
DRKVLAATYTTQFVSTVLSCPRTRLHALGGTATCYDKDTSSSGIPNTDVFNISSSDPSRV
SITAITLVNANRLSFQLTVAAEAPVGNVSISAHYQNLEAVNLQDAIVIGSPLTVTLLRGS
LACDRARIALGTSVDCQISTWPGSMALALSDFVAAATVPGGNQNINGSLGFTASPSTGNP
TTISASFFTGGPALTTTVPRPIVDGCTTTCTIPKASSPDLLVSDLALAAPSPAFGSVSGL
SASGGGALQFTYTALGAPTGVTLGFTYGTSIDPASSVSTSALQQAVFSLSSLGTLMCGVP
STKAFPYGSFKMLKGVSYTCSAPINGSATLTTADLTFPISTTGATATFSSLAADSSTGGL
SFSVEPTSAGSSSWAFELAACGTLETVSIDLIDKPVLSCPAVSAIGAKAPDAGIFTGYSL
KAANVYYFNFTNTNGTSATVYIDFAKSLINTTTTDVNGTATAASIRIGSASLSYVSASVS
CSRTTILAAARAACFLNKTASSAAFPSADVFSITSSNASRASIGAVSLVDGTNGAVATFD
VIAANNAPVSTITVSAQFANMGGYDLNSAAITGSPITISLTRPVVNGTLSCQRSRINAVG
GRSLCVINKTETSAKFPASSLFAVTSSATSSATIGPITIVDDGNAATFEVIGVSTGSASS
VTITAAFTDLEALVLQSAGISGSASITLLRATVACTPSRMVFGRNTTCTVSGTGLQSADL
ASASVGSAAATLAGLSFTLPPALGNSTVTVDFASGGTGPTTTVAAIQVQSLTCNKTRLQT
GCSTLCNLNPTGSPALLTTDATVSGNPTLSAVDGGLQFTYTGNRAVFFDHRAFSLELAAG
SLGGGDAGANLTFAYTASVDGTSVSTSSIYANIVTLSATLQCGLPLSSDFKLLRSNAYTP
SSPPPYTCVLSKAAGSGSLAVSDLTTLSATGAATTLSGVVVNGNG--------GLNFSAT
PTVGGTATWTLTLQTCSSPLITKTVDVIGPIQMSCHNVTAVGAKIRCTLNATEPSAAYGT
SLGAPYVESPEAGTFSALTSVGTANAAGIGEAHYFDFEATSLGTATVKLDFLQTVIQTIA
NNTASKLLVASSKITYIAATVSCAQTSVNASAGATVCFLNKTAASAAFPSTSFFMPIINH
PGRLTVGPVTITPGTNSTSAYFTLRAADYPNPVGTYSISVAYTGLSGVNLAPANVSGGPF
AIQFTRPSVGAAVNCVSTRVHLRGGSIRCYINATGTAFPSQATLSTNVLFTVSYNGGFSL
SSTMSAITYVSGSNWRAATFVLYGYGSGGVGGVVNVTVDYNAAVLGPGFFNDIDTTPIVN
SPLEISVLDAQFTCDGRRIALTKTLSCNITARESSPAILLSDLVPGSISALVPNISPEVK
SSTLIAALSKLSFDWTPTNAGGAGLTATSASMGDNGARTLQVSFVTGGVATASIFVLAAD
GSRFICPTRQTANCTQTCYIDQRYTDSYDGNVIKSRSVSLLPEDFVVAATHGTVSNIRVA
QVTNNHVTNSYSPSQYYALYFDYTGKFPLDLIPARDLESR
>gnl|BL_ORD_ID|15552 @Cyanophora_paradoxa@_ConsensusfromContig9504-snap_masked-ConsensusfromContig9504-abinit-gene-0.0-mRNA-1:cds:2478/440-548:0:+
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----VAMEAVQHVLSPVGESVQSSEAA---------------------------------
----------------------VERAYECPICHEVPDLLQPNAELRA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------AVARDCPNAYDERARANAS-------SV-----
----------------------------------LFVGSTGSGKSAAINYLCGERVCGTN
AFERETQ-----------------------------------------------------
------------------------------------------------------------
-------------------------------------------------DV---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------AWHARTLPAAGTEDGLDT--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------G
>gnl|BL_ORD_ID|22948 @Cyanophora_paradoxa@_ConsensusfromContig38007-snap_masked-ConsensusfromContig38007-abinit-gene-0.0-mRNA-1:cds:7925/1347-1474:1:-
MRAKL-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------EFEFDGRKDDFDSWY------------------
---------------------------------------SGAIATCAFIAFAGKEYRHAF
YIIGTAQ---RPLTQFSKLEFGIELEDELLLKDRPR------------------------
-----------------------------------------------------------A
CALAEELQLLFGLNQLRAKLEDAEWVMWTTRTYSAVTKEHLESALRDVDALLA-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------RCARASLPVPS-----SFFCDLVEVCAASGD-------------------
------------------------------------------------------------
-------------------WKRGQDYWARMPQRGVQRDGNALTYFELCFACLDEALAKFK
PKLVKAGLKLDEDGLDQLLKWDMYMNYE-LPSFKNPDVDEFSALSEDERREHEEFVS---
-----RLQLEEEEVRAPLTLMIKLMLMLMIMIKP--------------------------
------------------------------------------------------------
------------------------------MGMAMTSIKQMITIKRFSRFAVL-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------I
