>gnl|BL_ORD_ID|30484 @Glycine_max@_11g11250.1|PACid:16283464
MDYEADGFGANGEGESKRVVGGEGVSEESVAGSDQVKGLETEEVFQEAMEPREQVHDQGS
ELNLEDTVVDKQYDAETDAAQEPDYFKEAVLADADSGKLGGDDVISEQDLEERDGQGSDN
--------------V-HLDGVDSGVPVDGEIFDESHGVGDDNLESSDGGGGKEESGLNSD
REMLVQE---NGTMVDENSGL---VSERAEIDDSEFMTPRENG---DTELGDDKIEVKLN
ASADPSGEIQDDTSEEVHDNSAHMTLEHQDEVTRDMK------DDSLGTNMSHEDRNGEE
MSTDGIQNTEVRDY----GNGHAEAES---SPP--------FLENSSTNLTPSIQEASAA
EPKEASNKDDQSQIFDEEHRDHDNTSVVEEPESIQEKIIQQTGTTPSAAEPKEASNKDDQ
SQIFDEEHRDHDNTSVVEEPESIQEKIIQQTGTTPSAAEPKEASNKD-------------
----DQSQIFDEEHRDHDNTSVVEEPESIQEKTIQQTGTTPSAAEPKEAKIMTILLWLRS
LKAYRRRLFNRQEPLKSAGTVPTPVRPSSENS-------PAAGPTPVHPTGLGRAAPLLE
PASRVVQQPRANGAVSNTQSQQMEDSSSGEAEEYDETREKLQMIRVK-------------
------FLRLAHRLGQTPH------------NVVVAQVLYRLGLAEQLRGR------NGG
RVGAFSFDRASAMAEQLEAAGQEPL--DFSCTIMVLGKTGVGKSATINSIFD--------
EVKFNTSAFH--MGTKKVQDVVGT--VQGIKV--RVI--DTPG-LL-----------PSW
ADQRS-NEK-ILHSVKHFIKKTPPDIVLYLDRL-DMQSRDFSDMPL--------------
--------------------LRTITEIFGPSI-WFNAIVVLTHAASA-----------PP
EGPNGTASSYDWFVTQRSHVVQQAIRQAAGDMR-----LMN---------PVSLVENHSA
CRT--NRAGQRVLPNGQVWKPHLLLLSFASK-----------------------------
-----------ILAEANALLKLQDSP--PGKPYVARTRAPPLPFLLSTLLQSRPQLKLPE
EQF------------------------GDEDSLDD----DLGE--SSESDDENEHDDLPP
----------FKPLTKAQVE------------ELSKAHKKAYFDELEYREKLLMKKQLKE
EKKQRKMLKKRAESAKDLPSDHSENVEEESGGAASVPVPMPDLALPASFDSDNPTHRYRY
LDSSSNQWLVRPVLETHGWDHDVGYEGLNVERLFVVKEKIPLSFSGQVTKDKKDANVQME
ISSSVKHGKGKATSLGFDLQTVGKDLAYTLRSETRFTNFRRNNATAGLSFTLLGDALSSG
LKIE----------------------DKLVASKRFKLVVSGGAMTGRGDIAYGGSLEAQL
RDKDYPLGRFLTTLGLSVMDWHGDLAVGCNVQSQIPVGRHTNLVARANLNNRGAGQISIR
LNSSEQLQIALIGLIPLLKKLVGYH--QQ-TQFGQ-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------Y
