>gnl|BL_ORD_ID|24019 @Malus_domestica@_0000872008|PACid:22643995
------------------------------------------------------------
-ME---------------------------------------------------------
--------------------------NGDKIAGGSEVGENKGVDVKVVE-----------
-ERVVEGSNGLKDDAEDEVFEEAIETQENSQEQGSKVDLVDAVVVGEERETETVGGLGLA
SLIESPSVDTFEEAIEVPDEVGKSDDDD-------AEVKVENLVGGNSDDEVGVAGGIDD
EQTKKEAVTEETNGLTDDGLVGSQEDAVK-------------------------------
---EVTQVEAGGGISSLTGGDEA---DVKSVDLENVKFEKDNF------------ELNGL
A-DGLVGSQDVEVKEV-SEIITGAEIVGLTNVGEVDSKPNVVLENK--------------
------EPEKDDLDNSTSEPVSTDEKLDTEDLDSPQVTEFNKEILKEAGNGQELEENSLS
IENQDEKTVDLLSASDGVPLKLEDDNGVELLDRNMDTVHQEGDSAESN------------
---------------------------------DATLGIEEKQEY-NKTEELRDTLTFTD
AEHQGFSNGEVK-DSFTVLGSEHHEEKSEPKSISSDKQLSGEDSEE--------------
-MIVTSEREISALSERSAAEKTE---KIQDGATNLRAQSNKDDQPQRADEIAPEVRDNIA
VPEEPEKKENIQAEKGVTKVNKEQEIQPVSTLSSSGNST----QPSPPP-------ARP-
-------------------------------------AGLGRAAPLLEPAPRVVQHP---
-------RVNGTVS-HAQNQQIEDPVNGETEESDETR------------E---------K
---------------------LQMIRVKFLRLAHRLGQTPHNV---------VVAQVLY-
---RLGLAEQLR------------------------------------------------
------------------------------------------------------------
------------------------------------------------------GRNG--
GRVGAFSFDRASAMAEQLEASG-----------NEPLDFAC------TI-----------
------------------------------------------------------------
------------------------------------------MVLGKSGVGKSAT--INS
IFDEKRFTTDAFQMGTKKVQDVVGTV--QGIKVRVIDTPGLLPSWSDQ-RQNEKTLLNVK
------------------------------RFIKKTPPDIVLYLDRLDM-QSRDFSD--M
PLL--------RTITD---IFGPSI------WFNAIVVLTHAGSAPPEGPNGAASSYDM-
-------------------------------FV----TSRSHVVQQAI----RQAA----
--------------GDMRLMN-----PVSLVENHS-------------------ACRINR
AGQ-------RVLPNGQV----------------------------------------WK
--------PHL------LLLSFASKILA-EANALLKLQDSP-PGKPFATRTRAPPLP-FL
LSSLLQSRP---QLKLPEEQFGXDDSLDDDLDESSD------------------------
-------------------------------------------------S-----DDESE
FDELPPFRRLTKAQV------------EK-LSKAQKKAYF--------------DELEYR
EKLFMKK-------QLKEEKKRRKLMKKMAAASNELPSDYVENVEE--------------
---DSSGAASVPIPMPDLALPASFDSDNPTHRYRYLDSSNQWLVRPVLEQHGWD------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------HDVGYEGINAERLFVVKEKIPLSFSGQV
TKDKKDANVQMEIATSIKHGEG---------------------KATSLGFDMQ-------
---TVGKDLAYTLRSDTRISNFRKNKATAGLSVTLLGDAVSAGMKV-----EDK-----F
IAN---KRFQLVMTGGAMTA--RGDVAYG-GSLEA-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------QLRDKDHP---
----------------LGRSLSTLGLSVMDWHGDLAIGCNIQSQIPVGRHTNLIARANLN
NRGAGQLSLR---LNSSEQLQLALIGLVPLLRKLFTF--PQQLQYGQ-------------
------------------------------------------------------------
------------------------------------
>gnl|BL_ORD_ID|12853 @Malus_domestica@_0000744418|PACid:22632826
------------------------------------------------------------
-ME---------------------------------------------------------
--------------------------NGDKVAGGSEVGENKSVEVE--------------
---VVEGSNGLKDDAEDEVFEEAIETQENLQEQGSKNDLVDAAAVGEERKAEMVGGLGLD
SLIESPNVENFEEAIEFHDEVGKSDGDDGEEAIVAGEVKVENMVGKNSADEGGGPGGIDD
GQTIKEVVSEETNGLTDDELVGSQEDGVK-------------------------------
---EVTQVGAGGGIAGLTGGDEA---DVKSVVLENVKFEKVNF------------ESNGL
ADDGLVGSQDVEVKEV-SEIITGAEVAGLTDVDEVDSKPNAVLKNE--------------
------EPERNDIECSTSEPVPADEKLDTEDLDSPQVTEFTKEILKEAXNSQELEDNSLS
IENQDEKTVDLASASDGVPLKLQDDNXVELHDRNMDTVHQEGHSAESN------------
---------------------------------DATLSIEEKQEEDNKTEKPKDTLTVTD
AEHQGFSNGEVK-DSFTVPGSEHHEEKSEPKSVSSAKQLSGEGGEE--------------
-RIVTSEREISALSKTSATEKTE---KIQDGATNLRTESNKVXQPQRAGEIACEVRDNIA
-------KENIPGEKGITKVNKEQEIRPAPALSSSLNST----QRSPPP-------ARP-
-------------------------------------AGLGRAAPLLEPSPRVVQHP---
-------RVNGTIS-HVQNQQIEDPVNGEAEESDETR------------E---------K
---------------------LQMIRVKFLRLAHRLGQTXHNV---------VVAQVLY-
---RLGLAEQLR------------------------------------------------
------------------------------------------------------------
------------------------------------------------------GRNG--
GRVGAFSFDRASAMAEQLEASG-----------NEPLDFAC------TI-----------
------------------------------------------------------------
------------------------------------------MVLGKSGVGKSAT--INS
IFDEKKFTTDAFQMGTKKVQDVVGTV--QGIKVRVIDTPGLLPSWSDQ-GQNEKTLLNVK
------------------------------RFIKKTPPDIVLYFDRLDM-QSRDFSD--M
PLL--------RTITD---IFGASI------WFNAIVVLTHAGSAPPEGPNGAASSYDM-
-------------------------------FV----TSRSHVVQQAI----RQAA----
--------------GDMRLMN-----PVSLVENHS-------------------ACRTNR
AGQ-------RVLPNGQV----------------------------------------WK
--------PHL------LLLSFASKILA-EANALLKLQDSP-PGKPFATRTRAPPLP-FL
LSSLLQSRP---QLKLPEEQFGEDDSLDDDLDESSD------------------------
-------------------------------------------------S-----DDESE
FDELPPFRRLTKAQV------------EK-LSKAQKKAYF--------------DELEYR
EKLFMKK-------QLKEEKXRRKLMKKXAAAAKELPSDYVENVEE--------------
---ESSGAASVPIPMPDLALPASFDSDNPTHRYRYLDSSNQWLVRPVLEQHGWD------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------HDVGYEGINAERLFVVKEKIPLSFSGQV
TKDKKDANVQMEIATSIKHGEG---------------------KATSFGFDMQ-------
---TVGKDLAYTLRSDTRISNFRKNKATAGLSVTLLGDALSAGMKV-----EDK-----F
IAN---KRFQLVMTGGAMTA--RGDAAYG-GSLEA-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------QLRDKDHP---
----------------LGRSLSTLGLSVMDWHGDLAIGCNIQSQIPVGRHTNLIARANLN
NRGAGQLSLR---LNSSEQLQLALIGLVPLLRKFFTF--PQQLQYGQ-------------
------------------------------------------------------------
------------------------------------
