>gnl|BL_ORD_ID|54837 @Panucum_virgatum@_Pavirv00064825m|PACid:23811108
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------ENGGVVGWGRPEDR--------EGENGGVAE
AGESAV--------KRVAAEEEGGVD---VVVED--------G----DDAVAVEEADEDE
--AREENQGAGGDAVESGTPVAGDHQPVVTP-NTRVVLETGRHAAEKWGEDSPRAEINVE
GSVEENAMGQATRGYCHTKQDRPESVTRFAAEPAIIVEELDDLRSSDDENTATSAPPARS
RAASGRNNSPSLP-SRPAGLG---------------------------------------
----------------------------------SSSSLSQPP-ARPVQQARANGSVSSD
IGSQPSTE----------SAEDDGDENDEVHEKLQMIRVKFLRLAHRFGQTP--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------HNMVVSQVLYRLGLAEQL------------
----------------------------------------RR-----------TTAN--G
SLSFDRAREMA----ERLEAAGNEPL-------D------FSCTILVLGKTGV---G--K
SATINSIFD-----------DTSLDTNAF----DSSTRKVQE------------------
--------------------------VVGTV--EGITVR-VIDTP---GLSCSSLEQHHN
----------------QKVLNSVKRL-----------ISKNPPDIVLYFDRLDMQNRDNG
---------DIPLLQTITKVFGASVWFNAI-----V----VLTHAASA----------PP
DGLNGIPLS----------------YEMFVTQRS-HVVQQAIRQ----------------
-----------AAGDI--RLMN-----PVSLVENHAACRTNRAGQRVLPNGQVWKPQLLL
LCFASKVLAEANALLKLQDSPIGKL----SRTRIPPLPFLVSSLLQSRAPLKLPEEQFGD
DDDLE---DDSTDDSDSDDGSDYDDLPPFKRLTKAQLSKLNNAQRKAYLEELDYREKLFY
RKQLKEERMLRKLMKKMAAEASTRANDFYNSNPEDDSN-TPTNVAVPMPDMVLPSSFDSD
YPSHRYRFLDTPSEWLVRPVLETQGWDHDVGYEGLNVERLFVVKGKVPLSISGQLTKDKK
DCSMQMEVASSVKHAEGKTTSLGLDLQSAGKDMAYTIRGESRFKNFRRNSTAAGISATLL
GDSVSTGVKIEDKLIVNKQLRVLISGGAMSGRGEVAYGGR--------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------LE
ATLRDKDYPIGRMLSTLALSVVDWHGDLAI---------------------GCNVQSQIP
AGRASNLVGHANISNKGTGQVGIRLNSTEHIELALVALVP--------------------
------------------------------------------------------------
-------------------------------------------IFQNIRKLLQNYSEST-
--------
