>gnl|BL_ORD_ID|24605 @Phaseolus_vulgaris@_091015439m|PACid:23555468
M------------------------------------------------DYEAGGFGANG
EGESKRVGEGVSEESVVGSDSL------KSLDVEGDFQEAMEPREQAHDQGSELLSEEAV
VDKQDDANT---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------AGALTSALVDEKGPD--------VVQEHDSSEEADSEN
GKLGETDAIAYQDLERDGPGTHSVHLDGVASGVSGDGGFCDGSNGVVDDNLE----RSDG
GGGKEDSGLNSDVEVVVK----ENGVVEDENSGLMSE--KAEEVDDS-----------EF
MTPRQNGVRTLDDV-STDKEDDVDGVATEVIIKSESSEVIPAEGTD-AGDLKECDADPEL
GDDNIEVNLNASADSSGEIQDDTCEEVHGNSAHITLEQQDEVTRDV--KDVTLGTDISHE
DIIGEEMSTPGIQNAEVTSYENGDGEHENSSFLDNPSTKE--TL--PIQEASAADPKEGS
-NKDDQSQISDE---------N----QRD-----DDNSFVVEEPERTQEKIIQ-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------ETETT-----
-QETGEQPVQPSADISSSTENSSAAGPRPLLPSSENSTGPRPIL----------PSSENS
AAAGPTPVLPAGLGRAAPLLEPASRLVQQPRANGTVSNTQSQQMEDSSSGEAEEYD----
----ETREKLQMIRVKFLRLAHRLGQTP----------HNVVVAQVLYRLGLAEQLRGRN
G--GRVG-----AFSFDRASAMAEQLEAAGQEP-------LDFSCTIM------------
----------------------------------------------VLGKT---------
---------------G----VGKSATINS-------------------------------
------------------------------------------------------------
------------------------------------------------------IF----
------DEVKFNTSAFNMGTK-KVQDVVGT--VQGIKVR---------------------
---------------------------VIDT-----------------------------
-PGLLPSWS----------------DQRS-NE---------------------KILLS--
----------VKNFIKKTPPDIVLYLDRLDMQSRDFSDM-PLLRTITEI-----------
------------------------------------------------------------
----------------FGPSIWFNAIVVLTHAASAP------------------------
P-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
EGPNGTASSYDMF-------VTQRSHVVQQ------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------AIRQAAGDMR-----LMNP
VSL------VENHSACRINR-----------AG---------------------------
---------QRVLPNGQVWKPHLL---------LLSFASKILAEANALLKLQDSPP----
------------------------------------------------------------
----GKPYIA-R-RAPPLPFLLSTLLQSRPQLK----------------LPQEQF----G
DEDSLDDDLDEASESD-DENEHDDLPPFKPLTKAQ-------VEKLSKAHKKAYFDELEY
REKLLMKKQLKEEKKRRKFMKKMAEAAKDLPSDYSENVEEEGGGAASVPVPM--------
------------------------------------------------------------
---------------------------------------------------PDLALPASF
DSDNPTHRYRYLDSSNQ-------------------------------------------
------------WLVRPVLETHGWDHDVGYEGLNVERLFVVKDRVPLSFTGQVTKDKKDA
NVQMEIAGSVKHGEGKATSLGFDMQTVGKDLAYTLRSETRFT------------------
------------------------------------------------------------
------------------------------------------------------------
-NFRRNKATAGLSFTLLGDALSGGVKIEDK------------------------------
----------------LVASKRFRVVISGGAMAGRNDIAYGGSLEAQLRDKDYPLGRFLS
TLGLSVMDWHGDLAVGCNVQSQIPVGRHTNLVARANLNNRGAGQISIRLNSSEQLQIALV
ALIPLFKLNYGQVLVVNERTILYFICHQGRRQVSSTYAMGFVKHVDVRFQYSKRTSHRPN
EGDIVADDEISCGRSKPKSLGDDIPSNRLILKFQTLKLVLEFTSYF
