>gnl|BL_ORD_ID|6262 @Setaria_italica@_Si034092m|PACid:19679642
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------M---------
------------------------------------------------------------
--------------------------------------------------------ENGG
VVGGGR-------------------PEDRAGENGG-------------------------
-----------VPEAEESAVKTVAAEEEGGVDVVVEGGDDAVAAQDG-----DG------
------------------------DEVGEENRGPGGGAVESGAAGTPL--TGDHQPVVTP
NTRVVLETGQRAAE---KWDEASPRAEI----DIEESIA----SDVNQE-SADENAMGQA
IREYVTAAVLAD--RTKGKRLEKDMKSSAEP---------------AVV------VEELD
GLSSSD---------DENTATSAPP----AQSTSSSSTPAQSNSAV--------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------SGR
SNGPSL-PSRPAGLGSSSSLLQPPARPVQQVRFNGS---------------------AS-
----LATESAEDDGDGNDEI-------------------------------------HEK
LQMIRVKFLRLA------------------------------------------------
---------------------------------------------HRFGQTPHNMVVSQV
LYRL---------GLAEQLR-RTTAN--GSF--SFDRAREMAERLEA-------------
------------------------------------------------------------
-----------------------------------------------------AGNEPLD
------FSCTILVLGKTGV-----------------------------------------
-----------------------------------------------GKS---------A
TINSIFD----------------------------------DTRL---------------
-----------------------------DTNAFDFSTRKVQEVV---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------GTV--E
GIRVKVIDT----PG---------------------------------------------
------------------------------------------------------------
--------------------LSCSSLEQHHN----------------QKVLNSVKRLISK
NPPDIVLYFDRLDM-----------------------------------QSR--------
----DNGDVPLLQTITKVFGASV-------------------------------------
--------------------------------WFNAIVVLTHAASAPPDGLNGIPLSYEM
FVTQRSHVVQQAIRQAA-------GDIRLMNPVSLVENHA--------------------
---------------------------------------ACRTNRAGQRVLPNGQVWKPQ
LLLLCFASKVLA----------EANVLLKLQDSNPVGKL-SRTRIPPLPFLLS-------
SLLQSRAPLKLPEEQFGDDDDLEDDSADDCD---SDD-----------------------
----DSDYDDLPPFKRLTKAQLSKLN----------------------------------
---------------KAQQKAYLEELDYREKLFY--------------------------
--------------------------------------------------------RKQL
KEERMRRKLMKKMAAEASTRANDFNNSNSEDDPN-TPTNVAVPMPDMVLPSSFDSDN---
----------------------------------------------------------PS
HRYRFLDTPSEWLVRPVLETQGWDHDVG-------------------------------Y
EGLNVERLFAVKGKVPLSISGQ------LTKDKKDCSMQMEVASSVKHAEGKTTSL----
GLDLQSVGKDMAYTIRGESRFKNFRRNNTAAGISATLLGDSVSAGVK-------------
------------------------------------------------------------
--------------------------------------IEDKLIVNKQLRVLVGGGAMSG
RGDVAYGGRLEATLRDKDYPIGRMLSTLALSVVDWHGDLAIGCNIQSQIPAGRASNLVGH
ANLSNKGTGQVGIRLNSSEHLELALVALVPIFQNIRKLLQNYSEST---------
