>gnl|BL_ORD_ID|6113 @Selaginella_moellendorffii@_170624|PACid:15407391
M-----------------------------DYFPDK---------------KPED-----
------------------------------------------------------------
------------------------------------------------------------
DENEK-------------------------HEEVDYK-----------------------
----------------KP-EEAGNEKHGEADV--------IGSAAEAVRSQEEREPV-PE
TDSDEEEEEEVDTSAAL-----RAFAQAAAATETPSLGSAGPSLPAKPTATRLLSSIEGA
RNTQVAAHNPSGGSETTTAVEAADTNGEPNDENVETR---EKLQMIRVKFLRLAQRLGQS
ANNAVVAQVLYRLG----------------------------------------------
------------------------------------------------------------
LAEQLRGGRSSSRNSAFRFERASAIAEEQEAAGQ-EELDF--------------------
-----------------------------------------------------TCTIMVL
G------KSGVGKSATINSLF-DE-----------AKTETNAFAYSTK------------
------KVQEITGTVHGIK---------------------------------LRVIDTPG
LLPAVADQRHNEKIMA------------------------SVKRFIKKS-----------
--------------------------PPDIVLYFDRL-----------------------
---------------------DMQSRDYGDLPLLRT------------------------
-------------------ITDTFGAAIWFNAIVVLTHA--------------SSAPPDG
PNGLPLSYEMFVAQRSH--------VVQQTIRQAAGDMRLMN--PVSLVENHSACRT---
--NRSGERVL-PNGQVWKPQLLLLCFA-----------------SKILAEANSLLKLQES
TPGKPF-MRSK---------------------------------VPPLPFLLSSLLQSRP
PLKHSDENAVGEDD-----------------------TDDDIEDVEDSDEEDYDELPPF-
---------------------RRLTRDELDQLDKSSRDEYFEELQMREKLFQKKQWKEEI
------------------------------------------------------------
---RRRREMKKRAAS-SDSAEEYPAPVDDGYDDDNKSAPV-PVPLPDMQLPPTFDSDNPV
HRYRYLETASQWLVRPVMDLHGWDRDSGYDGFNMER-------MFTY-GKIPASLSGQVT
KDKKEANVTLECAASMKHGEGKVSQAGFDVQTVGKDFSYTLRSETRFSNFKKNKTIAGLA
MTMIGDTLAYGMKIEDRLMIGRRVKVVMNGGALTGKGDTAYGGTVEISLRDKDFPLGRSL
STCGLSVMNWHG-DMALGGNLQSQFMVGKTM-VVARGNLNNRGAGQITIRLSSSEQLQIA
LIGVMPLIKALFNSKFGTGQQA----
