>gnl|BL_ORD_ID|3984 @Thellungiella_halophila@_Thhalv10022323m|PACid:20183478
MGDGAEI-----------------------------------------------------
------------------------------------------------------------
---------------VNMSEGEEKKLPED-RISDEQVE-KNELVGSDEASDSDNEEEI--
------------------------------------------------------------
------------------------------------------------------------
-----------FEEAIGSQEAPKTEPFEVDGLHEDLRLEATPENFKDEHEVV--------
-------------------------------------------DDLEEVSSNESGVKDSK
TYHSIVGESHGE-----------------------------VNVQDITTGEAERDLVTPK
MND-DKGE-AGEEISHGQIDSSLDVVENSEKATCS-GSN--LAGEDVNMQNGNTHSFPEN
GI-------------ISVSALSEETRNDSIEDINWEEKADVSAGMETEEEIGGGEGTNKN
CSENGFVCINNVSGEQRNGETGAGYSS--VKMASGDKSLND-----SLEILNVGTSSPLE
KSSPEEKGEIEGHSS-------------------------SGFPGVTCREHETVQNSNVR
HDVQQSPQRNKDLEKQQGSRVNI------GPEITVSPHVEREFEVVSSDSRTES---VSS
LPPARPAGLGRAAPLLGP-TPRVTQQPRVNGNVSH----------DQHQQVE--------
DS-TAETDEHDETREKLQLIRVKFLRLAHRLGQTPHNVVVAQVLYRLGLAEQLRGRSGS-
RVGAFSFDRASAMAEQLEAAGQDP-----LDFSCT-------IMVL--------------
----------------------------------GKSGV---------------------
------------------------------------------------------------
-------------------------------GKSTTINSIFD-----------------E
VK----------------------------------------------------------
------------------------------------------------------------
----------------------MSTDAFQMGTKRVQN-------------VEGFVQGIKV
RVI----DTPGLL-PSWSDQHKNEKILRS--VRA----------------FIKKNPPDIV
LYL-----------------------DRLDTQSRDS------------------------
GDMPLL-RTIIDVFGPSIWFNAIVGLTHAASAPPDGPNGTASSYDMFVTQ----------
------------------------------------------------------------
-----RSHVIQQAIRQAAGDV-RL----------------------MNPVSLVEN-----
------------------HSACRTNRAGQRVL-----P---------NGQVWKPHLLLLS
FASKILAEANAL-LKSQDNTAGRP-FAARSKAPPLPFLLSSLLQSRPQAKLPEEQYGDGE
DED-GL---------------DESSDSDEE----SEYDQLPPFKRL--------------
------------------------------------------------------------
--------------TKAEMAKLSKSQKKQYLDEMDYREKLFMKKQMKEERKRRKMLKKFA
AEIKDLPN-GHSENVEEERSEPASVPVPMPDLSLPASFDSDNPTHRYRSLDSSNQWLVRA
VLETHGWDHDVGYEGVSAERLFVIKEKIPISFSGQVTKDKKDATVQLEMASSVKHGKGRS
T-SLGFDMQNVGKELAYTVRSDTRFKNFRNNKAAAGLSVTLLGDSVSAGLKVEDKLI---
------------------------------------------------------------
--ANKWFRMVMSGGAMTSRGDVAYGGSLEAQLRDKDYPLGQCLSTLGLSVMDWHGDLAIG
GNIQSQVPIGRSSNLIARANLNNRGAGQVSIRVNSSEQLQLAMVALVPLFKKLL------
-----------
>gnl|BL_ORD_ID|22651 @Thellungiella_halophila@_Thhalv10022525m|PACid:20202302
MGDGTDV-----------------------------------------------------
------------------------------------------------------------
---------------VVRSEGEEKKKLADDRISDEQVEKKNEFVRSDKA--KDNEDEI--
------------------------------------------------------------
------------------------------------------------------------
-----------FEEATG-------------------------------------------
--------------------------------------------DLDETSSNEGGVKDSK
VDYP-------------------------------------VNVQ----REAEPDFVTPK
MNG-DEEE-AGAENS--------NVVENSEKAADSNGSN--LVAEDVNMENGNTHSLSEN
GIVS-HENEELVADGISKSVAPEEMWNDGIEVENWEERADASPGIRTEPQVEGSGVTHEN
RPE-----------ANGNGETSADYTSNTVENASGEKSLNG-----GIGVASAVTSSPSE
KSSSDEKPEIESDSSCLKPEHHVASSLNSNLESSTEVRSNSGFPGVTSKEHETVQTANGG
HGVQQSPQPNKELENQQSSRVNI------DPEIKETSHVERESEVVNSVSPTESRSNPAA
LPPARPAGLGRAAPLLQP-APRAPQQSRVNGNVSH----------SQPQQAE--------
DSTTAETDEHDETREKLQLIRVKFLRLAHRLGQTPHNVVVAQVLYRLGLAEQLRGRNGS-
RVGAFSFDRASAMAEQLEAAGQDP-----LDFSCT-------IMVL--------------
----------------------------------GKSGV---------------------
------------------------------------------------------------
-------------------------------GKSATINSIFD-----------------E
VK----------------------------------------------------------
------------------------------------------------------------
----------------------FCTDAFQMGTKRVQD-------------VEGFVQGIKV
RVI----DTPGLL-PSWSDQSKNEKILNS--VKA----------------FIKKNPPDIV
LYL-----------------------DRLDMQSRDS------------------------
GDMPLL-RTISDVFGPSIWFNAIVGLTHAASVPPDGPNGTASSYDMFVTQ----------
------------------------------------------------------------
-----RSHVIQQAIRQAAEDM-RL----------------------MNPISLVEN-----
------------------HSACRTNRAGQRVL-----P---------NGQVWKPHLLLLS
FASKILAEANAL-LKLQDNIPGRP-FAARTKAPPLPFLLSSLLQSRPQPKLPEQQYGDEE
DED-DL---------------DESSDSDEE----SEYDQLPPFKHL--------------
------------------------------------------------------------
--------------TKDQMAKLSKSQKKQYLDEMEYREKLLMKKQMKEERKRRKMFKKFA
AEIKDLPNEPPSDNVEEESGGPASVPVPMPDLSLPASFDSDNPTHRYRYLDSSNQWLVRP
VLETHGWDHDIGYEGVNAETLFVVNKQIPVSLSGQVTKDKKDANVQLEMASSVKHGEGRS
T-SLGFDMQTVGKELAYTVRGETRFNNFRRNKAAAGLSLTLLGDSVSAGLKVEDKLI---
------------------------------------------------------------
--ANKWFRMVMSGGAMTSRGDVAYGGSLEAQLRDKDYPLGRFLTTLGLSVMDWHGDLAIG
GNIQSQIPIGRSSNLVARANLNNRGAGQVSVRVNSSDQLQLAMVAIVPLFKKLL--SYYS
-QQTQ---YGQ
