>gnl|BL_ORD_ID|9830 @Volvox_carteri@_Vocar20012343m|PACid:23133716
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------PSLPARPKGGLGGLPP-------------------
-------------------RGLPALS----------------------------------
-----------------------------------------------SKSASPQSSSPPA
PSAGPSA---AQPAAAASGSAPPIASMPKLPPR----PGAPSGLGLGLG--------LGA
RPAAGA-PRPPSEGVPAAAATPAA-----------AETAPAAAAAAA--------PPGVQ
QPAAAAA------------------------------AGPAGLGLGLGGAAAQ--RPTLP
PRPATAGT-------------------ATSSAAAAAQPRPAGAQSVGGAAAAAGGVRAMP
GLPPRPAGLGGAPPAPAAAAAATAGAAAAATPSMDVVDRT--------------ED----
------RRV------QRVQRTAHEIRVRLIRAATRLGLSPRSDQVAQFLQAIERSERMVG
AQHYKGTRRVDLIAAAEREARELDSREPPHSPIAGLRLKILVLGMTGTGK-SELINSLLD
RPASS----------------RTSPFREATRRVRVIRGHHNGIPLTFID----------T
PGLHASVSCTAENKAILRSIKAAYNCFKPDYVFYVDRLD---------APRPGLG-----
------ELGVLSLIAEALGPGVWRNTMAVL-----THAHAARA----AFGGQYDI-----
-----NSRQRRNIIT-QLLRQVAGDQQSR-------------------------------
NPVFLVDCHPS--------------------CPTNS-LGQQVIQEGPSAVPWKQQLLGQT
VGYKSYNAAAAVFKELAKSKAGKSAAAGGARGPQDIFKQLMRSRLPPMTFFVEQMTEGV-
-LKPEGWATMESVAGLGDEVTEDEEAES-----------FGHMYYQHMYDLAMSG-----
DPWAQREYAAMLRSYDKAQETFKA------SYEEADLDHAIEYGIESYVVDP--------
-IDFGPSFDPEDLYSYRHAYAEAADSAITVIPSQDYYGP----EHEDPLNG------FVM
QYESQPFARHGWGGVPFDLSVCVEKDKTSLCLQGETHLTVVHSVPPFGPRQVTQLTGSWE
MLRPNIKDVMYQLEVDTFKDGLLGRNDHAGCGMMLARLGEGGNPRKGPVAVGVRVQDTFR
LGAFKVEAC-----------------------ASKVAVQGPTGGKEEGWGARAFVMYDWL
PGVGIALDAIQEKGSEESGKRQRGYGINVTYDWEMLGAAFGAEFDYVAASKSL-------
-------YVSVNAFS------------------------GNDYRLAWVLLLPALGSDEIE
WETLGSVWARLRAAGGGAGQEEEAGEEEAGEEEYDEEDEDEGVAAMMAQAADM
