>gnl|BL_ORD_ID|15727 @Vitis_vinifera@_GSVIVT01024062001|PACid:17832352
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------YTP------
------------------VDEGVSASGTGRSPSVEDSAIEKSEMEQCAIEDSTIEKSETK
QG--------VT---------------SELA-----------------------------
--------------------AADNISPQPERAVENVAEVK------------NKYVVFEE
QETKEPNMEKEDQ------------------------------------KIQGNREREIR
PAEQ---VASSSGRSSNPG------------PPPAHPAGLGRAAPLLEPASRVVQQPRVN
GTTSQVQAQLIEDAGNGEAEENDETREKLQMIRVKFLRL--AHRLGQTPHNVVVAQVLYR
LGLAEQLRGRN-----------------------GGRVGAF------------SFDRASA
------------------------------------------------------------
-------------------------------------------------------MAEQL
EAA---------------------------------------GQEPLDFSCTIMVLGKTG
------------------------------------------------------------
------VGKSAT-------------INSIFDEVKFSTDA---------------FQVGTK
-----------KVQDVVGTV--QGIKVRVI-----------------------DT--P--
---------------GLLP-SWSDQRQNEK--ILHSVKRFIKKTPPDIVLYLDRLDMQ--
---------------------------------SRDFGDMPLLRTITE----IFGPSIWF
NAIVVL------------------------------------------------------
----------------------------------------THAASAPPDGPNGTA-----
---SSYDMFVTQRSHVVQQAIRQAAG--------DMRLM-----NPVSLVENHSA--CRT
NRAGQRVLPN--------------------ANTLLKLQDSPPGKPFTTRSRSPPLPFLLS
SLLQSRPQVRLPEEQ---------------------------------------------
------------------------KERRKMMKKMAASSKDLPSDYSENAEEESGGAASVP
VPMPDWALPASFDSDNPTHRYRYLDSSNQWLVRPVLETHGWDHDV---------------
-------------------------GYEGINVERVFAIKDKIPVSFSGQVTKDKKDANLQ
M------EIASSVKHGEGKATSVGFDMQTVGKDMAYTLRSETRFCNFRKNKATAGLSITA
LGDAITAGLKLEDKLIVNKRIRLVMTGGAMTGRGDVAYGGSLEATLRDKDHPLGRSLSTL
GLSIMDWHGDLAIGCNIQSQIPIGRFTNMIGRVNLNNRGAGQVSIRLNSSEQLQIALIGL
VPLLRKLLGYSQQGQSSCFLIVYAFGMNCKIPGMYQKGLSFFLYLYSWITSAGANETLGS
MLLGYVNICNTYESFS
