>gnl|BL_ORD_ID|6487 @Brachypodium_distachyon@_2g35587.1|PACid:21809257
MSTTDARVAPVADERPPAADGGVVAAADGSKSVGTAEVEVGGGGEAEEVRFEGTGKSFGG
SEGENGVVEAGDGEGVEAPVDVKDESAIEVVEEAAGDKVDGGDWESA-------------
-----VGDVKAASLATETVV----VESENGKLGEGDASLSTPDAPVGEEKGELSD----E
LEKSAT----------LEVEDVGKVADD-AELSEEKLEGVKDADVVTGG---EEDGDFGS
KEEVMASTRSTEAAEPEDKVAP---LAEANGKLGGEAELSAEMGVVADEEAPE-----AS
LEKELDVEDKAANPEPESD------------AGPVVVDNSSLEN----------------
------------------------HANLEDEAAKTELEIAGSPV---------------V
IDDSSLEN-HVNVEDKAAKPEPDFEASPMVTDADGLGSLEKLAPPSG-----------DI
VYEESTEKAQNAEG-QVVANEKADDIDGENPTEDQSVLAGGA---------------DVT
LSR---------------ELTPEPIKENNVVEENNGAAETVSHEVVASNDEKVVAAASDV
QKVIAVANDENLGDEEYEDDIETFDRDIHVVDDEIVLAAVGEDGGDNEVDEDYD------
-EASSDRSPARVAIIENSEAAKQIMKELGEGSSSGSPVSGLSS-SREYTNSMDGQIVLDD
SEDEDDDDDNEDDDEKG------FDSAALAALLKAAT--GASPDGNITVASQ--DGSRIF
SMDRPAGLGSSAPSLRPTAPRQPARSNLFNP-----------------------------
--------------------------------------------SELAMTAEPNE-----
-----EMTEEEKKLHEKVELIRVKFLRLVYKLGATPDETVAAQVLYRLSLAEGIRQGRQT
NR--AFSLDNA-------------------------------------------------
---RRKALQLE------AEG----------KEDL----SFS---CNILVLG---------
------------------------------------------------------------
------------------KIGVGKS------------ATINSIFG---------------
-----------------------------------------------EER-SKTDAFGAA
T--TS---VREISGNV-DG---VQI-----------------------------------
-----------------RIID------------TP-------GLRPNVMDQGT--N----
------------------------------------------------------------
-----------------------------------------RKILASVKKYTKKCPPDI-
------------------------------------------------VLYVDRLDSLSR
DLNDLPLLKTITAVLGSSIWFNA-----------------------------------IV
ALTHAASAPPEGL-----------------------------------------NGAPMT
YEV--LMAQRSHIVQQSIRQAAGDMR-----L----------------------------
----------------------------MNPV--------ALVENHPSCRKNREG--QKV
LPNGQSW-----------------------------------------------------
-----RHQML-----LLCYSSKILSEANSLLKLQDP-SPGKLFGFRFRSPPLPF------
-LLSSLLQSR-----AHPKLSPD--------------------QGGNEGDSDIELDEYSD
IEQ-DE-DEEEYDQL---------------------------------------------
-----------------------------------------------------------P
PFKPLTKAQLARLTKDQKNAYFDEYDYRVKLLQKKQWKDELRRLKEMK------------
------------------------------------------------------------
-----------RRGKSDLDS-YGYASIAGDDQDPPPENVSVPLPDMVLPPSFDCDNPTYR
YRFLEPTSTVLARPVLDAHGWDHDCG-----------------YDGVSVEESLALLSKFP
AAVAVQVTKDKKEFSIHLDSSVSAKLGEDASSLAGFDIQTVGRQLA--YILRGETKFKSI
KKNKTTGGFSVTFLGDIVATGLKVEDQLSVGKRLALVASTGAMRAQGDTAYGA-------
------------------------------------------------------------
--------------------------------------NLEARLKDKDYPIGQSLSTLGL
SLMKWRRDLALGANLQSQFSIGRGSKMAVRLGLNNKLSG-----QITVRTSTSEQVQIAL
LGLVPVIASIYRSFRPG------EPTFAY-------------------------------
---------------------------------------------------
