>gnl|BL_ORD_ID|28856 @Eucalyptus_grandis@_H01158.1|PACid:23590577
MESKPVAPE-TNALSSGSSSSSSSSSSSRDYDYVPPVVAHPVKVGGSGSGGESEEDGGFV
SGGEE-ERPAFAAPGSFRPVAKVSNDDDDDDE--------DGEAVDGEDDGEAVRGGSFG
E--PKVKVLAGAAEGGEELGSLEGGVRGLSGVSG---------------SGSLEKGVESG
NFGF--------GERRVSRRKSLKELLETSGGDDDYQEGVKEVPMGVKE---DKVIE---
-----SGDVVEQS--VQAGAVE--VAK----------------------LQSEGAVVEQA
LDSSGGGKSEEL----SKAVEFVYSSVASADR--VDSKNLEQKDVKQIE-----------
----------------------------------------------------------DD
GVKFNDGGDTVVD-----AVKVDLMASGAAVVGE--VMDGRDSEIPAVELSSEPVP-LEN
GFDQISP-------KAENPAEIMAVRLDESSDGLRNSIDEASERVPEMKK-D----DVPG
VGGDNMPEPSVAVVDQATEYPDQEVKKE----MQMEPEAESGPKHDEPATKAADHGVESA
YSHVSG----ERDE------------VQSLSLDSVTGH------AEPKLDGKAKPPENNG
TIAEVEGLGVETGVPVQSLSY-DQDVSVEPGDDDKLQVDEETDMEGSDTDGEK-------
----------GSM-LFENSQAAK-----QFLE---ELERGAGS----QSGAESS------
---HDHSQRIDGQIVTDSDEEVDTDEDGDGKELFD---------SAALAALLKAAT-GAD
TDAGNITITSQDGSRLFSVERPAGLGSSLRSVKPASRP--NRSSLFT---------SNLT
PA-ESDNNLTE---------EEKKKL----EKIQQLRVKFLRLVQR---------VGYSP
EDSLAAQVLYRLALVA---GRQAGQ--------L--FSLDSAKK----------------
---------------------------------TASELELEKKDDLNYSLNILVL-G---
KAGVG--------KSATINS----LLGEDKAMIH-----------AF-------------
-----------EPATTAVKEITGTVHGVK-------------------------------
-----------------------------------IRVFDTPGL----------------
---------------------KSSVM-EQNENRRIFSSIKK-FTKKCPPDIV--------
------------------------------------------------------------
------------------------------------------------------------
------------------------LYVDRLDTQTRDLND---------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------LP
LLKSITSALGPS-----------------------IWRSAIVTLTHGA-------SAPP-
------------------------------------------------------------
---------------DGPSGSPLSYD------VFVAQRSHVV------------------
--------QQSIGQAVGDLRLMNPSLMNPVSL----------------------------
------------------------------------------------------------
--------------------------VENHTSCRKNRDGEK-VLPNGQTWRPQLL-----
-LLCFSMKILAEASSLSKPQD---------------------PFDQRKLFGFRVRSPPLP
YLLSWLLQSRTHPRLSSDQGLENGDSDVDMAYSSDSDEED-EEDEYDQLPPFKPLRKSQI
AKLSKE------------------------------------------------------
------------QRKAYFEEYDYRVKLLQKKQWREELKRMREIKKKG-KVSPDE-YDYMG
GDGDPEDGSPAAVPVPLHDMVLPQSFDSDNPAYRYRFLEPTSQFVARPVLDTHGWDHDCG
YDGVNLEHSLAIASQFPGAVALQITKDKKEFNIHLDSSVAAKHGDNGSTMAGFDIQNIGK
QLAYIVRGDTKFKNFKKNKTAAGFSVTFLGENIATGFKVEDQIALGKRVMLVGSAGTVRS
NSDAAYGANLEVRLREADFPVGQDQTSMSLSLVKWRGDLALGANMQSQFSVGRSSKIAVR
AGLNNKLSGQISVRTSSSEQLQIALVGILPIVTAIYKSLRP-GVSE-TYS----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------IY
