>gnl|BL_ORD_ID|12663 @Glycine_max@_05g29990.1|PACid:16260118
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------KE---
----------------GDFSDSNEVFVEASG------------GDD--------------
----------------------DIKEIQSGVVAVENGVELSGTDKGFEAAAVELNEEEAK
EKEVEEKVNDGGTDNSDS----VVDE-KSEGVDVEKDDGG----GVD---------AVVD
SVEVNVLGSGVAVVGDELGVDESEIKGLEEPESRGVSLDNGFEPIEKGE----EEVVDKL
VDGGDGQSGAEG-----------------------VVVGGDDVSGENGDDG---------
-----DGLKSDIV-----------------------VPPEEGGGG--------SEFVEKD
E--VNMEGD-------------VVEGENGSRVEEEVGHHGDRE--IDDSELDGKI---GS
HVEEVEEIGANGDREINGSVSDEKEE-----------------E----------------
------------------TDDEGDGKE-LFDTATLAALLKAAS-GADQDGGSITITS---
------QDGSRLFSVE-----------------------------------RPAGLGSSL
SSGKPAM--RQTRP--SLFTPSISRASAISDSNLSEEEKKK------------------L
EKLHEIRVKYLRLVHRLGFTT---------------------------------------
------------------------------------------------------------
----------------------------------------------------------EE
SIAAQVLYRMTHVA---GRQS--GQM--FSVESAKETASQLEAE----A--RDNFDFS--
-----------------------VNILVLGKAGVGKSATINSIFGETKTSINACGPATTA
V-----------------------TEIVGVV--DGVK-----------------------
---IRIFDT-----------------PG-LKSSAFEQN---FNT------------KVLS
AVKKLTKKSP--PDIVLYVDRLDLQTRDMNDLPML-------------------RSITSV
LGSSIWRNVIVTLTHAASAPPDG-------------PSGAPLSYDVFVAQRSHIVQQTIG
QAVGD-----------------LRLMNPSLMNPVSLVENHPSCRKNRDGQKVLPNGQSWR
PLLLLLCYSMKILSEASNVSKTQE----SPFDQRRLFGFRPRSPPLPYLLSWLLQTRTYP
KLPADQGGADNGDSDIEMADLSDSDL-D-EDEDEYDQLPPFKPMKKSQVAKLT-------
-----KEQQKAYFEEYDYRVKLLQ------------------------------------
---------------------KKQWREELRRMREMKK--------KGNT-KENDYGY-TE
EDDQENGSPAAVPVPLPDMALPPSFDSDNPAYRYRFL-EPTSQLLTRPVLDSHGWDHDCG
YDGVNIEQSLAIINKFPAAVTVQVTKDKKDFSMHLDSSVAAKLGENGSAMAGFDIQNIGK
------------------------------------------------------------
------------------------------------------------------------
-QLAYIVRGETKLKNFKRNKTSAGVSVTFFGENVSTGLKVEDQIAVGKRVVLVGSTGVVK
SQTDSAYGANVEVRLREADFPIGQDQSSLSLSLVKWRGDLALGANLQSQFSVGRGYKVAV
RAGLNNKLSGQISVRTSSSDQLQIALIAILPIAKAIYKNFWPGAS-ENYSIY--------
------------------------------------------------------------
-------------------------------
>gnl|BL_ORD_ID|12663 @Glycine_max@_05g29990.1|PACid:16260118
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------KE---
----------------GDFSDSNEVFVEASG------------GDD--------------
----------------------DIKEIQSGVVAVENGVELSGTDKGFEAAAVELNEEEAK
EKEVEEKVNDGGTDNSDS----VVDE-KSEGVDVEKDDGG----GVD---------AVVD
SVEVNVLGSGVAVVGDELGVDESEIKGLEEPESRGVSLDNGFEPIEKGE----EEVVDKL
VDGGDGQSGAEG-----------------------VVVGGDDVSGENGDDG---------
-----DGLKSDIV-----------------------VPPEEGGGG--------SEFVEKD
E--VNMEGD-------------VVEGENGSRVEEEVGHHGDRE--IDDSELDGKI---GS
HVEEVEEIGANGDREINGSVSDEKEE-----------------E----------------
------------------TDDEGDGKE-LFDTATLAALLKAAS-GADQDGGSITITS---
------QDGSRLFSVE-----------------------------------RPAGLGSSL
SSGKPAM--RQTRP--SLFTPSISRASAISDSNLSEEEKKK------------------L
EKLHEIRVKYLRLVHRLGFTT---------------------------------------
------------------------------------------------------------
----------------------------------------------------------EE
SIAAQVLYRMTHVA---GRQS--GQM--FSVESAKETASQLEAE----A--RDNFDFS--
-----------------------VNILVLGKAGVGKSATINSIFGETKTSINACGPATTA
V-----------------------TEIVGVV--DGVK-----------------------
---IRIFDT-----------------PG-LKSSAFEQN---FNT------------KVLS
AVKKLTKKSP--PDIVLYVDRLDLQTRDMNDLPML-------------------RSITSV
LGSSIWRNVIVTLTHAASAPPDG-------------PSGAPLSYDVFVAQRSHIVQQTIG
QAVGD-----------------LRLMNPSLMNPVSLVENHPSCRKNRDGQKVLPNGQSWR
PLLLLLCYSMKILSEASNVSKTQE----SPFDQRRLFGFRPRSPPLPYLLSWLLQTRTYP
KLPADQGGADNGDSDIEMADLSDSDL-D-EDEDEYDQLPPFKPMKKSQVAKLT-------
-----KEQQKAYFEEYDYRVKLLQ------------------------------------
---------------------KKQWREELRRMREMKK--------KGNT-KENDYGY-TE
EDDQENGSPAAVPVPLPDMALPPSFDSDNPAYRYRFL-EPTSQLLTRPVLDSHGWDHDCG
YDGVNIEQSLAIINKFPAAVTVQVTKDKKDFSMHLDSSVAAKLGENGSAMAGFDIQNIGK
------------------------------------------------------------
------------------------------------------------------------
-QLAYIVRGETKLKNFKRNKTSAGVSVTFFGENVSTGLKVEDQIAVGKRVVLVGSTGVVK
SQTDSAYGANVEVRLREADFPIGQDQSSLSLSLVKWRGDLALGANLQSQFSVGRGYKVAV
RAGLNNKLSGQISVRTSSSDQLQIALIAILPIAKAIYKNFWPGAS-ENYSIY--------
------------------------------------------------------------
-------------------------------
>gnl|BL_ORD_ID|21082 @Glycine_max@_08g13100.1|PACid:16270964
MDSSSLPQTSLPP-----------------------------------------------
---------ASDSENDDGFLSGE-------------------------------------
----------------------------------ESDFEPEPTRPVLVNSSSQPPHEPVF
DSPPHRPIAKVSGDDDDDDDDGSI-VEDADDDVVLEEG-------GEKEESGEAVKD---
----------------GEVSDSNEVFVEASG------------GDD--------------
-------------------------------VAVENGVEFSGADKGFEGAAVELNEK---
----EDKVNDGGTDNSDSEV--VVDEKKGEGVDVEKDDDGGGGVGVD---------GAVD
NVEVNVLGS-----GDDVGIEESQIKGLDE---TAMNLENDFEPIEKGE----EEVVD--
--------GGVG-----------------------V--------GENGVEG---------
-----DGLKSDID-----------------------VPPEEGGGG--------SEFVEKN
E--VKMEGD--------------------------VGQHGDRE--IDDSVLDGEI---GS
H---VEEIGGNGEREINGSVSDEKGDGLVFGSTEAANKFLEDLE----------------
------------------LHQSREGKE-LFDTATLAALLKAAS-GADQDGGSITITS---
------QDGSRLFSVE-----------------------------------RPAGLGSPL
QSGKPAV--RQTRP--SLFTPSMSRPSAISDSNLSQEEKNK------------------L
EKLHEIRVKYLRLVHRLGFTT---------------------------------------
------------------------------------------------------------
----------------------------------------------------------EE
SIAAQVLYRMTLVA---GRQS--GQM--FSVESAKETASRLEAE----G--RDDFDFS--
-----------------------VNILVLGKAGVGKSATINSIFGETKTSINACGPATTS
V-----------------------KEIVGVV--DGVK-----------------------
---LRIFDT-----------------PG-LKSSALEQN---FNM------------KVLS
AVKKLTKKSP--PDIVLYVDRLDLQTRDMNDLPML-------------------RSITSV
LGSSIWRNVIVTLTHAASAPPDG-------------PSGAPLSYEVFVAQRSHTVQQTIG
QAVGD-----------------LRLMNPSLMNPVSLVENHPSCRKNRDGQKVLPNGQSWR
PLLLLLCFSMKILSDASNSTKTQE----S-FDHRRLFGFRPRSPPLPYLLSSLLQTHTYP
KLPADQSGPDNGDSDVEMADLSDSDL-D-EDEDEYDQLPPFKPMKKSQVAKLT-------
-----KEQQKAYFDEYDYRVKLLQ------------------------------------
---------------------KKQWREELRRMREMKK--------KGNT-KENDYGY-ME
EDDQENGSPAAVPVPLPDMAMPPSFDSDNPAYRYRFL-EPTSQLLTRPVLDNHGWDHDCG
YDGVNIEQSLAIINKFPAAVTVHVTKDKKDFTIQLDSSVAAKLGENGSAMAGFDIQSVGK
------------------------------------------------------------
------------------------------------------------------------
-QLSYSVRGETKLKNFKRNKTSAGVSVTYLGENVCTGLKVEDQIAVGKRLVLVGSTGVVK
SKTDSAYGANVEVRLREADFPIGQDQSSLSLSLVKWRGDLALGANLQSQISVGRGYKVAV
RAGLNNKLSGQITVRTSSSDQLQIALVAILPIAKAIYKNFWPGAS-ENYSIY--------
------------------------------------------------------------
-------------------------------
