>gnl|BL_ORD_ID|8566 @Linum_usitatissimum@_10006048|PACid:23147746
----------------------------------------MA-------S----------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------NAAPDSPSPSNFSAADDVTV---
EKSGIELDKPAHDDDDND---EKAREGLVKVAETMKEPDSVVEAVRVELAGPGVAVVGEA
EESKA-EKEEVVVD-ES-LPLDNEFDKIGGEAEESIQSDKKDKAIGG-DDKVSVE-LDTV
-----VDGVHLNLLEPGVVAVV-----EEVEGSKEEAEFVAMLEEKVESFPVDDNK----
---FDNIASGSEDLVKLDKVSLPEKGDAEELDSVVDAVHVELAEPGLAVVGEMEGSSKEE
AEFLAMLEEKVVDSFPVEDNKFETIA-------------------------GDSE-----
-D----LVKLDVNHTDARTGS--------------DDAADIKISGL---GNEGSEVNGN-
---VAEGDAVPKGELEVTAREVSL-------EELSGDTKSSDERKEANLLVDGGAADQTV
-VAVASSNRS---VP--VVDDLEQDDQAAESKESDKTMEALTESDVGQIAEFDNVTKEAE
DEESEDEGEEKTRSYEESESD-EETEDKVFGSSEAAKQFLNELKQ---------------
-------DGQIVTDSEEEEEEEEEGDTDEEEDGEGKELFDSAALAALLKAASAGGGTSSE
GGGGDHTVTITSQDGSQRLFSLERPAGLGSS-LGAMRPRTM-IPNR----SNLF------
--------------------GPPREEPSDES---LS-----DEQKKKLEDMQQMMIKYLR
LVFRLGYSPDESIVSQVLYRMAM---IAGKKSGQI--FNVDS------------------
---AKRIALQ-LETERKDD-----------------------------------------
------------------------------------------------------DDVSFS
------LNI------LVLGK----------------------------------------
--------------------------------------SGVG------KSSTVN----AI
FGEE--------------------------------KSVIDAFEPATGSVKEINGVA--D
GIKIRII--------------------DSPG-LKSSGSEQGTNRRILNS-----------
-IKRYMKRC-PPDIV---------------------------------------------
------------------------------------------------------------
-----LYVDRLDTQ--TRDLNDLPLLKSITSHLGS---------SIW-------------
-----------------RNAIVTLTHAASAPSDGP-------------------------
------------------------------------------------------------
---------SGAPLSYDVFVAQR-----------------------------SHVLQQSI
GQAVGDLRLMNPSLMNPVSLVENHSSCR----------------RNRDGEKVLPNGQSWR
LQ----LLLLCSSMKILSES----------------------------------------
-------------------TALSKPASSQDAAFDPRKLFGGGRARSPPLPYMLSWLLQS-
----------------RPHPKLPADE--SSIDEDIELAD-------------------YS
DSDQED-ESDEYDQLPPFKPLRKSLL----------------------------------
------------------------------------------------------------
---------------------AKLSKEQKKAYLEEYDYRVKLLQKKQLK-----------
------------------------------------------------------------
--------------------------EELRRMKEM---------KKKGKNAAVLEDDYAA
---DPENGEPAAVQVPLPDMVLPPSF------------DSDNPVYRYRFL-EPNSQLLVR
PVLDT------------------------------HGWDHDPGYDGV-------------
-------------NVENSLAIAGKYPAALTVQVTKDKKDFNLHLDSSVATKHGGEDNSGS
SMAGFDIQNVGK-QMAYIVRGETKFKNFKKNRTA-VGVSVTFLGPNVATGFKLEDQISLG
KRMVLVGSTGTVRSQGDSAYGANLEVRLREADFPIGQDQSSLGLSLVKWRGDLALAANLQ
SQFSVGRSSKIAVRAGLNNKLSGQISVRT-SSSDQLQI-ALVGLLPILASIYK-------
------------------------------------------------------------
--------------------------------------------------------SIR-
---PPASEESYSLY--
>gnl|BL_ORD_ID|25289 @Linum_usitatissimum@_10028707|PACid:23164469
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------MKEI---------KKKGKSAAVLEDDYAA
---DPETGEPAAVQVPLPDMVLPPSF------------DSDNPVYRYRFL-EPNSQLLVR
PVLDT------------------------------HGWDHDPGYDGV-------------
-------------NVENSLAIAGKYPAALTVQVTKDKKDFNLHLDSSVATKHGGENNSGS
SMAGFDIQNVGK-QMAYIVRGETKFKNFKKNRTT-AGVSATFLGPNVATGFKLEDQISLG
KRVVLVGSTGTVRSQGDSAYGANLEVRLREADFPIGQDQSSLGLSLVNWRGDLALAANLQ
SQFSVGRSSKIAVRAGLNNKLSGQISVRT-SSSDQLQI-ALVGLLPIAVSIYK-------
------------------------------------------------------------
--------------------------------------------------------SIR-
---PPLNDESYSLY--
>gnl|BL_ORD_ID|25415 @Linum_usitatissimum@_10028706|PACid:23164595
----------------------------------------MA-------S----------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------TTAPDSPSPSNFSADDDVTV---
DKSGIELDKPVQNDDEND---EKAGESLVKVAETMKEPDSVVEAVRVELAEPGVSVVGEA
EESKAEEKVEVVVD-ES-LPLDNEFDKIGVEAEESVQSD-KDKAIGD-DDKVSVE-LDTV
-----VEGVHLNLLEPGVVAVS-----EEVEGSKEEAEFVAMLEEKVESFPVDDNK----
---FDNIASGSEDLVKLDKVSLPEMGDVEELDSVVDAVRVELAEPGLAVVGEMEGSSKEE
AEFLAMLEEKVVESFPVEDNKFENIA-------------------------GDSE-----
-D----LVKLDVNHTEART-V--------------NDAADIEISGL---GNEGSEVNGN-
---VTEYDSVPKVEPDVSAREVSVVKEA---EEVSGET-----------VVGGGTADKTV
AVAVASSDRSVPVVP--VVNDLEEDDQAAESKESDKTIEALTESDVGQVAEFDNVTK-AE
AEDESDGGEEKTRSDEESESDEEETEGKVFGSSEAAKQFLNELKQ---------------
-------DGQIVTDSEEEEEEEEEEMDTDDEEGEGKELFDSAALAALLKAASAGGGTSSE
GGGGDHTVTITSQDGSQRLFSLERPAGLGSS-LGAMRPRTN-IPNR----SNLF------
--------------------GPPREEPSDES---LS-----DEQKKKLEDMQQMMIKYLR
LVFRLGYSPDESIVSQVLYRMAM---IAGKKSGQI--FNVDS------------------
---AKRIALQ-LETERK-E-----------------------------------------
------------------------------------------------------DDVSFS
------LNI------LVLGK----------------------------------------
--------------------------------------SGVG------KSSTVN----AI
FGEE--------------------------------KSVIDAFEPATGSVKEINGVV--D
GITIRII--------------------DSPG-LKSSGSEQGTNRRILNS-----------
-IKRYMKRC-PPDIV---------------------------------------------
------------------------------------------------------------
-----LYVDRLDTQ--TRDLNDLPLLKSITSHLGS---------SIW-------------
-----------------RNAIVTLTHAASAPPDGP-------------------------
------------------------------------------------------------
---------SGAPLSYDVFVAQR-----------------------------SHVLQQSI
GQAVGDLRLMNPSLMNPVSLVENHSSCR----------------RNRDGEKVLPNGQSWR
LQ----LLLLCSSMKILSES----------------------------------------
-------------------TALSKPA-SQDAAFDPRKLFGGGRARSPPLPYMLSWLTPS-
----------------CP------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------PA---------------------QTAGGGGTHEGE
H-----------------------------------------------------------
------------------------ENRRR-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------Y--
