>gnl|BL_ORD_ID|4265 @Mimulus_guttatus@_mgv1a000181m|PACid:17673660
MDSKEATTQPISEVSSGTTSSQFIISSLYYANSPDETLLNNKIASAGDSRSDSKGTVPED
EGYVSGNEEFEPASDKLV--VDEIVEEENSDELEKIESLLISGVVVNDDDDVEKGDK---
------DIEGGGVLEGDKVGGV----EGFDRNGEVLDSVEKLGVNSNDGVDGEEGKVGVR
EAEMKVEESEVNEKSEPQAKDASQAAV----VEHVESEFSDAVD--------------VK
TTPEGDAV-----VDAIQVDVAAPGVVVVGETEEDGDAGNEPEKEVIS--EVAVIEQ---
--------EKSEVVSLVNEGQTSQGDPVA----------VDETEPKEENLTSVDKLEPKE
VAENVGLAD------------------------------------VALASEGDSVVD---
--AIQVDKVGPGVVVVGELEGEKI--------------------EGVEVPLVSVSGPTET
ADDVEEVGTREVLAANIVDVVDADENSDAVGVVDLENGVHASSESNDSVDSGDTIKKPEV
EFESPRIPDSRIAGKARPIIVGINNLEVEGGGEPESAPISEAVENSTTPKIATDGEVEGE
VNPRENTGKAPPVVIGRSSPKVEEDVEYESAPISEVAENSITAKIAADGEVEGELDGLSN
TVTVPPVVIEPNNLQVEDDVEYESAPISE---AVENSTTAKTATYGEVEGEAG-DIIGRN
DPPVEDDNGEEVNPED-SMSDEDSDGMIFGSSEAAKKFIEELERES--VEDSHAGGEGSL
HQSRGIDGQIVTDSEEE-EEEEEGETDEEGDGKELFDNAALAALLKAAS-RAESDGGSIT
ITSQDGSRLFS-VERPAGLGSSL--------------QSLRPAQR----P--N-------
--------------------------------------RPSLFGTAAPSAGGGGGGEVED
RL------SDEEKKKLEKLQEIRVKFLRLVHRLGLSPEESVAAQVLYRLALLG----GRQ
STHT--FNLDAAKRTA-LLLE-------AGGN----DDLDFSINILVLGKSGVGKSATIN
SV----------FGEEKAPIDAFETGT-ASARE---ISGLVDGVKVRV------------
------------------------------------------------------------
------------------------------------------------------------
-------IDTP-----------------------------G----------------L-K
SS-----V----ME-QSFNRGVLSSVK----KFTKKS-PPDVVL----------------
-YVDRLD------AQS-RDLND------------LPLL----------------------
---KTITSSLNSS------------I----------WRSAIVTLTHAASA-PPDGPSGAP
------------------LSYDVFVS--QRSHVVQ-------------------------
------------------------------------------------------------
-------------------------------QSIGHAVGDLRMMSPSLMN--PVSL----
------VENH----------------PSCRKNRDGHKILPNGQIWRPQLLLLCYS-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---MKILSEASSLS--KPQD---P--FDHR-K-------------------------LFG
MRQRAPPLPYMLSSMLQTRTHPKLQSDQGGDSVDS-DIDL--------------------
------------------------------------------------------------
------------------------------------------------------------
-----------DEDLSDDDQEG--VDEYDQLP----------------------------
------------------------------------------PFKPLKKAQMAKLTAEQR
KAYFEEYDYRVKLLQKKQWREELKRMR---------------------------------
----------------EMKKNGGK-DAAAGDYA---FAEDDADAGAAAPIAVPLPDMALP
PSFDGDNPAYRFRFLEPTSQFLARPVLDNHGWDHDCGYDGVNLEHSLAIASRFPAVYTVQ
VTKDKKDFSISLDSSVSAKYGDDISTMAGFDIQSMGKQLAYIFRGEAKIKNLKKHRATGG
LSFTLLGENVVPGVKIEDQISLGKQYSLSGSAGAVRSQQDTAYGANFELQRRELDYPIGQ
VQSTLSVSVVKWRGDLALGLNSLAQFSLGRNSKVAVRAGINNKLSGQITVRTSSSEHLSL
ALTAI-IPTVLSVYKKFF-A--GGGEKYPIY-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
