>gnl|BL_ORD_ID|43011 @Populus_trichocarpa@_POPTR_0008s22130.1|PACid:18249494
MS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------ELEQRLAFSCPSG
TEVSHDHSLKIDEKITADSDEEADTLQ-EQMGKELVDSPPAARVSHDYSNQLIIADPDEE
ADIVKEKNREESFDSPPGRIDEQNIAAAGVSHDYSNQQIIADPDEEADIVTEKSREESFN
SPLRRIDEQIIAAAGASHDYSNQQ-------ITADLDEEAGMVKEKSREELFDSPSGRID
KQIIAAAGVSRDFSNQQITADPDEETDIIKEKSREESFDSPLGRFDEQIVADADEEGKIV
TEKMGNELFDSPSWADISHDRSRRTNEQIITDSD--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------EDADIVEEQMGRELADMVK
EQMEK-------------------ELFDSLSGLQVSHDHSQS-------IHEQIIADSDE
EADSINEKIGEELFDASSGRIDGQVITDSDEEGDMDTEQIGNDLLESDALAALLKAAS-S
AGMD------GGRVAITSADGSRVFSLERLVGSDSPFRIVRPAP--LSET----------
--------------VEDVAKNDLNEEDKKVIEKIQQIAVKFL------------------
------------------------------------------------------------
----RLVQRLGQSP----------------------------------EDSIVAQVLHRL
VVATRAHVNQ-----EFSLENAEKMAMQLEAEGK--------------------------
----------------------------------------------DDLDFSLSILVLGK
TGVGKSATINSI--------------------------------------------FGEK
K--------------V-----EINAFEP----------------------------ATTM
L--KEVVGIV--DGVKI-RIIDTPGLRSSV-KEEAI---NRK-----------------I
LASIKTSINKFPPDV-----------------ILYTDRLDTHSLDLNDLPMLR-------
-----LLTKSLTSSIWK--NSVVTLTHATSPPPDGPSGSPLSFEMFVGQRSHAIQQAIS-
--------------QAVGDLRLIHPRMMHPVSLVENHPLCQKNEN---------------
SEYILPNGQSWRPQL-----LLLCYSLKILSEASSIAKPRDPFDHKKPFGFRLRSLPL--
------------------------------------------------------------
---------------PHLVSSLLQSRPHPKLTADQGGDDI---DSDIDMVDLSDSDEEI-
-EDEYDQLPP---------------------------------------FKPLK------
--------KSHVAKLTKEQR---------KAYLEEYDYRVKL----------LQKKQWRE
EV-----------KMLKGMKKKGKD------------------------GYDGIGEDVDQ
EDVGPATVPVAMPDFVLPPSFDS------DNPSYRYRALEPTSQFLMRPVLDSHGWDHDC
GYDGVSLERNLAVAGQFPGAFAVQITKDKKDFNIHLDSSVCAKHGENGSTMAGFDIQ-NV
GRQLAYILRSETKF----------------------------------------------
----------------------------------------------KNFKMNKTSAGISF
TVLGENVATGLKIEDQIAVAKRLALVGAAGAVRSGGDTAYGANFEVCLKSKDFPIEKDQS
TLGLSLMKWRGDLGLMANLQSQFSIGRNSKMAVRVGMNNKRSGQVTIKTSSS-EMQVALI
AIVPIVTSLLRSIYSGYAASNSHTLDY
>gnl|BL_ORD_ID|34277 @Populus_trichocarpa@_POPTR_0010s01820.1|PACid:18240675
MAFFPLFLFLLLLCFPVGC-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------CFV
APLEE-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------KELLRRKWLLLLWGSVE-A
-------------VALTSPDGSRVFSLERLVGSASPFRIVRLAP--LSE-----------
-T------------VVDVVKNDLNEED-MVIEKIQKMAVKFL------------------
------------------------------------------------------------
----RIVQRLGQSP----------------------------------EDSIVAQVLHRL
-----------------------KMATQLEAEGK--------------------------
----------------------------------------------DDLDFSLNILVLGK
TGVGKSATVNSV--------------------------------------------FGEK
K--------------V-----EINAFEP----------------------------ATTT
V--KEIVGTV--DGVKL-RIIDTPGLRSSV-NEEVV---NRK-----------------I
LASIKNSIKNFPPDV-----------------VLYTDRLDTHSRDLIDLPF---------
------------------------------------------FEMFVGQRSHVIQQVIS-
--------------QAVGDLCLIHSRMIHPVSLVENHPLCRKNDN---------------
RENILPNGQDWRPPL-----LLLCYSLKILSEASSVAKPRDPFDHKKPFNFRLRSLPL--
------------------------------------------------------------
---------------PHLVSTLLQSRTHPKLTSDQGGDDV---NSDIEESLL--------
------------------------------------------------------------
-----------------------------------------------------------E
EV-----------KRMKEVKDKGKD-GR----------N----------GYDGIGEAVDQ
EDVGPTTVPVAMPDFFFPPFFDS------DNPSYRYQALELTSQFLVRPILESHGWDHDC
GYDGVSLERNIAI--------AFQITK---------DSSVCAKYGGNGSTMAGFDIQ-NV
GRQLAHILRSETKI----------------------------------------------
----------------------------------------------K-------------
------------------------------------------------------------
--------WAG--------HHQGKQLRNASCPYR--------------------------
----------------------YLFEV
>gnl|BL_ORD_ID|41513 @Populus_trichocarpa@_POPTR_0008s22140.1|PACid:18247976
MM----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------NGVEDGRLSDVVK
VP--------------SFGVQERE--DTVLRV-----KALGTEEEKEGELLVQSNSSSVD
NQ--SGLLMERDDGPDNVVLGPKDAA--VMNGSVNDSGSVNLVEDNSHVVTVIQPINLLV
ND-------ESPETSEGDRMEDLRESYTTSHDIK--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------DEANLDSETIGGQEGLLSD
DHIEELIFGG--------------SAFSSPPGIEAYHDHPQT-------IDAQITMDSDE
D-------------------------TDSDEEADVVKEPVGKQLFDYDALAALLKAAT-G
AELD------GGRIAISSVDGSGLFSLERPAGSGFPFHSRRPAP--PP------------
----------------DVLKCTLSEEEEKILEKIHNIRVKFL------------------
------------------------------------------------------------
----RLVQRLGQSP----------------------------------EDSIVESVLHRL
DPGEGKRFSR-----VFSLENAKSMATQLEAEGK--------------------------
----------------------------------------------DDLDFSLNILVLGK
TGVGKSATINSI--------------------------------------------FGEK
R--------------V-----EINAFAP----------------------------ATTR
V--NEIVGTI--NGVKI-RIIDTPGLMSSV-KEEAT---NRK-----------------I
LASIKKSINKFPPDA-----------------VLYVDRLDTHDRDRNDLLLLR-------
-----SLSRTLTSSIWN--GAIVTLTHAASPPPDGPSGSSLGFDVYVAQRSRVIQQAII-
--------------QSVGDPHLMHPSMKRPVSLVENHSLCQKNEN---------------
RENVLPNGQSWRPQL-----LLLCYSLKVLSEASSVSKPEDVIDDKKPFGLRLRALPL--
------------------------------------------------------------
---------------PHMVSSLLQSRPHLKLPTDLSGEDI---DSDMDLVDLSDSDGED-
-EDEYDQLPP---------------------------------------FKPLR------
--------KSQVQKLSKEQR---------KAYFEEYDYRVKL----------LQKKEWRD
EL-----------KRLKEIKKRGKN-SR----------N----------DYHDIGEDVDQ
EDEGPTPVPVPLPDFVLPHSFDS------DNPSYRYRVLEPASQFLVRPVLDARGWDHDC
GYDGVSIESNLAVAGRFPGAFTVQITKDKKDFNIQLDSSICAKHGESGSTMAGFDIQ-TI
GRQLAYILRSETKL----------------------------------------------
----------------------------------------------KKFKLNKTSAGISI
TLLGENVVTGLKIEDQIAVGKRLALVGNAGTVRSGGDTAYGANLEVHLKSKDFPIEEDQS
TLGLSLMKWRGDLGLMAHLQCQFSVGRNSKMAIRVGMNNKLSGQISIKTNSS-ELQAALI
VIVPVAVSILRSIYPGSNAGSSNKLDY
>gnl|BL_ORD_ID|33365 @Populus_trichocarpa@_POPTR_0010s01800.1|PACid:18239755
MA--------SKIHVPVSTTQGTPPSLPS-------------------------------
------------------------------------------------------------
----------------------------------------------PTGFLPIRAPITVD
DFQSDGYKTDTSDSDIGSSRSGTGSNIDNGFVSGEEEFDSASERPFLGDPDEENSEEDDF
GGMYRVSRPFV----------------ADPDEEISV------------------------
-------LEEVEEEESGVTDEFIPVVGLDSGNSNGIRP---IAQLSMDDDEFDKVTGDE-
--------------------------------------------GMVSKVDDGSFSGVVK
VP--------------SFGAQEIV--DVAPLV-----KVLDIEEDKEDGLLVQSNSSSDD
NK--SRLSTERDFGADSCVLGPKDAV--VTNGSANDSGSVKLVEDNGHVVTVTQPTNLWV
NG-------DSPENSEGDKMEDVRESNTNSSGIKD-------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------EAN
RDSETIGGQKGLLSPENFEGDKMEEVRESNTNSSGIKDEANRDSETIGGQKGLLSPENFE
GDKMEEVRESNTNSSGIKDEANRDSETIGGQKGLLSSENFEDEANRDSETIGGQKGLLSD
DDIEELIFGGSGTTKLIMNELEQNSAFSSPPGIEAYHDHPQT-------IDGEITMDSDE
D-------------------------TDSDEEADEVREPVGKQLFDSAAFAALLKAAT-G
AELD------GGRIALSSVDGSGLFSLENPAGSGFQFRTRRHAP--PP------------
----------------DMVKRTLSEEEKKILEKIQHIRVKFL------------------
------------------------------------------------------------
----RLVQRLGQSP----------------------------------EDSIVESVLHRL
DPDEGRRVSR-----EFSLETAKSMAMQLEAEGK--------------------------
----------------------------------------------DDLNFSLNILVLGK
TGVGKSATINSI--------------------------------------------FGEK
R--------------V-----EINAFAP----------------------------ATTR
V--NEIVGTV--DGVKI-RIIDTPGLRSSV-KEEAT---NRK-----------------I
LASVKKLINKFPPDV-----------------VLYVDRLDTHDRDRNDLLLLS-------
-----SLSRTLTSSIWK--NAIVTLTHATSPPPDGPSGSSLAFEVYVAQRSHVIQQAIS-
--------------QAVGDSYLMHPSMKHPVSLVENHSLCQKNEN---------------
GENVLPNGQSWRPQL-----LLLCYSLKVLSEASSISKPQDLIDHKKPFGLRLRSLPL--
------------------------------------------------------------
---------------PHLVSSLLHSRPHLKLPTDLGDEDI---DSDMDLVDLPDSDAED-
-EDEYDQLPP---------------------------------------FKPLR------
--------KSQVQKLSKEQK---------KAYFEEYDYRVKL----------LLKKQWRD
NL-----------KRLKEIKKRGKD-CS----------N-------------DIGEDVDQ
EDEGTEL-------WSLHHSFLSGQFWMPRAGIMIADMMVLTSKVILLLLV---------
-------------------SFLVHL-----------------------------------
------------RF----------------------------------------------
----------------------------------------------KSQKIRKTS-----
------------------------------------------------------------
------------------------------------------------------------
------------------------ISN
