>gnl|BL_ORD_ID|49591 @Panucum_virgatum@_Pavirv00018746m|PACid:23805811
----------------------------------MDS-----------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------DLEYEDAEPQLDNE-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------ASPVVVNDGSAEEPA--PAS
ANSVVQDSPEKEQNAE---DQAAASEAVED--------------------VGAKKLTEVE
N--------GAAAPELVPESS--------NDNNGADETTGATEVADHEEEAGERDIVVAE
AVADDEDGV--------------GNEADEDE--------DGVNSDT----------SPAR
VAILESSEAAKQIMKE------------LAEGSS-----SGSVSGSRDFNDSM-----DG
QIMLDDSED-DEDDDGDEKGFDSAALAALLKAATGGSSD--GKISVASQDGSRIFTMDRP
AGLGSSATSLRPT----------APR-QPAR-----------------------------
------------------SN--PYSPSELAVTADPTEEMTEEEKKLHEKV---ELIRVKF
LRLVYRLGATPEETVAAQVLYRLSLAEGIRHGRQTNR--AF-------SLDNA------R
RKAL------ILEAEGKEDLD-------------FSCNI---------------------
------------------------------------------------------------
-------------------------------------------LVLG---------KIGV
GK----------------------------SATINSIFG-----------EEKTRTDAFN
SATTNVREIVGDV--DG-----VKIRIIDT---P--GLRPNVM-------------DQ-G
SNRKVLSA--------------VKKFTKKCPPDIV-----LYVDRLDSLSRDLNDLPLLK
TI---TAVLGSSIWFNAIVALTHAASAPPEGLNGAPMTYEVLMAQRSHIIQQSIRQAAGD
-MR--------LMNP-----VALVENHPSCRRN---------------------------
------------------------REGQKVLPNGQSWRHQML---LLC---------YSS
K-------------------ILSEANSL-LKLQDP-NPGKLFGFRFRSPPL---------
----------------PFLLSSLLQSRAHPKLSAEQGGNEGDSDIELDDYSDVEQDDDE-
EEYDQLPPFKPLTK-----AQLVRL------------------------TKEQKNAYFDE
YDYRVKLLQKKQWKDEIRRLKEMKKRGKTDLDDDYMYANITGEND--QDPPPENVSVPLP
DMVLPPSFDCDNPTYRYRFLEPT-------------------------------------
-------------STVLARPVLDAHGWDHDCGYDGVS------------------LEETL
AILNRFPANVAVQVTKDKKEFSIHLDSSIA--------------------AKHGDNASSL
AGFDIQTVGR-----QLAYILRGE-------------------------------TKIKN
IKKNKTTGGFSVTFLGDIVATGLKVEDQLSLGKRLSLVASTGMMKAQGDTAYGANLEARL
KDKDYPIGQSLSTLGLSLMKWRRDLALGANLQSQFPIGRGSKIAVRLGLNNKLSGQITIR
TSTSEQVQIALLGLVPVAASIYRSF----RPSEPSFAY---
>gnl|BL_ORD_ID|12740 @Panucum_virgatum@_Pavirv00012228m|PACid:23768588
----------------------------------M-------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------DSEYEDAEPQLDSE-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------ASPVDVNGGSAEEPA--PAS
ANSVVEDSPEKKQNAE---DQVAASEAVED--------------------VGAKKLTEVE
N--------GAAAPELVPESS--------NENNGADETVGATEVADHKEEAGDNDIIEAE
AVADVEDGV--------------GNEADEDE--------DGANSDT----------SPAR
VAILESSEAAKQIMKE------------LAEGSS-----SGSVSGSRDFNDSM-----DG
QIMLDDSED-DEDDDGEEKGFDSAALAALLKAATGGSSD--GKISVGSQDGSRIFTMDRP
AGLGSSATSLRPI----------APR-QPAR-----------------------------
------------------SN--PFSPSELAVTTDPTEEMTEEEKKLHEKV---ELIRVKF
LRLVYRLGATPEETVAAQVLYRLSLAEGIRHGRQTNR--AF-------SLDNA------R
RKAL------ILEAEGKEDLD-------------FSCNI---------------------
------------------------------------------------------------
-------------------------------------------LVLG---------KIGV
GK----------------------------SATINSIFG-----------EEKTRTDAFS
SATSNVREIVGDV--DG-----VKIRIIDT---P--GLRLNVM-------------DQ-G
SNRKVLSA--------------VKKFTKKCPPDIV-----LYVDRLDSLSRDLNDLPLLK
TM---TAVLGSSIWFNAIVALTHAASAPPEGLNGAPMTYEVLMAQRSHIIQQSIRQAAGD
-MR--------LMNP-----VALVENHPSCRRN---------------------------
------------------------REGQKVLPNGQSWRHQML---LLC---------YSS
K-------------------ILSEANSL-LKLQDP-NPGKLFGFRFRSPPL---------
----------------PFLLSSLLQSRAHPKLSAEQGGNEDDSDIELDDYSDVEQDDDE-
EEYDQLPPFKPLTK-----AQLVRL------------------------TKEQKNAYFDE
YDYRVKLLQKKQWKDEIRRLKEMKKRGKTDLDDDYGYANITGEND--QDPPPENVSVPLP
DMVLPPSFDCDNPTYRYRFLEPT-------------------------------------
-------------STVLARPVLDAHGWDHDCGYDGVS------------------VEETL
AILNRFPANVAVQVTKDKKEFSIHLDSSIA--------------------AKHGDNASSL
AGFDIQTVGR-----QLAYILRGE-------------------------------TKIKN
IKKNKTTGGFSVTFLGDIVATGLKVEDQLSLGKRLSLVASTGMMKAQGDTAYGANLEARL
KDKDYPIGQSLSTLGLSLMKWRRDLALGANLQSQFPIGRGSKMAVRLGLNNKLSGQITIR
TSTSEQVQIALLGLVPVAASIYRSF----WPSEPSFAY---
