>gnl|BL_ORD_ID|19945 @Phaseolus_vulgaris@_091025519m|PACid:23550718
MDS---------------------------------------------------------
------------------------------------------------------------
---------------------------------SQSSFPQSSVLLSHQSPSLDVASD---
---DSENEGF----------------ASGEEGDFEVDSTG--PILVKSSAPLQEPKLD--
---------GPLQEAHRPIAK---VSQDDDDGSVE-----DADDVAEPDADG--------
VVWENTAERGES---VTDGDFSDSNEVF------------VEASGGDDREPESAAA----
----VENGVGADKGFEGDGVGLDEREEEDKAVEEVNDGG-TNHLDSV----VDEKGEG--
------GVVEKDGGGGLEVNLLGSGVVGGGDELGVQESKIKGLD----------------
-----EAAGVSLDNGFEAIEKGGAE--------------DDVGGVQNVDDPD-GVTGGDK
SVVQNVDDPDGVTGGDESVVQNVDDSDGVIGGDDE---------SGENGVGGDELK----
-SDIVVPHEERGGSEFVEQDEI--KEGDVEGEIENHVEEEGG-----DEVEVGHYGDREI
DGLVRDENIGSSDE---KVEEVENDGSYDDDREINGSVSDE---KVEEVVYGSNAAAANK
FLEDLE------------------------------------------------------
--------------------------------------------LQQLSRARDGK-----
---------------------------------ELFDTATLAALLKAAS-----------
-------------------GADQDG-------GSITITSQDGS-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------RLFSVE--RPAGLGSSLQSGKPAM
R----P--TRPNLFSPSINRGSAVPDSSMSEEEKK-------------------------
---------------------------------------------KLSALQDIRVKYLRF
VHRLG------------------------------------FTTEESIAAQVLYRM----
------------------------TL---VAGRQS-------------------------
------GQM--FSLESAKETAIRL-------------------------EEEGRDDLDFS
VNILVLGKAGVG-KSATINSIFGE----TKTCINSCGPATTAV-----------------
------K------------------------------------EIVGV--VDGVK-----
---------------------IRIFDTPG-------------------------------
----------------------------LKSSAFEQ-NFN------------TKVLSAVK
RLTKKCPPDIVLYVDRL---------------------DLQT------------------
------------------------------------------------------------
-------------------------------------------------RDMND------
LPMLRSI-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------------TSVLGSSIWR
NVIVTLT-----------------HGASAPP-----------------------------
--------DGPSGAPLSYDVFVAQRSHIVQ------------------------------
------------------------------------------------------------
------Q--------TIGQAVGDLRLMNPSLMNPVSLVENHPSCRKNRDG----------
------------------------------------------------------------
--------------------QKVLPNGQSWRPLLL------LLCF---------------
----------------SMKILSEAGNASKAQESFDHRRLFGFRTRSPPLPYLLSWLLQSR
TY----------PKLPADQAGA-DNGDSDTEMADLSD--SDL-DEEEDEYDQLPPFK---
------------------------------------------------------------
PMRKSQVAKLTNEQKKAYIEEYDYRVKL-----LQKKQWRDEL-----------------
-------RRMREVKKRGNA-KVDDYGYP-EEDDQ--------------------------
-----------------E------------------NGTPAAVPVPLPDMALPQSFDSDN
PAYRYRFLEPTSQLLTRPVLDNHGWDH---------------------------------
----DCGYDGVNIEHSLAIINKFPAAVTVQITKDKKDFSIHLDSSVAAKLGENGSSMAGF
DIQNIGKQLAYIVRGETKFKNFKRNKTSGGVSVTFLGENVSTGLKIE-------------
------------------------------------------------------DQIAVG
KRLVLVGSTGIVKSQTDSACGANLEVRL-------------READFPIGQDQSSLSLSLV
KWRGDLALGANLQSQFSLGRSYKMAVRAGLNNKLSGQISVRTSSSDQLQIALVAILPIAK
AIY---------------------------------------------------------
---KNFWPGAS--------------------------------------ENYSIY
