>gnl|BL_ORD_ID|20495 @Ricinus_communis@_30129.m000375|PACid:16818660
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------SWAEIV---------------
INKGKEV----------------------------LVGTG--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------ETADNYSA
ENEKSEVSGGEE---VERSDTL----------GSENEKLDTGTSEPNF-------EADNG
EKFTTSG----GDSVVEAVHVDTSESGVVFVGG----------VEESKDSETKEDEVLA-
----------DGSVP-LNNGFDKISRDVEGPGDVDIKSEKNVEAVTDFSTEPAEMECNG-
-------KEIDVSGVV---EGVTPAIN----GAVTKESLDMMEVSVEKNEPNETIDKEL-
---------------------ELETDKGIKQIEPAVETAIDVSDAMANYQVDGGNGDETL
AI--NSNSEIPQTNVADGTSNAIKELEDEVFGGHDVPESAELGAVTSREVELEA-ENEEE
NLGGGDDENKGSVTDGENEGMIFGSSEAARQFLEELER-GSGIGAH-DGAESSHDHSERI
DGQIVTDSDEEVDTDEE-------------------------------------------
------------------------------------------------------------
----------------------------------------GRQTNQ-----VFSLDAAKR
TALQLEAEGKEDLEFS-----L------------------NILVLG--------------
--KAG----VGKSATINSI-------------FGEEKSPIHAFEP---------------
-----------------------------------------ATNSVKEITGLV-------
---------------------DGIKIRVIDCPG-LK------------------------
-------------------------------SSGSEQGLNRKLLSSVKKFMKKCPPDIVL
Y----------VDRLDTQTRDLN-------------------------------------
-------------DLPLLRSITSSLGSSIWRNA---------------------------
------------------------------------------------------------
------------------------------------------------------------
---------VVTLTHAASAPPDGPSGSPLSYEVFVAQRSHVVQQSIGQAVGDLRLMNPSL
MNPVS-----LVENHSSCRKNRDGQKVLPNGQTWRPQLLMLCYSMKILS--------EAS
SLSKPQDPFDHRKLFGFRSRSPPLPYLLSWLLQSRSHPKLSSDQGV-DNVDSDVDLADLS
DSDDEE-EEDEYDQLPPFKPLRKNQLAKLSKEQKKAYFEEYDYRV---------------
-------------------------------------------------KLLQKKQWREE
LRRMREIRKKGKA-PVDEYGYNEEDVDPENGAPAAVP-VPLPDMVLPPSFDGDNPAYRYR
FLEPTSQFLARPVLDTHGWDHDCG-YDGVNVEHSLAIVNRFPATVAVQVTKDKKEFSVHL
DSSVS-------------------------------------------------------
------------------------------------------------------------
-----------------------------------------AKHGDKGSSMAGFDIQNVG
KQLAYIFRGETKFKNFKMNKTAAGVSVTFLGQNVASGFKLEDQIALGKRLMLVGSTGTVL
SQGDSAYGANLEVRLREADYPIGQDQSSLGLSLVKWRGDLALGANLQSQFSIGRNSKIAV
RAGLNNKMSGQLTVRTSSSDQLQIALVGLLPIAMSIYKSLRPGVSES--YMY----
