>gnl|BL_ORD_ID|4590 @Setaria_italica@_Si004865m|PACid:19677955
QEA--------------------AMATTTDAAAVAPVEEENPAPVAA----EAAAEEDPT
KKVEPAMDITTDAAPVAPPL------EDEKPAPAAGEEEPREYSESKEIKAGRGEEEEVR
LEGHGEGFGGPEAENGEAKGAGGGGDGGKVEEAEEDVKGVSQGAAEAEKDDVGGEAVAAP
APAVESKSETGELGEEDASLASPDAPEGDEKGGLREEQEEAGAAVEAEAVDKVADDGQSA
VAEE--EKREPEAAKGEEVVSGGGDVGELGDEKEVEFSARSMEVTKPEDKV---------
PVAESNGELADKK--GASDDVVALGSEEALEESTNKGADVEDEAANPEPASEPSPVDSP-
--EKGQN-AEGQDAASEAPKESTNMD-------ADLEDEAAKVQPSSE------------
---TSPVVVNDGSAEEPSPARTDSVIEDSLEK------EQAAEEQAAASEAVEDAGAKKL
KE------------------------VENGAAAPELAPESSNE-----------------
--------------------------YNGADETKGATEVADHEEE-AGDSDI--I--E--
-----AE-AVADVEDGVG-------NE---ADEDDD-------GANSDTSPA--------
--------------RVAILESSEAAKQIMKELAEGSS----------RGSVSGSRDFAES
MDGQIMLDDSE---------------------------------DDDDDDEEDGDE-KGF
DSAALAALLKAATGGSSD--GNITVASQDGSRIFTM------------------------
----------------------------------DRPAGLGSSATSLRPTAPRQPARPN-
-------------------PFSPSELAVTAD--------------------PTEEMTEEE
KKLHDKVELIRVKFLRLVY--------------------RLGATPEETVAAQVLY-----
-RLSLAEGIRHGRQTNR--AFSLDNARRKALLL-----------EAEGKED---------
----LDFSCNILVLGKVGV-----G------------------KSATINSI---------
------------------FGEEKTRTDAFSSAT-----------------------TNVR
EIVGVVDG-------VK-------------------------IRIIDTP-----------
---------------------------------------------------GLRSNVMDQ
-------------GSNRKVLSAV--------------KKFTKKCPPD---IVLYVDR---
-----LDSL----SRDLNDLPL-------LKT--IT----AVLG----------------
------------------------------------------------------------
------------SSIWFNAIVALTHAASAPPEGLNGAPMT--------------------
------------------------------------------------------------
--------------------------------YEVLMAQRSHIIQQSIRQAAGDMR----
-LMNPVALVE-----------------------------NHPSCRRNREGQKVLPNGQSW
RHQML-----L------LCYSSKILSEANSLLKLQDP-NPGKLFGFRFRSPPLPFLLSS-
-LLQSRAHPKLSAEQ---------------------------GGNEGDSDIELDDYSDVE
QDDEE-EEYDQLPP--------FK-----------------------------------P
LTKAQLLRLTKEQKNAYFDEYDYRVKLLQKKQWKDEIRRLKEMKKRGKTDLDDDYGYANI
AGEND--QDPPPENVSVPLPDMVLPPSFDCDNPTYRYRFLEPTSTVLARPVLDAHGWDHD
CGYDGVSVEETLAILNRFPANVAVQVT----KDKKEFSIHLDSSIAAKHGDNASSLAGFD
I-----------------------------------------------------------
---------------QTVGRQLAYILRGETKIKNIKKNKTTGGFSVTFLGDIVATGLKVE
DQLSLGKRLSLVASTGMMKAQGDTAYGANLEARLKDKDYPIGQSLSTLGLSLMKWRRDLA
LGANLQSQFSIGRGSKMAVRLGLNNKLSGQITVRTST---------------------SE
QVQIALMGLVPVLASIYRSF----RPSEPSFAY---
>gnl|BL_ORD_ID|27643 @Setaria_italica@_Si021197m|PACid:19701162
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------MVTASEVVEDIGVKKP
LE------------------------VENIAVVIE---DISVE-----------------
--------------------------KFIEIENVVAIEGVDVKPELASEPSI--VPLE--
-----VE-NIADVVEDIG---VVKPTE---IEDVVL-------VEGIDVKPE--------
--------------SV----SEVVHDGSVKEFDPVST----------DSVLEDSHGKEQN
AEGLATISEAV---------------------------------EDDGDDNGD----KGF
DYATL-----APTGGPSY--GNIIFSSQDGSGILNM------------------------
----------------------------------DWAGGLGSSTPSLRPTAPHQPAGSN-
-------------------LFITSELALTDD--------------------PTEEMTEEE
KKLHDKVELIRVKFLRLVY--------------------RLGATLEETVVAQVLY-----
-RLSLVEGIIHGRQTNQ--AFSLDYTWKKALIL-----------EAEGKED---------
----MNFSCNILVLGKTGV-----G------------------KSATINSI---------
------------------FGEEKLKTDAFSLAT-----------------------TSMR
EIVGDVHG-------VK-------------------------IRIIDTP-----------
---------------------------------------------------GLRPSVMDQ
-------------GSNRKILVAV--------------KKYIKKCPPD---IVLYVDR---
-----LDCL----SRDLSDLPL-------LKT--IT----AILG----------------
------------------------------------------------------------
------------SSIWFDAIVALTHAAST-PEGLNGAPMT--------------------
------------------------------------------------------------
--------------------------------YDVIMAQSSHIIQQSIRQAAGDMR----
-LMNPVALVE-----------------------------NHPSCRRNSEGQKVLPNGQSW
RHQML-----L------LFYSSKILSEANSLLKLHDP-NQENHFGFHFSSLALHFLLSS-
-LLQSRAHPKLLVEH---------------------------GGNEGNFDIELDDYSDVE
QADDE-EEYDQLPP--------F-------------------------------------
------------------------------------------------------------
-------------------PDMVLPPSFDCDNPTYRYRFLEPTSTVQARPVLDAHGWDHD
CGYDTISVEETLAILNRFPAKVAVQVT----KNKKEFSIHLDSSIVAKHGENASSLAGFD
I-----------------------------------------------------------
---------------QTVGRQFAYILRGESKIKNIKKNRTTGGFLVTFLGDTVATGLKVE
DQLYLGKRLSLVARTGAMRVQGDTAYGANLEAHLKDKECPIGQSLSTLGLSLMKLRQDLA
LGANLQSQFSIGIGSKMALHLGLNNKLSGQITVKTST---------------------SE
QVQIALLGLMPVAASIYKSF----RPSKP-------
