>gnl|BL_ORD_ID|6113 @Selaginella_moellendorffii@_170624|PACid:15407391
-MD---------------------------------------------------------
---------------------------------------YFPDKKPE-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------DDENEKHEEVDYKKPEEA------------
GNEKHG-EADVIGSAAEAVRSQEEREPVPETDSDEEEEEEVDTSAALRAFAQAAAATETP
SLGS------AGPSLPAKPTATRLLSSIEGARNTQVAAHNPSGGSETTTAVEAADTNGEP
NDENVE-----TREKLQMIRVKFLRLAQRLGQSANNAVVAQV------------------
-----------------------LYRLGLAEQLRGGRSSSRNSAFRFERASAIAEEQEAA
GQ-EELDFTC------------------TIMVL---------------GKSGVGKSATIN
S--LFDEA-KTETNAFAYSTKKVQEITGTV------------------------------
-----------------------H-GIKLRVIDT---------PGLLPAVADQR------
-----------------------------------------------------HNEKIMA
SVK-----RFIKKSPPDIVLYF--------------------------------DRLDMQ
SRDYGDLP---LLRTITDTFGAAIWFNAIVVLTHASSAPPDGPNGLPLSYEMFVAQRSHV
VQQTIRQAAGDMR---------LMNPVSLVENHSACR-TNRSGERVLPNG----------
QVWKPQLLLLCFASKILAEANSLLKLQE---STPGK------------------------
--------------------PFM--RSKVPPLPFLLSSLLQSRPPLKHSDENAVGEDDTD
DDIEDVEDSDEED-----YDELPPFRRLTRDELDQLDKSSRD------------------
----------------------EYFEELQMREKLFQKKQWKEEIRRRREMKKRAASSDSA
E-EYPAPVDDGYDDDNKSAPV-PVPLPDMQLPPTFDSDNPVHRYRYLETASQWLVRPVMD
LHGWDRDSGYDGFNMERMFTYGK-IPASLSGQVTKDKKEANVTLECAASMKHGEGKVSQA
GF-------------------DVQTVGKDFSYTLRSETRFSNFKKNKTIAGLAMTMIGDT
LAYGMKIE-DRLMIGRRVKVVMNGGALTGKGDTAYGGT----------------------
------------------------------------------------------------
------------VEISLRDKDFPLGRSLSTCGLSVMNWHG-DMALGGNLQSQFMVGKTMV
VA-RGNLNNRGAGQITIRLSSSEQLQIALIGVMPLIKALFNSKFGTG-----QQA
>gnl|BL_ORD_ID|12035 @Selaginella_moellendorffii@_60423|PACid:15413313
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------TQGNT
EEKTRI-----LCEKLQDIRVKFVRLVHRLGQSADNGIAAQV------------------
-----------------------LYRFALAEQLKGGK--MRNSTSGYDKACAVAMEEEAS
SRDEELDFCC------------------TVLLL---------------GKSGVGKSATVN
S--IFGKP-MASTSAFSSGTNKVEVIDGTM------------------------------
-----------------------K-GIRMRVIDT---------PGLSASMADRR------
-----------------------------------------------------YNERVVA
SIK-----RCIRRNPPDIVLYV--------------------------------DRLDSQ
SK---DAA---LMRYIGDRFGPAIWFNAIIVLTHGASSPPDGPDGFPLRYDSYVGQRTRM
FQQTVRSAVGDTR---------LLNPVTLIENHPACR-TNRAGERVLPNG----------
MVWRPELLLLCFSARILAEANTYLKLPE---SMPLT------------------------
--------------------RLCE-RRSGSPMPVLLASMLQARSEVQQPDEEEYGEVDPD
ED-----EDGEAE-----FDQLPPFRRLLQDELDALDEDNRQ------------------
----------------------SYFEELALREKLFKRKLWKTQCRRWREMKNRG------
-------VEDGEDEQQQHRDMAPGISPDFALPTSFSSDDPSHRYRYVDDAS-WNVRPVLD
-SRWDHENGFNSANLDRSFHLAKNIPVSVSGQIVMDKKEYHVTFDGSAAIKHGPNRVSTG
GL-------------------DIQTVGRDVCYSLWGGTTFKNHECNKTLAGMGVTMVGEN
AVVGVRLE-DKVVIGKRAKILMSGATSLTRGDKAYGAI----------------------
------------------------------------------------------------
------------MEATVVGPDYPVDRTNCTLGLSVMNWTAKDIAYGINLHSQIHLGGTAM
VV-RGNANNRGTGQISIKVNSTDRIQLALLGLLPVIRSL----------------
