>gnl|BL_ORD_ID|9830 @Volvox_carteri@_Vocar20012343m|PACid:23133716
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PSL----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------PA
RPKGGLGGLPPR-------GLPALSSKSASPQSSSPPAPSAGPSAAQPAAAASGSAPPIA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----SMPKLPPRPGAPSGLGLGLGLGAR-------------------------------
---------PAAGAPRPPSEGVPAAAATPAAAETAP---AAAAAAAPPGVQQPAAAAAAG
P-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------AGLGLGLGGAAAQRPTLPPRPATAGTATSSAAAAAQPRPAGAQS-----
-------------------------------VGGAAAAAGGVRAMPGLPP----------
------------------------------------------------------------
-------------------------------------RPA--------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------GLGGA--------------
------------------------------------------------------------
------------------------------------------------------------
------------PPAPAAAAAATAG--AAAAATPSMDVVDRTE----DRRVQRVQRTAHE
I------RVRLIRAATRLGLSPRS-----------------------DQVAQF-------
----LQAIERSERMVGAQHYKGTRRVDLIAAAEREARELDSREPPHSPIAGLR-LK----
-------------------ILVLGMTGTG-KSELINSLLDRPASSRTSPFREATRRVRVI
RGHHNGIPLTF----------------IDT------------PGLHASVSCTAENKAILR
SIKAAYNCFKPDYVFYVDRLDAPRPGLG-----------ELGVLSLIAEALGPGVWRNTM
AVLTHAHAA----RAAFGGQYDINSRQRRNIITQ-LLRQVAGD-----QQSRNPVFLVDC
HPSC--PTNSLGQQVIQEGPSAV----PWKQQLLGQTVGYKSYNA--AAAVFKELAKSKA
GKSAAAGGARGPQDIFKQL-MRSRLPPMTFFVEQMTEGVLKP-----EGWATMES---VA
GLGDEVTEDEEAESFGHM-YYQHMYDLAMSGDPWAQREYAAMLRSYDKAQETFKASYEEA
DLDHAIEYGIESYVVDPIDFG--------------------------PSFDPEDLYSYRH
AYAEAADSAITVIPSQDYYGPEHEDPLNGFVMQYESQP----------------------
-------------------------------------------FARHGWGGVPFDLSVCV
EKDKTSLCLQGETHLTVVHSVPPFGPRQVTQLTGSWEMLRPNIKDVMYQLEV-----DTF
KDGL------------LGRNDHAGCGMMLARLGEGGNPRKGPVAVGVRVQDTFRLGAFKV
EACASKVAVQGPTGG-KEEGWGARAFVMYDWLPGVGIALDAIQEKGSEESGKRQRGYGIN
VTYD------------------------------------------------WE---MLG
AA----------FGAEFDYVAASK-----------SLYVSVNAFSGNDYRLAWVLLLPAL
GSDEIEWETLGSVWARLRAAGGGAGQEEEAGEEEAGEEEYDEEDEDEGVAAMMAQAADM
