>gnl|BL_ORD_ID|11234 @Vitis_vinifera@_GSVIVT01017736001|PACid:17827859
M---------------------ESRPRVSLSAAQVTSSTSAGYPHDQPSEFMVSQQTLPG
FLP--------------------------IRAPLSLDS----------------------
----------------------------------DFDIYVRSDDNVISTSGSESGRNMSE
EDEFEFETASERPFVGFPDEETSVGSDDVEEYVLASPFLAVPDEETLEAPLQDEQNDA--
IGHYALTFVPVVVDDSNSKYSMPTARLSMDDD--------------------CDNGSGEE
E------LSEVEDGGFSGADRITGIRVLEEIDNVPK----------------------FK
VLGIEEDDLQPRI-----KV------NPDVFIGVGNEVLGSEKAKSLVEQSVDDLVEQ--
---RDFDNTEE-----AIS-EASAVNREDIAE-----------------ETLKLNENVKC
PSTESQVLRKLDN---QETGLKGRDVGEQSSSE-------FNNNDAVYVKLVGSR-----
-VDVKEPTEVVEESLIMVDSADVVEEYG---------------------DFKSD-ESMGN
STGKNE-IESVNRSKISILNPTHETKYLGNGDLPGATEDVMLEDQIYGKSSNSVSRIPSS
YLDPDFEVNDVANNVSEDVE----GEGTISDGDAGGLVFRSSD-----------------
------------------------------------------------------------
-----------------------------------------------TAKQIVNE-EKQS
LAPTSGSG-AQIPQHHLQTTEGQTLKDSEEKLEEDGDDEDHKIFDSEVLTSLLKAATSAG
LDGDSGNGVFTSVDDSRVFSLKRHAGLGSSLRP---------VPQSNGLNISASSDLMAG
AESKDSIS----------------------------------------------------
------------------------------------------------------------
---------------------------------------------EEEKKKLEKIQLLRV
RFLRLVQRLGHSPEDSIVSQVLYQLAIDAG------------------------------
---------------KHSNE--AFSLESAKGMAMKLEA--------EGKGDIEFSLNILV
LGKTGVGKSATINS-IFC-------------EEKAMTNAFEPT-----------------
---------------------------------TSAVNEIIGTI---DGVKIRVLDT---
------------------------------------------------------------
-PGLRSSLMEQAFN--------------------------------RKILSSIKK-----
----FMKKFPPDVV-------------LYVDRLDTEDKDLNDLPLL--------------
------------------------------------KSITSSLGSSIWRNAIVTLTHGAS
--------SPPDKPSG--------------------------------------------
------------------------------------------------------------
----------------SPLSYDLFVSQRS-------------------------------
----------------HSVQQSIRQTVG---------------DLRLMNPNLINPVSLVE
NHP--LCRKNGNGQK--------------------------------------KVIWLSA
PFPTLPYLLSSLLQSFTHPKLSTD---------QGGENVDSDIELGNMTDTDEE--NDDV
YDQLPAFKPLRRSDIAKLSKEQRKAYFEEYDYRVKLLRKKEWRQELKRLREMKKKCKDGG
NDNV-HVGEDGDQESGSPATVPVPLPDMVLPPSFDADNPAYRYRSLDAMSRHLARPVLIT
RCWDHDCGYDGVSLEENLAIAGMFPTEISVQVTKGKNEFNIHFDSSVSAKHGENGSTMAG
FNIQTIGRQVAYI------------------------------LRGETKIKNFQTNKTAA
GVSITFSGKNVAAGLKIEDQIAVGRRLVF-----------------VGSTGAILSQNDAA
YGANFEIRLKENDFPIGQDQATLGLSLMKWRNDFALMGNLQCHFSVGQSSKMAFHVGLNN
KLSGQITVRTSSLEQLQIALMGFL------------------------------------
------------------------------------PIAITIFRSLCPGSV----LFHCT
DVVIHLSRSDSKL-----------------------------------------------
---------------------
>gnl|BL_ORD_ID|18594 @Vitis_vinifera@_GSVIVT01027981001|PACid:17835219
M----------------GGWFGKSW-----------------------------------
-----------------------------VGGQFRHFS----------------------
------------------------------------------------------------
--------------ENGGFVSGEEDFETASEPIMED-----PDEEIVEKGIGGEGIDSPF
VGSSEF-FVP--------KMVMPVARVSTDDEEEEGGDDVVGGPRARVLG--GEEETGET
ESIGVGADGSKRIGLDPGVENCENEGKGVSVQMDSMEKPVVRELVEGSSIGGAAQGNSIE
ALGADNGDSTFETPKFDDRI------KEDAFLGGGTDLVGPLIAEAAAAADNKPVATESV
NIAREGDSVVD-----AIHVSVSGSGSAIVGD-----------------EGFRQNADGES
DQVSPLIAEPADNKFLEEDGVKLNGGGDSVVEA-------MHTNFSGSGPTIAGD-----
-EEENKDSEIEGKEMMVDDSVKLDKRFD---------------------QISGDLEEPVN
SKSVGV-DTDFDKSIKPVTNLNVETSELGEKTDGGVEKDQEL----------NVGAVVPI
KLD---ETNHHSDEDDEEGE----IEGSVTDEESKGMVFEGSE-----------------
------------------------------------------------------------
-----------------------------------------------AAKHFLEELEQVS
GG-----------------------------------------------------AATSA
-SSDSGSITITSPDGSRLFSVDRPAGLGSANRSLKP------APRPNRSNLFTPSNLAIG
GDSENTLS----------------------------------------------------
------------------------------------------------------------
---------------------------------------------EEDKRKQEKIQLIRV
KFLRLVQRL--------------------G------------------------------
---------------RQTGE--EFSLDTAKRRAMQLEA--------EGKDDLNFSLNILV
LGKSGVGKSATINS-IFG-------------EQKALINAFEPA-----------------
---------------------------------TTTVREIIGTI---DGVKIRVFDT---
------------------------------------------------------------
-PGLKSSFLEQGVN--------------------------------RKILSSIQK-----
----FTKKCPPDIV-------------LYVDRLDAQTRDLNDLPLL--------------
------------------------------------RTITSSLGPSIWRSAIVTLTHGAS
--------APPDGPSG--------------------------------------------
------------------------------------------------------------
----------------APLSYETYVSQRS-------------------------------
----------------HVVQQ---------------------------------------
------------------------------------------------------------
---------YYLKQSRTHPKLSAE---------Q----------------------DEDE
YDQLPPFKPLRKSQIAKLSKEQRKAYFEEYDYR---------------------------
-------------DNGGPAAVPVPLPDMVLPPSFDCDNPAYRYRFLEPTSQFLARPVLDT
HGWDHDCGYDGVNLEQSLAILGQFPAAVSVQVTKDKKEFNIHLDSSAAAKHGENGSSMAG
FDIQNIGKQLAYI------------------------------LRGETKFKILKKNKTAA
GFSVTFLGENVATGFKVEDQ----------------------------------------
-------------------------------GDLALGANLQSQFSIGRSSKMAVRVGLNN
KLSGQITVKTSSSEQLQIALVGII------------------------------------
------------------------------------PVVMAIYKAIWPGVNSILPCLHLF
QALV--------I-----------------------------------------------
---------------------
