>gnl_BL_ORD_ID_3664_AT2G16640_1_PACid_19641611
-----------------MGDGTEFVVRSDREDKKLAED-RISDEQVVKNELVRSDEVRDD
NEDEVFEEAIGSENDEQEEEEDPKRELFESDDLPLVETLKSSMVEHEVEDF----EEAVG
DLDETSSNEGGVK----DFTAVGESHG--------AGEAEFDVLATKMNG-DKGEGGGGG
-SY------DKVESSLDVVDTTENATSTNTNGSNLAAEHVGIENGKTHSFLGNGIASP-K
NKEVV--AEVIPKDDGIEEPWNDGIEVDNWEERVD---GIQT------------------
-------------------------------EQEVEEGEGTTENQFEKRTEEEVVEGEGT
SKNLFEKQTEQDVVEGEGTSKDLFENGSVCMDSESEAERNGETGAAYTSNIVTNASGDNE
VSSAV-----TSSPLEES----------------SSGEKGETEGDSTCLKPEQHLASSPH
SYPESTEVHSNSGSPGVTS------------------------------REHKPVQSANG
GHDVQSPQPNKELEKQQSSRVHVDPEITE------------------NSHVETEPEVVSS
VSPTESRSNPAALPPA--------------------------------------------
------------------------------------------------------------
----------------------------------RPAGLGRASPLLEPASRAPQQSRVNG
NGSHNQFQQAEDSTTTEADEHDETREKLQLIRVKFLRLAHRLGQTPHNVVVAQVLYRLGL
AEQLRGRNGS-RVGAFSFDRASAMAEQLEAAGQDPLDFSCT-------------------
--------------------------IM----------------VLGKSGVGKSATIN--
---------SI--FDEVKFCTDAFQMGTKRV------QDVEGLV----------------
-----------------------------QGIKVRVIDTPGL------------------
------LP-SWSD------------------------------------------QAKNE
KILNSVKAFIKKNPPDIVLYLDRLDMQSR-------------------------------
---------------DSGDMPLLRTIS-------DVFGPSIWFNAIVGLTHAASVPPDGP
NG-----TASSYDMFV-----------------------TQRSHVIQQAIRQAAGDMR--
---LMNPVSLVENHSA-CRTNRAGQRVLP-NGQVWKPHLLLLSFASKILAEANALLKLQD
NIPGRP-FAARSKAPPLPFLLSSLLQSRPQPKLPEQQYGDEEDED-DLEESSDSDEE---
-SEYDQLPPFKSLTKAQMATLSKSQKKQ--YL----------------------------
------------------------------------------------------------
---------DEMEYREKLLMKKQMKEERKRRKMFKKFAAEIKDLPDGY-SENVEEESGGP
ASVPVPMPDLSLPASFDSDNPTHRYRYLDSSNQWLVRPVLETHGWDHDIGYEGVNAERLF
VVKEKIPISVSGQVTKDKKDANVQLEM-ASSVKHGEGKSTSLGFDMQTVGKELAYTLRSE
TRFNNFRRNKAAAGLSVTHLGDSVSAGLKVEDKFIASKWFRIVMSGGAMTSRGDFAYGGT
LEAQLRD-----------------------------KDYPLGRFLTTLGLSVMDWHGDLA
IGGNIQSQVPIGRSSNLIARANLNNRGA------------GQVSVRVNSSEQLQLAMVAI
VPLFKKLLSYYYP-QTQYGQ----------------------------------------
--------------------------------------------


>Toc159_gnl_BL_ORD_ID_6068_AT4G02510_1_PACid_19644015
MDSKSVTPEPTNPFYASSGQSGKTYASVVAAAAAAAADKEDGGAVSSAKELDSSSEAVSGNSDKVGADDLSDSEKEKPNLVGDGKVSDEVDGSLKEDSTTPEATPKPEVVSGETIGVDDVSSLSPKPEAVSDGVGVVEENKKVKEDVEDIKDDGESKIENGSVDVDVKQASTDGESESKVKDVEEEDVGTKKDDEGESELGGKVDVDDKSDNVIEEEGVELTDKGDVIVNSSPVESVHVDVAKPGVVVVGDAEGSEELKINADAETLEVANKFDQIGDDDSGEFEPVSDKAIEEVEEKFTSESDSIADSSKLESVDTSAVEPEVVAAESGSEPKDVEKANGLEKGMTYAEVIKAASAVADNGTKEEESVLGGIVDDAEEGVKLNNKGDFVVDSSAIEAVNVDVAKPGVVVVGDVEVSEVLETDGNIPDVHN---KFDPIGQGEGGEVELESDKATEEGGGKLVSEGDSMVDSSVVDSVDADINVAEPGVVVVGAAKEAVIKE--DDKDDEVDKTISNIEEPDDLTAAYDGNFELAVKEISEAAKVEPDEPKVGVEVEELPVSESLKVGSVDAEEDSIPAAESQFEVRKVVEGDSAEEDENKLPVEDIVSSREFSFGGKEVDQEPSGEGVTRVDGSESEEETEEMIFGSSEAAKQFLAELEKASSGIEAHSDEANISNNMSDRIDGQIVTDSDEDVDTEDEGEEKMFDTAALAALLKAATGGGSSEGGNFTITSQDGTKLFSMDRPAGLSSSLRP------LKPA----AAPRANRSNIFSNSNVTMADETEINLSEEEKQKLEKLQSLRVKFLR-------------------------------LLQRLGHSAEDSIAAQVLYRLAL---LAGRQAGQL---FSLDAAKKKAVE--------SEAEGNEELIFSLNIL---------VLGKAG-------VGKSATIN---S------------------ILGNQIASIDAFGLS------------------------------------------------TTSVREI--SGTVN-GVKIT---FIDT-P-------------------------------------------------------------------G------------LKS-A-AMDQSTNAKMLSSVKKVMKKCPP----------------DIVLYVDRLDT-----QTRDL--NNLPLLRTITAS----------LG-T-----------SIWKNAIVTLTHAASAPPDG----PSGTPLS-YDVFVAQCSHIVQQSIGQA------------------------------------------VGDLRLMNPSLMNPVSLVENHPLCRKNR--EGVKVLPNGQTWRSQLLL----------------------------------------------LCYSLKVLSET--------NSLLRP--------------------------QEPLDHRKVFGFRVRSPPLPYLLS--WLLQSRAHPKLPGDQGGDSVDSDIEIDDVSD----------------------SEQEDGEDDEYDQLPPFKP--LRKTQLAK---------------------------------------------------------------------LSNEQRKAYFEEYDYRVKLLQKKQWREELKRMKEMKKNGKKLGESEFGYPGEEDDPENGAPAAVPVPLPDMVLPPSFDSDNSAYRYRYLEPTSQLLTRPVLDTHGWDHDCGYDGVNAEHSLALASRFPATATVQVTKDKKEFNIHLDS-SVSAKHGENGSTMAGFDIQNVGKQLAYVVRGETKFKNLRKNKTTVGGSVTFLGENIATGVKLEDQIALGKRLVLVGSTGTMRSQGDSAYGANLEVRLREADFPIGQDQSSFGLSLVKWRGDLALGANLQSQVSVGRNSKIALRAGLNNKMSGQITVRTSSSDQLQIALTAILPIAMSIYKSIRPEATNDK-------YS------------------------------------------------------------------------------------------------------------------------------------------------------------------------MY

>gnl_BL_ORD_ID_6337_AT4G02482_1_PACid_19644284
M-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------GT-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------MVLP-------------------------------WQ-------------------------------------------------------------------GFISREVSNLCNSRRNELTLGGLVTFF--------------------------GTTRSEEDSSYEGNLELRLREADFPIGQNQPHMGVSLKNSKDDLTVTANLRHQVSVGRQTKVTTFVSLDSKRTGCFTVRTNSSDQLQIAVMALLLLAM-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

>Toc120_gnl_BL_ORD_ID_26585_AT3G16620_1_PACid_19664532
M----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------GDGAEIVTRLYGDEKKL--AEDGRISELVGSDEVKDNEEEVFEEAIGSQEGLK-------------PESLKTDVLQEDFPLASNDEVCDLEETSRNERGVENLKVNYSEIGESH-GEVN-EQCITTKEADSDLVTL--KMNDYDHGEVADADISYGK------------MASS--LDVVENSEKATSNLATED--VNLENGN----THSSSENGVVSPDENK-------ELVAEVISVSACSVETGSNGIDDEKWEEEIDVSAGMVTEQRNG------KTGAEFN-------------SVKIVSGDKSLNDSIEVAAGT-------LSPLEKSSSEEKGETESQNSNGGHDIQSNKEIVKQQDSSVNIGPEIKESQHMERESEVLSSVS-----------PTESRSDTAALPPARPAGLGRAAPL------LEPAPRVTQQPRVNGN--VSHNQPQQAEDSTTAETDEHDETREKLQFIRVKFLR-------------------------------LSHRLGQTPHNVVVAQVLYRLGLAEQLRGRNGSRVGA-FSFDRASAMAEQ--------LEAAAQDPLDFSCTIM---------VLGKSG-------VGKSATIN---S------------------IFDELKISTDAFQVG------------------------------------------------TKKVQDI--EGFVQ-GIKVR---VIDT-P-------------------------------------------------------------------G------------LLP-S-WSDQHKNEKILKSVRAFIKKSPP----------------DIVLYLDRLDM-----QSRDS--GDMPLLRTITDV----------FG-P-----------SIWFNAIVGLTHAASAPPDG----PNGTASS-YDMFVTQRSHVIQQAIRQA------------------------------------------AGDMR-----LMNPVSLVENHSACRTNR--AGQRVLPNGQVWKPHLLL----------------------------------------------LSFASKILAEA--------NALLKL--------------------------QDNIPGGQ-FATRSKAPPLPLLLS--SLLQSRPQAKLPEQQYDDEDDED-DLDESSD----------------------SEEE----SEYDELPPFKR--LTKAEMTK---------------------------------------------------------------------LSKSQKKEYLDEMEYREKLFMKRQMKEERKRRKLLKKFAAEIKDMPNGY-SENVEEERSEPASVPVPMPDLSLPASFDSDNPTHRYRYLDTSNQWLVRPVLETHGWDHDIGYEGVNAERLFVVKDKIPVSFSGQVTKDKKDAHVQLEL-ASSVKHGEGRSTSLGFDMQNAGKELAYTIRSETRFNKFRKNKAAAGLSVTLLGDSVSAGLKVEDKLIANKRFRMVMSGGAMTSRGDVAYGGTLEAQFRDKDYPLGRFLSTLGLSVMDWHGDLAIGGNIQSQVPIGRSSNLIARANLNNRGAGQVSIRVNSSEQLQLAVVALVPLFKKLLTYYSPEQMQYG-------H---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

>Toc90_gnl_BL_ORD_ID_27842_AT5G20300_1_PACid_19665789
M-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------KGFK-------------------------------------------------------------------------------------------------------------------------------------------DWVFALSNS--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------MASSRPLLGSDPFFR--------DPHQEQDNHSQAPAAPQPVTLSEPPCSTSSDLEILPPLSQQ----------QVPLESLYQSSIDLNGKKHNPLAKIGGLQVQFLR-------------------------------LVQRFGQSQNNILVSKVLYRVHLAMLIRAEESELKNVKLRQDRAKALARE--------QESSGIPELDFSLRIL---------VLGKTG-------VGKSATIN---S------------------IFGQPKSETDAFRPG------------------------------------------------TDRIEEV--MGTVS-GVKVT---FIDT-P-------------------------------------------------------------------G------------FHPLS-SSSTRKNRKILLSIKRYVKKRPP----------------DVVLYLDRLDM-----IDMRY--SDFSLLQLITEI----------FG-A-----------AIWLNTILVMTHSA-ATTEG----RNGQSVN-YESYVGQRMDVVQHYIHQA------------------------------------------VSDTK-----LENPVLLVENHPSCKKNL--AGEYVLPNGVVWKPQFMF----------------------------------------------LCVCTKVLGDV--------QSLLRF--------------------------RDSIGLGQPSSTRTAS--LPHLLS--VFLRRRLSS------GADETEKEIDKLLNLD----------------------LEEE----DEYDQLPTIRI--LGKSRFEK---------------------------------------------------------------------LSKSQKKEYLDELDYRETLYLKKQLKEECRRRRDEKLVEEE---------NLEDTEQRDQAA---VPLPDMAGPDSFDSDFPAHRYRCVSAGDQWLVRPVYDPQGWDRDVGFDGINIETAAKINRNLFASATGQVSRDKQRFTIQSETNAAYTRNFREQTFSVAVDLQSSGEDLVYSFQGGTKLQTFKHNTTDVGVGLTSFGGKYYVGGKLEDTLLVGKRVKLTANAGQMRGSGQTANGGSFEACIRGRDYPVRNEQIGLTMTALSFKRELVLNYGLQTQFRPARGTNIDVNINMNNRKMGKINVKLNSSEHWEIALISALTMFKALVRRSKTEMTEENEEEKIVNFL------------------------------------------------------------------------------------------------------------------------------------------------------------------------VS

>Toc34_gnl_BL_ORD_ID_30278_AT5G05000_1_PACid_19668225
M----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------AALQT-------------------------------LREWIGIQQFPPATQSKLLEILG--------------------------------------KYKEEDVSSLTVL---------VMGKGG-------VGKSSTVN---S------------------VIGEKAAAVSTFQSE--------------------------------------------------GLRPTLVSRTRS-GFTLN---IIDT-P-------------------------------------------------------------------G-----------------LIEGGYVNDQAINIIKRFLLNMTI----------------DVLLYVDRLDV-----YRVDD--LDRQVVGAITDA----------FGK------------EIWKKSALVLTHAQFSPPDG---------LN-YNHFVSKRSNALLKVIQTG------------------------------------------AQLKKQDLQGFSIPVILVENSGRCHKNE--SDEKILPCGTSWIPNL------------------------------------------------FNKITEISFNG----------------------------------------------------------------------------------------------------------------------------------NKAIHVDKKLVEGPNPNE---------------------------------------------------------------------RGKKLIPLMFAFQYLLVMKPLVRAIKSDVSRESKPAWELRDSGLASRRS-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

>Toc33_gnl_BL_ORD_ID_12992_AT1G02280_1_PACid_19650939
M----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------GSL---------------------------------VREWVGFQQFPAATQEKLIEFFG--------------------------------------KLKQKDMNSMTVL---------VLGKGG-------VGKSSTVN---S------------------LIGEQVVRVSPFQAE--------------------------------------------------GLRPVMVSRTMG-GFTIN---IIDT-P-------------------------------------------------------------------G-----------------LVEAGYVNHQALELIKGFLVNRTI----------------DVLLYVDRLDV-----YRVDE--LDKQVVIAITQT----------FGK------------EIWCKTLLVLTHAQFSPPDE---------LS-YETFSSKRSDSLLKTIRAG------------------------------------------SKMRKQEFEDSAIAVVYAENSGRCSKND--KDEKALPNGEAWIPNL------------------------------------------------VKAITDVATNQ----------------------------------------------------------------------------------------------------------------------------------RKAIHVDKKMVDGSYSDD---------------------------------------------------------------------KGKKLIPLIIGAQYLIV-KMIQGAIRNDIKTSGKPL--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

>gnl_BL_ORD_ID_7436_AT4G15810_1_PACid_19645383
MESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLL-----------------------------------------------------------------GEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDK------------LDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNI----------GELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLV------------------------------------------------------------ESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDR------------------------KLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIMEN--ETMARLIHNHTFMELDEYEGTGD---------------------------------------------------------------------TSEKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQLLKEKLQR-------------------------------IIRRTCLSRENSTVTKVASKMSLA---GGEHPTSLGLDHMFDGTKIVLPE--------QEFPA--DLDFSINVL---------VIGKTG-------VGKSATVN---S------------------IFGETKSAVGAFGVT------------------------------------------------TNSANYV--VGNVG-GIQIS---ILDT-P-------------------------------------------------------------------G------------LLS-S-ATEEQFNQEVLIA-------RCL----------------GIVLAENNMSF-----FSANK--SSESTC-------------------------------------------------------------------------------------------------------------------------------------------------------------------SDWRLNLLI----------------------------------------------LCCSVKIRSKA--------GSLQKQ--------------------------NTDVEKAGVFGSQLSS--FTLFCSLWNVLLNSGHTSHSHDDLEEKKRKLLDSYPEII----------------------WDEQSQECLEQETL------------------------------------------------------------------------------------LVENQESEDVERQHEKGTVLGRVRTRR--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------GRLGFQATKRFGIYLDTSDVHAGFSIGSRD-----------------------------------CRRNVQEEGKILVRMRGS----MSVLGLVPMLISVFTSGKDI----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

>gnl_BL_ORD_ID_19118_AT1G33950_2_PACid_19657065
M-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------NKGGAQQKGHSSKQAENIV---------LVGRTG-------NGKSATGN---S------------------LIGKKVFASKAHASG------------------------------------------------VTMKCQTHGVVTKD-GHKIN---VIDT-P--------------------------------------------------------------------------------------VSAEYISKEIVRCLT--LAEGGI----------------HAVLLVLSART------RITQ--EEENTLRTLQAL----------FG-S-----------QILDYVVVVFTGGDVLEECK---------ET-LEDYLGRDCPTFIKEVMRM------------------------------------------SSNRK----------VVIDNKTHDEG-K--KAEQVHK----------L----------------------------------------------LSLVDDIRRSK--------CGEA-Y--------------------------TDDTYH-------------------------------------------------MI----------------------KEES-EKLRKHHEELESKN--YSEECAAE---------------------------------------------------------------------MKNQSLIL-YKENLKQMSEQLEKKLKDAAEAQEKALSKMTQ-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ENNELNLALKIHI----------------------------------------------------PLPPITPCN------------------------------------------------------------------------------------------------------------------------------------------------------IL
