>TOC100
M-------------------------------------ESEKPGIVSILAAATVDSEKPR
VSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEE
LGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEE
VRMNYSDKLDDGLMSFGNIEESS-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------LGVPPEGSSDFMAENEGNSSEASIELGQN
FKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSN
IGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSL
VEQGV-GQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDS---------------
------------------------------GDKDAGNMIGKAEEHCENDRGAVSELEKLE
CADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQES
DDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIMENETMARL
IHNHTFMELDEYEGTG--------------------------------------------
--DTSEKLTGSSFQNSSELLSSNHSVELISERVKE----RVEKTQLLKEKLQRIIRRTCL
SRENSTVTKVASKMSLAGGEHPTSLGLDH------------------MFDGTKIVLPEQE
FPADLDFSIN-VLVIGKTGVGKSATVNSIF-----------GETKSAVG-----------
-----------------------------------------AFGV---TTNSANYVVGN-
VGGIQISILDTPGL------LSSATEE--------------------QFNQEVLIARCLG
-----IVLAENNMSFFSANKSSESTCSD--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------WRLNLLILCCSVKIRSKA
GSLQKQNTDVEKAGVFGSQLSSFTLFCSLW----------NVLLNSGHTS--------HS
HDDLEEKKRKLLDSYPEIIWDEQSQECLEQETLLVENQESEDVERQHEKGT---------
------------------------------------------------------------
---------------------------------VLGRVRTRRGRLGFQATKRFGIYLDTS
DVHAGFSIGSRDCRRNVQEEGKILVRMRGSMSVLGLVPMLISVFTSGKDI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
