>gnl|BL_ORD_ID|21165 @Brassica_rapa@_033515|PACid:22704675
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------LNMEREK
QLRGISIIAAEAVNPDKSRGIAIPAVRAVVADALLLTRSLSGTFSSAGSVPIRAPITIDD
EDDDDDDDGSVTDDGFESVSGDADDEAELEDVI-------RVLGEESVGENGDGSVVEEE
ASVNYSPLEEESESEVS-------EAKLVIPRASLSLND---DEVLGSSSGDEEAEVEDK
TLQSGDLGLVDEPECSGSVLTDVVSTEDEAVEMKVTTDRLEDGLISFGDIEDLSLGVPSG
GSKLLI--------------------------------EEDGGGSIHESDALMKPGDVQG
VEDSVVELS--------EGSGSVTGELVSTEEEMVQLNLCDDASVSFETGLGVAPGDCSE
FVVESEGNAVDVYKGLDETVSKLVEQRVGQESASKESDNKIDDGSAREADESMIQGEGSI
GSGRREPEDEDTGFMVGDAKELTKNACGA-------ECEGELEIGMNSECSQVTPTLDSA
TTRNLDVSRGIDVDVNGCGSFIQKDDQETEDEGTQESEDIDRKLPLPDEDRASSLRSSFE
LANESVENGEQIDKEVNFQSDSELNQISVGTGETSLLSVKDVERSMPEKSYVTANDVMEN
EMQMAGLIHNHNHTCLELGEYEGTGDTKEKLSESTFQNHPEELSSDNSVQLISGRVKERI
EKTKLLKEKIQKIIKG--------------------------------------------
------------------------------------------------------IDLCNE
DSAVTEVESQQSLVGEDHHTSSELDDDHVYDGTKTKLPEQELPLGLDFSINVLVIGKT--
--GVGKSA--------TINS-----------------------------I----------
-FGE----TKSA-VGAFRVTTKSSEYIVGN------------------------------
----------VGGILITI------------------------------------------
-LD---TPGLMSSA----------------------------------------------
-------------TEKRYNQEVLMSIKKSMRRFPV-------------------------
-----------------DVVLYI---------------------DRLDENPDVH------
-LLRTITSS-------------------------------LGSSIW--------------
------------------------------RNAIVVLTHAASDVPDSSSYTAQ-------
---RSSLMHQSIRE-----------AVPELSCVEQRKMPGIVLAENNMSE----------
----STCPDWRLNLLVLCCSVKIRCKSGSLVKKPDAFD-----SSQLRSFTLFCSLWNVL
LLGSNQGHASQSPDDLEEKKRRLLESYPEILWDEQSQESLEQE-----------------
-------------------------------------------------ETLPVKNQEDE
GRRQEKES------VRRRRGRLGFQATKRLGIYLDTCNLHTGFSMGSSGSRKVEQEEGKM
LVRMRGSLSVLGLVHVLTSDGHDSEDTTK-------------------------------
------------------------------------------------------------
----------------------------------------------------QSTADMTA
FVQNLLQQMQSSSLDDMGGRINELEQSINDLRAEMGVEGTPPAASKSGDEPKTPPSS---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------T
