>TOC100
-M----------------------------------------------------------
--ESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFET
DEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVI
PRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMA
ENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVE
LAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEG
NAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDS
GDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEV
AGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVE
DGNQLISRTMPENSSVIAYDIMENETMARLIHNHTFMELDEYEGTG--------------
---------------------------------------------------------DTS
EKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIR---------RTCL
SRENSTVTKVASKMSLAGGEHPTSLGLDHMFDGTKIVLPEQEFPADLDFSIN--------
----------------------------VLVIGKTGVGKS--------------------
--------A------------TVNSI-----FGETKSAVGA-------------------
-------------------------------------------------FGVTTNSANYV
VGN---VGG--IQ-----------------------------------------------
---ISILD---------TP----------------------------GLLSSATEEQFNQ
EVLIAR------------------------------------------------------
-----------CLGIVLA------------------------------------------
-------------------------------ENNMSFFSANKSSESTCSDWRLN------
------------------------------------------------------------
-----------------------------------------------------------L
LILCCSVKIR-------------SKAGSLQKQNTDVEK----------------------
------------------------------------------------------------
----------------------AGVFGSQLSSFTLFCSL---------------------
------------------------------------------------------------
------------------WNVLLNS-----GHTSHSHDDLEEKKRKLLDSYPEIIWDEQS
QECLEQETLL--------------------------------------------------
------------------------------------------------------------
----------------------------------------------VENQESEDVERQHE
KGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRGS
MSVLGLVPMLISVFTSGKDI----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
