>TOC100
M-----------------------------ESEKPGIVSILAAATVDSEKPRVSISAVRA
IAAARADSFLLT-------------------PSSEASSYSNGLDFETDEDETVLEDVVLD
GVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFD
EILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIEL
GQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYA
GSNIGELVSIEEVMVQEKSSDNVLVSF---------------------------------
----------------ESSLGVMTGEC----KE-----FLVESEGNAVDEDK--------
------------------------------------------------------------
------------------------------------------------------------
--------------GLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPR----
-----------------------------------------DE--SIGSESRDSGDKDAG
NMIGKAEEHCENDRGAV-------------------------------------------
------------------------------------------------------------
--------------------------------------------------SELEKLECAD
EPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDT
D-----------------------------------------RKLSLPDEDRASSLISSF
ETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLIHNHTFMELDEYEGTGDTSEKL
TGSSFQNSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIRRTCLSRENSTVTK-VA
SKMSLAGGEHPTSLGLDHMFDGTKIVLPEQEFPAD----LD-------------FSINVL
VI-----------GKTGVGKSAT---------------------VNSIFGETKS------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------A-VGAFGVTTNSANYVVG--
----NVGGIQISILDTP-------GLLSSATEEQFNQ-----------------------
-----------EVLIAR-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------CLGIVLAENNMSFFSANKSSESTCSDWRLNLLI
LCCS--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------VKIRSKAGSLQKQNTDVEKAGVFGSQLSSFT-------LFCSLWNVLLNSG
HTSHSHDDLEEKKRKLLDSYPEIIWDEQSQECLEQETLLVENQESEDVERQHEK------
--------------------------GTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAG
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------FSIGSRDCRRNVQ
EEGKILVRMRGSMSVLGLVPMLISVFTSGKD-----------------------------
------------------I
