>TOC100
M-------------------------------------ESEKPGIVSILAAATVDSEKPR
VSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEE
LGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEE
VRMNYSDKLDDGLMSFGNIEESS-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------LGVPPEGSSDFMAENEGNSSEASIELGQN
FKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSN
IGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSL
VEQGV-GQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDS---------------
------------------------------GDKDAGNMIGKAEEHCENDRGAVSELEKLE
CADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQES
DDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIMENETMARL
IHNHTFMELDEYEGTG--------------------------------------------
--DTSEKLTGSSFQNSSELLSSNHSVELISERVKE----RVEKTQLLKEKLQRIIRRTCL
SRENSTVTKVASKMSLAGGEHPTSLGLDH------------------MFDGTKIVLPEQE
FPADLDFSIN-VLVIGKTGVGKSATVNSIF-----------GETKSAVG-----------
-----------------------------------------AFGV---TTNSANYVVGN-
VGGIQISILDTPGL------LSSATEE--------------------QFNQEVLIARCLG
-----IVLAENNMSFFSANKSSESTCSD--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------WRLNLLILCCSVKIRSKA
GSLQKQNTDVEKAGVFGSQLSSFTLFCSLW----------NVLLNSGHTS--------HS
HDDLEEKKRKLLDSYPEIIWDEQSQECLEQETLLVENQESEDVERQHEKGT---------
------------------------------------------------------------
---------------------------------VLGRVRTRRGRLGFQATKRFGIYLDTS
DVHAGFSIGSRDCRRNVQEEGKILVRMRGSMSVLGLVPMLISVFTSGKDI----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|25057 _355185|PACid:16058804

M------------------------ESEKPGIVSIL----TDSEKPRVSISAVRAVAAAR
ADSFLLTRYVPIRAPVTIDEDDDTGSVTDEHNSASSEASSYSNGVDFETDEDETEELEDV
ILGGVRVDRLLGEEFGGEIGDESEFSGGSVIYRPFAGDVDEETSVNYSSLGEESENSDEV
EGVSESEVSEGERGSMKAKVVIPRAVLSLDDNEFDEILGSDDEEGVLLRVTKALGEEETE
IEDRGLQFGGKGVVDEPECSGSFISDVDSNEEEEVRMNYSDECDDGLVSFGNIEESSLGV
VPPGGFNDFKAETEGNSIEASMEVGKSFKQLLETGVVQRTIIKEDGSGSNNEFDALMILN
DAERVEDSAVELAEMVMTDKPEYVGSNTGELVSTEEDMVQEKSSDGGLVSFASSLGVATG
ECNEFLVESEGNAVDVDKGLDETVTVSSLVEQGVVVGQGSTSKESNNRTDVGSVCEADEL
MILGDGSIGSE-------------------------------------------------
------------------------------------------------SRDSRDEDTGNM
IGEAKEHCGNDCGAVCELEKTECEGGPEVVMSSESVQLTPPPDSETTRNLEVAGGIDVAV
SGCGSSDRKAEQESESEGNQESDD-------TDRKLSLPVEDRASSLRNSFETANETVEN
GKQINKQVIFQSDSEPNQISVG--------IEETSLPSVKEIERTMPENSSVIGYDIMEN
DTRMAPLIHNHTFVKLDEYEGTCDTRERLSESSFQNYSEVLCSDHSVQLISEKVK-----
----ERVEKTQLLKEKLQRIIRRTDLCSENLTVTEVESKLSIAGGEHQTTLGL-------
------------------------------------------------------------
-----------------------DNVSDRTKIMLPEHEF---------------------
---------------PD--DLDFSINVLVIGKTG--------------VG----KSATIN
SI-------F----GETKSLVG--AFGVTTKSANYVVGNV--GGILIRIL-DT-------
-PG------------------LMS-SATEERFNQK-VLMSIKKSMRKFPVDVILYIDRLD
E-----------------------------------------------HPDIHLLR----
--------------------IITNSLG--SSVWRNAIVVLTHAASNIPDSS------SYK
DF---------------------------IAQRCSLMH-----QSIRQAVPELSCVGQSK
MPGIV--------LAEN--------------------------NMSSFSTNKRSESTCPD
---WRLNLLILCCSVKI----RSKAGLLQKQITVVE-KADVFGNQLHSFTLFCSLWNVLL
LGANSGHTSHSHDDLDEKKRQLLDSYPKIIWDE---------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------QSQECLEQR----ESQEPEDQERRDEKGKTNRGL
EEVTVRGRMRRGRLG--------------------------------------------F
QATKRFGIYLDTSDLHTGFSIGSRGCRKNEQEEGRILVRMRGSMSVLGLVPMLISVFTSV
YGGKNI------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Brachypodium_distachyon_gnl|BL_ORD_ID|18383 _1g68540.1|PACid:21821153

MA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------TPIPRE
WVGLQQFP----------------------------------------------------
------------------------------------------------------------
--------AATQTKLHELLGKLKEENVS--------------------------------
------------------------TLTILVMGKGGVGKSST-------------------
----------------------VNSIVG-----------ERVANV---------------
---------------------------------------------------S-AFQSEGL
RPMMCSRTRAG----FTLNVIDT--PGLIEGGYINE------------------------
----------------------------------QAVEIIKRFLLDKTI-----------
---------------------------DV-------------------------------
------------------------------------------LLYVDRLDAYRMDTL---
------------------------------------------------------------
---------------------------DEQVIRAIT--NSFG-----------------K
DIWRRTLVVLTHAQLSPPDG---------------------------------------L
EYSDF----FTRRSESLLRYIRSGAGIGKRE------------------------LADFP
------------------------------------------------------------
----------------------------------------------------LPLALVEN
S-GRCKTNENGEKILPDGTPWVP-------------------------------------
-----------------------NLMKEITV-------------------VVSNGSKPIH
VDQKLIDGPNPNNRWKMYIPLILAVQYFFVVKGIRRAIHSD-------ISNGKLDDWEQR
YRDLVGSGN---------------------------------------------------
-----------------------------------------------------PVDQRVS
SSR---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------NPKA
>Brassica_rapa_gnl|BL_ORD_ID|21165 _033515|PACid:22704675

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------LNMEREK
QLRGISIIAAEAVNPDKSRGIAIPAVRAVVADALLLTRSLSGTFSSAGSVPIRAPITIDD
EDDDDDDDGSVTDDGFESVSGDADDEAELEDVI-------RVLGEESVGENGDGSVVEEE
ASVNYSPLEEESESEVS-------EAKLVIPRASLSLND---DEVLGSSSGDEEAEVEDK
TLQSGDLGLVDEPECSGSVLTDVVSTEDEAVEMKVTTDRLEDGLISFGDIEDLSLGVPSG
GSKLLI--------------------------------EEDGGGSIHESDALMKPGDVQG
VEDSVVELS--------EGSGSVTGELVSTEEEMVQLNLCDDASVSFETGLGVAPGDCSE
FVVESEGNAVDVYKGLDETVSKLVEQRVGQESASKESDNKIDDGSAREADESMIQGEGSI
GSGRREPEDEDTGFMVGDAKELTKNACGA-------ECEGELEIGMNSECSQVTPTLDSA
TTRNLDVSRGIDVDVNGCGSFIQKDDQETEDEGTQESEDIDRKLPLPDEDRASSLRSSFE
LANESVENGEQIDKEVNFQSDSELNQISVGTGETSLLSVKDVERSMPEKSYVTANDVMEN
EMQMAGLIHNHNHTCLELGEYEGTGDTKEKLSESTFQNHPEELSSDNSVQLISGRVKERI
EKTKLLKEKIQKIIKG--------------------------------------------
------------------------------------------------------IDLCNE
DSAVTEVESQQSLVGEDHHTSSELDDDHVYDGTKTKLPEQELPLGLDFSINVLVIGKT--
--GVGKSA--------TINS-----------------------------I----------
-FGE----TKSA-VGAFRVTTKSSEYIVGN------------------------------
----------VGGILITI------------------------------------------
-LD---TPGLMSSA----------------------------------------------
-------------TEKRYNQEVLMSIKKSMRRFPV-------------------------
-----------------DVVLYI---------------------DRLDENPDVH------
-LLRTITSS-------------------------------LGSSIW--------------
------------------------------RNAIVVLTHAASDVPDSSSYTAQ-------
---RSSLMHQSIRE-----------AVPELSCVEQRKMPGIVLAENNMSE----------
----STCPDWRLNLLVLCCSVKIRCKSGSLVKKPDAFD-----SSQLRSFTLFCSLWNVL
LLGSNQGHASQSPDDLEEKKRRLLESYPEILWDEQSQESLEQE-----------------
-------------------------------------------------ETLPVKNQEDE
GRRQEKES------VRRRRGRLGFQATKRLGIYLDTCNLHTGFSMGSSGSRKVEQEEGKM
LVRMRGSLSVLGLVHVLTSDGHDSEDTTK-------------------------------
------------------------------------------------------------
----------------------------------------------------QSTADMTA
FVQNLLQQMQSSSLDDMGGRINELEQSINDLRAEMGVEGTPPAASKSGDEPKTPPSS---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------T
>TOC100
-M----------------------------------------------------------
--ESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFET
DEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVI
PRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMA
ENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVE
LAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEG
NAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDS
GDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEV
AGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVE
DGNQLISRTMPENSSVIAYDIMENETMARLIHNHTFMELDEYEGTG--------------
---------------------------------------------------------DTS
EKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIR---------RTCL
SRENSTVTKVASKMSLAGGEHPTSLGLDHMFDGTKIVLPEQEFPADLDFSIN--------
----------------------------VLVIGKTGVGKS--------------------
--------A------------TVNSI-----FGETKSAVGA-------------------
-------------------------------------------------FGVTTNSANYV
VGN---VGG--IQ-----------------------------------------------
---ISILD---------TP----------------------------GLLSSATEEQFNQ
EVLIAR------------------------------------------------------
-----------CLGIVLA------------------------------------------
-------------------------------ENNMSFFSANKSSESTCSDWRLN------
------------------------------------------------------------
-----------------------------------------------------------L
LILCCSVKIR-------------SKAGSLQKQNTDVEK----------------------
------------------------------------------------------------
----------------------AGVFGSQLSSFTLFCSL---------------------
------------------------------------------------------------
------------------WNVLLNS-----GHTSHSHDDLEEKKRKLLDSYPEIIWDEQS
QECLEQETLL--------------------------------------------------
------------------------------------------------------------
----------------------------------------------VENQESEDVERQHE
KGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRGS
MSVLGLVPMLISVFTSGKDI----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>TOC100
M-----------------------------ESEKPGIVSILAAATVDSEKPRVSISAVRA
IAAARADSFLLT-------------------PSSEASSYSNGLDFETDEDETVLEDVVLD
GVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFD
EILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIEL
GQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYA
GSNIGELVSIEEVMVQEKSSDNVLVSF---------------------------------
----------------ESSLGVMTGEC----KE-----FLVESEGNAVDEDK--------
------------------------------------------------------------
------------------------------------------------------------
--------------GLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPR----
-----------------------------------------DE--SIGSESRDSGDKDAG
NMIGKAEEHCENDRGAV-------------------------------------------
------------------------------------------------------------
--------------------------------------------------SELEKLECAD
EPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDT
D-----------------------------------------RKLSLPDEDRASSLISSF
ETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLIHNHTFMELDEYEGTGDTSEKL
TGSSFQNSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIRRTCLSRENSTVTK-VA
SKMSLAGGEHPTSLGLDHMFDGTKIVLPEQEFPAD----LD-------------FSINVL
VI-----------GKTGVGKSAT---------------------VNSIFGETKS------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------A-VGAFGVTTNSANYVVG--
----NVGGIQISILDTP-------GLLSSATEEQFNQ-----------------------
-----------EVLIAR-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------CLGIVLAENNMSFFSANKSSESTCSDWRLNLLI
LCCS--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------VKIRSKAGSLQKQNTDVEKAGVFGSQLSSFT-------LFCSLWNVLLNSG
HTSHSHDDLEEKKRKLLDSYPEIIWDEQSQECLEQETLLVENQESEDVERQHEK------
--------------------------GTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAG
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------FSIGSRDCRRNVQ
EEGKILVRMRGSMSVLGLVPMLISVFTSGKD-----------------------------
------------------I
>TOC100
M-----------------------------------------------------------
------------------------------------------------------------
-----------------------ESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARAD
SFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFI
DHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMS
FGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSI
HEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVS
FESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSLVE--------------QGVGQAS
TSKESNNRTDVGSVCDAD------------------------ELIIPRDESIGSESRDSG
DKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVA
GGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRKL------------------------
SLPDEDRASSLISSFETANETV--------------------------------------
------------------------------------------------------EDGNQL
ISRTMPENSS---------------VIAYDIMENETMARLI-------------------
--HNHTFMELDEYEGTGDTSEKLTGSS-------------------------FQNSSELL
SS----------NHSVELISERVKERVEKTQLLKE-KLQRIIRRTCLSRENSTVTKVASK
MSLAGGEHPTSLGLDHM-------------------------------FDGTKIVLPEQE
FPADLDFSINVLVIGK-TGV-----GKSATV------NSI-----------FGET--KSA
VGAFGVTTNSANYVVGNV-----------GGIQIS-------------------------
---ILDT-------------------------------PGLLSSAT-----------EEQ
FN----------------------------------------------------------
------------------------------------------------------------
---------------QEVLIARCLGIVLAENNMSFFSA----------------------
--NKSSESTCSDWRLNLLI-----------------------------------------
------------------------------------------------------------
----------------------------------LCCSVKIRSKAGSLQKQNTDVEKAGV
FGSQLSSFTLFCSLWNVLLNSGHTSHSHDDLEE---------------------------
------------------------------------------------------------
--KKRKLLDSYPEIIW--------------------------------------------
--------------------------------------------------------DEQS
QECLEQETLLVENQESEDVERQHEKGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGF
SIGSRDCRRNVQEEGKILVRMRGSMSVLGLVPMLISVFTSGKD-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------I
>TOC100
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------ESEKPGIVSI
LAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVL
DGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEF
DEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIE
LGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEY
AGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDET
VSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKA
EEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCG
SSDQKAEEESENEGNQESDDTDRKLSLPDEDRASSLISSFE-------------------
-----------------------------TANETVEDGNQLISRTMPENSSVIAYDIMEN
ETMARLIHNHTFMELDEYEGTGDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVEKT
QLLKEKLQRIIRRTCLSRENSTVTKVASKMSLAGGEHPTSLGLDHMFDGTKIVLPEQEFP
ADLDFSINVLVIGKTGVGKSATVNSIFGETKSAVGAFGVTTNSANYVVGNVGGIQISILD
TPGLLSSATEEQFNQEVLIARCLGIVLAENNMSFFSANKSSESTCSDWRLNLLILCCSVK
IRSKAGSLQKQNTDVEKAGVFGSQLSSFTLFCSLWNVLLNSGHTSHSHDDLEEKKRKLLD
SYPEIIWDEQSQECLEQETLLVENQESEDVERQHEKGTVLGRVRTRRGRLGFQATKRFGI
YLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRGSMSVLGLVPMLISVFTSGKDI
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|5312 _06.g252200.t1.1|PACid:19863610

M-----------------------------------------------------------
------------------------------------------------------------
--------AQPPRPAEEY------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------DDDVQEDEDELKEGELD-------
------------------------------------------------------------
-------------------------------------------------------DDESH
EAASEGGEAAAGDEEAEDD-----------------------------------------
---EQ--------------DEEDGDEDSQPWAGLNRLPERDDMLDILN------------
--------------ELRA-----------------EGRKQLTVLLLGKSSVGKSSLINSL
L----------------------------------------G------------------
---EAVVRVQAFKLQADTDITTTVVRQ-------------------------------VA
VGNSEVDGFRLKLID---------TCGLED-PEAGDTVNLGALSKIAEDVRGVGIDVVLY
CDRLDLYRVDPL----------DKAIIDAISSTF----------------GRGIWRRTVV
ALTHANLVQTPPGTD----------YDSFVNGRVRLIRGAVRGPLFFRPSLP-----VAL
VENSETCPVSSESGFRVL--PDGEPWLVALVSQLVDMA------AARRRPYKYHPRLSSK
PSHRF-------------------------------------------------------
---------------------------------------------RWLLPVAIAAEVLFY
RRFLHPRLDDN-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------QRRVEREEERVWALRGQQRRALGLHRPHRPDKDAAWRLEQMYD---------
------------------------------------------------------------
-----------DD
>Capsella_rubella_gnl|BL_ORD_ID|8280 _v10004016m|PACid:20893956

-------MESEKPGIVSILEAATVDSKKRRVSISAVRAVEAARAESFLLTRTLSGSFSSA
GSVPIRAPLTVDDEDDDDDVDSGSVIEEHSLASSEASRGIDSGTDDGYESVSGDADDETE
LEDVIMGGDRVHRILGEELSGEIGDVSDFSGGSVIYRPFAGDADEETSVNYSSLEERSEN
SDEVEGVSENEVSEADGVSMKAKVVIPRAILSLDDDEFDEILGSGDEEAVLLRGTKASSD
EEAEIGDRVFQFADEGVVNEPECSDSFIADVVSTEEEAVRMNYSEKLDDGLMSFGNIDES
SLDVLPGGSNDFMAENEGNSTEASMELGQSFKQLMEKGEIQSTINKDNGGGNIHNFDALV
KPNDAERVEDSAVDIANMGVNDKPEYTGSNIGEFVSTEEDM-------VQEKSSDDGLVS
FKSNLDAVPGDCNEFLVESEGNTVHEDIGLDETVSSLVEQQVGQGSI---SNNRT-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------YVGSACEANELMIPCEGY
IGSESRDSGD--------------------------------------------------
----------------------------------------------LDAVNMIGEAKEYF
ENDCGALSELEKPECEDEPEIDLSSESFQVSPTLDSLMARNLDVAGGVDVVVSGCGSSDR
KTEQESINEENHE-----------------------------------------------
------------------------------------------------------------
---------------------------------------SEDIARKLSL-SEDRASS---
------------------------------------------------------------
-----------LRSSSGTANETVEIGEQINLQVNFEPDVERTMPENSPVIVERTMPENSP
VIDYEIIENETQMAQRNHNNTFMELDECK-GSGDTRKELSKSTFQDYSEVLPSNHSVELI
SGKVKERVE-----------------------------------------KTKLLKEKLQ
RIIRNTGCCSENLSDTEVVSKLSLDGGEHQASLELDYISDGTKIKIT------EQKFPAD
LELSINVLV---IGKT-----------GVGKSATVNS----------I---------FGE
TK--S-------------------------------------------------AVGAFA
VTTKSANYVVGNVG----GLRIRI------------------------------------
-----------------------------------------------LDTP---------
----------------------------GF-------------------------MSSAT
EKQFNQGVLMSIKRSMRKFPVDVIL-----------------------------------
--------Y---------------------------------------------------
-----------------------------IDRL---------DDTPDIGLLRIITS----
-----------SLGS--------------------------------------------S
IWQNAIVVLTHAASDVPDT-----------------------------------------
----LSYKDFIAQRSYLMHQSIRQAVPKLSCVGQSKMPKIILAENN---------MSSFS
ANKSSESTCPD-----------------WRLKLLILCCSVKIR-----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------SKAGSLQKQNTDVEKAG
AF------------------------------------------------------GSQR
SSFTLFCSLWNVLLNSGHTSHSQDDLE---------------------------------
EKKRQLLDSYPEIIWDEQSQECLEQETLLIENQGPEDEERQHEKGKTNRGLEEGTVIDRV
RTRRGRLGFQATKRLGIYLDTSNLHTGLSIGTGGCRNNEEEEGRILLKMRGSMPVIGLVP
MLMSVFTSVHGGKDT---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>TOC100
M-----------------------------------------------------------
-------------------------------------ESEKPGIVSILAAATVDSEKPRV
SISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEEL
GGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEV
RMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSS------------------
--------------------------------------------EASI------------
------------------------------------------------------------
------------------------------------------------------------
----ELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMN
DKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDK
GLDETVS-----------------------------------------------------
----------------------------------------SLVEQ------------GVG
QASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGA
VSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEES
ENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIM
ENETMARLIHNHTFMELDEYEGTGDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVE
KTQLLKEKLQRIIRRTCLSRENSTVTKVASKMSLAGGEHPTSLG-----LDHMFDGTKIV
LPEQEFPADLDF------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------SINVLVIGK--------TGVG---------------------------------
------------------------------------------------------------
----------------KSATVNSI-----------F------------------------
------------------------------------------------------------
----------------------------------GETKSAVG-----AFG----------
---------------------------------VTTNSANYVVGNVG---GIQ-------
------------------------------------------------------------
------------------ISI----------------LDTPG------------------
------------------LLSSATEEQFNQEVLIA--------------RCLGIVLAEN-
-----------NMSFF--------------------------------------------
------------------------------------------------------------
------------------------------SANKSSESTCSDWRLNLLILCCSVKIRSKA
GSLQKQNTDVEKAGVFGSQLSSFTLFCSLWNV----------------------LLNSGH
TSHSHDDLEEKKRKLLDSYPEIIWDEQSQE------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------CLEQETLLVENQESEDVERQH
E-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------KGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKIL
VRMRGSMSVLGLVPMLISVFTSGKDI----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>TOC100
----M-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----ESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDF
ETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKV
VIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDF
MAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSA
VELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVES
EGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESR
DSGDKDAGNM--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------IGKAEEHCENDRGAVSELEKLECADEPEIGMSSES
FQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRKLSLPDED
RASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLIHNHTFMELDEYE
GTGDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIRRTCLSRE
NSTVTKVASKMSLA----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----GGEHPTSLGLDHMFDGTKIVLPEQEFPADL--DFSINVLVIGK-------------
------------------------------------------------------------
TGVGK-----------------SATVNSI---------FGETK---------SAVGAF--
-----------------------------GVTTNSANYVVGN-VGGI-------------
----QISILDTP------------------------------------------------
--------------------GLLSSATEE--QFNQEVLIA---------RCLGIVLAENN
MSFFSANKSSESTCSDWRLNLLILCCSVKIR-----------------------------
SKAGSLQK-------------------QNTDVEKAGVFGSQLSSFTLFCSLWNVLLNSGH
TSHSHDDLEEKKRKLLDSYPEIIWDEQSQECLEQETLLVENQESEDVERQHEKGTVLGRV
RTRRGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRGSMSVLGLVP
MLISVFTSGKDI------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------
>TOC100
MESEKPGIVSILAAATVDSEK-----------------------------PRVSISAVRA
IAAARADSFLLTPSSEASSYSNGLDFET--------------------------------
------------------------------------------------------------
---------------------------------------DEDETVLEDVVLDGVRVDRLL
GEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVD
SEEVRMNYS----------DKLDDGLMSFGN-------------IEESSLGVPPEGSSDF
MAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVER-----
---VEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGE
CKEFLVESEGN-----AVDEDKGLDETVSSLV--EQGVGQASTSKESNNRTDVGSVCDAD
ELIIPRDESIGSESRDSGDKDAGN---MIGKAEEHCENDRGAVSELEKLECADEPEIGMS
SESFQLTPTSDSEM-------IMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDT
DRKLSLPDEDRASSLIS----------SFETANETVE--------------------DGN
QLISR-TMPENSSVIAYDIMENETM--------------ARLIHNHTFMELDEYEGTGDT
SEKLTGSSF--QNSSELLSSNHSVELISERVKERV----EKTQLLKEKLQRIIRRTCLSR
ENST-------------------------------------------VTKVAS------K
MSLAG----GEHPTSLGLDHMFDGTKIVLPEQEFPA--DLDFSINVLVIGKT--G-VGKS
ATVNSI---------FGE--TKSA------------------------------------
----------------------------VGAFGVT---------------TNSANYVVG-
NVGGIQISILD-----------------------------------------TPG-----
-LLSSAT-EEQFNQEV------------L-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------IARCLG----------------------------------------------
----------------------------IVLAENNMSFFS--------------ANKSSE
S-TCSD---WRLNL------LILCCSVKIRSKAGSLQKQ----------NTDVEKAGVFG
SQLSSFTLFCSLWNVLLNSGHTSH-----------------SHDDLEEKKRKLLDSYPEI
----------IWDEQSQECLEQ----ETLLVENQESEDVERQHEKGTVLGRVRTR-----
--------------------------------------------------------RGRL
GFQAT------------------------KRFGIYLDTSDVHAGFSIGSRDCRRNVQEEG
KILVRMRGS---------------------------------------------------
------------------------------------------------------------
-----------------------MSVLGLVPMLISVFTSGKDI----------
>TOC100
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------ESEKPGIVSI
LAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVL
DGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEF
DEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIE
LGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEY
AGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDET
VSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKA
EEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCG
SSDQKAEEESENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPE
NSSVIAYDIMENETMARLIHNHTFMELDEYEGTGDTSEKLTGSSFQNSSELLSSNHSVEL
ISERVKERVEKTQLLKEKLQRIIRRTCLSRENSTVTKVASKMSLAGGEHPTSLGLDHMFD
GTKIVLPE------------------------------------QEFPADLDFSINVLVI
GK--------------------TG------------------VGKSATVN----------
------------------------------------------------------SI----
-------FGETKSA--VGAFGVTTNSA-----------------------NYVVGN----
----------------VGGIQIS--------------------------------ILDT-
------------------------------------------------------------
--------PG------------LLSSATEEQFNQEVLIARCLGIVLAENNMSFFSANKSS
ESTCSDWRLNLLILCCSVKI----------------------------------------
-----------------------------------------RSKAGSLQK----------
---------------------------------------------------------QNT
DV-----------------EKAGVFGSQLSSFTLFCSLWNVLL-----------------
NSGHTSHSHDDLEEKKRKLLD-----------------------------SYPEIIWDEQ
SQECLEQETLLVENQESEDVERQHEKGTVLGRVRTRRGRLGF------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------QATKRFGIYLDTSDVHAGFSIGSRDCRRNVQ
EEGKILVRMRGSMSVLGLVPMLISVFTSGKDI----------------------------
------------------------------------------------------------
------------------------------------------------------------
-
>Linum_usitatissimum_gnl|BL_ORD_ID|12132 _10027712|PACid:23151312

-------------------------------M----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----DWSLPNWFSKSLAS----------LSPVTFYESPPSDHHSDDDRDLTANSEA---
-LSPPDASPQQVVE----------------------ASSQPSTHHTEERDTHPLENIEHL
KINFFRLLR------------------------------RFGLPMDSPLVAKVLYRLHIA
ISIRGELPK---------------------------------RVRNINA---------LT
ITAAQEGSGVPELDFSVR----------------------------------------IL
V---LGKTGVGKSATINSI----L-----DQRATVTSAFQPATDRVQEV----IGTL--Y
GVRVTF-------------------------IDTPGFLPHSG-SGIRRNLKIMRSVKRFI
RES-PPDIVLFV--------------------------ERLDHLNTGYS-DFPLLQLM--
-----------TDVFGDAIWFNTMIIMT--------------------------------
------------------------------------------------------------
---------------------------------------------------HASSSLP--
------------------------------------------------------------
---------------------------------EGSIGGPVSYESHVSRCSQMMQHYIHE
AVSDTTLQN---------------------------------------------------
----------------------------------------LVVVVENHPQCDKNSN----
---GDAILPNGQVWRSQFLL----------------SCICTKVLGD--------------
---------------ASNILELKNSIELG-------PKTRPQVLSLPRLLSWL-------
-----------------------------IKNKAVSGPTPDGHDLDEIILVDED------
-----------------------------------------------------EED----
--EYDHLPPIRILTKSQFAKLSKSQKNDYLDELDYR------------------------
------------------------------------------------------------
------------------------------------------------------------
---EMVYMKKQLKEESRSRREKMLLGKAS-------YEEFDKSEATNAPPETVLLPDMAV
PPSFDSDCPVHRYRCLIEI-----------------------------------------
---------------------------GDQLLTRPVLDPRGWDHDVGFDTIDLETAIEMK
KNLCASYSGQINKDKNNFSIQSECAVTYADLKGPTYS---AGLNVQKAGKDDLVYTIHGN
TRSKIFTNNNVADCGVSVTSSCNKCYLGAKLENSVLVGKRLKLLINGGQMRGPGQVVNGG
SLEATILGTDYPMRNDKVSLSLTALSFNKETVVSGGVESEFQLMRGTRVAVNANLNSLHM
GKVGIKA--SSSEHLEIAVIAALTIFSAIFR-----------------------------
------------------------------------------------------------
-----------KRVANTSPDVSET------R
>Malus_domestica_gnl|BL_ORD_ID|24019 _0000872008|PACid:22643995

------------------------------------------------------------
-ME---------------------------------------------------------
--------------------------NGDKIAGGSEVGENKGVDVKVVE-----------
-ERVVEGSNGLKDDAEDEVFEEAIETQENSQEQGSK------VDLVDAVVVGEERETETV
GGLGLASLIESP-------SVDTFEEAIEVPDEVGKSDDDD-------------------
-------------------------------------------AEVKVENLVGGNS----
--------DDEVGVAGGIDDEQTKKEA-------------------VTEETNGLTDDGLV
G--SQEDAVKEVTQVEAGGGISSLTGGDEADVKSVDLENVKFEKDNFELNGLA-DGLVGS
Q--------DVEVKEVSEIITGAEIVGLTNVGEVDSKPNVVLENKEPEKDDLDNSTSEPV
STDEKLDTE---DLDSPQVTEFNKEILKEAGNGQELEENSLSIENQDEKTVDLLSASDGV
PLKLEDDNGVELLDRNMDTVHQEGDSAE------S-------------------------
----------------NDATLGIEEKQEY-NKTEELRDTLTFTDAEHQGFSNGEVK-DSF
TVLGSEHHEEKSEPKSISSDKQLSGEDSEE------------------------------
-----MIVTSEREISAL---SERSAAEKTEKIQDGATNLRAQSNKDDQ--PQR-ADEIAP
EVRDNIAVPEEPEKKENIQAEKGVTKVNKEQEIQPVSTLSSSGNSTQPSPPPA------R
PAGLGRAAPLLEPAPRVVQHPRVNGTVSHAQNQQIEDPVNGETEESDETREKLQM-----
---IRVKFLRLAHRLGQTPH----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---NVVVAQVLYRLGLAEQLRG--------------------------------------
---------------------------------------------------------RNG
--GRVGAFSFDRASAMAEQLEASG------------------------------------
----NEPLDFA------C------------------------------------------
--TIMVLGKSGVGKSA---------TINSIFDEKRFTTDAF----QMG------------
TKKVQDVVGTV--QGIKVR------------------------------------VIDTP
-----------------------------GL----------------------------L
PSWSDQ-RQNEKTLLNVK------------------------------RFIKKTPPDIVL
YLDRLD-----MQSRDFSDM-----PLLRTITDIFG--P-----------SIWFN-----
-----------AIVVLTHAGSAPPEGPNGAASSYDMFVTSRSHVVQQAIRQAAGDMRLMN
-----PVSLVENHSA-CRINRAGQR----------VLPNGQVWKPHL------LLLSFAS
K----------------------------------ILAE---------------------
A-----------------------------------------------------------
------------------------------------------------------NALLKL
QDSP-PGKPFATRTRAPPLPFLLSSLLQSRPQLKLPEEQ--------FGXDDSLDDDLDE
SSDSD-------------------------------------DES-------------EF
DELPPFRRLTKAQVEKLSKAQKKAYFDELEYREKLFMKKQLKEEKKRRKLMKKMAAASNE
LPSDYVENVE---------------EDSSGAASVPIPMPDLALPASFDSDNPTHRYRYLD
SSNQWLVRPVLEQHGWDHDVGYEGINAERLFVVKEKIPLSFSGQVTKDKKDANVQMEIAT
SIKHGEGKATSLGFDMQTVGKDLAYTLRSDTRISNFRKNKATAGLSVTLLGDAVSAGMKV
EDKFIANKRFQLVMTGGAMTARGDVAYGGSLEAQLRDKDHPLGRSLSTLGLSVMDWHGDL
AIGCNIQSQIPVGRHTNLIARANLNNRGAGQLSLRLNSSEQLQLALIGLVPLLRKLFTFP
Q---QLQYGQ--------------------------------------------------
-----------
>Manihot_esculenta_gnl|BL_ORD_ID|15640 _4.1_002111m|PACid:17975485

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---KSIRDWVFTRLLS----SSRSLSGSGSFFSEGPADEDSNA-------PEVAPVLPDT
SYFSGNTEGNEPHPSLPGDLNR--------------------------------------
----------------SNNVNDCEKADSLAKIEDLEVKFFRLLRRLG-------------
-----HSSDNLLVA--------------------KVLYRIHLATSIRGR------ESDLK
RARKIAAEQ------------EAIDKPK---LNFSI-RILVLGKTG--------------
------------------------VGKSATINSI-----------FDQRKTTTDAFEA--
---------ATKHIQEIVGT------------V--SGVK---------------------
-----------------VTFIDTPGF-----------------------LPASANNVRRN
RKIMLS--------------VKRFI--RKSPPDIVLFC----------------------
-ERLDLVNMGYSDFPLVKLMTEVLGS----AIWFN-------------------------
------------------------------------------------------------
----------TI---------LVMTHASSMLPEGPNGFSVNYESYVTKCTDLMQQFIHQA
VL------------------------DRKL-----ENPVLLVENHPQ-CKKNFAGENILP
NGQAWKSQFLLLC--------------------------ICTKILGDVS-----KLLEFQ
GSIE---LGSSSPRVPSLPHLLSSLLRHHVS-----------------------------
----------------------NPNEVDDDVYEILLSDAEEE---DEYDQL-PPIRILTK
SQFERLTKSQKRDYLDELDYRETLYLKKQLK-------EDARSKREKKLAEAERLG----
---EDNS-DDQQTPTEAVLLPDMAVPPTFDSDCPVHRYRCLATSDQWLMRPVLDPRGWDH
DVGFDGINLETAVEIKRNISASIAGQMCKDKQNFSIQSECAAAYTDPRGPTYSVGFDVQS
AGKDIIYTVH--------------------------------------------------
--------GNTKLATLKHNNADCAVSLTSFGKKYYVGAKIEDNILIGKRLKFVMNAGQMR
GRGQVAYGG---------------------------------------------------
----------------------TFEATLRGQDFPVRNDIISLSLTALSFKKEMVLSGGFQ
SEFRPVRNMRVAVNANLNSQKMGQVSIKMSSAEHIEIALAAIFSIFRVMLYRKESKNGSR
ETLEM-----------------------------------------------
>TOC100
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------ESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEA
SSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGD
ERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLG
VPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPS
DVERVEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTG
ECKEFLVESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPR
DESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPT
SDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRKLSLPDEDRASSLI
SSFETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLIHNHTFMELDEYEGTGDTS
EKLTGSSFQNSS------------------------------------------------
--------ELLSSNHSVELISERVKERVEKTQLLKEKLQRIIRRTCLSRENSTVTKVASK
MSLAGGEHPTSLGLDHMFDGTKIVLPEQ--------------------------------
--------------------EFPADLDFSINVLVIGK-----------------TGVGK-
-SATVNSIF-----------GETKS---------------------------AVGAFGVT
TNSANYVVG---------------------------------------------------
--------NVGG---------------------------IQISIL---------------
------D--------T-----------P-GL-LSSATEEQFNQEVLIARCLGIVL-----
AENNMSFFSANKSSESTCSDW-RLNL----------------------------------
------------------------------------------------------------
---------------------LILCCSVKIR-----------------------------
------------------------------------------------------------
-----------------------------SKAGSLQKQNTDVEKAGVFGSQLSSFT----
------------------------------------------------------------
------------------------------------------------------------
-------------LFCSLWNVLLNSGHTSHSHDDLE------------------------
------------------------------------------------------------
------------------------------------------------------------
------EKKRKLLDSYPEIIWDE-------------------------------------
------------------------------------------------QSQECLEQ----
------------------------------------------------------------
-------------------ETLLVENQESEDVERQHEKGTVLGRVRTRRGRLGFQATKRF
GIYLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRGSMSVLGLVPMLISVFTSGK-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------DI
>Medicago_truncatula_gnl|BL_ORD_ID|3363 _CU651589_6.1|PACid:17435014

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------CVLREFTLRAFLNGRLDLSQAENVGKL
IAAKSV------------------------------------------------------
--------------------------------AAADAALEGIQACLAQFCFLLFITGGFS
SLVRSLRNQCIDLLTEIEARLDFE-----------DEMPPLDLNGIMDK-IHHMSQDVEN
A------------------LETANYDK-LLQSG------LQIA-----------------
---------------------------IVGR-----PNVGKS------------------
------------------------------------------------------SLLNAW
---------SKSERAI--VTEIAGTTRDVI-----EASININGIPITL------------
----------------------------------LD------------------------
------TAGIRDTDDIVEKIGV--------------------------------------
------------------------------------------------------------
--------------------E------RSEAV-----------------ARGAD----LI
IMTV--------------------------------------------SAVEGWTSE--D
TKLLERI-------------------------QSAKESTGSS------------------
------------------------------------------------------------
-----------------------------------------TPVIL--------------
--------VVNKIDCKPCAETEWDKGMHSHKIFSKQVFTCAVTSQGLQDLER--------
-----------------------AVLEIVGMDGIASGGRRWTVNQRQCEQLVRTKEA--L
VR----------------------------------------------------------
-----------------LQ-------SSIKEELP------------MDFWTIDLRDAA--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------LSL-------------------GQISGEDISEEVLSN
IFGKFCIG----------------------------------------------------
---------------------------------------------------------K
>Oryza_sativa_gnl|BL_ORD_ID|30676 _LOC_Os03g61890.1|PACid:21913148

MALLPIRARLSALDDD--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------DDDAATVSS-----SRSSSAATSPSRSP
SPLVPRASVLGAPRVAAQLSSTE-------------------------------------
------------------------------------------------------------
--------------------------------DDNG------GGEDEV------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------FDESTDYGDDEAAG-----------------
---------------------------EVLDELSNGFFRIARVPPPSEDSSPIS------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------GGEPVVSVSSPTESGYFGAAE
------------------GSLKEEGFVGARNFADVFDAGSRVGFEDANGVTAGAK-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------NTGVESSL
EGSFQ-SSGSVVGVFDDTD-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------VTTIGDLVSASDGSPLNVDKQ--GDQDSGAEVV-------------------
------------------------------------------------------------
------------------------------------------------------------
------NDEPVDAEVVNGIEPEPLVGESVDAEVVN-------------GVVPEPL-----
-----------VGESGGSDGGG--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----MHV-------EDELEMEGG-------------KSDNG--------IAELPPVVSAL
EKQDTDLELRNDDSGAKDGAD---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------NHEDATNFV-D
SSTGYVATG---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------DGASELLEVPANVDDLHFV
TDD---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------GHNDDAE-----
-----------------ETDGGYEASDGYVSMPTF-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------GNNNAVEIPVNESEHNVPASKGRRFGLGD
SDDEFHDDDVEEEEGEVNGKEI--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------EFFDYAALAELLRAAT------------PGQGMAKVFPIE---
---SSVPLQ---------------------------------------------------
-VPPTTVSVPRKNVASSPVLEVAPN------------------------PDNEMT-----
EEE--------------------------------------RKLYRKVDVARIKYLRLIH
RLGYDTE-HHIAIQVLYRLSLVEGFRRIKV-ANH-SSELESAWKKALQLEAEGT------
-------EDLE----FSCNVLVLGKTGVGKSAT---------------------------
INSIFG-----------EDK--SKTSAFLPATTAVKEISGVVGG---VKF--R-----VV
DTPGLGTTHM-------DEKSNRKVLN--------------SVKKYIKRCPPD-V-----
-----V-------LYVDRI--DTQRQDANNLSLLQCITSVLGSSIWSKTII---TLTHSA
AAP-------------------------PEGPSGIPLNYEMF------------------
---------VTQRTHAIQQSIRQATNDPR-------------------------------
------------------------------------------------------------
---------------------------------FE-----NTSALVENHHLCRRNTEGEK
VLPNGLI--------------------------------WRRLLL-----LLCYSVKTV-
ETNS-LSAR-VASPANLFSLRFRMPPLPHFLSSLLQSREHPRCAADQ--DVGDIDPD---
-------------------------------------------------ELINEDEEDDY
DQLPPFKPLSKSQVAKLSKEQQKLYFDEYDYR--------TKLLEKKQLKE---------
------------------------------------------------------------
-------------------QLRRLKEMKIEGNNHDVLGD---NDNP---DDEYETERSV-
--MPDWALPSSFDSDD-PAYRYRCLDPKPNFLVRAITNPDGWDHDCGFDGVSLQYSLDAA
NA---FPASLWVQVNKDKRESTIHLVSSI---SAKHRENVSSLAGFDIQTIMDQLAYTLR
GESKFKNSKKNTTTGGLSMTFLGDTMVTGAKFEDKLSVGDRLTLLANTGAVSIRGDTAYG
VNMEATLREKDYLMGQDLAILGASLVRWHKEWSMAAKLDSQFSMGRASNVAVHVDLTNKL
TGRVSIKANTSEQLKIALLGVCSMTMYLWNRMHP-FID----------RNY
>TOC100
MESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETD
EDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDER----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------GSMKAKVVIPRAV
LSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEG
NSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKM
GMND------KPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVES
EGNAVDEDKGL-------------------------------DETVSSLVEQGVGQASTS
KESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELE
KLECADEPE-------------------------------------IGMSSESFQLTPTS
DSEMIMNLEVAGGIDVV---------------VIGCGSSDQKAEEESENEGNQESDDTDR
KLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIME--NETMARLIHN
HTFMELDEYEGTGDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQ--------
--------LLKEKLQRIIRRTCLSRENSTVTKVA-SKMSLA----------GGEHPTSLG
LDHMFDGTKIVLPEQEFPADLDF------------------------------SINVLVI
GKT--GVGKSATVN--SIFGE------------TKSAV----------------------
----------------------------GAFGVTTNSA----------------------
--------NYVVGNVGGIQ-----------------ISI---------------------
-------------------------------------------------------LDTP-
-----------GLLS---------------------------------------------
--------------------------------------------------SATEEQFNQE
VLIARCLGIVLAENNMSFF-----------------------------------------
---S----------------ANKSSESTCSDWRLNLLILCCSVKIRSKAGSLQKQN----
----------------------------------------------------TDVEKAGV
FGSQLSSFTLFCSLWNVL-----------LNS----------------------------
---------------------------------------GHTSHSHDDLEEKKRKLLDSY
PEIIWDEQSQECLEQETLLVENQESEDVE-------------------------------
----------------------------------------------------------RQ
HEKGTVLGRVRTR-----------RGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNV
QE---------------------------------------EGKILVRMRGSMSVLGLVP
MLISVFTSGKDI------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------
>TOC100
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------ESEKPGIVSILAAAT
VDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRV
DRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILG
SDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNF
KQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNI
GELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSLV
EQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCE
N-----------------------------------------------------------
------------------------------------------------------------
----------------------DRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIM
NLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRK--------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------LSLPDEDRASSLISS
FETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLI------------HNHTFMEL
DEYEGTGDTSEKLTGSSFQNSSELLSSNHSVEL---------------------------
----------------------------------ISERVKERVEKTQLLKEKLQRIIRRT
CLSRENSTVTKVASKMSLAGGE--------------------------------------
------------------------------------------------------------
-----HPTSLGLDHMFDGTKIVLPEQEFPADLDFSI------------------------
--NVLVIGKTG---------------------------VGKSATVNS-------------
-IFG-----------ETKS-----------------------------------------
----AVG---------------------AFGVTTNSANYVVG-NVGGIQISILD------
----T----------PGLLSSAT------------EEQFNQEVLIARCLGIV--------
------------------------------------------------------------
-----------LAENNMSFFSA---------NKSSESTCSDWRLNLLILCCSVKIRSKA-
-----------------------------GSLQKQNTDVEKAGVFGSQLSSFTLFCSLWN
VLLNSGHTSHSHDDLEEKKRKLL-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------DSYPEIIWDEQSQE
CLEQETLLVENQESEDVERQHEKGTVLGRVRTRRGRLGFQATKRFGIYLD----------
------------------------------------------------------------
---------TSDVHAGFSIGSRDCRRNVQEEGKILVRMRGSM------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------SVLGLVPMLISVFTSGKDI
>Populus_trichocarpa_gnl|BL_ORD_ID|20537 _POPTR_0004s01160.1|PACid:18226770

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------IRVKILRLAHRL------------------------------------
-----------GQTPDNVVVAQLRGR------------NGGRVAGFDRANTIAEHLKAVG
QKS---------------LDFSCTTMVL-----------------------------GKT
CVGKSATINSI----F-------DEVKLYKCFTGVG------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------SWFALQMLVKVL--EVEML--
-----Y------------------------------SIDLSWLLNYLSLDCLF-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>TOC100
----------------------------------M--------------ESEKPGIVSIL
AAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLD
GVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFD
EILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIEL
GQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYA
GSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETV
SSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAE
EHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGS
SDQKAEEESENEGNQESDDTDRKLSLPDEDRASSL---ISSFETANETVEDGNQLISRTM
PENSSVIAYDIMENETMARLIHNHTFMELDEYEGTGDTSEKLTGSSFQNSSELLSSNHSV
ELISERVKERVEKTQLLKEKLQRII-RRTCLSRENST----------VTKVASKMSLAGG
EHP--TSLGLDHMFDGTKIVLPEQEFPADLD-------------------FSINVLVIGK
---------TGVGKSATVNSIF-----------GETKSAVG-AFGVTTNSANYVVGNV-G
G-----IQISILDTPGLLSSATE--------------------EQFNQEVLIARCLGIVL
AENNMSFFSANKSSE---------------------------------------------
--------------------STCSDWRLNLLILCCSVKIRSK------------------
----------------------------------------AGSLQKQNTDVEKAGVFGSQ
LSSFTLFCSLWNV------LLNSGHTSHSHDDLEEKK-----------------------
------------------------------------------------------------
---RKLLDSYPEIIWDEQSQECLEQETLLVENQE-----------------------SED
VERQHEKGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKIL
VRMRGSMSVLGLVPMLISVFTSGKDI----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>TOC100
MES---------------------------------------------------------
-------------------------------------------EKPGIVSILAAATVDSE
KPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLL
GEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVD
SEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLI
EKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNIGELV
SIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSLVEQGV
GQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRG
AVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEE
SENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDI
MENETMARLIHNHTFMELDEYEGTGDTSEKLTGS---------------------SFQNS
SELLSSNHSVELISERVKERVEKTQLLKEKLQRIIRRTC---------------------
--------------------------------------------LSRENSTVTKVASKMS
LAGGEHP-----------TSLGLDHMFDGTKIVLPEQEFPADL-----------------
------DFSINVLVIGKTG-----------------------------------VGK---
------------------------------------------SATVNSI--FGE------
---TKSAVGAFGVT----------------------------------------------
--TNSANYVVGN---VGGIQISILD---------------TP----GLLS---SATEEQF
N-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--QEVLIARCLGIVLAENNMSFFSANK---------------------------------
---SSESTCSDWRLNLLILCCSVKIRS---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----KAGSLQKQNTDVEKAGVFGSQLSSFTLFCSLWNVLLNSGHTSHSHDDLEEKKR---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KLLDSYPEIIWDEQSQECLEQETLLV
ENQESEDVERQHEKGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNV
QEEGKILVRMRGSMSVLGLVPMLISVFTSGKDI---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>TOC100
MESEKPGIVSILAAATVDSEKP--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------RVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFET
DEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFID--------------------
-----HLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDD
GLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDS
GGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDN
VLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTD
VGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEP
EIGMSSESFQLTPTSDSEMIMN--------------------------------------
---------------------------LEVAGGIDVVVIGCGSSDQKAEEESENEGNQES
DDTDRKLSLPDEDRASSLISSFETANETVED--------GNQLISRTMPENSSVIAYDIM
ENETMARL--------IHNHTFMELDEYEGTGDTSEKLTG--------------------
---------------------------------SSFQNSSELLSSNHSVELISERVKERV
-------------------------EKTQLLKEKLQRIIRRT------------------
------------------------------------------CLSRENSTVTKVASKMSL
AGGEHPTSLGLDHMFD------GTKIVLPEQE------FPADLDFSI-------------
------NVLVIG------KTGVGKSAT---------------------------------
VN-------------------------SI-----------FGE------------TKSAV
GA----FGVTTNSANYVVGN-V--GGI---------------------------------
----------------------------------------------QISILDTP------
------------GL-----------------------LSSA-TEEQ--------------
FNQEVL------------------------------------------------------
------------------------IARCLGIVLAEN------------------------
--NMSFFSANK-S-----------------------------SESTCSD-----------
----------------WR----------------------LNLLILCCSVKIRSKAGSLQ
KQNTDVEKAGVFGSQLSSFTLFCSLWNVLLNSG---------------------------
----------HTSHSHDDLEEKK-------------------------------------
---------------------RKLLDSYPEIIWDEQSQECLEQ-----------------
-----------------ET--LL----------VENQESEDVERQ---------------
-----------------------------------------------------------H
EKG-------TVLGRVRTRRGRLGFQATK---RFGIYLDTS---------DVHAGFSIGS
R-----------------------------------------------------------
------------------------------------------------------------
--DCRRNVQEEGKILVRMRGS----MSVLGLV----------------------------
--------------PMLISVFTSGK---------DI-------
>TOC100
M----------------------------------------ESEKPGIVSILAAATVDSE
KPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDV-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------VLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERG
SMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPP
EGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVE
RVEDSA-------VELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLG
VMTGECKEFLVESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADEL
IIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQ
LTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRKLSLPDEDRA
SSLISSFETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLIHNHTFMELDEYEGT
GDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIRRTCLSRENS
TVTKVASKMSLAGGEHPTSLGLDHMFDGTKIVLPEQEFPADLDFSI-NVLVIGKTGVGKS
ATV----------------------------------NSIFG-----------ETKSAV-
GAFGVTTNSANYVVGNV-----GG----------IQIS-ILD------TPGLLSSATEEQ
FN-QEV------------------------------------------------------
-----------------LIARCLGIV----------------------------------
----------LAENNMSFFSANKSSES---------------------------------
------------------------------------------------------------
-----------------------------------------TCSDWRLNLLILCCSVKIR
SKAGSLQKQNTD-----------------VEKA-------------------------GV
FGSQLSSFTLFCSLWNVLLNSGHTSHSHDDLEEKKRKLLDSYPEIIWD------------
--------------------------------EQSQECLEQETLLV--------------
------------------------------------------------------------
-----------------------------------------------------ENQESED
VERQHEKGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGFSIGS-RDCRRNVQEEG--
------------------------------------------------------------
-------------KILVRMRGSMSVLGLVPMLISVFTSGKDI------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>TOC100
ME-----SEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGL
DFETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKA
KVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSS
DFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVED
SAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLV
ESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSE
SRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIM
NLEVAGGIDVVVIGCGSSD-----------------------------------QKAEEE
SENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSS------
------------------------------------------------------VIAYDI
MENETMARLIHNHTFMELDEYEGTGDT--SEKLTGSSFQNSSELLSSNHSVELISERVKE
RVEKTQLLKEKLQRIIRRTCLSRENSTVTKVASKMSLAGGEHPTSLGLDHMFDGTKIVLP
EQ----------------------------------------------------------
--------------EFPADLDFSIN-----------------------------------
---------------------------VLVIGKTGVG--------------------KSA
-----------------------TVNSIFGE-----------TK--SAV-----------
---------------------------------GAF-GVTTNSANYVVGNV-GGIQISIL
-----------------------------DTPGL-----------------------LSS
A------------------TEEQFNQEVL-----------IARCLGIVL-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------AENNMSFFSANKSSESTCSD--------WRLNLLILCCSVKIRS
KAGSLQKQNTDVEKAGVFGSQLSSFTLFCSLWNVLLNSGHTSHSHDDLEEKKRKLLDSYP
EIIWDEQSQECLEQETLL------------------------------------------
----------------------------VENQESEDVERQHEKGTVLGRVRTRRGRLGFQ
ATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRGSMSVLGLVPMLISVFTSGK
DI----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|13289 _97911|PACid:15414567

KKPKVEKDPGIPNAWPFKEQE---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------LKALEERRARVLKELEEKKLAKKLRAKERLDDLVRDTETRTAQGTL
SADGSKRAFYK------------------------ELLKVIEASDVIIEVLDARDPLGTR
CPDMERLVFKSQTSKRLVLLLNKIDLVPKEIAEKWLKYLREELPTVAFKCNTQMQRSNLS
RK---------------KSKSKVILETSSDCLGADTLLQLLKNYSRSDELKRA-------
--ITVGIVGLPNVGKSSLINSLKR-SRAVSAGGTPGLTRTMQEVQLDK------------
---------------------------------------------HVKLLDCPGVVLASA
TDS----KPLMDLRNCTRIEKLADP-----------------VAPVKEIVSKCGHEKLMS
F---YKIPSFSTVDEF--------------------------------------------
-------------------------------LQLVATIRGKF------------------
------------------------------------------------------------
-------------------------------------------KKGGVVDTETAARIVLH
DWNEGKI-----------------------------------------------------
-------------------------------------SH-----------------YTVP
PVREPAGPSESAIVTSWG------------------------------------------
-----------------------------------------------------------K
EFNVDEVFKR-----EQSTVIAGLPCLSDADHTELP------------------------
------------------------------------------------------------
------------------------AGAPMSMDVTMMEVRKSFFSSGFLWIEPHPSL----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>Thellungiella_halophila_gnl|BL_ORD_ID|14253 _Thhalv10024270m|PACid:20193804

ME---PRGISILA---VDSEKPRAIAIPAARAVA---ADAFLLTHISNASNYSRGVDSGT
DDGFESVSGDADDETELEDVIMGGVRVHRVLGDNPGGETGDGSDFSGGSVIYRPFAGDIE
EETSLNYSSLEEESENNSEDVDGVSE----------------------------------
------------------------------------------------------------
--------------------------------SEVSEADGVSMKAKVVIPRAILSLDDDE
FDEILGSDDEGAALLRVTKAPGGEETEDRTSQFGGVGMADEPECSDSVIGEFVSTEEEVV
MDNTDELDNGLKSFGNTDEQSLGVPTGGANDFIVEKEGNSTESAMGFGGNSKQLVEHEVQ
RSIIN-NDGGGSIHEVDTLMKPCDVEGVDDNAVESGKMGRVDKPECSGSVTSEIVSTDED
MVQVKISDNGLVSVETSLGVAPGDCNEFLVESEGNVVDADRGLDETF-------------
SKESGNRTDDNRSCEADESMIPGEGSIGIGRKESGDEVTGNMIGESKEHCENDCGAVSEL
EKSECKGEPEIGLSSETFQLSPTLNAVTTRNLEVDGGIDVVVSGCGSSDQKAEQEAENEG
KQESEDINRKLSLADEDRAPS---------LRNSFETASESPEKRGQILEQINKQVFFQS
DTEPNQISIE--------------------------------------------------
-----------------------------------------ETSLLSVKDVERTMLENSC
VTTYAEVENETQMARLVNNHTFM-------------------------------------
-GKNTESNFQNCSEELSPD--------------------------------NSVQLISEK
VKERVEKTKL--------------------------------------------------
---------------------------------------------------------LKE
KLQRIIRTI----------------------------DLGGENSAVT-------------
--------------------------------------------------------EVES
KLSL---ADGEHQTSLGL------------------DYVSDGTKIMLPEQEF--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------PDDLDFSINVLVIGKTGVG---KSATVNSI---------FGETK
--SPVGAFRVT-------------------------------------------------
-TKSANYVVGN-VGGVLIRVLDTPGL-----------------------V-SSAT-----
------------EEQYNQDVLMS--------------IKKSIRAFPVDVFLFI-------
------------------DRLD----DNPDI----------HLLRIVTSSLGSS------
-----------IWRNAIVVLTHAASDV---------------------------------
-----PDS-----SSCKDF--IAQRSSLMHQSIRQAVPEL--------------------
-AYVDQSKMPGIV-LAENNNLSSLCGNKTSESTCV-------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------DW------------------RLNLLILCCSVKIGSKAD---------
-----SL-QKHKAIIEKAGVIGSQRRSFTVFCSLWNVLLLGANSGHASHSQDDLEEKK--
-----------------------RRLLDSYPEILWDDQSQES----------LEP----E
DEETR-HENGNVNKGLERGTVHGRVRTR--------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------RGRLGFQATKRFGIYLDTSDLHTGFSIG---
-----------------------------SRGCRKHEQEEEEERRILVRMRGS----MSV
LGLVPMFMS---------VFTCVYGRKDN-------------------------------
------------------------------------------------------------
---------------------------
>TOC100
MESEKPGIVSILAAATVDSEKPRVSISAVRAI------------------AAARADSFLL
TPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQ
SEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNI
EESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFD
ALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESS
LGVMTGECKEFLVESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDAD
ELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEI------
-----------------GMSSESFQLTPTSDSEMIMNLEVAGGIDV-----VVIGCGSSD
QKAEEESENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSS
VIAYDIMENETMARLI--------------------------------------------
-----------------HNHTFMELDEYEGTGDTSEKLTGSSFQ----------------
----------------------NSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIR
RTCLSR-------------ENSTVTKVASKMSLAGGEHP---------------------
----TSLGLDHMFDGTKIVLPEQEFPADLDFSINVLVIGKTGVGKSATVNSIFGETKSA-
VGAFGVTTNSANYVVGNVGGIQISILDTPGLLSSATEEQFNQEVL---------------
---------------------IARCLGIVLAENNMSFFSANKSSEST-------------
------------------------------------------------------------
------------------------------------------------------------
----CSDWRLNLLILCCSVKIRSKAGSLQKQNTDVEKAGVFGSQLSSFTLFCSLWNVLLN
SGHTSHSHDDL-------------------------------------------------
------------------------------------------------------------
---EEKKRKLLDSYPEIIWDEQSQECLEQETLLVENQESEDVERQ---------------
-HEKGTVLGRVR-----TRRGRLGFQATKRFGIYL-------------------------
------------------------------------------------------------
------------------------------------------------------------
--------DTSDVHAGFSIGSRDC-----------RRNVQEEGKILVRMRGSMSVLGLVP
MLISVFTSGKD-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----I
>Vitis_vinifera_gnl|BL_ORD_ID|15727 _GSVIVT01024062001|PACid:17832352

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------YTPVDEGVSASGTGRSPSVEDSAIEKS----------------------
--------------------------------------------------------EMEQ
CAIEDSTIEKS--ETKQGVTSELAAADNISPQPERAVENVAEVKNKYVVFEEQETKEPNM
EKEDQKIQGNRERE---------IRPAEQVASSSGRSSNPGP------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PPA
HPAGLGRAAPLLEPASRVVQQPRVNGTTSQVQAQLIEDAGNGEAEENDETREKLQ-----
--------------------------------MIRVKFLRLAHRLGQT------------
----PHNVVVAQVLYRLGLAEQLRGRNGGRVGAFSFDRASAM------------------
-----------------------------------------------------AEQLEAA
GQEPLDFSCTIMVLGKTG---------------------------VG--KSATINSIFDE
------------VKFSTDA-----------------------------------------
---------FQVGTKKVQDVVGTV--QGIKVRVI------------DTPGLLPSWS----
----------DQRQNEKILHSVKRFIKKTPPDIVLYLD---------------------R
LDMQSRDFGDMPLLRTI---------------TEIF--------------GPSIWFNAIV
VLTHAA--------SAPPDGPNGTASSYDMFVTQRSHVVQQA------------------
------------------------------------------------------------
------------------------------------------------------IRQAAG
DMR-----LMNPVSLVENHSA------------CRTNRAGQRVLPNAN------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------TLLKLQDSPPGKPFTTRSRSPPLPFLLSSLLQSRP
QVRLP-------------------------------------------------------
EEQKERRKMMKKMAASSKDL-------------------------------------PSD
YSENAEEESGGAASVPVPMPDWALPASFDSDNPTHRYRYLDSSNQWLVRPVLETHGWDHD
VGYEGINVERVFAIK---------------------------------------------
----------------------------------DKIPVSFSGQVTKDKKDANLQMEIAS
SVKHGEGKATSVGFDMQTVGKDMAYTLRSETRFCNFRKNKATAGLSITALGDAIT-----
------------------------------------------------------------
----------------------------------------------------------AG
LKLEDKLIVNKRIRLVMTGGAMTGRGDVAYGGSLEATLRDKDHPLGRSLSTLGLSIMDWH
GDLAIGCNIQSQIPIGRFTNMIGRVNLNNRGAGQVSIRLNSSEQLQIALIGLVPLLRKLL
GYSQQGQSSCFLIVYAFGMNCKIPGMYQKGLSFFLYLYSWITSAGANETLGSMLLGYVNI
CNTYESFS-----------------------------------
>TOC100
MESEK-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------PGIVSILAAATVDSEKPRVSISAVRAIAAA
RADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGV
GFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDG
LMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSG
GSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNV
LVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDV
GSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPE
IGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRK
LSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLIHNHTF
MELDEYEGTGDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQLL---------
---------KEKLQRIIRRTC---LSRENSTVTK--VASKMSLAGGEHPTSLGLDHMFDG
TKI------------------------------------------VLPEQEFPADLDFSI
-------NVLV---------------------------------IGKT------------
----------------------------GV----------------------GKSAT-VN
SIFG-----------E------------TKSAVG-A--------FGVTTN----------
-------------------------------------------SANYVVG---NVGGIQI
SILD---------------TPGLLSS----------------------------------
-------------------------------ATEEQFNQEVLIAR---------------
------------------------------------------------------------
-----------------------------------------------------CLGIVLA
ENNMSFF----------------------------SANKSSEST----CSDWRLNLLILC
CSVKIRSKAGSLQKQNTDVEK---------------------------------------
-------------------AGVFGSQLSSFTLFCSLWN----------------------
---------------------------------------------VLLNSGHTSHSH---
-------------------DDLEEKKRKLLD-----------------------------
--------------SYPEIIWDEQSQECLEQ-----------------------------
--------------------------------------------------ETLLVENQES
EDVERQHEKGTVLGRVRTRRGR--------------------------------------
------------------------------------------------------------
---------------LGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRG
SMSVLGLVPMLISVFTSGKD----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------I
