>TOC100
M-----------------------------------------------------------
------------------------------------------------------------
-----------------------ESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARAD
SFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFI
DHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMS
FGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSI
HEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVS
FESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSLVE--------------QGVGQAS
TSKESNNRTDVGSVCDAD------------------------ELIIPRDESIGSESRDSG
DKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVA
GGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRKL------------------------
SLPDEDRASSLISSFETANETV--------------------------------------
------------------------------------------------------EDGNQL
ISRTMPENSS---------------VIAYDIMENETMARLI-------------------
--HNHTFMELDEYEGTGDTSEKLTGSS-------------------------FQNSSELL
SS----------NHSVELISERVKERVEKTQLLKE-KLQRIIRRTCLSRENSTVTKVASK
MSLAGGEHPTSLGLDHM-------------------------------FDGTKIVLPEQE
FPADLDFSINVLVIGK-TGV-----GKSATV------NSI-----------FGET--KSA
VGAFGVTTNSANYVVGNV-----------GGIQIS-------------------------
---ILDT-------------------------------PGLLSSAT-----------EEQ
FN----------------------------------------------------------
------------------------------------------------------------
---------------QEVLIARCLGIVLAENNMSFFSA----------------------
--NKSSESTCSDWRLNLLI-----------------------------------------
------------------------------------------------------------
----------------------------------LCCSVKIRSKAGSLQKQNTDVEKAGV
FGSQLSSFTLFCSLWNVLLNSGHTSHSHDDLEE---------------------------
------------------------------------------------------------
--KKRKLLDSYPEIIW--------------------------------------------
--------------------------------------------------------DEQS
QECLEQETLLVENQESEDVERQHEKGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGF
SIGSRDCRRNVQEEGKILVRMRGSMSVLGLVPMLISVFTSGKD-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------I
