>gnl|BL_ORD_ID|8280 @Capsella_rubella@_v10004016m|PACid:20893956
-------MESEKPGIVSILEAATVDSKKRRVSISAVRAVEAARAESFLLTRTLSGSFSSA
GSVPIRAPLTVDDEDDDDDVDSGSVIEEHSLASSEASRGIDSGTDDGYESVSGDADDETE
LEDVIMGGDRVHRILGEELSGEIGDVSDFSGGSVIYRPFAGDADEETSVNYSSLEERSEN
SDEVEGVSENEVSEADGVSMKAKVVIPRAILSLDDDEFDEILGSGDEEAVLLRGTKASSD
EEAEIGDRVFQFADEGVVNEPECSDSFIADVVSTEEEAVRMNYSEKLDDGLMSFGNIDES
SLDVLPGGSNDFMAENEGNSTEASMELGQSFKQLMEKGEIQSTINKDNGGGNIHNFDALV
KPNDAERVEDSAVDIANMGVNDKPEYTGSNIGEFVSTEEDM-------VQEKSSDDGLVS
FKSNLDAVPGDCNEFLVESEGNTVHEDIGLDETVSSLVEQQVGQGSI---SNNRT-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------YVGSACEANELMIPCEGY
IGSESRDSGD--------------------------------------------------
----------------------------------------------LDAVNMIGEAKEYF
ENDCGALSELEKPECEDEPEIDLSSESFQVSPTLDSLMARNLDVAGGVDVVVSGCGSSDR
KTEQESINEENHE-----------------------------------------------
------------------------------------------------------------
---------------------------------------SEDIARKLSL-SEDRASS---
------------------------------------------------------------
-----------LRSSSGTANETVEIGEQINLQVNFEPDVERTMPENSPVIVERTMPENSP
VIDYEIIENETQMAQRNHNNTFMELDECK-GSGDTRKELSKSTFQDYSEVLPSNHSVELI
SGKVKERVE-----------------------------------------KTKLLKEKLQ
RIIRNTGCCSENLSDTEVVSKLSLDGGEHQASLELDYISDGTKIKIT------EQKFPAD
LELSINVLV---IGKT-----------GVGKSATVNS----------I---------FGE
TK--S-------------------------------------------------AVGAFA
VTTKSANYVVGNVG----GLRIRI------------------------------------
-----------------------------------------------LDTP---------
----------------------------GF-------------------------MSSAT
EKQFNQGVLMSIKRSMRKFPVDVIL-----------------------------------
--------Y---------------------------------------------------
-----------------------------IDRL---------DDTPDIGLLRIITS----
-----------SLGS--------------------------------------------S
IWQNAIVVLTHAASDVPDT-----------------------------------------
----LSYKDFIAQRSYLMHQSIRQAVPKLSCVGQSKMPKIILAENN---------MSSFS
ANKSSESTCPD-----------------WRLKLLILCCSVKIR-----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------SKAGSLQKQNTDVEKAG
AF------------------------------------------------------GSQR
SSFTLFCSLWNVLLNSGHTSHSQDDLE---------------------------------
EKKRQLLDSYPEIIWDEQSQECLEQETLLIENQGPEDEERQHEKGKTNRGLEEGTVIDRV
RTRRGRLGFQATKRLGIYLDTSNLHTGLSIGTGGCRNNEEEEGRILLKMRGSMPVIGLVP
MLMSVFTSVHGGKDT---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
