>TOC100
M-----------------------------------------------------------
-------------------------------------ESEKPGIVSILAAATVDSEKPRV
SISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEEL
GGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEV
RMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSS------------------
--------------------------------------------EASI------------
------------------------------------------------------------
------------------------------------------------------------
----ELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMN
DKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDK
GLDETVS-----------------------------------------------------
----------------------------------------SLVEQ------------GVG
QASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGA
VSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEES
ENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIM
ENETMARLIHNHTFMELDEYEGTGDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVE
KTQLLKEKLQRIIRRTCLSRENSTVTKVASKMSLAGGEHPTSLG-----LDHMFDGTKIV
LPEQEFPADLDF------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------SINVLVIGK--------TGVG---------------------------------
------------------------------------------------------------
----------------KSATVNSI-----------F------------------------
------------------------------------------------------------
----------------------------------GETKSAVG-----AFG----------
---------------------------------VTTNSANYVVGNVG---GIQ-------
------------------------------------------------------------
------------------ISI----------------LDTPG------------------
------------------LLSSATEEQFNQEVLIA--------------RCLGIVLAEN-
-----------NMSFF--------------------------------------------
------------------------------------------------------------
------------------------------SANKSSESTCSDWRLNLLILCCSVKIRSKA
GSLQKQNTDVEKAGVFGSQLSSFTLFCSLWNV----------------------LLNSGH
TSHSHDDLEEKKRKLLDSYPEIIWDEQSQE------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------CLEQETLLVENQESEDVERQH
E-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------KGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKIL
VRMRGSMSVLGLVPMLISVFTSGKDI----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
