>TOC100
----M-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----ESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDF
ETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKV
VIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDF
MAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSA
VELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVES
EGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESR
DSGDKDAGNM--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------IGKAEEHCENDRGAVSELEKLECADEPEIGMSSES
FQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRKLSLPDED
RASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLIHNHTFMELDEYE
GTGDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIRRTCLSRE
NSTVTKVASKMSLA----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----GGEHPTSLGLDHMFDGTKIVLPEQEFPADL--DFSINVLVIGK-------------
------------------------------------------------------------
TGVGK-----------------SATVNSI---------FGETK---------SAVGAF--
-----------------------------GVTTNSANYVVGN-VGGI-------------
----QISILDTP------------------------------------------------
--------------------GLLSSATEE--QFNQEVLIA---------RCLGIVLAENN
MSFFSANKSSESTCSDWRLNLLILCCSVKIR-----------------------------
SKAGSLQK-------------------QNTDVEKAGVFGSQLSSFTLFCSLWNVLLNSGH
TSHSHDDLEEKKRKLLDSYPEIIWDEQSQECLEQETLLVENQESEDVERQHEKGTVLGRV
RTRRGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRGSMSVLGLVP
MLISVFTSGKDI------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------
