>TOC100
MESEKPGIVSILAAATVDSEK-----------------------------PRVSISAVRA
IAAARADSFLLTPSSEASSYSNGLDFET--------------------------------
------------------------------------------------------------
---------------------------------------DEDETVLEDVVLDGVRVDRLL
GEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVD
SEEVRMNYS----------DKLDDGLMSFGN-------------IEESSLGVPPEGSSDF
MAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVER-----
---VEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGE
CKEFLVESEGN-----AVDEDKGLDETVSSLV--EQGVGQASTSKESNNRTDVGSVCDAD
ELIIPRDESIGSESRDSGDKDAGN---MIGKAEEHCENDRGAVSELEKLECADEPEIGMS
SESFQLTPTSDSEM-------IMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDT
DRKLSLPDEDRASSLIS----------SFETANETVE--------------------DGN
QLISR-TMPENSSVIAYDIMENETM--------------ARLIHNHTFMELDEYEGTGDT
SEKLTGSSF--QNSSELLSSNHSVELISERVKERV----EKTQLLKEKLQRIIRRTCLSR
ENST-------------------------------------------VTKVAS------K
MSLAG----GEHPTSLGLDHMFDGTKIVLPEQEFPA--DLDFSINVLVIGKT--G-VGKS
ATVNSI---------FGE--TKSA------------------------------------
----------------------------VGAFGVT---------------TNSANYVVG-
NVGGIQISILD-----------------------------------------TPG-----
-LLSSAT-EEQFNQEV------------L-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------IARCLG----------------------------------------------
----------------------------IVLAENNMSFFS--------------ANKSSE
S-TCSD---WRLNL------LILCCSVKIRSKAGSLQKQ----------NTDVEKAGVFG
SQLSSFTLFCSLWNVLLNSGHTSH-----------------SHDDLEEKKRKLLDSYPEI
----------IWDEQSQECLEQ----ETLLVENQESEDVERQHEKGTVLGRVRTR-----
--------------------------------------------------------RGRL
GFQAT------------------------KRFGIYLDTSDVHAGFSIGSRDCRRNVQEEG
KILVRMRGS---------------------------------------------------
------------------------------------------------------------
-----------------------MSVLGLVPMLISVFTSGKDI----------
