>TOC100
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------ESEKPGIVSI
LAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVL
DGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEF
DEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIE
LGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEY
AGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDET
VSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKA
EEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCG
SSDQKAEEESENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPE
NSSVIAYDIMENETMARLIHNHTFMELDEYEGTGDTSEKLTGSSFQNSSELLSSNHSVEL
ISERVKERVEKTQLLKEKLQRIIRRTCLSRENSTVTKVASKMSLAGGEHPTSLGLDHMFD
GTKIVLPE------------------------------------QEFPADLDFSINVLVI
GK--------------------TG------------------VGKSATVN----------
------------------------------------------------------SI----
-------FGETKSA--VGAFGVTTNSA-----------------------NYVVGN----
----------------VGGIQIS--------------------------------ILDT-
------------------------------------------------------------
--------PG------------LLSSATEEQFNQEVLIARCLGIVLAENNMSFFSANKSS
ESTCSDWRLNLLILCCSVKI----------------------------------------
-----------------------------------------RSKAGSLQK----------
---------------------------------------------------------QNT
DV-----------------EKAGVFGSQLSSFTLFCSLWNVLL-----------------
NSGHTSHSHDDLEEKKRKLLD-----------------------------SYPEIIWDEQ
SQECLEQETLLVENQESEDVERQHEKGTVLGRVRTRRGRLGF------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------QATKRFGIYLDTSDVHAGFSIGSRDCRRNVQ
EEGKILVRMRGSMSVLGLVPMLISVFTSGKDI----------------------------
------------------------------------------------------------
------------------------------------------------------------
-
