>gnl|BL_ORD_ID|12132 @Linum_usitatissimum@_10027712|PACid:23151312
-------------------------------M----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----DWSLPNWFSKSLAS----------LSPVTFYESPPSDHHSDDDRDLTANSEA---
-LSPPDASPQQVVE----------------------ASSQPSTHHTEERDTHPLENIEHL
KINFFRLLR------------------------------RFGLPMDSPLVAKVLYRLHIA
ISIRGELPK---------------------------------RVRNINA---------LT
ITAAQEGSGVPELDFSVR----------------------------------------IL
V---LGKTGVGKSATINSI----L-----DQRATVTSAFQPATDRVQEV----IGTL--Y
GVRVTF-------------------------IDTPGFLPHSG-SGIRRNLKIMRSVKRFI
RES-PPDIVLFV--------------------------ERLDHLNTGYS-DFPLLQLM--
-----------TDVFGDAIWFNTMIIMT--------------------------------
------------------------------------------------------------
---------------------------------------------------HASSSLP--
------------------------------------------------------------
---------------------------------EGSIGGPVSYESHVSRCSQMMQHYIHE
AVSDTTLQN---------------------------------------------------
----------------------------------------LVVVVENHPQCDKNSN----
---GDAILPNGQVWRSQFLL----------------SCICTKVLGD--------------
---------------ASNILELKNSIELG-------PKTRPQVLSLPRLLSWL-------
-----------------------------IKNKAVSGPTPDGHDLDEIILVDED------
-----------------------------------------------------EED----
--EYDHLPPIRILTKSQFAKLSKSQKNDYLDELDYR------------------------
------------------------------------------------------------
------------------------------------------------------------
---EMVYMKKQLKEESRSRREKMLLGKAS-------YEEFDKSEATNAPPETVLLPDMAV
PPSFDSDCPVHRYRCLIEI-----------------------------------------
---------------------------GDQLLTRPVLDPRGWDHDVGFDTIDLETAIEMK
KNLCASYSGQINKDKNNFSIQSECAVTYADLKGPTYS---AGLNVQKAGKDDLVYTIHGN
TRSKIFTNNNVADCGVSVTSSCNKCYLGAKLENSVLVGKRLKLLINGGQMRGPGQVVNGG
SLEATILGTDYPMRNDKVSLSLTALSFNKETVVSGGVESEFQLMRGTRVAVNANLNSLHM
GKVGIKA--SSSEHLEIAVIAALTIFSAIFR-----------------------------
------------------------------------------------------------
-----------KRVANTSPDVSET------R
