>gnl|BL_ORD_ID|24019 @Malus_domestica@_0000872008|PACid:22643995
------------------------------------------------------------
-ME---------------------------------------------------------
--------------------------NGDKIAGGSEVGENKGVDVKVVE-----------
-ERVVEGSNGLKDDAEDEVFEEAIETQENSQEQGSK------VDLVDAVVVGEERETETV
GGLGLASLIESP-------SVDTFEEAIEVPDEVGKSDDDD-------------------
-------------------------------------------AEVKVENLVGGNS----
--------DDEVGVAGGIDDEQTKKEA-------------------VTEETNGLTDDGLV
G--SQEDAVKEVTQVEAGGGISSLTGGDEADVKSVDLENVKFEKDNFELNGLA-DGLVGS
Q--------DVEVKEVSEIITGAEIVGLTNVGEVDSKPNVVLENKEPEKDDLDNSTSEPV
STDEKLDTE---DLDSPQVTEFNKEILKEAGNGQELEENSLSIENQDEKTVDLLSASDGV
PLKLEDDNGVELLDRNMDTVHQEGDSAE------S-------------------------
----------------NDATLGIEEKQEY-NKTEELRDTLTFTDAEHQGFSNGEVK-DSF
TVLGSEHHEEKSEPKSISSDKQLSGEDSEE------------------------------
-----MIVTSEREISAL---SERSAAEKTEKIQDGATNLRAQSNKDDQ--PQR-ADEIAP
EVRDNIAVPEEPEKKENIQAEKGVTKVNKEQEIQPVSTLSSSGNSTQPSPPPA------R
PAGLGRAAPLLEPAPRVVQHPRVNGTVSHAQNQQIEDPVNGETEESDETREKLQM-----
---IRVKFLRLAHRLGQTPH----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---NVVVAQVLYRLGLAEQLRG--------------------------------------
---------------------------------------------------------RNG
--GRVGAFSFDRASAMAEQLEASG------------------------------------
----NEPLDFA------C------------------------------------------
--TIMVLGKSGVGKSA---------TINSIFDEKRFTTDAF----QMG------------
TKKVQDVVGTV--QGIKVR------------------------------------VIDTP
-----------------------------GL----------------------------L
PSWSDQ-RQNEKTLLNVK------------------------------RFIKKTPPDIVL
YLDRLD-----MQSRDFSDM-----PLLRTITDIFG--P-----------SIWFN-----
-----------AIVVLTHAGSAPPEGPNGAASSYDMFVTSRSHVVQQAIRQAAGDMRLMN
-----PVSLVENHSA-CRINRAGQR----------VLPNGQVWKPHL------LLLSFAS
K----------------------------------ILAE---------------------
A-----------------------------------------------------------
------------------------------------------------------NALLKL
QDSP-PGKPFATRTRAPPLPFLLSSLLQSRPQLKLPEEQ--------FGXDDSLDDDLDE
SSDSD-------------------------------------DES-------------EF
DELPPFRRLTKAQVEKLSKAQKKAYFDELEYREKLFMKKQLKEEKKRRKLMKKMAAASNE
LPSDYVENVE---------------EDSSGAASVPIPMPDLALPASFDSDNPTHRYRYLD
SSNQWLVRPVLEQHGWDHDVGYEGINAERLFVVKEKIPLSFSGQVTKDKKDANVQMEIAT
SIKHGEGKATSLGFDMQTVGKDLAYTLRSDTRISNFRKNKATAGLSVTLLGDAVSAGMKV
EDKFIANKRFQLVMTGGAMTARGDVAYGGSLEAQLRDKDHPLGRSLSTLGLSVMDWHGDL
AIGCNIQSQIPVGRHTNLIARANLNNRGAGQLSLRLNSSEQLQLALIGLVPLLRKLFTFP
Q---QLQYGQ--------------------------------------------------
-----------
