>gnl|BL_ORD_ID|15640 @Manihot_esculenta@_4.1_002111m|PACid:17975485
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---KSIRDWVFTRLLS----SSRSLSGSGSFFSEGPADEDSNA-------PEVAPVLPDT
SYFSGNTEGNEPHPSLPGDLNR--------------------------------------
----------------SNNVNDCEKADSLAKIEDLEVKFFRLLRRLG-------------
-----HSSDNLLVA--------------------KVLYRIHLATSIRGR------ESDLK
RARKIAAEQ------------EAIDKPK---LNFSI-RILVLGKTG--------------
------------------------VGKSATINSI-----------FDQRKTTTDAFEA--
---------ATKHIQEIVGT------------V--SGVK---------------------
-----------------VTFIDTPGF-----------------------LPASANNVRRN
RKIMLS--------------VKRFI--RKSPPDIVLFC----------------------
-ERLDLVNMGYSDFPLVKLMTEVLGS----AIWFN-------------------------
------------------------------------------------------------
----------TI---------LVMTHASSMLPEGPNGFSVNYESYVTKCTDLMQQFIHQA
VL------------------------DRKL-----ENPVLLVENHPQ-CKKNFAGENILP
NGQAWKSQFLLLC--------------------------ICTKILGDVS-----KLLEFQ
GSIE---LGSSSPRVPSLPHLLSSLLRHHVS-----------------------------
----------------------NPNEVDDDVYEILLSDAEEE---DEYDQL-PPIRILTK
SQFERLTKSQKRDYLDELDYRETLYLKKQLK-------EDARSKREKKLAEAERLG----
---EDNS-DDQQTPTEAVLLPDMAVPPTFDSDCPVHRYRCLATSDQWLMRPVLDPRGWDH
DVGFDGINLETAVEIKRNISASIAGQMCKDKQNFSIQSECAAAYTDPRGPTYSVGFDVQS
AGKDIIYTVH--------------------------------------------------
--------GNTKLATLKHNNADCAVSLTSFGKKYYVGAKIEDNILIGKRLKFVMNAGQMR
GRGQVAYGG---------------------------------------------------
----------------------TFEATLRGQDFPVRNDIISLSLTALSFKKEMVLSGGFQ
SEFRPVRNMRVAVNANLNSQKMGQVSIKMSSAEHIEIALAAIFSIFRVMLYRKESKNGSR
ETLEM-----------------------------------------------
