>TOC100
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------ESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEA
SSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGD
ERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLG
VPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPS
DVERVEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTG
ECKEFLVESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPR
DESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPT
SDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRKLSLPDEDRASSLI
SSFETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLIHNHTFMELDEYEGTGDTS
EKLTGSSFQNSS------------------------------------------------
--------ELLSSNHSVELISERVKERVEKTQLLKEKLQRIIRRTCLSRENSTVTKVASK
MSLAGGEHPTSLGLDHMFDGTKIVLPEQ--------------------------------
--------------------EFPADLDFSINVLVIGK-----------------TGVGK-
-SATVNSIF-----------GETKS---------------------------AVGAFGVT
TNSANYVVG---------------------------------------------------
--------NVGG---------------------------IQISIL---------------
------D--------T-----------P-GL-LSSATEEQFNQEVLIARCLGIVL-----
AENNMSFFSANKSSESTCSDW-RLNL----------------------------------
------------------------------------------------------------
---------------------LILCCSVKIR-----------------------------
------------------------------------------------------------
-----------------------------SKAGSLQKQNTDVEKAGVFGSQLSSFT----
------------------------------------------------------------
------------------------------------------------------------
-------------LFCSLWNVLLNSGHTSHSHDDLE------------------------
------------------------------------------------------------
------------------------------------------------------------
------EKKRKLLDSYPEIIWDE-------------------------------------
------------------------------------------------QSQECLEQ----
------------------------------------------------------------
-------------------ETLLVENQESEDVERQHEKGTVLGRVRTRRGRLGFQATKRF
GIYLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRGSMSVLGLVPMLISVFTSGK-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------DI
