>TOC100
MESEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETD
EDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDER----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------GSMKAKVVIPRAV
LSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEG
NSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKM
GMND------KPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVES
EGNAVDEDKGL-------------------------------DETVSSLVEQGVGQASTS
KESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELE
KLECADEPE-------------------------------------IGMSSESFQLTPTS
DSEMIMNLEVAGGIDVV---------------VIGCGSSDQKAEEESENEGNQESDDTDR
KLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIME--NETMARLIHN
HTFMELDEYEGTGDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQ--------
--------LLKEKLQRIIRRTCLSRENSTVTKVA-SKMSLA----------GGEHPTSLG
LDHMFDGTKIVLPEQEFPADLDF------------------------------SINVLVI
GKT--GVGKSATVN--SIFGE------------TKSAV----------------------
----------------------------GAFGVTTNSA----------------------
--------NYVVGNVGGIQ-----------------ISI---------------------
-------------------------------------------------------LDTP-
-----------GLLS---------------------------------------------
--------------------------------------------------SATEEQFNQE
VLIARCLGIVLAENNMSFF-----------------------------------------
---S----------------ANKSSESTCSDWRLNLLILCCSVKIRSKAGSLQKQN----
----------------------------------------------------TDVEKAGV
FGSQLSSFTLFCSLWNVL-----------LNS----------------------------
---------------------------------------GHTSHSHDDLEEKKRKLLDSY
PEIIWDEQSQECLEQETLLVENQESEDVE-------------------------------
----------------------------------------------------------RQ
HEKGTVLGRVRTR-----------RGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNV
QE---------------------------------------EGKILVRMRGSMSVLGLVP
MLISVFTSGKDI------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------
