>TOC100
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------ESEKPGIVSILAAAT
VDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRV
DRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILG
SDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNF
KQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNI
GELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSLV
EQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCE
N-----------------------------------------------------------
------------------------------------------------------------
----------------------DRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIM
NLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRK--------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------LSLPDEDRASSLISS
FETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLI------------HNHTFMEL
DEYEGTGDTSEKLTGSSFQNSSELLSSNHSVEL---------------------------
----------------------------------ISERVKERVEKTQLLKEKLQRIIRRT
CLSRENSTVTKVASKMSLAGGE--------------------------------------
------------------------------------------------------------
-----HPTSLGLDHMFDGTKIVLPEQEFPADLDFSI------------------------
--NVLVIGKTG---------------------------VGKSATVNS-------------
-IFG-----------ETKS-----------------------------------------
----AVG---------------------AFGVTTNSANYVVG-NVGGIQISILD------
----T----------PGLLSSAT------------EEQFNQEVLIARCLGIV--------
------------------------------------------------------------
-----------LAENNMSFFSA---------NKSSESTCSDWRLNLLILCCSVKIRSKA-
-----------------------------GSLQKQNTDVEKAGVFGSQLSSFTLFCSLWN
VLLNSGHTSHSHDDLEEKKRKLL-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------DSYPEIIWDEQSQE
CLEQETLLVENQESEDVERQHEKGTVLGRVRTRRGRLGFQATKRFGIYLD----------
------------------------------------------------------------
---------TSDVHAGFSIGSRDCRRNVQEEGKILVRMRGSM------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------SVLGLVPMLISVFTSGKDI
