>TOC100
MES---------------------------------------------------------
-------------------------------------------EKPGIVSILAAATVDSE
KPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLL
GEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVD
SEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLI
EKGDSKSTINKEDSGGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNIGELV
SIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSLVEQGV
GQASTSKESNNRTDVGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRG
AVSELEKLECADEPEIGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEE
SENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDI
MENETMARLIHNHTFMELDEYEGTGDTSEKLTGS---------------------SFQNS
SELLSSNHSVELISERVKERVEKTQLLKEKLQRIIRRTC---------------------
--------------------------------------------LSRENSTVTKVASKMS
LAGGEHP-----------TSLGLDHMFDGTKIVLPEQEFPADL-----------------
------DFSINVLVIGKTG-----------------------------------VGK---
------------------------------------------SATVNSI--FGE------
---TKSAVGAFGVT----------------------------------------------
--TNSANYVVGN---VGGIQISILD---------------TP----GLLS---SATEEQF
N-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--QEVLIARCLGIVLAENNMSFFSANK---------------------------------
---SSESTCSDWRLNLLILCCSVKIRS---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----KAGSLQKQNTDVEKAGVFGSQLSSFTLFCSLWNVLLNSGHTSHSHDDLEEKKR---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KLLDSYPEIIWDEQSQECLEQETLLV
ENQESEDVERQHEKGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNV
QEEGKILVRMRGSMSVLGLVPMLISVFTSGKDI---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
