>TOC100
MESEKPGIVSILAAATVDSEKP--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------RVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFET
DEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFID--------------------
-----HLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDD
GLMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDS
GGSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDN
VLVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTD
VGSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEP
EIGMSSESFQLTPTSDSEMIMN--------------------------------------
---------------------------LEVAGGIDVVVIGCGSSDQKAEEESENEGNQES
DDTDRKLSLPDEDRASSLISSFETANETVED--------GNQLISRTMPENSSVIAYDIM
ENETMARL--------IHNHTFMELDEYEGTGDTSEKLTG--------------------
---------------------------------SSFQNSSELLSSNHSVELISERVKERV
-------------------------EKTQLLKEKLQRIIRRT------------------
------------------------------------------CLSRENSTVTKVASKMSL
AGGEHPTSLGLDHMFD------GTKIVLPEQE------FPADLDFSI-------------
------NVLVIG------KTGVGKSAT---------------------------------
VN-------------------------SI-----------FGE------------TKSAV
GA----FGVTTNSANYVVGN-V--GGI---------------------------------
----------------------------------------------QISILDTP------
------------GL-----------------------LSSA-TEEQ--------------
FNQEVL------------------------------------------------------
------------------------IARCLGIVLAEN------------------------
--NMSFFSANK-S-----------------------------SESTCSD-----------
----------------WR----------------------LNLLILCCSVKIRSKAGSLQ
KQNTDVEKAGVFGSQLSSFTLFCSLWNVLLNSG---------------------------
----------HTSHSHDDLEEKK-------------------------------------
---------------------RKLLDSYPEIIWDEQSQECLEQ-----------------
-----------------ET--LL----------VENQESEDVERQ---------------
-----------------------------------------------------------H
EKG-------TVLGRVRTRRGRLGFQATK---RFGIYLDTS---------DVHAGFSIGS
R-----------------------------------------------------------
------------------------------------------------------------
--DCRRNVQEEGKILVRMRGS----MSVLGLV----------------------------
--------------PMLISVFTSGK---------DI-------
