>TOC100
M----------------------------------------ESEKPGIVSILAAATVDSE
KPRVSISAVRAIAAARADSFLLTPSSEASSYSNGLDFETDEDETVLEDV-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------VLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERG
SMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPP
EGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVE
RVEDSA-------VELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLG
VMTGECKEFLVESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADEL
IIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQ
LTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRKLSLPDEDRA
SSLISSFETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLIHNHTFMELDEYEGT
GDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIRRTCLSRENS
TVTKVASKMSLAGGEHPTSLGLDHMFDGTKIVLPEQEFPADLDFSI-NVLVIGKTGVGKS
ATV----------------------------------NSIFG-----------ETKSAV-
GAFGVTTNSANYVVGNV-----GG----------IQIS-ILD------TPGLLSSATEEQ
FN-QEV------------------------------------------------------
-----------------LIARCLGIV----------------------------------
----------LAENNMSFFSANKSSES---------------------------------
------------------------------------------------------------
-----------------------------------------TCSDWRLNLLILCCSVKIR
SKAGSLQKQNTD-----------------VEKA-------------------------GV
FGSQLSSFTLFCSLWNVLLNSGHTSHSHDDLEEKKRKLLDSYPEIIWD------------
--------------------------------EQSQECLEQETLLV--------------
------------------------------------------------------------
-----------------------------------------------------ENQESED
VERQHEKGTVLGRVRTRRGRLGFQATKRFGIYLDTSDVHAGFSIGS-RDCRRNVQEEG--
------------------------------------------------------------
-------------KILVRMRGSMSVLGLVPMLISVFTSGKDI------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
