>TOC100
ME-----SEKPGIVSILAAATVDSEKPRVSISAVRAIAAARADSFLLTPSSEASSYSNGL
DFETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQSEVSGDERGSMKA
KVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNIEESSLGVPPEGSS
DFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFDALMKPSDVERVED
SAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESSLGVMTGECKEFLV
ESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDADELIIPRDESIGSE
SRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEIGMSSESFQLTPTSDSEMIM
NLEVAGGIDVVVIGCGSSD-----------------------------------QKAEEE
SENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSS------
------------------------------------------------------VIAYDI
MENETMARLIHNHTFMELDEYEGTGDT--SEKLTGSSFQNSSELLSSNHSVELISERVKE
RVEKTQLLKEKLQRIIRRTCLSRENSTVTKVASKMSLAGGEHPTSLGLDHMFDGTKIVLP
EQ----------------------------------------------------------
--------------EFPADLDFSIN-----------------------------------
---------------------------VLVIGKTGVG--------------------KSA
-----------------------TVNSIFGE-----------TK--SAV-----------
---------------------------------GAF-GVTTNSANYVVGNV-GGIQISIL
-----------------------------DTPGL-----------------------LSS
A------------------TEEQFNQEVL-----------IARCLGIVL-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------AENNMSFFSANKSSESTCSD--------WRLNLLILCCSVKIRS
KAGSLQKQNTDVEKAGVFGSQLSSFTLFCSLWNVLLNSGHTSHSHDDLEEKKRKLLDSYP
EIIWDEQSQECLEQETLL------------------------------------------
----------------------------VENQESEDVERQHEKGTVLGRVRTRRGRLGFQ
ATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRGSMSVLGLVPMLISVFTSGK
DI----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
