>gnl|BL_ORD_ID|14253 @Thellungiella_halophila@_Thhalv10024270m|PACid:20193804
ME---PRGISILA---VDSEKPRAIAIPAARAVA---ADAFLLTHISNASNYSRGVDSGT
DDGFESVSGDADDETELEDVIMGGVRVHRVLGDNPGGETGDGSDFSGGSVIYRPFAGDIE
EETSLNYSSLEEESENNSEDVDGVSE----------------------------------
------------------------------------------------------------
--------------------------------SEVSEADGVSMKAKVVIPRAILSLDDDE
FDEILGSDDEGAALLRVTKAPGGEETEDRTSQFGGVGMADEPECSDSVIGEFVSTEEEVV
MDNTDELDNGLKSFGNTDEQSLGVPTGGANDFIVEKEGNSTESAMGFGGNSKQLVEHEVQ
RSIIN-NDGGGSIHEVDTLMKPCDVEGVDDNAVESGKMGRVDKPECSGSVTSEIVSTDED
MVQVKISDNGLVSVETSLGVAPGDCNEFLVESEGNVVDADRGLDETF-------------
SKESGNRTDDNRSCEADESMIPGEGSIGIGRKESGDEVTGNMIGESKEHCENDCGAVSEL
EKSECKGEPEIGLSSETFQLSPTLNAVTTRNLEVDGGIDVVVSGCGSSDQKAEQEAENEG
KQESEDINRKLSLADEDRAPS---------LRNSFETASESPEKRGQILEQINKQVFFQS
DTEPNQISIE--------------------------------------------------
-----------------------------------------ETSLLSVKDVERTMLENSC
VTTYAEVENETQMARLVNNHTFM-------------------------------------
-GKNTESNFQNCSEELSPD--------------------------------NSVQLISEK
VKERVEKTKL--------------------------------------------------
---------------------------------------------------------LKE
KLQRIIRTI----------------------------DLGGENSAVT-------------
--------------------------------------------------------EVES
KLSL---ADGEHQTSLGL------------------DYVSDGTKIMLPEQEF--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------PDDLDFSINVLVIGKTGVG---KSATVNSI---------FGETK
--SPVGAFRVT-------------------------------------------------
-TKSANYVVGN-VGGVLIRVLDTPGL-----------------------V-SSAT-----
------------EEQYNQDVLMS--------------IKKSIRAFPVDVFLFI-------
------------------DRLD----DNPDI----------HLLRIVTSSLGSS------
-----------IWRNAIVVLTHAASDV---------------------------------
-----PDS-----SSCKDF--IAQRSSLMHQSIRQAVPEL--------------------
-AYVDQSKMPGIV-LAENNNLSSLCGNKTSESTCV-------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------DW------------------RLNLLILCCSVKIGSKAD---------
-----SL-QKHKAIIEKAGVIGSQRRSFTVFCSLWNVLLLGANSGHASHSQDDLEEKK--
-----------------------RRLLDSYPEILWDDQSQES----------LEP----E
DEETR-HENGNVNKGLERGTVHGRVRTR--------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------RGRLGFQATKRFGIYLDTSDLHTGFSIG---
-----------------------------SRGCRKHEQEEEEERRILVRMRGS----MSV
LGLVPMFMS---------VFTCVYGRKDN-------------------------------
------------------------------------------------------------
---------------------------
