>TOC100
MESEKPGIVSILAAATVDSEKPRVSISAVRAI------------------AAARADSFLL
TPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGVGFIDHLQ
SEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDGLMSFGNI
EESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSGGSIHEFD
ALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNVLVSFESS
LGVMTGECKEFLVESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDVGSVCDAD
ELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPEI------
-----------------GMSSESFQLTPTSDSEMIMNLEVAGGIDV-----VVIGCGSSD
QKAEEESENEGNQESDDTDRKLSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSS
VIAYDIMENETMARLI--------------------------------------------
-----------------HNHTFMELDEYEGTGDTSEKLTGSSFQ----------------
----------------------NSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIR
RTCLSR-------------ENSTVTKVASKMSLAGGEHP---------------------
----TSLGLDHMFDGTKIVLPEQEFPADLDFSINVLVIGKTGVGKSATVNSIFGETKSA-
VGAFGVTTNSANYVVGNVGGIQISILDTPGLLSSATEEQFNQEVL---------------
---------------------IARCLGIVLAENNMSFFSANKSSEST-------------
------------------------------------------------------------
------------------------------------------------------------
----CSDWRLNLLILCCSVKIRSKAGSLQKQNTDVEKAGVFGSQLSSFTLFCSLWNVLLN
SGHTSHSHDDL-------------------------------------------------
------------------------------------------------------------
---EEKKRKLLDSYPEIIWDEQSQECLEQETLLVENQESEDVERQ---------------
-HEKGTVLGRVR-----TRRGRLGFQATKRFGIYL-------------------------
------------------------------------------------------------
------------------------------------------------------------
--------DTSDVHAGFSIGSRDC-----------RRNVQEEGKILVRMRGSMSVLGLVP
MLISVFTSGKD-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----I
