>gnl|BL_ORD_ID|15727 @Vitis_vinifera@_GSVIVT01024062001|PACid:17832352
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------YTPVDEGVSASGTGRSPSVEDSAIEKS----------------------
--------------------------------------------------------EMEQ
CAIEDSTIEKS--ETKQGVTSELAAADNISPQPERAVENVAEVKNKYVVFEEQETKEPNM
EKEDQKIQGNRERE---------IRPAEQVASSSGRSSNPGP------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PPA
HPAGLGRAAPLLEPASRVVQQPRVNGTTSQVQAQLIEDAGNGEAEENDETREKLQ-----
--------------------------------MIRVKFLRLAHRLGQT------------
----PHNVVVAQVLYRLGLAEQLRGRNGGRVGAFSFDRASAM------------------
-----------------------------------------------------AEQLEAA
GQEPLDFSCTIMVLGKTG---------------------------VG--KSATINSIFDE
------------VKFSTDA-----------------------------------------
---------FQVGTKKVQDVVGTV--QGIKVRVI------------DTPGLLPSWS----
----------DQRQNEKILHSVKRFIKKTPPDIVLYLD---------------------R
LDMQSRDFGDMPLLRTI---------------TEIF--------------GPSIWFNAIV
VLTHAA--------SAPPDGPNGTASSYDMFVTQRSHVVQQA------------------
------------------------------------------------------------
------------------------------------------------------IRQAAG
DMR-----LMNPVSLVENHSA------------CRTNRAGQRVLPNAN------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------TLLKLQDSPPGKPFTTRSRSPPLPFLLSSLLQSRP
QVRLP-------------------------------------------------------
EEQKERRKMMKKMAASSKDL-------------------------------------PSD
YSENAEEESGGAASVPVPMPDWALPASFDSDNPTHRYRYLDSSNQWLVRPVLETHGWDHD
VGYEGINVERVFAIK---------------------------------------------
----------------------------------DKIPVSFSGQVTKDKKDANLQMEIAS
SVKHGEGKATSVGFDMQTVGKDMAYTLRSETRFCNFRKNKATAGLSITALGDAIT-----
------------------------------------------------------------
----------------------------------------------------------AG
LKLEDKLIVNKRIRLVMTGGAMTGRGDVAYGGSLEATLRDKDHPLGRSLSTLGLSIMDWH
GDLAIGCNIQSQIPIGRFTNMIGRVNLNNRGAGQVSIRLNSSEQLQIALIGLVPLLRKLL
GYSQQGQSSCFLIVYAFGMNCKIPGMYQKGLSFFLYLYSWITSAGANETLGSMLLGYVNI
CNTYESFS-----------------------------------
