>TOC100
MESEK-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------PGIVSILAAATVDSEKPRVSISAVRAIAAA
RADSFLLTPSSEASSYSNGLDFETDEDETVLEDVVLDGVRVDRLLGEELGGDGSEFQVGV
GFIDHLQSEVSGDERGSMKAKVVIPRAVLSLDDDEFDEILGSDVDSEEVRMNYSDKLDDG
LMSFGNIEESSLGVPPEGSSDFMAENEGNSSEASIELGQNFKQLIEKGDSKSTINKEDSG
GSIHEFDALMKPSDVERVEDSAVELAKMGMNDKPEYAGSNIGELVSIEEVMVQEKSSDNV
LVSFESSLGVMTGECKEFLVESEGNAVDEDKGLDETVSSLVEQGVGQASTSKESNNRTDV
GSVCDADELIIPRDESIGSESRDSGDKDAGNMIGKAEEHCENDRGAVSELEKLECADEPE
IGMSSESFQLTPTSDSEMIMNLEVAGGIDVVVIGCGSSDQKAEEESENEGNQESDDTDRK
LSLPDEDRASSLISSFETANETVEDGNQLISRTMPENSSVIAYDIMENETMARLIHNHTF
MELDEYEGTGDTSEKLTGSSFQNSSELLSSNHSVELISERVKERVEKTQLL---------
---------KEKLQRIIRRTC---LSRENSTVTK--VASKMSLAGGEHPTSLGLDHMFDG
TKI------------------------------------------VLPEQEFPADLDFSI
-------NVLV---------------------------------IGKT------------
----------------------------GV----------------------GKSAT-VN
SIFG-----------E------------TKSAVG-A--------FGVTTN----------
-------------------------------------------SANYVVG---NVGGIQI
SILD---------------TPGLLSS----------------------------------
-------------------------------ATEEQFNQEVLIAR---------------
------------------------------------------------------------
-----------------------------------------------------CLGIVLA
ENNMSFF----------------------------SANKSSEST----CSDWRLNLLILC
CSVKIRSKAGSLQKQNTDVEK---------------------------------------
-------------------AGVFGSQLSSFTLFCSLWN----------------------
---------------------------------------------VLLNSGHTSHSH---
-------------------DDLEEKKRKLLD-----------------------------
--------------SYPEIIWDEQSQECLEQ-----------------------------
--------------------------------------------------ETLLVENQES
EDVERQHEKGTVLGRVRTRRGR--------------------------------------
------------------------------------------------------------
---------------LGFQATKRFGIYLDTSDVHAGFSIGSRDCRRNVQEEGKILVRMRG
SMSVLGLVPMLISVFTSGKD----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------I
