>gnl|BL_ORD_ID|433 @Arabidopsis_lyrata@_911963|PACid:16034180
MDSKSATPEPTNPFYASGKSGKTYASVVAAAAAAAADKEDGGAVSSAKELDSSSEALSGN
SDKVGADDLSDKEKPNLEGDGKVSDEVDDSAIPEATPKPEVVSDGTIEEDGVSLLSPKPE
AVSDGLVVVEENKKVNEDVEDIKDD---------GES-----KIENGSVDVGEKQAS---
-TDGIVVDENPERESESKVKDVGEEDVGAKKVDEVTQASGANEEESELSGKVDVDDKSDY
VIEEEGVKLTD-------------------------------------------------
---------------------------KGDVIVDSSPVESVHVYVAKPGVAVVGDAEGSE
ELNINADAETLEVANKFDQIGDDDGGELEPVSDKAIEEVEEKLSSGADSSKLESVDTNAA
EPEVVAVESGTEPKDVEQTNGLEKGMTYAEVIKAATAVADNGTKEEESVFSGVVDDEEEG
VKLTNKGDFVVDSSAIKAVNVDVAKPGVVVVGDVEASEVLETDGKITDVHNKFDPVGQVE
GDGVERESVKATEEGGEKLTSEGDSVVDSS----VVESVDADINVAEPGV--VVVRAAKE
AVIKEDDGDDEVD--KTIPNIEEPDDLTAAYDGNFELAAKEMSGAAKVEPD---EPKVGV
EVEESPVS----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------ESLTVGSVDAKEDSNPAAQSQFEANQNPEVREVFEGDNAEEGGNKLPAE
DIVSSREFSFEGKEVDQEPSGEGVTRVDGSESEEETEEMIFGSSEAAKQFLAELEKASSG
IEAHSDEANISNNMSDRIDGQIVTDSDEDVDTEDEGEEKMFDSAALAALL----------
-------KAATGGGSSEGGNFTITSQDGTKLFSMDRPAGLSSSLRPLKPAAAPRANRSNI
FSNP---NVTMADETEVNLSEEEKEKLEKLQSLRV--------KFLRLLQKLGHSAEDSI
AAQVLYRLAL---LAGRQTGQF--FSLDAA------------------------------
--------------KKKAVESEAEGNEDLNFSLNILVLGKAGVGKSATINSILGNQKASI
DAFGLSTTSVREISE---------------------------------------------
-------------TVGGVKITFIDTPGLKSAA----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MDQSANAKMLSSVKKVMKKCPPD-
------------------------------------------------------IVLYVD
RLDTQTRDLNNM------------------------------------------------
---------------------------------------------PLLRTITASLGTSIW
KN--------AIVTLTHAA----------------SAPPDGPSGTPLSYDVFVAQC----
-------------SHIVQQSI--GQAVGDLRLMNP----------SLMNPVSLVEN----
---------------------------HPLCRKNREGVKVLPNGQTWRPQLLLLCYSLKV
LSEANSLLKPQEPLDHRKVFGFRVRSPPLPYLLSWLL-----------------------
------------------------------------------------------------
------------------------------------------------------QSRAHP
KLPGDQGGDSVDSDIEIDDVSDSEQEDGEDDEYDQLPPFKPLRKTQLAKLSKE-------
----------------------------------------------QRKAYFEEYDY---
---RVKLLQKKQWREELKRMKEMKKNG-KKVGESEFGYPGEEDDPENGAPAAVPVPLPDM
VLPPSFDSDNSAYR----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---YRFLEPTSQLLTRPVLDTHGWDHDCGYDGVNAELSLAVASRFPATAT------VQVT
KDKKEFNIHLDSSVSAKHGENGSTMAGF--------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------DIQNVGKQLAYVVRGETKFKNLRKNK
TTVGGSV-----------------------------------------------------
-TFLGENIATGVKLEDQIALGKRFVLVGSTGTMRSQGDSAYGANLEV-RLREADFP----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------IGQDQSSFG-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------LSLVKWRG----------------------------D
LALGANLQ--SQLSVG--RNSKIALR--------------------AGLNNKMSGQITVR
TSSSDQLQIALTAILPIAMSIYKSIRP---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----DATNDKYSMY
