>gnl|BL_ORD_ID|12035 @Selaginella_moellendorffii@_60423|PACid:15413313
T-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------QGNTEEKTRILCEKLQDIRVKFVRLV
HRLGQSADNGIAAQVLYRFALAEQLKGGK--MRNSTSGYDKACAVAMEEEASSRDEELDF
C---CTVLLLGKSGVGKSATVNSIFGK----------------PMASTSAFSSG------
--------TNKVEVIDGTMKGIRMRVI---DTPGLSASMAD-----------------RR
YNERVVASIKRCIRRNPPDIVLYVDRLDSQSK-------------------DAALMRYIG
DRFGPAIWFN-----------------------AIIVLTHGASSPPDGPD----------
---------------------------------------GFPLRYDSYVGQR--------
---------TRMFQQTVRSAVGDTRLLNPV------------------------------
-----------------------------------------------TLIENHPACRTNR
AGERVLPNGMVWRPELLLL-----------------------------------------
--------------------------------CFSARILAEANTYLKLPESMPLTRLCER
RSGSPMPVLLASMLQA---------------------------RSEVQQPDEEEYGEVDP
DED-----EDGEAEFDQLPPFRRLLQDELDALDEDNRQSYFEELALREKLFK--------
-----------------------RKLWKTQCRRWREMKNRG------------VEDGEDE
QQQHRDMAPGISPDFALP-TSFSSDDPSHRYRYVDDAS-WNVRPVLDS------------
-------------RWDHENGFNSANLDRSFHLAKNIPVSVSGQIVMDKKEYHVTFDGSAA
IKHGPNRVSTGGLDIQTVGRDVCYSLWGGTTFKNHECNKTLAG-----------------
-----------------------------------------------------------M
GVTMVGENAVVGVRLEDKVVI---GKRAKILMSG----------ATSLTRGD--------
---KAYGAIMEATVVGP-------------------DYPVDRTNCT--LGLSVMNWTAKD
IAYGIN-----------------LHSQIHLGGTAM-------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------VVRGNANNRGTGQISIK---------------------
------------------------------------------------------------
-------VNSTDRIQLALLGLLPVIRS---------------------------------
------------------------------------------------------------
-----------------------------L
