>gnl|BL_ORD_ID|17720 @Thellungiella_halophila@_Thhalv10029135m|PACid:20197318
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------DVVAGRGYNEHEVLSNVKGSN-------------------TSSQSLAG-
----KSESCVAGGT---NDSSLYNSDQSALPMTDSVTSVSPESGSS-SLSTMSEVETVEE
EDGLESKDGIKEERSFDDDNKSDQVV------QEEIVNFTCTESKDSPIVSVDAKEDSKS
---AAESSQP----------------SSDGTKNLSVEPPAPPRPKGFNIFPSLKLAMD--
-EESVHNLSEAEKHKLEKLQSLR----------VKYLRLVHRLRQSIDISIAEHVLHRLA
L---LSGKGSGQ--SFSLDAAKKKAMESEAEGEDDLNFSV-NILVLGKSGVGKSATINSI
FGEQNAPIDAFGPSTTSVREISGTVGGVKITIIDTPGLKSSAMDQNANSKMLSSVKKA--
------MKKCPPDVVLYVDRLDTQTKDLNNLLLI--KTIAASLGPSILKNAIVTLTHAAS
APPDGPSGNPLNYDVFVSQCSYLIQQSIGQAVG---LTYSGPMTPVSLVENHPLCRKNRA
GEKILPNGQAWKPGLLLLCYSLKVLSEAVSLSIPPQE----SKFFGSRVRAPPLSSILSW
LLPSRAHLKLPADQGGAGVDSDIEIDDVSDSEQE--EDDEYDQLPP-FKPLRKSQLAKLS
KEQRNAYFDEY----------NYREKLLKRKQWKE------------ELRRMRETKKNGK
KIEDEP------EEEEDDPLASSSPALLPDIELPTSFDSDNSAYRYRSLEPTSKFLTRSL
LDPRGWDNDCGFDCVIAEHSLAIAKRFPAAFTVQMTKDKKEFNIHLESSVCAKHGDNRST
MAELHILG-SEQLMYLLRGETKAKIFKKNKMTFGGTMAFIDRNIVTGLKLEDQI------
ALGKRLVLVGNAGTT--------RSQGDSAYEANL--------------EVRFREAD---
--FPIGQNQLALGLSLTKSNDDLTLKPNLRSQVCIGGDTRLAASASIDNKRFGQVTVR--
---ASGSDQWQISGMAILA--LAMTIYKRFIRSGDS------
>gnl|BL_ORD_ID|18151 @Thellungiella_halophila@_Thhalv10028361m|PACid:20197753
MDSKAEQTNPFSASGQSGKTYASVVAAAAAAANKEGGAVSSAKEFDSSPEAVSGNSDNGI
VGGADNLSDAETEKEKEKESSILKVGGDEKISDERDSATPEDTSSLSPKPEVVSDKTIGE
NDVGVAEENKKVEEGVEVIENDGEGKLQNGSVDVGEKQASTEGIVESESNVKDVEDEADG
SKKDVEVPKADGTNKEESEFSGKVDVDDKSDDVIGEEGVKLTDKGDFDVDSSVVESVHVD
VATPGVAVVGDVEGIEEMKINADVENLEVANKFDQIGDDDGGGFEVESDKAVVEVEGKLT
TGADSIADSSKLESADTSAAEPEVEAVGSGTEPKDVEEANGSEKGMTYAEVIKADSAVAD
SRTKEEESGLSGVVDEEEEAVKSTAIESVHVDVAKPGVVVVGDVEGSEVLETDGSIADLH
NKFDPVGQGEGDGVELQSNKVTEEGGENLTSEGDSIVDSSVVDSIDADINVAEPGVV---
--------VVGVAKEAETKADDGDDEVVKTIPKIEEADDLTAAYDGNFELAAKETSEAAR
VEPDQPKVGVVEEEEEMPVSESLKVGSVDAREES--KSAAESQFEANSNPEVREVSEGDN
AEEGGNKSPVADIVSSREFSLESKEVNQEPSG-------------------EGDIGVDGS
ESEEETEEMIFGSS---EAAKQFLAELEK--ASSGIEAHSDEANTSNNMSDRIDGQIVTD
SDEDVDTEDEGEEKMFDSAALAALLKAATGGGSSEGGNFTITSQDGTKLFSMD-------
--------RP----------------AGLSSSLRPLKPASAPRANRSNIFSNPNVTMA--
-DEGEVNLSEEEKQKLEKLQSLR----------VKFLRLLQRLGHSAEDSIAAQVLYRLA
L---LAGRQTGQ--LFSLDAAKRKAVESEAEGNEDLNFSL-NILVLGKAGVGKSATINSI
LGNQKASIDAFGLSTTSVREISETVGGVKITFIDTPGLKSAAMDQSTNAKMLSSVKKV--
------MKKCPPDIVLYVDRLDTQTRDLNNLPLL--RTITASLGTSIWKNAIVTLTHAAS
APPDGPSGSPLSYDVFVSQCSHIVQQSIGQAVGDLRLMNPSLMNPVSLVENHPLCRKNRE
GVKVLPNGQTWRPQLLLLCYSLKVLSEANSL-LKPQEPLDHRKIFGFRTRAPPLPYLLSW
LLQSRAHPKLPADQGGDSVDSDIEIDDVSDSEQEDGEDDEYDQLPP-FKPLRKTQLAKLS
KEQRKAYFEEY----------DYRVKLLQKKQWRE------------ELKRMKEMKKHGK
KVGESEFGFLGEEEDPENGAPAAVPVPLPDMVLPPSFDSDNSAYRYRFLEPTSQLLTRPV
LDTHGWDHDCGYDGVNAEHSLAIASRFPATATVQVTKDKKEFNIHLDSSVSAKHGDSGST
MAGFDIQAVGKQLAYVVRGETKFKNLRKNKTTLGGSVTFLGENVATGVKLEDQV------
ALGERFVLVGSTGTM--------RSQGDSAYGANL--------------EVRLREAD---
--FPIGQDQHSLGLSLVKWRGDLALGANLQSQVSVGRHSKIALRAGLNNKMSGQITVR--
---TSSSDQLQIALTAILP--IVMSIYKSLRPEGANDKYNMY
>AT4G02482_gnl_BL_ORD_ID_6337_AT4G02482_1_PACid_19644284
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GTMVLP----WQ------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------GFISREVSNLCNSRRNELTLGGLVTFF--------------------
------------GTT--------RSEEDSSYEGNL--------------ELRLREAD---
--FPIGQNQPHMGVSLKNSKDDLTVTANLRHQVSVGRQTKVTTFVSLDSKRTGCFTVR--
---TNSSDQLQIAVMALLL--LAM------------------
>gnl|BL_ORD_ID|3984 @Thellungiella_halophila@_Thhalv10022323m|PACid:20183478
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--GDGAEIVNMSEGEE-KKLPEDRISDEQVE-KNELVGSDEASDSDNEEEIFEEAIGSQE
---------------------------APKTEPFEVDGLHEDLRLEATPENFKDEHEVVD
D-LEEVSSNESGVKDS----------KTYHSIVGESHGEVNVQDITTGEAERDLVTPKMN
DDKGEAGEEISHGQIDSSLDVVENSEKATCS-GSNLAGEDVNMQNGNTHSFPENGI----
--------ISVSALSEETRNDSIEDI------NWEEKADVSAGMETEEEIGGGEGTNKNC
SENGFVCINNVSGEQ--------RNGETGAGYSS--VKMASGDKSLNDSLEILNV-----
----GTSSPLEKSSPEEKGEIEGHSS-------------------------SGFPGVTCR
EHETVQNSNVRHDV---QQSPQRNKDLEK--QQGSRVNIGPEITVSPHV-----------
-------------------------------------------EREFEVVSSDSRTESVS
---SLPPARP----------------AGLG-RAAPLLGPTPRVTQQPRVNGNVSHDQHQQ
VEDS-TAETDEHDETREKLQLIR----------VKFLRLAHRLGQTPHNVVVAQVLYRLG
LAEQLRGRSGSRVGAFSFDRASAMAEQLEAAGQDPLDFSC-TIMVLGKSGVGKSTTINSI
FDEVKMSTDAFQMGTKRVQNVEGFVQGIKVRVIDTPGLLPSWSDQHKNEKILRSVRAF--
------IKKNPPDIVLYLDRLDTQSRDSGDMPLL--RTIIDVFGPSIWFNAIVGLTHAAS
APPDGPNGTASSYDMFVTQRSHVIQQAIRQAAGDVRL-----MNPVSLVENHSACRTNRA
GQRVLPNGQVWKPHLLLLSFASKILAEANAL-LKSQDNTA-GRPFAARSKAPPLPFLLSS
LLQSRPQAKLPEEQYGDGEDED-GLDESSDSDEE----SEYDQLPP-FKRLTKAEMAKLS
KSQKKQYLDEM----------DYREKLFMKKQMKE------------ERKRRKMLKKFAA
EIKDLPN-GHSENVEEERSEPASVPVPMPDLSLPASFDSDNPTHRYRSLDSSNQWLVRAV
LETHGWDHDVGYEGVSAERLFVIKEKIPISFSGQVTKDKKDATVQLEMASSVKHGKGRST
SLGFDMQNVGKELAYTVRSDTRFKNFRNNKAAAGLSVTLLGDSVSAGLKVEDKL------
IANKWFRMVMSGGAM--------TSRGDVAYGGSL--------------EAQLRDKD---
--YPLGQCLSTLGLSVMDWHGDLAIGGNIQSQVPIGRSSNLIARANLNNRGAGQVSIR--
---VNSSEQLQLAMVALVP--L----FKKLL-----------
>gnl|BL_ORD_ID|22651 @Thellungiella_halophila@_Thhalv10022525m|PACid:20202302
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--GDGTDVVVRSEGEEKKKLADDRISDEQVEKKNEFVRSDKA--KDNEDEIFEEATG---
------------------------------------------------------------
D-LDETSSNEGGVKDS----------KVDYP--------VNVQR----EAEPDFVTPKMN
GDEEEAGAENS--------NVVENSEKAADSNGSNLVAEDVNMENGNTHSLSENGIVSHE
NEELVADGISKSVAPEEMWNDGIEVE------NWEERADASPGIRTEPQVEGSGVTHENR
PE-----------AN--------GNGETSADYTSNTVENASGEKSLNGGIGVASA-----
----VTSSPSEKSSSDEKPEIESDSSCLKPEHHVASSLNSNLESSTEVRSNSGFPGVTSK
EHETVQTANGGHGV---QQSPQPNKELEN--QQSSRVNIDPEIKETSHV-----------
-------------------------------------------ERESEVVNSVSPTESRS
NPAALPPARP----------------AGLG-RAAPLLQPAPRAPQQSRVNGNVSHSQPQQ
AEDSTTAETDEHDETREKLQLIR----------VKFLRLAHRLGQTPHNVVVAQVLYRLG
LAEQLRGRNGSRVGAFSFDRASAMAEQLEAAGQDPLDFSC-TIMVLGKSGVGKSATINSI
FDEVKFCTDAFQMGTKRVQDVEGFVQGIKVRVIDTPGLLPSWSDQSKNEKILNSVKAF--
------IKKNPPDIVLYLDRLDMQSRDSGDMPLL--RTISDVFGPSIWFNAIVGLTHAAS
VPPDGPNGTASSYDMFVTQRSHVIQQAIRQAAEDMRL-----MNPISLVENHSACRTNRA
GQRVLPNGQVWKPHLLLLSFASKILAEANAL-LKLQDNIP-GRPFAARTKAPPLPFLLSS
LLQSRPQPKLPEQQYGDEEDED-DLDESSDSDEE----SEYDQLPP-FKHLTKDQMAKLS
KSQKKQYLDEM----------EYREKLLMKKQMKE------------ERKRRKMFKKFAA
EIKDLPNEPPSDNVEEESGGPASVPVPMPDLSLPASFDSDNPTHRYRYLDSSNQWLVRPV
LETHGWDHDIGYEGVNAETLFVVNKQIPVSLSGQVTKDKKDANVQLEMASSVKHGEGRST
SLGFDMQTVGKELAYTVRGETRFNNFRRNKAAAGLSLTLLGDSVSAGLKVEDKL------
IANKWFRMVMSGGAM--------TSRGDVAYGGSL--------------EAQLRDKD---
--YPLGRFLTTLGLSVMDWHGDLAIGGNIQSQIPIGRSSNLVARANLNNRGAGQVSVR--
---VNSSDQLQLAMVAIVP--L----FKKLLSYYSQQTQYGQ
>gnl|BL_ORD_ID|12862 @Thellungiella_halophila@_Thhalv10018781m|PACid:20192406
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------SATPEWVMVGGEGPESYNQNSYYQRALLEAAKE
KMNEAISSKLSLDMISDRFSVADFGCATGPNTFVAVQNIIDAVEDKYRKETGQNPADN--
------------------------------------------------------------
---------------------------------IEFQVLFNDFTTN--------------
------------------------------------DFNT-LFQSLPQGRRYYSAGVPGS
FFERVLPKQSFHIGVINY------------AFHFTSKIPKGITDRDSPS-----------
------------------------------------------------------------
------------------------------------------------------------
----------WN------------------------------------------------
---------------------------------------------------RDMHCTGFN
EAVKKAYLDQY-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------SADTKNLLDARAEELVPGGLMLLFGSCLRDGVKMSETAKGIVLD
IVGDSLNDLAQQGVI--------EQDKVDSFSTPLYFAE----------EGEIRQII---
--KENGKFTIEAFEDIVHSKGEFTIDPKILAV-----SCRASFGSFLSAHFGGEVITKAF
-ELIEAKARQELPRFHNAK--PGMQYLIVLRKN---------
>gnl|BL_ORD_ID|12863 @Thellungiella_halophila@_Thhalv10018893m|PACid:20192407
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--NEAISSKLSLDMISDRFSVADFGCATGPNTFVAVQNIIDAVEDKYRKETGQNPADN--
------------------------------------------------------------
---------------------------------IEFQVLFNDFTTN--------------
------------------------------------DFNT-LFQSLPQGRRYYSAGVPGS
FFERVLPKQSFHIGVINY------------AFHFTSKIPKGITDRDSPS-----------
------------------------------------------------------------
------------------------------------------------------------
----------WN------------------------------------------------
---------------------------------------------------RDMHCTGFN
EAVKKAYLDQY-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------SADTKNLLDARAEELVPGGLMLLFGSCLRDGVKMSETAKGIVLD
IVGDSLNDLAQQGVI--------EQDKVDSFSTPLYFAE----------EGEIRQII---
--KENGKFTIEAFEDIVHSKGEFTIDPKILAV-----SCRASFGSFLSAHFGGEVITKAF
-ELIEAKARQELPRFHNAK--PGMQYLIVLRKN---------
>gnl|BL_ORD_ID|11280 @Thellungiella_halophila@_Thhalv10005791m|PACid:20190818
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--DDSCAVCADNLEWVAYGSCGHREVCSTCVVRLRFVLGDPRCCICKTESPFIFVTKALG
DYTRTINDFSTFPSA---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----PKEGRVGGGFWYHEDTQAFFDDLDHYRMIKAMCRLSCSVCDKTDDQPKEGGPGPRH
RLRIKSVEQLKGHLYHKHKLHMCGLCLEGRKIFICEQKLYTRAQLNQHIHTGDSEVDGSE
SERGGFAGHPMCEFCRNPFYGDNELYAHMSTEHYTCHICPRPQPGQYEYYKNYDDLELHF
RRD--HFLCEDESCLAKKFIVFQNESELKRHNAIEHGGKMSRAQRSAALQIPTSFRYRRN
DQENRRGRAR----SFRRE-----------PGDDDYNLAVHAALRLSESEYSRQ------
--EPAPPPTSAPPGFSEINNRHIDDGDPLIQ----PMESLSTTDMEPPSRYLQAVGSSGG
VVTRLGESAFPP--------LAGQPRSGQNLESVPTNTLAARLRRQTNRTPTATATAVAS
PSQAWPA-----------------------------------------VNRGPAQASNIS
GRGNSSSG--WPAIGRTPAQASSSSAQSRSHARVSQPRPPNSAVPQAARNANRIPHSSSA
PNLSDSRSLLPSHSDFPPVSSAVVQNHKSSSTST--QGSSNSQPPPDVQSANKSLIEKMR
SALGH---DEELFMTFKDVSGQYRQGLIDARTYLEYVKGYGLSHLVIDLARLCPDPKRQK
ELIDTHNASSSKDDTKANGQAAA-------------------------------------
----------------------------------------QSSSQAKESQGSKKNKGKAV
KIADPKEALADNFMDTVRRLQSSQNPQAEEEDA---------------------------
ISKDKNTYRSDKGKS--------QVTVIDSYSTGS--------------SKQQRKKTSKF
HRLRLGDGSMAALLDLNNSNHEPEPESTVDNQ-----TSGLAVRGVWRKGGAKLFS----
------------------------------------------
>gnl|BL_ORD_ID|19827 @Thellungiella_halophila@_Thhalv10004669m|PACid:20199432
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------GRCLTKRLFLIQSP--------ILFLHLL--------------------
-----------------------------------ISFSSGAVKPDSKGVCVSKGGRFQP
YESEGKPPKSVGRGSKDL------------------------------------------
-------------------------------------TLCRVFRKRTCCSSAQTNSAFVA
V-----------------------------------------------------------
-RNLATYGEASQDCLHLFELLECSICNPNVG-----------------------------
-----------------------------------------------IQPGPPRICASFC
NKVFEACKDAY-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------FASNALTQMIGPC------------GVNDD
IICVKASNWESNGTAFCEAAGFSVQTNDDSREEPCYGSKASLESVVESWSRETRKKT---
---ASKTETLSCFKDLLQWVRVMTTIQKI--------SLGVSFLV------AGMFLIRWY
RQWHNRNQKQRLAAIHKAARRLGGNVNGNSYSAAINRRIVQS
