>gnl|BL_ORD_ID|13906 Aquca_006_00073.1|PACid:22036942
M-----------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------V
DDSIFK-----------------------------FQNRMKAFKDWISSQ--AV------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------SKSLLSSRPLLGGGN
------IFEEETINENNE----------IQGSTA---TGM--------------------
---QERPVSANN-------L--------LQSSIDNE-ESRRASADDLGLSGNMDRNRMDP
LAK-----IESLQIKFMRLVHRLGQSHDNILVAKVLYRLHLATLIR---VGE----KTSL
RNDRARAMAAELEAAGRPDLNFSLRILVLGKTGVGKSATINSIFDQMK------------
----------------------------------------AATDAFQPATNHIREVIGT-
-------S--KGIKLTFIDTP---------------------------------------
----------GLLPSSTRNV----------------------RRNR--------------
----------KILRSVKNF-IRNT---PPDIVLYFERLDHINM-GYSDFPL---------
---LKLITDTFGSAIW-LNTILVMT-------HSSGALPEG--PNGYPVSYEPFVAQCT-
NLVQHYIHQAVSDLK------------IENPVLMVENHPQCKKNISGEKV----------
-----------------LPNGQAWRSQFLLLCICMKVLGDANTLLKFRDGFQIGP-SASN
-RLPSLPHLLSTLLRPR------STERENDELDDQDT------D---DEDEYDQL-----
-------------------------PPIRILTKAQFEKLTKSQKNAYLDELDYRET--LY
LKK------QLRADIQKRRNNLLPKDGNSANDEDYDNHE--------GNPEAVQLPDIA-
---VPPSFDSDWPVHRYRCVVTSDQ----WLARPVLDPQGWDHDVGFDGINLENVVEMKK
NLHLSVLGQLSKDKQDFSVQTECNALFT-DLKGSSASASLDVQTAGKDLVCTARGDTKLR
NLKHNTTGCGVSVTSFGNKYFVGAKIEDTISVGRRVELDLNVGRMGGLGQVAYG------
--------------------------------------------------GSFEATVRGR
DYPVRNEKIGLTMTVLSFDKEMVFGGNILSDFRIGHSSKISLNANLNSRRMGQICVKTSS
SDHVEIGLIAVISICR-AIFRRRAIE----------------------------------
-----DRTVD
