>gnl|BL_ORD_ID|8882 Bra002291|PACid:22692392
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------KGFIDW----------
--------------------------------------------------------VFDL
SNSMASSSRPLLGTAPFSRH-HEPH-----------------------------------
--------------------------------------------------------DSHS
QA---------------------------------------PALPEPVARS---------
------------EPPCSTSVDVEAHP----PI-----SQQQTPLESL-----HQSSLDLN
DKKHNPLAKIGDLQVQFLRLVHRFGQSQ-N-NILVSKVLYRVHLAMLIRAEESELKTVKL
KQDKAKTLAKEQESSGVPELDFS----LR---IL--------------------VLGK-T
GVGKSATIN---SILGQ----S------------------KSE-TDAFQPATDRIEEVNG
TV--SGVKV--------------------------------TFIDTPGLHQPSPSSARK-
-------------------NRKTLLSIKRYVKKRPPDVVLYLDRLDTIDLRYSDYP--LL
SLITEVLGAAL-----WL-----NTILVMTHSSVA-SEGRN---MNYESY---------V
GQRVDVVQH--YIHQAVS-----------DTK-----LENPVLLVENHPSC---------
---------------------RKNHAGECVLPNGL-------------------------
-VWKPQFMFLC-VCTKVLGDVQ-----SLLRFRD--SIGLGQASGTRTA--SLPHLLS--
------------------------------------------------------------
--------------VFLRRR------LSSGG-D--EAERE------------ID------
-----ELMDSELEE---EEEDEYDQLPAIRILGKARFEKLSKSQK---------------
----------REYLDELDY-----------------------------------RETLY-
-LKKQLKEECRRRKDEKLNEEE----------------EEKSD--QAAVPLPEMAGPDSF
DSDFPSHRYRSIATSDQWL----------VRPVYDPQGWDHDVGFDGINIETAVKVKKNL
FASAN----------GQVSRDK----QRFTIHSETNAAYTTDS------RIQTFSVAADV
Q-SSGDDLVYTFHGGTKLKTFKQNTTDLGVGLTSFGGKYYLAGKIEDSLLVGKRVKLTVN
-AGQMKGSG---------------------------------------------------
--------------ETAHGGSFEACIRGRDYPVRN-EQIGVTVTALSFK-KELVLNWGLQ
TQVRPTRDTNVDVSVNMNNRKMGKINVKLNSSEHWEIALISAFTLFKALVRRKKAVSEIT
NENEEE------------------------------------------------------
--------------------------------------------------------L
