>gnl|BL_ORD_ID|36196 Glyma13g23110.1|PACid:16291257
------------------------------------------------------M-----
------------------------------------------------------------
------------------------------------------------KGVRDWVFSQIL
SKSLVSPSPLSGSNSLYAG-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---EHRNENFN--------------------------------------------EQGH-
HLRLVVGLTILRSCREHCDMIHHLAYGG-----TGTV--------------------ELV
SDTEIYQ--YQHNTNGRRK-----DTLAKVEELQVKFFRLLQRLGQSQEN----------
-LLVAKVLYRMHLATLIRAKEL-----------------DLK------------------
------------------RVNHISSSARAIASEQEAT----GMPQ-LDFSCRILVLGKTG
VGKSATINSIFG------------Q----------AKTTTGAFQPATNC--IQEVVGNV-
-------------------------NGLN--IAFIDTPGFLPSSTNNM------------
---------------------------KRNKRIMLSIKRFI---RKSPPDIVLYFERLDF
INAGYVD---------------------FPLLKLVT-------EVFGSAIWFNTIIVMTH
----------SSSAIPE---------GPDGYTFNYE---SYVSYCTNMIQLHIQQVVFDS
KV-----------------------ESPVLLVENHSQCPQNIMGEKI-------------
-----------------------LPNGQVWRSQLLLFCI---CTKVLGDVNSLLKFQNSV
------------GLGPSNSARIPSMPHLLSSLLRHRPVSNVSGIDDEIE----------E
ILLSD-KEEDEYDQLPSIRVLTKSQFKKLPEPLKKDYLDEMDYRETLYLKKQL----KED
CRRRKEKL------LLTDKKFLNSDNPDDQQAPPEPVLLPDMAVPPSFDLDCHSHRYRCL
-VSDDRLLVRPVLDPQGWDHDVGFDGINLETTTEIKKNVYASVVGQMNKNKQDFSIQSEC
VAAYV-DPSGPTYSMGVDVQSSGKDFICTVHSNTKLKNIKHNIADCGV------------
----------------------------------------------------SLTSFAKK
YYVGAKLEDTVFVGKRLKFVLNAGRMEGAGQMAYGGSFEANLRGEDYPVRNDNVSLTMTV
LSFNKEMVLSGSLQSEFRLSRSSKASVSANLNSRKMGQICIKISSSEHLQIASVAVFSIL
KFLSRRKETKNVVRDVMD---------
>gnl|BL_ORD_ID|46717 Glyma17g11770.1|PACid:16305250
------------------------------------------------------M-----
------------------------------------------------------------
------------------------------------------------KGVRDWVFSQIL
SKSLVSPSPLSASNSLYAG-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---EHRNGDVN--------------------------------------------EQGSD
HSASSVSSPIPSDSSNS-------SYGDQSNQHSSSL--------------------QLV
SDTEIYQ--YQHNTNGRRK-----DTLAKVEELQVKFFRLLQRLGQSREN----------
-FLVAKVLYRMHLASLIRAKES-----------------DLK------------------
------------------RVNHSSSRARAIASEQEAT----GMPQ-LDFCCRILVLGKTG
VGKSATINSIFG------------Q----------AKTTTGAFQPATNC--IQEVVGNV-
-------------------------NGLN--LTFIDTPGFLPSSTNNM------------
---------------------------KRNKRVMLSIKRFI---RKSSPDIVLFFERLDF
INAGYVD---------------------FPLLKLVT-------EVFGSAIWFNTIIVMTH
----------SSSAIPE---------GPDGYTFNYE---SYISYCTNIVQQHIQQAVFDS
KV-----------------------ENPVLLVENHSRCPQNIMGEKI-------------
-----------------------LPNGQVWRSQLLLFCI---CTKVLGDVNSLLKFQNSV
------------ELGPLNSPRIPSMPHLLSSLLRHRLVSNLSGTDDEIE----------E
ILLSDKKEEDEYDQLPSIRVLTKSQFEKLPEPLKKDYLDEMDYRETLYLKKQL----KED
YQRRKEKL------LSTDKKFLNGDNPDDQQAPTEPVLLPDMAVPASFDSDCHSHRYRCL
-VSDDQLLVRPVLDLQGWDHDVGFDGINLETTTEIKKNVYASVVGQMNKNKQDFSIQSEC
TAAYV-DPLGPTYSMGVDVQSSGKDFICTVHSNTKLKNIKHNIADCGV------------
----------------------------------------------------SLTSFVKK
YYVGAKLEDTVFVGKRLKFVLNAGRMEGAGQMAYGGSFEANLRGEDYPVRNDNVSLTMTV
LSFNKEMVLSGSLQSEFRLSRSSKASVSANLNSRKMGQICIKISSSEHLQIASVAILSIW
KFLSRRKETKNLVKEVMD---------
