>gnl|BL_ORD_ID|32806 Lus10006471|PACid:23171986
-------------------------------M----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------P-----
--SFSLA---------------------DLPANSEAASAPDASPQ---------------
------------------------------------------------------------
---------------QVVEASSQPSTHHIKERDTHPLENVEHLKINFFRLLRRFGLPMES
ALVAKVLYRIHIATSIRGELPK----R--------V---RNIN------AKTIA---AAQ
EG--SGV---PELNFSVRILVLGKTGVGKSATINSILDQRATITSAFQPAT---------
-NRVQE-------------VT----------GTL--NGVR--------------------
------VTFIDTPGFLPHSGSG-IRQNLKIMRSVKRFIRKS-PPDIVLFVERLDHLNTGY
SDF--LLLQLMTDVFGDAIWFNT-------MIIMTHASSSLPE-----------------
------------------------------------------------------------
----------------------------------------------GSTGGPVSYESYVS
RCSQMMQHYIHEAVSDTT-----LQN--LVVVVENHPQCEKNSNG---------------
------------------------------------------------------------
------------------------DAILPNGQVWRSQFLLFCICTKVLGDASNILELKNC
-------VELGPKTRPQVLSLPRLLSWLIKNKAVSGPTPDGHDLDEIVVVD-------ED
EEDEYDQLPPIRILTKSQVA-----------------------KLSKSQKNDYLDELDYR
EMVYMKKQLKEESRSR----------RENMLFGKASYEEFDNSEATNASPETVLLPDMAV
PPSFDSDCPVHRYRCLVAIGDQLLTRPVLDPRGWDHDVGFDTVDLETAIEMKKN------
----------------------------------------------------LCASVSGQ
INKDKNNFSIQSECAVTYA---DLKGPTYSAGLNVQSAGK-DLVYTIHGNTRSKIFAHNN
VADCGVSLTSSCRKCYLGAKLENSVLVGKRLKLLINGGQMRGAGEVANGGSVEATILGTD
YPMRNDKASLSLTALSFNKETVVSGGVESEFQLIRGTRVAVNANLNSLNMGKVGIKVS-S
SEHLEI-AVIAALTIFSAIFRKRVANTSPDVSETGEFPVV-S
>gnl|BL_ORD_ID|12132 Lus10027712|PACid:23151312
-------------------------------M----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------DWSLPN
WFSKSLASLSPVTFYESPPSDHHSDDDRDLTANSEALSPPDASPQ---------------
------------------------------------------------------------
---------------QVVEASSQPSTHHTEERDTHPLENIEHLKINFFRLLRRFGLPMDS
PLVAKVLYRLHIAISIRGELPK----R--------V---RNIN------ALTIT---AAQ
EG--SGV---PELDFSVRILVLGKTGVGKSATINSILDQRATVTSAFQPAT---------
-DRVQE-------------VI----------GTL--YGVR--------------------
------VTFIDTPGFLPHSGSG-IRRNLKIMRSVKRFIRES-PPDIVLFVERLDHLNTGY
SDF--PLLQLMTDVFGDAIWFNT-------MIIMTHASSSLPE-----------------
------------------------------------------------------------
----------------------------------------------GSIGGPVSYESHVS
RCSQMMQHYIHEAVSDTT-----LQN--LVVVVENHPQCDKNSNG---------------
------------------------------------------------------------
------------------------DAILPNGQVWRSQFLLSCICTKVLGDASNILELKNS
-------IELGPKTRPQVLSLPRLLSWLIKNKAVSGPTPDGHDLDEIILVD-------ED
EEDEYDHLPPIRILTKSQFA-----------------------KLSKSQKNDYLDELDYR
EMVYMKKQLKEESRSR----------REKMLLGKASYEEFDKSEATNAPPETVLLPDMAV
PPSFDSDCPVHRYRCLIEIGDQLLTRPVLDPRGWDHDVGFDTIDLETAIEMKKN------
----------------------------------------------------LCASYSGQ
INKDKNNFSIQSECAVTYA---DLKGPTYSAGLNVQKAGKDDLVYTIHGNTRSKIFTNNN
VADCGVSVTSSCNKCYLGAKLENSVLVGKRLKLLINGGQMRGPGQVVNGGSLEATILGTD
YPMRNDKVSLSLTALSFNKETVVSGGVESEFQLMRGTRVAVNANLNSLHMGKVGIKAS-S
SEHLEI-AVIAALTIFSAIFRKRVANTSPDVSET-------R
>gnl|BL_ORD_ID|37184 Lus10004619|PACid:23176364
-------------------------------M----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------P-----
--SFSLA---------------------DLPANSEAASAPDASPQ---------------
------------------------------------------------------------
---------------QVVEASSQPSTHHIKERDTHPLENVEHLKINFFRLLRRIGLPMES
ALVAKVLYRIHIATSIRGELPK----R--------V---RNIN------AKTIA---AAQ
EG--SGA---PELDFSVRILVLGKTGVGKSATINS------TITSAFQPAT---------
-NRVQE-------------VT----------GTL--NGVR--------------------
------VTFVDTPGFLPHSGSG-IRRNLKIMRSVKRFISESPPPDIVLFVERLDHLNTGY
SDS--LLLQLMTDVFGDAIWFNT-------MIIMTHASSSLPE-----------------
------------------------------------------------------------
----------------------------------------------GSTGGPVSYESYVS
RCSQMM------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------LFGLMFRSYK-----------------H
