>gnl|BL_ORD_ID|26569 cassava4.1_002049m|PACid:17986541
M-----------------------------------------------------------
-------------------KGIRDWAFAQLL-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------SKSLASA--------RLLSSSGSFFSEGPVNEDSNDPAHMACPEVTVLLP
DTLCSSDN-------------------------------------THENGPHPSLQED--
-----------ANRTNHA-----SDPLAKIEDLQVKFFRLLQRLGYSNDNVLVAKVLYRI
RLAISIRGRE-------LDLKRARK-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------VAEEQEAID-------------------------------------
------------TPE---LDFSVRILVLGK-TG-----------------------VGKS
ATINSIFD----------------------QRKMITDAFEPATN--HIEEIAGTV--NGF
R--------------------------ITFID-----TPG---------------FFPSS
ASNMRRNRK--I----MLSV------------------KRFIRKSPPHIVL---------
-FFER---------------L------DLVNMGYY-DFPLMKLMTEV---------FGSA
IWFNTI--------LVMTHASS-TLPEGPSGFPVNYESYVTRCTDLIQ-------H---F
IHQAVSDTKL-----ENPVLLAENHTQCKKNFMGENVLPNGQAWRSQFLLLCMCTKVLGD
ANILLEFQDS---IELGS-SSPRVPSLSHLLLSLLRHRL-----------SSPNGAEYDV
NEILLSDADEE---DEYDQLP---------------------------------------
------------------------------------------------------------
-------------------PIRILTK----------------------------------
------SQIERLTKSQKRDYLDELDYRETLYLKKQLKEDISRKREKKLAESE--------
------------------------------------------------------------
----------------------TS------GEDNNHEDQQPPPDNVLLPDMAVPPTFDSD
CPVHRYHCVATSDQWLVRPVLDPQGWDHDVSFDGINLETAMEIKRNIYASITGQMSKDKQ
NFSIQSECVAAYT-DPRGPTYSLGFDVQSAGKD----------------LIYTVHSNTKL
-------------------------------------KTLK-----HHITECAMSLTCFG
ENYYVGTKLEDTILIGKRLKFIMNAGQMRSSGQVAYGG----------------------
---------------------------------------------------TFEATLRGR
DYPVRNDIISLSMTALSFKKETVLGVGFQSEFQPVRGMRMAVNANLNSQKTGQVSLKMSS
SECTEIALVAIFSILRALF-HRKDEGNGRKEVLE--------------------------
--------------------M
>gnl|BL_ORD_ID|15640 cassava4.1_002111m|PACid:17975485
M-----------------------------------------------------------
-------------------KSIRDWVFTRLL-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------SSS--------RSLSGSGSFFSEGPADEDSN------APEVAPVLP
DTSYFSGN-------------------------------------TEGNEPHPSLPGD--
-----------LNRSNNVNDCEKADSLAKIEDLEVKFFRLLRRLGHSSDNLLVAKVLYRI
HLATSIRGRE-------SDLKRARK-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------IAAEQEAID-------------------------------------
------------KPK---LNFSIRILVLGK-TG-----------------------VGKS
ATINSIFD----------------------QRKTTTDAFEAATK--HIQEIVGTV--SGV
K--------------------------VTFID-----TPG---------------FLPAS
ANNVRRNRK--I----MLSV------------------KRFIRKSPPDIVL---------
-FCER---------------L------DLVNMGYS-DFPLVKLMTEV---------LGSA
IWFNTI--------LVMTHASS-MLPEGPNGFSVNYESYVTKCTDLMQ-------Q---F
IHQAVLDRKL-----ENPVLLVENHPQCKKNFAGENILPNGQAWKSQFLLLCICTKILGD
VSKLLEFQGS---IELGS-SSPRVPSLPHLLSSLLRHHV-----------SNPNEVDDDV
YEILLSDAEEE---DEYDQLP---------------------------------------
------------------------------------------------------------
-------------------PIRILTK----------------------------------
------SQFERLTKSQKRDYLDELDYRETLYLKKQLKEDARSKREKKLAEAE--------
------------------------------------------------------------
----------------------RL------GEDNS-DDQQTPTEAVLLPDMAVPPTFDSD
CPVHRYRCLATSDQWLMRPVLDPRGWDHDVGFDGINLETAVEIKRNISASIAGQMCKDKQ
NFSIQSECAAAYT-DPRGPTYSVGFDVQSAGKD----------------IIYTVHGNTKL
-------------------------------------ATLK-----HNNADCAVSLTSFG
KKYYVGAKIEDNILIGKRLKFVMNAGQMRGRGQVAYGG----------------------
---------------------------------------------------TFEATLRGQ
DFPVRNDIISLSLTALSFKKEMVLSGGFQSEFRPVRNMRVAVNANLNSQKMGQVSIKMSS
AEHIEIALAAIFSIFRVML-YRKESKNGSRETLE--------------------------
--------------------M
