>gnl|BL_ORD_ID|27646 ppa001605m|PACid:17668321
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------GSLKDWISSQLVSMSLVSSRPLSG---------------------
--SDSFFREEP----SHEGF-DGQG-----------------------------AAHSNT
S--LTSPIIPDTSPSVGSD------------QENQSNPSRQHVVVEN-------SDQSRN
GSDKKKMDPLVRIDDLQVKFLRLILRLGLSQNNLLVAKVLYRIHLATLIR----------
------------------------------------AEESDLKRVNLRSDRARAVAAEQE
ASGLPEMDFSLR------------------------------------------------
---ILVLGKTGVGK----------------------------------------------
-----------------------------SATINSI------------------------
-------------FDQ----------------------RKTVTNAFRPG---TD-HIREV
VGTI--NGVR-------------------------VTI---------I--DT-PG-----
------------FLPSSTGNFR--------------------------------------
----------------------------------------------RNKKIMLSVKRFIR
KCPPDIVLF-FERLDLINASYNDFSLLKLITEVF--------------------------
----------G--PAIWFNT-----ILVMTHSSSALPE----------------------
----------GPDGYPVSYESYVRQ------STDMVQHYIHQAVSDSR-----LENPVLL
VENHPQCKKNIIGEKILPNGQVW--------------------------------KSQFL
LLCLCTKVLGDVNTLMKFEDSIQLGP--SSASHMPSLPHLLSSLL---------RHRSVV
S--------PSGVD-IEVDESLLSDTEEEDE-----------------------------
------------------------------------------------------------
----------------------------YDQLPPIRILTKSQFERLTKSQKKDYLDE---
--------------------------------------------------------LDYR
---ETLYLKKQLKEEYRRRMEIK-LSKEKIFASNDNSDRQQA--SQESA----VLLPDME
VP-----------------------------------------PSFGSDCTAHRYRCLVT
GDQWIMRPVLDPHGWDNDVCFDGISLETAMQINSNVFTTVTGQMSKDKQDFSIQSECAAA
YS-DPSGTTYTVGLDVQSAGKDTIYTFHSNTKLKKVWRNTADCGVSLTSFGNKC------
------------------------------------------------------------
--------------------------------------------YIGAKLEDTISVGKRL
KFVMNAGQMVGPEQVAYGGGIEATLRGRDYPVSNDNVSLTMTLLSFNEEMVLGGNLQSES
RLGRNLRVSVNANLNSRKMGKICIKTSST-------------------------------
------------------------------------------------------------
------------------DHLQFSMAAAFTIFWALLQKKAVKSTSHE-----------
