>gnl|BL_ORD_ID|1972 Pavirv00014117m|PACid:23757692
----------------------------------M-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MNFRDWLSFRLGSSLLSARP------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------FALSAGDDDRASDGDADGTTQNEFV---------------------
--------------ETVSANRFPSNDTRVSEVTTS---GAVYPAPVQQ---DNDNKKSDP
LMKVEALQIKFLRLVHRTG---------------------------------VPPSTDVV
VQVLYRLQLANLIKAGE--------SGARRTNLAINKARVIAAQQEAPGGPDL--DLPL-
----------RILLLGKTGVGKSATINSIFDERKVST-----------------------
-----------DALVPAT--------------------------------------HRIN
KTEGII--KG-----IR--------------VTVIDTPGLMP-H---YLGQRRNK-----
-----------KILNSVKRYIKRSPPD-----------I-------VLY-FERLDHINSR
YSDYPLLKLMTDILGSS---------MWFNTVLVMTHCSSSPPEGPDGYPLEY-------
----DAYTRYCKNVVQRHIQAVVSNTQ--LDN-----PVVLVDNHPMCRRN---TKGERV
LPNGQVWVSELL---LLC---------GATKLLAEANS--------LLKFQDSF--VLSQ
-ANNRLPSLPHLLSSLLKPNSS--------SSSDSIDSELTEM-----S-----DEEDEY
DQL------------------PPFR----ILKKSEYENLT----------NDQKSAYLDE
LDYR---ET-----LYLKKQWKEGIRR---QKLTEVQNDEVAD----------DYEEG--
----ASPEVVHMSDMEIPLSFDSDYPVHRYRHIITDDQ-MFRPVLDPQGWDHDIGFDAIN
FEASQELKKNVSAGIVGQMRKDKEDMYVNSEC----------------------------
--------------------------------------------------SVSYSDQ-RG
CSLIGGMDMQTASKDLLCTVHGDAKFRNLPW----------------NTTGGGISVTKFG
NKYFAGAKLEDSVTIGKRVKLVANAGRMAGCGQVAHGGGMEIIAWGKDYPVREESIAFSV
TALSFEKDTV----------------------IGANVQSDFRVGRGSKMSV---------
-------GANLNSRNLGKLSIKTSTSDHAEIALIAVVSLIQFFRRRSG---AADKGDQQF
DTNQDD---
>gnl|BL_ORD_ID|31706 Pavirv00001536m|PACid:23787757
----------------------------------M-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------MNFRDWISFRLGSSLLSARP------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------FALSSGDDDGASQGDADGTTQNEFV---------------------
--------------ETVSANRFPSNDTRMSEVTTNFNGGAVYPAPVQQ---DNDNKKSDP
LMKVEALQIKFLRLVHRTG---------------------------------VPPSTDVV
VQVLYRLQLANLIKAGE--------SGARRTNLAINKARVIAAQQEAPGGPDL--DLPL-
----------RILLLGKTGVGKSATINSIFDERKVPT-----------------------
-----------DALVPAT--------------------------------------HRIK
KIEGTI--KG-----IR--------------VTVIDTPGLMP-H---YLGQRRNR-----
-----------KILNSVQRYIKRSPPD-----------I-------VLY-FERLDHINSR
YSDYPQLKLMTDILGSS---------MWFNTVLVMTHCSSSPPEGPDGYPLEY-------
----DTYTRYCKSVVQQHIQAAVSNTQ--LDN-----PVVLVDNHPMCRRN---TKGERV
LPNGQVWVSELL---LLC---------GATKLLAEANS--------LLKFQDSF--VLSQ
-ANNRLPSLPHLLSSLLKPNSS--------SSSDGIDSELTEM-----S-----DEEDEY
DQL------------------PPFR----ILKKSEYENLT----------NEQKSAYLDE
LDYR---ET-----LYLKKQWKEGIRR---QKLTEVQNDEVAD----------DYEEG--
----ASPEVVHMSDMEIPLSFDSDYHVHRYRHIITDDQ-LFRPVLDPQGWDHDIGFDAIN
FEASQELKKNVSAGIAGQMRKDKEDMYINSEC----------------------------
--------------------------------------------------SVSYSDQ-RG
CSLIGGMDMQTASRDFLCTVHGDAKFRNLPW----------------NTTGGVISVTKFG
NKYFAGAKLEDSVTIGKRVQLVANAGRIAGCGQVAHGGGMEITARGKDYPVREESVTFSV
TALSFEKETV----------------------IGANLQSDFRVGRGSKMSV---------
-------GANLNSRYLGKLSIKTSTSDHAEIALIAVVSLIQFFRRGSG---AADKGDQQF
DTYLDD---
