>gnl|BL_ORD_ID|25456 Thhalv10012730m|PACid:20205134
MKG---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------FKDWVFA--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------LTNSMASSRPLMGSDPFFRE-NEEQ-----
---------------------------------------------------DNQSQAPVL
PEPVARSETPCSTSGDVEIQLPLSQQ----------------------------------
----------------------------QVPL------------ES---LYQSSFDLNEK
KHNPLARIGDLQVQFLRLVQRFGQSQSNILVSKVLYRVHLAMLIRA------EES-----
-----------ELKTVKLRQDRAKALAREQESRGIPELDFSLRILVLGKTGVGKSA----
TIN---SIFG----------------------QSK--SETDAFRPTTDRIEEVMG-----
----------------------TVSGVKVTFIDTPGFQPPSAS-----------STRKNR
KILLSIKR----------------YVKKRPPDVVLYLDRLDMID----------------
-----MRYSDFPLLKLISEILGAAIWLNTI-----------------------LVMTHSS
IA-SEGRNGQSVNYETYVGQRMDV------VQHYIHQAVSD-TK-----LENPVLLVEN-
--HP-SCKKNPAGEHVLP------------------------------------------
---------------------------------------NGLVWKPQFMFLCVCTKVLGD
VQSL-LRFRDSIGLGQPISTRTAS--LPHLLTLFLRRRLSS-------GADEAE------
------------------------------------------------------------
-----K-EI---------------DELLSSELE--EEDEYDQLPAIRI-LGKSRFEKLSK
SQKKE-----------YLDELDYRETLYL-----KKQLKEECRRRRDEKLVEE-------
----ENVNNDTE------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------QSDQAAVPLPDMAGPDSFDSDFPAHRYRCIVT-------SDQW
LVRPVYDPQGWDRDVGFDGINIETAAKVKRNLFASATGQVSRDKQRFTIQSETNAAYTTD
SREQTFSVAVDLQSSGEDLVYSFQGGTKLKTFKHNTTDLGVALTSFGGKYYMGGKLEDTL
LVGKRVKLTVNAGQMKGSGQ----------------------------------------
--------------TAHGGSFEACIRGSDYPVRNEQIGLTMTALSFNQELVLNWGLQTQL
RPNRDTNIDVNINMNNRKMGKINVKLNSSEHWEIALISAFTI----FKALLRRKKVVSEI
TKENEEE--------------------------------L
