>gnl|BL_ORD_ID|3368 GRMZM2G100579_T02|PACid:20823094
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------LMN
FRDWISYRLGSSLLSARPFALSPG------------------------------------
---------------------------ADDGASEGDAHGTAHNDFVDTVTANTF----SS
NDMRASE---------------------------------VTANSGSGAIYSGIVQ----
-------QDDDNKKSDPLMKV----EALQIKFLRLV------------------------
------------------------------------------------------------
---------------------------------------------------------YRT
GVSPSADVVAQVLYRLQLA-------NLIKASESDARRTNLAINKARVIAAQQEAPG---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------GPDLDVSMQILLLGKSGVG------------KSAT
INSIFDERK-VATDALVPATHRIKK-----------------------------------
--------------I--EGTIKGIRVTVIDTPGLV-------------------------
------------------------------------------------------------
------------------------------------------------S-H---------
--------------------YHGQRRNMKILNSVKH------------------------
-------------------------FIKRSPPDIILYFERLDHINSRYSDYPLLK--LMT
DILGSPMWFNTV---------------LVMTHCSSSPPE---------------------
------------------GPDGYPLEYDT---YTRYCKNVVQRHIQAAVSNT--QLDN--
---PFVLIDNHPMCRRNTKGERVLPNGQVWVSELLL-------LCGATKLLTEANSLLKF
QDSFL------------------LSQANTRLPSLPHLLSSLLKPHSS-------------
SSSDAIDSQLTEMSDEED------------------------------------------
------------------------------------------------------------
-------------------EY------------DQLPPFRILKKSEYENLTNEQKSAYLD
ELDYR---ETLYLKKQWKEGIRRKKLTEA---QSDEVGDDY---------DESASPEIVH
-----MSDMDIPLSFDSDYPVHRYRHIITDDQ-LFRPVLDPQGWDHDIGFDAINFEASQE
LKKNVSAAITGQMRKDKEDMYIHSECSVSYNAQ-RGCSLMGGMDMQTASKDLVCTVHGDA
KFHNLPWNSIGGGISVTKFGNKYFAGAKLEDSVTIGRRVKLVANAGRMSGCGQVAHGGGV
EITARGKDYPVREGSVTAAVSALSFEKETVIG----------------------------
------------------------------------------------------------
---ANLQSDFRVGRGSKISVSANLNSRNLGNLSVRTSTSDHAEIALITVVSLIQFILRRR
SAADNKDEQQIGTNLDD--
