>gnl|BL_ORD_ID|8838 @Brachypodium_distachyon@_4g40530.1|PACid:21811608
MM----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------LNFRDWISYRLGSSLLSARPFAI----------------
------------------------------------------------------------
----------------------SGPGAGASEGGVNDGTTE--------------------
---------------SEFVETVSANRFPSNDSHAASAVTSNSQD----------------
------------------------------------------------------------
---------------------------------GAVSSGPLHPDHDNSKPDPLMQVEALQ
IKFLRLVHRTGVPPNTNVVAQVLYRLQLANLIKAGESDARRTNLAMNKARVIAAEHEA--
---------------------------------------------------------PGG
PDLDLPLRVLLL-G-------KTGVG-------------------------------KSA
TVNSIFD---------------------------------------------------ET
KVAT------------------DALAPATNRIKMVDGTI------------KG---VRVT
V--IDTPG-------------------------LTP-HYHSQRR-NRKILHAVKRFIKRS
PPDIVLYFERIDH------------------INSKYSDYPLLKLIT--------------
------------------------------------DI------LGS-------------
-------------------------SIWFNTVLVMTHCSSSPPEGPDGYPLEYDAY----
------TRYCKNVV------------------------QRQIQVAASNTQLE-----N--
----------------------------------------------------------PI
VLVDNHPLCRRNTRGERVLPNGQVWVSELL-----LFCGATKLLADANSLLKFQD--SFL
LSHANTRLPSLPHLLSS----------------------LLKPYPSSSYDSI--------
------------------------------------------------------------
------------------------------DNEMTDLS--------DEEDEYDQLPPFRV
LKKSEYE---KLTKEQKTAYLDELDY----------------------------------
-----------RETSYLKHQWKEGIRR---QKLAEAQSTEASYGVA---------DDYEE
STAPEVVHMSDMEIPLNFDSDYPAHRYRHL-ITNDQLFRPVLDPQGWDHDIGFDGINFES
SHELKRNISSSIAGQMRKDKEDMYIQSECSVSYTDQ----------RGYSLMGGMDMQT-
-----------------------------------------------------ASKDLVC
TVHGDAKYRNFPWNTTGGGISVTKFGSKYFSGAKLEDSIIIGKRVQLVANAGRMV-----
------------------------------------------------------------
----------------------------------------------GCGQVA--------
-----------DGGGLEVTVRGKDYPVREGSTTIAATALSFEKDTVISANLQSVFRVGRG
SKLSVSANIN--------------------------------------------------
NRKLGRLSVKTSTSDHVEIALLAAVSLIQFLLRRRSP-----------------------
-----------------PTDKGDQQFDTDSLEE---------------------------
------------------------------------------
