>gnl|BL_ORD_ID|8882 @Brassica_rapa@_002291|PACid:22692392
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------KGFIDW----------
--------------------------------------------------------VFDL
SNSMASSSRPLLGTAPFSRH-HEPH-----------------------------------
--------------------------------------------------------DSHS
QA---------------------------------------PALPEPVARS---------
------------EPPCSTSVDVEAHP----PI-----SQQQTPLESL-----HQSSLDLN
DKKHNPLAKIGDLQVQFLRLVHRFGQSQ-N-NILVSKVLYRVHLAMLIRAEESELKTVKL
KQDKAKTLAKEQESSGVPELDFS----LR---IL--------------------VLGK-T
GVGKSATIN---SILGQ----S------------------KSE-TDAFQPATDRIEEVNG
TV--SGVKV--------------------------------TFIDTPGLHQPSPSSARK-
-------------------NRKTLLSIKRYVKKRPPDVVLYLDRLDTIDLRYSDYP--LL
SLITEVLGAAL-----WL-----NTILVMTHSSVA-SEGRN---MNYESY---------V
GQRVDVVQH--YIHQAVS-----------DTK-----LENPVLLVENHPSC---------
---------------------RKNHAGECVLPNGL-------------------------
-VWKPQFMFLC-VCTKVLGDVQ-----SLLRFRD--SIGLGQASGTRTA--SLPHLLS--
------------------------------------------------------------
--------------VFLRRR------LSSGG-D--EAERE------------ID------
-----ELMDSELEE---EEEDEYDQLPAIRILGKARFEKLSKSQK---------------
----------REYLDELDY-----------------------------------RETLY-
-LKKQLKEECRRRKDEKLNEEE----------------EEKSD--QAAVPLPEMAGPDSF
DSDFPSHRYRSIATSDQWL----------VRPVYDPQGWDHDVGFDGINIETAVKVKKNL
FASAN----------GQVSRDK----QRFTIHSETNAAYTTDS------RIQTFSVAADV
Q-SSGDDLVYTFHGGTKLKTFKQNTTDLGVGLTSFGGKYYLAGKIEDSLLVGKRVKLTVN
-AGQMKGSG---------------------------------------------------
--------------ETAHGGSFEACIRGRDYPVRN-EQIGVTVTALSFK-KELVLNWGLQ
TQVRPTRDTNVDVSVNMNNRKMGKINVKLNSSEHWEIALISAFTLFKALVRRKKAVSEIT
NENEEE------------------------------------------------------
--------------------------------------------------------L
>Toc90_gi|75291915|sp|Q6S5G3.1|TOC90_ARATH RecName: Full=Translocase of chloroplast 90, chloroplastic; Short=AtToc90; AltName: Full=90 kDa chloroplast outer envelope protein; AltName: Full=Plastid protein import 4
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------KGFKDW----------
--------------------------------------------------------VFAL
SNSMA-SSRPLLGSDPFFRDPHQEQ-----------------------------------
--------------------------------------------------------DNHS
QA---------------------------------------PAAPQPVTLS---------
------------EPPCSTSSDLEILP----PL-----SQQQVPLESL-----YQSSIDLN
GKKHNPLAKIGGLQVQFLRLVQRFGQSQ-N-NILVSKVLYRVHLAMLIRAEESELKNVKL
RQDRAKALAREQESSGIPELDFS----LR---IL--------------------VLGK-T
GVGKSATIN---SIFGQ----P------------------KSE-TDAFRPGTDRIEEVMG
TV--SGVKV--------------------------------TFIDTPGFHPLSSSSTRK-
-------------------NRKILLSIKRYVKKRPPDVVLYLDRLDMIDMRYSDFS--LL
QLITEIFGAAI-----WL-----NTILVMTHSAAT-TEGRNGQSVNYESY---------V
GQRMDVVQH--YIHQAVS-----------DTK-----LENPVLLVENHPSC---------
---------------------KKNLAGEYVLPNGV-------------------------
-VWKPQFMFLC-VCTKVLGDVQ-----SLLRFRD--SIGLGQPSSTRTA--SLPHLLS--
------------------------------------------------------------
--------------VFLRRR------LSSGA-D--ETEKE------------ID------
-----KLLN--LDL---EEEDEYDQLPTIRILGKSRFEKLSKSQK---------------
----------KEYLDELDY-----------------------------------RETLY-
-LKKQLKEECRRRRDEKLVEEE------------NLEDTEQRD--QAAVPLPDMAGPDSF
DSDFPAHRYRCVSAGDQWL----------VRPVYDPQGWDRDVGFDGINIETAAKINRNL
FASAT----------GQVSRDK----QRFTIQSETNAAYTRNF------REQTFSVAVDL
Q-SSGEDLVYSFQGGTKLQTFKHNTTDVGVGLTSFGGKYYVGGKLEDTLLVGKRVKLTAN
-AGQMRGSG---------------------------------------------------
--------------QTANGGSFEACIRGRDYPVRN-EQIGLTMTALSFK-RELVLNYGLQ
TQFRPARGTNIDVNINMNNRKMGKINVKLNSSEHWEIALISALTMFKALVRRSK--TEMT
EENEEEKIVNF-------------------------------------------------
------------------------------------------------------LVS
