>gnl|BL_ORD_ID|10791 @Citrus_clementina@_0.9_002789m|PACid:19261909
-M----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------KSVRDW---
---------------------------------------------VF--SQLL-------
---ASSRQLSGNGNFF--------------------HGGPTGEEFDDQARTSSLVAPPVL
A--------------------DAGCSSDVNQ--DNRRYSTS-----------QQVPVEDP
SPHNQNTDDKMMDPLVKIEDLQVKFLRLLQRFGQSQDNILAVKVLYRLHLATLIRAGESD
MKMVNLRSDRTRAIAREQEAAG-IPDLDFSIRIL--------------------------
-----VLGKTG------------------------VGK-------SATIN---SIFDQTK
TETD---AFQPATDCIREVKGSV--NG----------IKVTF------------------
----------------------------IDTP---GFLPSCVRNVKRNRKIMLSVKKFIR
RSPP--DIVLYFERLDLISMGFSDFPLLKLMTEVFGTAIWFNTILVMTHSSSTLPEGSSG
YPFSYESYVTQCTDLVQQRIHQAVSDARLEN-----QVLLVENHPQCRRNVKGEQILPNG
QIWKSRFL--------LLCICTKVLGDANALLGFRDSIELGPLGNTR--VPSMPHLLSS-
---FLRHRSLSSPS--------EAENEIDEILASEI-DEEDEYDQLPPIKILKKSQFERL
SKSQKKSYLDELDYREILYFKKQLKEESRRRKENKLSKEECLPNDSTPDEQTSSE-----
--AVMLPDMVVPPSFDPDCLAYRYRCLVTSDQWLVRPVLDLQGWDHDVGFDGINL-----
-ETAVEIKSNVFASIAGQITKDKHDFNIHSESAAAYV-DPEGPTYCIGLDVQSSGKDMIY
-----------------------------------------------TVHGNTKLRNFKH
NVTDCGVSL-----TSFGNKNYVGAKLEDSLLVGKRLKLVMNAGRMGGSGQVAYGGSFEA
ILRGADYPVRNDNISLTMTALSFNKEVVLTGGFQSEFRPIRGLNMSVNANLNSRKMGQVC
IKLNSSAHMEIALLAVFSI----FRGLLRRKAAENKSTEALE------------------
-----------------------------------------TG-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
