>gnl|BL_ORD_ID|11606 @Cucumis_sativus@_132440.1|PACid:16962561
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------KGVRDWLFSQLVSKSVVSSRPLLGSDGFFGEE
NKEHMDENQDDEVAQATNIVAPTTPHTSDSNGNLENQDD---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------LSLAQVGGDS-SQSQHDSNGVKK
DVLTKIEDLQVQFFRLLLRIGQTQNNLLVEKVLYRIHLATLIQVGESDLKRVNLERIKAR
AKAAEQEAAGIPELNFT----FRIL----------------------VLGKTGV------
-GKSATINSLFDQAKTPTNAFQPATG-HIHE---------------------------IV
GTI--NGIKVSIIDTP------------------------------------GLSQSSS-
-GNMK----------------------RNKKIMFSVKRYIRKS----------PPDIVLY
FDRLDLVNKHHGDYLLMKLMNEVFGSAIWFN-----------------------------
----------------------------------------TILVLTHCSS-ALP--EGPD
GYPVSFESYV--------------AHCSDVLQQNIYQALSDSK-----LD----------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------NPILLVENHPQCKKNIMGEKVLPNGQVW
RSHFLLLCICTKILGSIN-----------TLLKFQN-----------CIELGP--SAISR
LP-------SLPHLLSSFLRHRSMANTLGVDNDFEAILLNDI----------DEDDYDDL
PSFRILTKSQFKKLSNSLK-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----KEYLDELDYRETL-----------YLKKQLREEYQKRKEIKL-----------LKD
RDLVHNDNNGDLQAMPEADAVLLPDMAVPPSFDPDCPVHRYRCIAVDD------------
-QWIVRPVLDPQGWDHDVGFDGINLETAMEMNKNVFTSVAGQVSKDKNVFNIQSECAASY
MDS-RRTSYTLGLDVQSAGTDKMYTVHSNAKLGSIKHNLPGIGVSLTSFKKNCYYGAKLE
DTISLGKRVKFVINGGRIEGAGQMAYGGSIDATLRGRDYPVRNDHLRVTMTVLSFDKETI
LGGNVESEFRLSRSMRLSVNTNLNTRKMGQICIKASSCEHLQIALVSAFTILRALMRRKE
INT---------------------------------------------------------
---------------------------------------------S
