>gnl|BL_ORD_ID|33002 @Citrus_sinensis@_1.1g003845m|PACid:18125948
----M-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------KSV
RDWVF--SQLLASSRQLSGNGNFFHGGPTGEEFDDQARTSSLVAPPVLADAGCSSDVNQD
NRRYSTSQQVPVEDPSPHNQNTDDKMMDPLVKIEDLQVKFLRLLQRFGQSQDNILAVKVL
YRLHLATLIRAGESDMKMVNLRSDRTRAIA--------------------REQEATGIPD
LDFSIRILVLGKTGVGKSATINSIFDQTKTETDAFQPATDCIR-----------------
------------------EVKGSV--NGI--KVTFIDTP---------------------
------------------------------------------------------------
------------------GFLPSCVRNVK--RNRKIMLSVKKFIRRSPP--DIVLYFERL
DLISMGFSDFPLLKLMTEVFGTAIWFNTILVMTHSSSTLPEGSSGYPFSYESYV------
------------------------------------------TQCTDLVQQRIHQAVSDA
RLEN-----QVLLVEN-----------HPQCRRNVKGEQI--LPNGQIWKSRFLLLCICT
KVLGDANALLGFRDSIELGPLGNTR--VPSMPHLLSSFLRHRSLSSPSEAENEIDEILAS
EI---------DEEDEYDQLPPIKILKKSQFERLSKS-----------------------
-------------------------------------QKKSYLDELDYREILYFKKQLKE
ESRRRKENKLSKEECLPNDSTPDEQTSSE-------AVMLPDMVVPPSFDPDCLAYRYRC
LVTSDQWLVRPVLDLQGWDHDVGFDGINLETAVEIKSNVFASIAGQITKDKHDFNIHSES
AAAYV-DPEGPTYCIGLDVQSSGKDMIYTVHGNTKLRNFKHNVTDCGVSLTSFGNKNYVG
AKLEDSLLVGKRLKLVMNAGRMGGSGQVAYGGSFEAILRGADYPVRNDNISLTMTALSFN
KEVVLTGGFQSEFRPIRGLNMSVNANLNSRKMGQVCIKLNSSAHMEIALLAVFSI----F
RGLLRRKAAENRSTEALE------TG
