>gnl|BL_ORD_ID|8347 @Eucalyptus_grandis@_C00581.1|PACid:23570068
MKSVRE------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------WVFSQLLTNSLSSSRPLSGSDSYFGEAANE-----
--------GPHEQAHADSLEVSQASIDQSASSNGTLE-----------------------
------------------------------------------------------------
---------------------------SQHYPSQRQGLVENCSQSHSSSDRGKSNPMSKI
NDLQIKFLRILQRLGHQQDNLLAAKVLYRVQLATLIQSGEADPKVLKHMHDKARAQAAQE
E-----AAGVPELDFSFKVLVLGRTGVGKS----------------------A-------
-----------------------------------------------------------T
INSIFDQTK-VVTNA----------FQPATDSIREVTGTVGGMKITFV------------
----DTPGLCPSSTANMRRNRKILLSVKK-YIRKSPPDIVLFFERLDLIN-VN-------
----------YSDFPLLKLLSEVFGNAIWFNTILVMT-----------------------
-----------------------------------------HASCSLP------------
--EGPNGYPVVYE------SYVGQC-----------ANLIQ-------------------
---------------------------------------SYIHLAVSDSKIENPVL----
------------------------------------------------------------
-----------------------------------------------------LVENHSQ
CRKNLLGEK-VLP--------------NGQVWKSHF------LLLCVCMKVLSDA-----
------------------------------------------------------------
------NKFLEFR-----------------------------------------------
---------------------------------------------------------DSI
ALGPPNA--KRQPSLPHLLSSLLRHRPSPSTGGADYEMDDSILSDT---------EEEDE
YDQLPPIKILSRSQFEKLTKSQKKDYLDELDYRETLYM----------------------
------------------------------------------------------------
---KKQLREELQRQRELREDKLLRKENSDYNDSSDNQETSSE---PFLLPDMAVPPSFDS
DCPLHRYRGLVTGEQLIVRPVLDPHGWDHDVGFDGINLETSIETKSNVYALVTGQMSKEK
NDFSIHSECSAVYNST-SGPSYTLGLDVQSAGKDLMYTMHSNTRLNNLKHNIAECGLSLT
RFGDKCYTGAKIEDTMHIGRRVKLVVNAGRLGAAEQVAYGGSFEATVRGRDYPVRTDSIS
LSMTVLSFDKETVLSGGLQSEFRLSRDTKVMINGNLNSRKMGQLFLKTSSSEHMEIALIA
LVSIIRGLFRRKNTENVGTGSLES------G
