>gnl|BL_ORD_ID|51704 @Medicago_truncatula@_Medtr8g121750.1|PACid:17483355
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------NMWLCCDAEKGRDKVELL
SST-----------------------------QLCCDEEKEEMKLSHTH-----------
----------------------------------------------------------SV
ALPIPSGTSNSSANQSNQ----SSSTLQQASDAEIYQ-SQHSGN---GRRKDTLAK----
----------------VEDLQVKFFRLLQRLGQSKENLLVAKVLYRMHLATLIRAEETDL
QRVN--------------------LS-------------------------SSGAREIAN
QHEAADMPQ---LDFSCRILVL-------GKTG---------------------------
---------------------VGKSAT--------------INSIFDQEK----------
---ATTN---AFQPA--TDCIQEIVGTVNGLNIT------------FIDTP---------
-----------------------------------------------GFLPSSTNNVKRN
KRIMLS----------VKRFIRKSPPDIVL------------------------YFERLD
LINS---GYSDFPLL----------KL--ITEVFGAAIWFNTILVMTHS-----SSS---
-----------------------------------IPEGPNGYTVNYDSYTSQCTNLIQQ
YIHQAILDSR--------------------------------------------------
-----------------LENPALFVENHPQ------------------------------
-------------------------------------------CPRNILGEKI--LPNGQ
IWRSQ-------------------------------------------------------
------------------------------------------------------------
------------------------------LLLFCICTKVLGDVNSLLKFQNGVELGPTN
S--ARVPSLPHLLSSLLRHRS------------VSNQSGIDDEIEEILLSDKEEGDEYDQ
LPSIRILTKSQFEKLSKSQKEDYLDELEYRETLYLKKQMKEE------------------
-------------YRRRKEKLLLEEQKFSD----IDNSDDQQGPPE--PVQLPDMAVPLS
FDSDCAIHRYRCLVDNDQLLVRPVLDPQGWDHDVGFDGINLETTTEVKKNV---------
---------------------------------YASVVGQMHKNKQDFNIQSECAAAYV-
NPMGPSYSIGVDVQSVGGKDMVCTVHSNTKLKNIKHNIADCGVSLTSFGKKYYVGAKLED
TLLIGKRLKFVINAGRMEGQGQVAHGGSFEACLRGEDYPIRNDNLSLTMTVLSFNKETVL
SGNLQSEFRLSRSLKATVSANLNSRKMGQICIKTSSSEHLQIALVAVFSILKVLLHRKEI
-----------------
