>gnl|BL_ORD_ID|13091 @Physcomitrella_patens@_Pp1s123_63V6.1|PACid:18049626
MDALRKLSSLGRNQDK---ILDTASSSSYTEASVAEIPKASVETGGKDEASPSGLAPIKV
RVSNDVGAEIEEKRGGDEESVGSGESFDSALERLAASSVTSFEPPSPVGSVGEQSQ----
---------------------------------------------------FAGGVSEDL
EERGQEEYLYYDDYGDDGEVEKD-------------GSEKDSTSSSSSSS----------
----------------------SSECSSSASNTEDEMDISEYGASSERA-----------
-----------MPLANPS----------------------GVTD----------------
-----EEEEDGKEEETGIEEKFE---------------------------------EVYD
GGVDS-------PLEEIDVASAGNVTAREFRDEPEAWVSSRDSTEDSGKFIVTVS-----
-------------------------------------VTELKYNVERAVT----AEENMP
NGLKLGSEAR------------------------GIASSSRGA-------ELGNAFKDSR
EDHEVQEELTERSVKVAV------------------ENYDQEG-----------EDADST
EIKKEFPRELTQSRTVIESPAYRFTS-EPVDPALLELKSEKAQPNTQSFARI--------
----AEGESDADADADADDEDVESGDEHEDGYTE---------INIRQAAGKSESENESG
NNPSLGP------------------------------------AGPSLISVLVRKTARRP
ASTAATD-----TQSSNAASSTQVAGTTDVNPSIEVN-EVNETREKLQNIRVKFLRLVHR
LGQSPQNVVVA-------------------------------------------------
------------------------------------------------------------
------------------------------QVLYRLGLAESLRGGSTRNHTRAFDFDRA-
------------------------------------------------NAIAEEQEADNQ
EEE-------------------------------------------LDFACTILV-----
-----------LGKTGVGKSATINSIFDE-------------------------------
---------------------HK-SVTNA-------YNPSTTN------------VYEV-
VGTMLGVKVRFVDTPGLLF-SVADQRHNERIM----------------------GRVKKY
IKKAS--PDIVLYFDR--------------------------------------------
--------------------------MDMQT--REFGDVPLLRTITN-------------
------------------------------------------------------------
-----------------------------------VFGTAVWFNTIV-------------
-------------------VLTHASTAPPDGPNGTPMGYELFVAQRSH-----SVQQSIR
QVAGDMRLQN--PVSLVENHPACRANRNGQR-----------------------------
------------------------------------------------------------
--------VLPNGQIWKPHLMLLCFASKILAEANTLLKLQDTAAPGRPFGQRSRVPPLPF
LLSSLLQSRAQLKLPDEQLDESDESDD---------------------------------
DEEDEEEGDEYDDLPP--FRSLSKEELEELSKDQR-------------------------
-------------------------------------QEYAEELAVRERLFQKKQHREQL
QRRKEMKKRATAMRKEGLSHPADEADDEAGQPAAVPVPMPDMALPPSFDSDNPTHRYRYL
ETANQWLVRPVLETHGWDHDAGYDGFNVEKMFVVKNKIPASISGQVTKDKKESQVNFEAA
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----SLKHGEGKVTLT-GFDVQTIGKDLAYTLRAETRFNNFKRNKTTAGVTATYLNDTIA
AGVKLEDRILIGKRVKMVVNGGVLTGKGDKAFGGSLEATLRGKEYPLSRTLSTLGLSVMD
WHGDLAIGGNLQSQFMVGK-TMMVGRANLNNRGSGQVSIRASSSEQLQMVLIGIVPILRS
LINCRFGFGGGQSS----------------------------------------------
------------------------------------------------------------
-----Q
>gnl|BL_ORD_ID|232 @Physcomitrella_patens@_Pp1s136_59V6.1|PACid:18036766
MDALRKLGSLGRRRDE---V-DTASSPLKNEASAAEIPRDPVQISGKDEASPSGLTPIRV
RVPEDVRSESEVKRDGDEESVGSGESFDSALERMEASSITSFEPPSPMESIDGRFQ----
---------------------------------------------------FEDGVREDL
AESGLDGNFSYDDDDDDEEEEED-------------GSE-EGESTSSSII----------
----------------------NSEYSSSASNTEDEMDISGYGASSART-----------
-----------MLVSNDA----------------------SKSD----------------
-----EE-----------------------------------------------------
------------------------------------------------------A-----
-------------------------------------IDEPKYKLRNVVT----GEENMS
GGLSVENEAR------------------------GVALSSWKS-------ELEDFYEASL
EDNDVQEELAEKIIKVAS------------------EQNDEED-----------EEVHFP
VIANELPGRITRNRTMIDSPAHLYSAVKAVDSTLPALKSESTKSITQGFVEA--------
----EEAESDVFTEGE-DGYD----DEDEDGDIQ---------MDVSQATEKSGTPDESE
SNPSMGA------------------------------------GGPRLPSLPQRSSARRS
AATTATG-----VPRPNTASSTQSAATSDASISSESS-EANEIREKLQNIRIKFLRLARR
LNQSPQNVVVA-------------------------------------------------
------------------------------------------------------------
------------------------------QVLYRLGLAESLRGGSSLNRTRAFSFDHA-
------------------------------------------------NALAEEQEA-AK
YED-------------------------------------------LDFACTILV-----
-----------LGKTGVGKSATINSIFDE-------------------------------
---------------------CK-TVTSA-------YYPSTTK------------VHEV-
SGTVLGVKVRFIDTPGLLP-STADQRHNKNIM----------------------RQVKKY
IKKVS--PDIVLYFDR--------------------------------------------
--------------------------MDMQT--RDSGDVPLLRTITD-------------
------------------------------------------------------------
-----------------------------------VFGAAVWFNATV-------------
-------------------VLTHASKAPPDGSNGTPMSYDYFVAQRSH-----FVQQTIR
QAAGDARLQN--PVSLVENHPACRINRSGQR-----------------------------
------------------------------------------------------------
--------VLPNGQPWKQQLLLLCFASKILAEANTLLKLQEASTPGKPFGQRSRVPPLPY
LLSSLLQSRAQLKMPDEQHGESEDSDDD-------------------------------S
DEEDEEEGDEYDDLPP--FRPLSKQELEDLSKEQR-------------------------
-------------------------------------QEYAEELADRERLFQKKQYREQI
RRRRERKKQASVMSKEEPSIPGDGAEDESGQPATVAVPMPDMALPPSFDSDNPTHRYRYL
ETANQWLVRPVLETHGWDHDAGYDGFNVEKMFVVKEKIPASVSGQVTKDKKEAQVNFEAA
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----SLRHGEGKVTLT-GFDVQTIGKDLAYTVRAETRFNNFKRNKTTAGVTATYLNDTIA
AGVKLEDRVLIGKRVKLVVNGGVLTGKGDKAYGGSLEATLRGKEYPLSRTLSTLGLSVMD
WHGDLAIGGNLQSQFMVGK-TMMVGRANLNNRGSGQVSIRASSSEQLQMVLIGIVPILRS
LINCRFGFGG-QPQ----------------------------------------------
------------------------------------------------------------
-----Q
>gnl|BL_ORD_ID|251 @Physcomitrella_patens@_Pp1s136_62V6.1|PACid:18036785
METLRNVSSTEKSKESSEAVRGASETSSIPERNSGGGP-DVEESGGRIN-SYAGPSPPRA
PVTDDTEDEVEEV-----DETEDDDNDDSAVE--NTSSLVDSAASRPLGSYADALT----
------------------------------------------------SMPVAKVTTEDE
EQDDDD-----DDADKADEEEVD-DEEYEEADDQASVEDLYGNSSALSRGSEGSLPRSIP
RIIARESGDDISEEPSEDEYNDISEEEYNEEAVEEAVEPEEKEQVTMEVEEKEQFESPVA
AEESTVKELNATPAVVPPADADVGDVSRTDNSNAEESPMNADADVGDVLKKENSNAEESP
MNSDACREEDIVAEKVEKELS-QAVMTEDSQEVGSAQSQEEVTELMQAVSSLAAESESTD
QGVKQEVAPEVVPLATSEIKQGELEEIEQATTLPKTDVETRGCSLDLAEELQKLSVSRSL
SNDVLKSDEAERAAIIENAPAESTIDESV---VNVETVTESGYIVKRAASNDLMAELEKL
AAARLEKEASNNTVNPVREVSEDDVKDVSGETTVVTTSISEGANESLSKKEDEPALIGSN
VPEELEGN----SLEVQSAITTDLEKVSSTPTPSNAEKESPEATEVRIVEEGKLEKADPS
VVNEELSKEILEDPEVVPSPAKMYTALKAVDGDMPVLKSENGNVAGDENVESESRVLPAV
DFAGKDGDTDANTADE-DNENDEDDVDEDEDEDDADMDTAKALAELAMTAGKSGDVSESG
TKPSMGA------------------------------------AGPSLPSLPQRPAVRKP
IAATASDSPGRNTQRPNGALSTQITSTTDESASSDAA-EGDETREKLQNIRVKFLRLAHR
LGQSPQNVVVA-------------------------------------------------
------------------------------------------------------------
------------------------------QVLYRLGLAESLRGGSAPNRSGAFSFDRA-
------------------------------------------------NALAEEQEAANQ
EEE-------------------------------------------LDFACTILV-----
-----------LGKTGVGKSSTINSIFDE-------------------------------
---------------------RK-SVTSA-------FKPSTNK------------VQEV-
IGTVHGIKVRVIDTPGLLP-SVADQQHNERIM----------------------GQVKKY
IKKAS--PDIVLYFDR--------------------------------------------
--------------------------LDMQS--RDFGDLPLLRTITD-------------
------------------------------------------------------------
-----------------------------------LFGAAVWFNAIV-------------
-------------------VLTHASSAPPDGPNGVPLSYEMFVAQRSH-----VVQQTIR
QAAGDMRLMN--PVSLVENHPACRTNRTGQR-----------------------------
------------------------------------------------------------
--------VLPNGQIWKPQLLLLCFASKILAEANSLLKLQETTAPGRPFGQRSRVPPLPF
LLSSLLQSRAQLKLPDEQAGESDESDDD-------------------------------E
EEED-SDADDYDELPP--FRPLSKEELEDLTKEQR-------------------------
-------------------------------------EDYMEELADRERMFQKKQYREEI
RRRKEAKKRQAQMSKEELAEA-EEAEDEAGNAAAVPVPMPDMALPPSFDSDNPTHRYRYL
ETANQWLVRPVLETHGWDHDAGYDGFNVEKMFVVKEKIPASVSGQVTKDKKEAQVNFEAA
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----SLRHGEGKVTLT-GFDVQTIGKDLAYTVRAETRFNNFKRNKTTAGVTATYLNDTIA
AGVKLEDRVLIGKRVKLVVNGGVLTGKGDKAYGGSLEATLRGKEYPLSRTLSTLGLSVMD
WHGDLAIGGNLQSQFMVGK-TMMVGRANLNNRGSGQVSIRASSSEQLQMVLIGIVPILRS
LINCRFGF-GGQSQ----------------------------------------------
------------------------------------------------------------
-----Q
>gnl|BL_ORD_ID|13071 @Physcomitrella_patens@_Pp1s123_61V6.1|PACid:18049606
MDTSSKVSSMEGNKET------TEDASVAVERSNGGGP-NGVEIEGRGD-SYVGPSPPRA
PVTDDTEDEVEEV-----DGSGDNDSFDSAVERFGASSAASVEPSSPVSSYADALKTKDT
APEVKEEESVEKDESNKVKENGGGSSAKDEARARNSEGEEEFSEVPIRTMPVAKVTTVDE
DQDG--------DVEEDDEEEVDNEEEFEEANDQVFGEEEYATSTAFRQEYEGSLPRSMP
RIIARESGDDISDE--------FSEEEFNEEETEDEAEQEEGGAVTEATGKEE------F
GKETTSKEVTDIPLVEQP----------------------AETEVGDRLKSDDSSNVENF
VNTQGSGREDVSEEQRGLEVSLQAAKIEEAQVVESEQPHEEEKELTRAVSSLVAEPENFD
VGVKEVVASEVVPLATVDVKEGELETTDEATTAPKMDVENRECSADLAEELRKLSASRSL
SEEVFTNEEAEPAVGTENASTDSKPDEVKEFDVDSFPVTESNYVVRRAASNDLVAELEKL
AAARLENESSDNATIPVEEDSKADVKDTSQDITVATASSSEGAN-----KEDEPASTESS
SPKEPEVDDGEGSVEVQSSIIEDLEKVGNDFTPSNAEKGSSEA---QIVEENKV-GVDPA
LVSEGAPEGVIEGPAVVSSPAKMYTALKAVDDEMPPLKSENKAVVETEKVESKPRGFSAI
DFAEEDGDSDADAEDE-DDEDDEDDDEDDDDEDDKDMVTAKALAELANAVGKSGDGAESG
KKSSMGA------------------------------------AGPSLPSLPQRPAVRKT
AAATALDTAGRITQRPNGAPSTQLTATTEENANSDTA-EGNETREKLQNIRVKFLRLAHR
LGQSPQNVVVA-------------------------------------------------
------------------------------------------------------------
------------------------------QVLYRLGLAESLRGGNTSNRAGAFSFDRA-
------------------------------------------------NALAEEQEAANQ
EEE-------------------------------------------LDFACTILV-----
-----------LGKTGVGKSATINSIFDD-------------------------------
---------------------RK-SVTSA-------FKPSTNK------------VQEI-
VGTVHGIKVRVIDTPGLLP-SVADQQHNERIM----------------------GQVKKH
IKKAS--PDIVLYFDR--------------------------------------------
--------------------------LDMQS--RDFGDLPLLKTITD-------------
------------------------------------------------------------
-----------------------------------LFGAAVWFNAIV-------------
-------------------VLTHASSAPPDGPNGVPLSYEMFVAQRSH-----VVQQTIR
QAAGDMRLMN--PVSLVENHPACRTNRNGQR-----------------------------
------------------------------------------------------------
--------VLPNGQIWKPQLLLLCFASKILAEANSLLKLQETATPGRPFGQRSRVPPLPF
LLSSLLQSRAQLKLPDEQLDESDESDDD-------------------------------E
EEED-SEADDYDELPP--FRPLSKEELEELTKEQR-------------------------
-------------------------------------QDYMDELADRERLFQKKQYREEM
RRRKEMKKRQAQMSKEELAQP-DEADDEAGQPAAVPVPMPDMALPPSFDSDNPTHRYRYL
ETANQWLVRPVLETHGWDHDAGYDGFNVEKMFVVKNKIPASISGQVTKDKKESQVNFEAA
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----SLKHGEGKVTLT-GFDVQTIGKDLAYTLRAETRFNNFKRNKTTAGVTATYLNDTIA
AGVKLEDRILIGKRVKMVVNGGVLTGKGDKAFGGSLEATLRGKEYPLSRTLSTLGLSVMD
WHGDLAIGGNLQSQFMVGK-TMMVGRANLNNRGSGQVSIRASSSEQLQMVLIGIVPILRS
LINCRFGFGGGQSS----------------------------------------------
------------------------------------------------------------
-----Q
