>gnl|BL_ORD_ID|6388 @Populus_trichocarpa@_POPTR_0006s06230.1|PACid:18212433
MK----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------GIRDWV
FGQLLSKSLASTGPLSGSGSFFSEEPVNEE---SDDPEML---ESSSPTSDTSCSSNCNQ
ETGSPQSLEQVAADS-YQPNHEVEVKKADSLTKIEDLRINFF------------------
------------------------------------------------------------
--------------------RL---------LLRF-------------------------
------------------------------------------------------------
------------------------------------------------------------
----GRSHDNLLV--------------------AKVLHRLHLAAAIRAGESNLK--RVKA
DGARTV---------------------AAEQ------------EASG----TPELNFSLR
IL---VLGKTGVGK-SATINSV----------------------FDQPKA-----PTDAF
-----RPATEHIKEVVGSI--NGVKVT---------------------------------
----FIDT-PGF----------------------------LPSSTSNLRRNRK-------
----------IMLSVRRFIRKSPPDI----------------------------------
-----VLFFERLDLINMGYCDFPLLK------------LMTEVFGNAVWFNTILVMTHGS
S-TPEGPTGYPISYESYVTQCTGLMQHYINQAVSDSKL-----ENPVVLVENNPHCKKNL
MGES-----------VLPNGQVWKSHF-----LLFCICTKVLGDANTLLEFEG-------
----------GIELGPLITPRVPSL----------------------PHLLSSFLKHRST
P--------CPSESEPEVDEILL---SDADEED-----DY-DQLPPIRIMTKSQFEKLTK
SLKKDYLDELDYRETLYLKKQLKDESRRRRERKLSGEE------------NFGEDSNSDP
QQASPEAVL--------------LPDMAVPPSFDSDCTIHRYRCLVTSDQWLVRPVLDPQ
GWDHDVGFDGVNMETAIEIRKNVHASITGQMSKDKQDFSIQSECAAAYA-DPRGRTYSVG
LDVQ-SSGKGTIYTVHSNTKLKNLKQNVTECGVSLTSFGNKYYVGTKLEDTMLVGKQLKF
VVNAGQMRCS-----------EQVAYGGSLEATLRGGDYPVRDDRISLSMSALSFKKEMV
LGGGFQSEFRPVRGMRMAVNANLNSQNMGQVNIKISSSEHIEIALVSVFSIFKAILHKKM
TENKSREVLEMG------------------------------------------------
---------------------------------------------------------
>gnl|BL_ORD_ID|44952 @Populus_trichocarpa@_POPTR_0025s00620.1|PACid:18251457
MK----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------GVRDWV
FGQLLSKSLASTRPLSGSGSFLSEEPVNED---SDDPGHMARSESSSPTSDTSCSSSCNQ
ETGSPQSLQQVAEDS-CQSIQGVEVKKADPLTKIEDLRINFF------------------
------------------------------------------------------------
--------------------RL---------LLRF-------------------------
------------------------------------------------------------
------------------------------------------------------------
----GQSHDNLLV--------------------AKVLHRLQLAASIRAEEMNLI--RVKV
DRARAV---------------------AAEQ------------EASG----IPELNSSLR
IL---VLGKTGVGK-SATINSV----------------------FDQTKA-----LTDAF
-----RPATIHIKEVVGSI--NGVKVT---------------------------------
----FIDT-PGF----------------------------LPSSTSNLRRNRK-------
----------IMFSVRRFIRKSPPDI----------------------------------
-----VLFFERLDLINMGYCDFPLLK------------LMTEVFGNAFWFNTILVMTHGS
A-TPEGPSGFPITYESYVTQCADLMQHYINQAVSDSKL-----ENPVVLVENDPHCKKNF
MGES-----------VLPNGQVWKSHF-----LLLCICTKVLGDANTLLDFEG-------
----------SIELGPLITPRVPSL----------------------PHLLSSLLKHRST
T--------DSTGVEQDADEILL---SDAEEED-----DY-NQLPPIRILTKSQFEKLTK
SQKKDYLDELDYRETLYLKKQLKEESQRRRERRLSREE------------DCGVGDNSDH
QQASPEAVL--------------LPDMAVPPSFDSDCTIHKYRCLVTSDQWLVRPVLDPH
GWDHDVGFDGVNLETAIEIRRNVYASITGQMSKDKQDFSIHSECAAAYA-DPRGQTYSAA
LDVQTSSGKGMIYTVHSNTKLRNLKQNVIECGVSLTSYDNKYYVGAKLEDTILVGKRLKV
VVNAGQMRGP-----------EQVAYGGTLEATLKGGDYPVRDDRISLSMSALSFKNEMV
LGGGFQSEFRPIRGMRMAVNANLNSQNMGQVNIKISSSVHIEIALVAVFSIFKAILRKKV
TENKSRELLKMG------------------------------------------------
---------------------------------------------------------
