>gnl|BL_ORD_ID|30638 @Phaseolus_vulgaris@_091029429m|PACid:23561633
------------------------------------------------------------
-------------------M----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------KGVRDW-----------
------------------------------------------------------------
-----------------------------------------------VFSQVLSKSLASP
SSLSGG--------NNFYAEEHRIQ--------------------------------NEN
FNEQGSDHSASSAIP-----SDSSNSSNGDQSNHHSSSLQLVSDTEVDHYQDNTNGRRK-
--DTLAKVEDLQVKFFRLLQRL--------------------------------------
----------------------------G-----------QTQENLLVAKVLYRMHLATL
IRTKESDLKRVNHSSSRA----------------------------RAVASEQEAIGVPQ
LD-----FSCRILVL------------------GKTG--VGKSA----------------
----------TINSIFG----------QEK-TTTGAFQPATNCI----------------
-------QEVVGN--VNGIN--------------------------ITFIDTPGFLPSST
NNMKRNKRIMLA----IKRFIRKSP---PDIVLYFER-----------------------
---------LDFINAGYVDFPLLKLVTEV-------------------------------
--------------------------------------FGSAIWFNTII-----------
--------VMTH--------SSSAIPEGPDGYTINYE----------SYI----------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------SHCTNIIQQ--------HIHQAVFDS
RLENP-----VLLVENHS----------------------QCPKNIMGEKILPNGLVWRS
QLLFFCVCTKVLGDVNILLKFQNSVDLGPTSS--TRIPSMPHLLSSLLR-----------
---------------------------------HHPISNLSGID----DEIEEILLSD--
-----NEEEEYDQLPPIRVLTKSQFEMLSEPLQKDYLDEMDYRETLFLKKHLKEDYRKRK
-EKLLLTEQKFLNSDNPD------------------------------------------
---DQQAPPEPVLLPDMAVPASFDSDCQSHRYRCVVSDDQWLLRPVLDPQGWDHDVGFDG
INLETTTEIKKNVNASVVGQMNKNKQDFSIQSECAAAYV-DPRAPTYSVGVDVQSTGKDF
ICTVRSNTKLKNIKHNIADCGVSLTSFAKKYYVGAKLEDTVFVGKRLKFVLNAGRMEGAG
QMAYGGSFEANLLGEDYPVRNDNVSLTMTVLSFNKEMVLSGNLQSEFRLSRSSRASVSAN
LNSRKMGQICIKISTSEHLQFASFAIFSILKF----------------------------
--------------LSRRKATRNVVK----------------------------------
------EGMD
