>gnl|BL_ORD_ID|60 @Ricinus_communis@_27394.m000352|PACid:16798225
MN----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------VIEAASVSPDTSFSSNNTLENGHHPCLQQDSEESNRFSHGGD--HKRMDPLA
KIEALQIKFFRLLQR---------------------------------------------
------------------------------LGHSHDNLLAAKVLYRLHLAASIRAGET--
-----DSKRVRKVAAEQEAI-------------DIPKLNYSMRILVLGKTG---VGKSAT
INSVFDQT-KTMTNAFEPA-----------------------TSRIQEIVGTV--KGIK-
-------------------------VTFIDTPGFLPSST---------------STVRRN
RKMMLS--------------------VKKFISKYPPD---IVL---FFERLDLV-NLGY-
--SDFPLLTLMTEVFGSAIWFNTVLVMTHAAPTLPEGPNGYPVNYESYVTR---------
--------------------------------CTDVLQHYIHQAVSDAKLE---------
-----------------------------------------NPVLLVENHPQC---KKNF
MGES---ILPNGQAWKSQVLLLCICNKILGDASTLLEFQ--DSIKLGSSNSQ--RMPSLP
-------HLL--SSVLQHRSVS-------SPNESEHEVDGI-----LLSDADEE---DEY
DQLPPIRILT---------------KSQ--------------------------------
---FERLTKSQKRDYLDELDYRET--LY----------LKKQLKEDARRRRE--KQLSDA
ENFGEDNTYDDQQ-----ASPEAVLLPDM-------------AVPPSFDSDCPVHRYRCL
ATSDQWLVRPVLDPQGWDH----------DVGFDGINLETAIEVKRNIHASIVGQMTKDK
QHFSIQSECAAAY-KDPKGPTYSVGFD------------------VQSSGKDLIYTVHSD
TKLRILRHNIADCAVSLTSFGNKYYVGAKLEDAILIGKRLKFVMNAGQMRGPGQVAYGGT
LEATLKGRDYPVRNDSTSLSMTALSFKKEMVLGGGFQSQFRPILGMTMAVNANLNSQKMG
KVSIKLSSSEHTEIALIAIFSIFRGLLHRKEAENGSKEALEM-------
