>gnl|BL_ORD_ID|23631 @Sorghum_bicolor@_Sb08g006190.1|PACid:1977861
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------LMNFRDWISYRLGSS
LLSARPFALSPG---ADDAVASEGDAHGTTHNDYVDTVTASP-------------FSSND
--------TRVSDVTTNSNGGAIYSGTVQQDDDNKKSDPLMKVEALQIKFLRLVYRTGVS
PSADVVAQVLYRLQLANLIKAGESVARRPNLAINKA------------------------
--------------------------------------RVIAAQQEAPGGPDLDVSLR--
-----------------------------------------IL-L----------LGKTG
VGKS-------------AMINSIFDERKVAT---------------------DA--LVPA
THRIKKIEGTI--KG----IR------------------------------VTVIDTPG-
-----------LMP-HYHGERRNRKILSSVKRFIKR--SPPDIVL---------------
------------------YFERLDHINSRYNDYPLLKLM----------TDILGSSMWFD
TVLVMTHCSSSPPEGPD-------------------------------------------
---------------GYPLEYDNYTRYCKNVVQRHIQAAVSNMQLDN-----PFVL----
----------------------------------------TDNHPMCRRNTKGER-----
-------------------------------------VL-----------------PNGQ
VWVSELL-----LLCGATK----LLTEANSLLKFQDSFLLSQ--ANTRLPSLPHLLSSL-
----------------------------------------LKPHS-------------SS
SSDAIDSEFTEMSDEEDEYDQLP----------------------------PFRILKKSE
YENLTNEQKSAYLDELDYR---ETLYLKKQ----------WKEGIRKQKLTEA---QNDE
VGDDYEESASPEVV--------------HMSDMDIPLCFDSDYPVHRYRHIITDDQ-LFR
PVLDPQGWDHDIGFDAINFEASKELKKNVSGAITGQMRKDKEDMYIHSECSVSYNAH-RG
CSLMGGMDMQMASRDLVCTVHGDAQFRNLPWNTT--------------------------
------GGGISVTKFGNKYFAGAKLEDSVTIGKRVKLVANAGRMAGCGQV----------
--------------------------------------------------------AHGG
GVQITA---------RGKDYPVREESVTAAVSALSFEKETVIGANLQSDFRVGRGSKISV
SANLNSRNLGKLSVRTSTSDHAEIALIAVVSLIQFILRRRSAAADKGEQEIDDTYLDD-
