>gnl|BL_ORD_ID|21382 @Setaria_italica@_Si009414m|PACid:19694856
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------MMNFRDW-----
---------ISYRLGSSLLSARPFALSSGADAA----ASEGDADGAHNEVVE--------
----------------------------TVSANRFPSNDSRASEVTTGSGATYPGLV---
--------------QQDEDNKKSDP-----------------------------------
----LMKVEAL---------------------------QIKFLRLVYRTGVPP-------
-----------------------------------------TTDVVAQVLYRLQLANLIK
AGESDARRTNLAINKARVIAAQQ--------------EAPGGPDLD------LSLRILLL
-----------GKTGVGKS--ATINSIFD-------------------------------
--------------------ERKVATDAL-------------------------------
--------------------------VPATHRIKKIEGT---------------------
--I--KG--IRVTVIDTPGLIP-HYHGQRRNR---------------------KILNSVK
RFIKR--SPPDIVLY------FERLDHINSRYSDYPLLKLM-------------------
-----------------TDILG-----SSMWFNTVLVMTHCSSSPP--------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------EGPD-----------------GYPLEYD---AYTR
YCKNV------VQRHIQAAV-------SNTQL---DNPVVLVD------NHPMCRRNTKG
ERV---------------------------LPNGQVWVSELLLLCGATKLLAEANS----
------------------------------------------------------------
-------------------------------------------------LLKFQDSFLLS
PA--NNRLPSLPHLLST-------LLKPNS--------SSSSDRIDGEL-----TETSDE
EDEYDQLPPFRILKKSE-----------------------------------------YE
KLTNEQKSAYLDELDYRETLYLKKQWKEGIRRQRLT---EAQNDEVADDYEES-------
------ASPEVVHMSDMEIPLTFDSDYPVHRYRHIITDDQ-LFRPVLDPQGWDHDIGFDA
--------------------------INFEASQELKKNVSATIAGQMRKDKEDMYIHSEC
SVSYSDQ-KGCSLMGGMDMQTASRDLVCTVHGDAKFRNLRWNTTGGGISVTKFGNKYFAG
AKLEDSVTI---------------------------------GKRVQLIANAGRMAGCGQ
VAHGGGVEITARGKDYPVREESITVSVTALSFDKETVIGANLHSDFRLGRGSKMSVGAKL
NSSNLGKLSIRTSTSDHAEIALIAVVSLIQFFRRRSGAADKGEQQFDTYLDD---
