>gnl|BL_ORD_ID|6113 @Selaginella_moellendorffii@_170624|PACid:15407391
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DYFPDKKPEDDENEKHE
EVDYKKPEEAGNEKHGEADVIGSAAEAVRSQEEREPVPETDSD---EEEEEEVDTSAALR
AFAQAAAATETPSLGSAGPSL--PAKPTATRLLSSIEGARNTQVAAHNPSGGSETTTAVE
AADTNGEPNDENVETREKLQMIRVKFLRLAQRLGQSANNAVVAQVLYRLGLAEQLRGGRS
SSRNSAFRFE-------------------------RASAIAEEQEAAGQ-EELDFTC---
---------TIMVL---------GKSGVGKSA----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------TINSLFDE---------------AKTETN----------------------
------------------------------AFAYSTKKVQEITGTVH-GIKLRVIDTP--
----------------GLLP-AVADQRH---------------NEKIMASVKRFIKKS--
---------P--------PDIVLY------------------------------------
---------------------FDRLDMQSRDYGDLPLLRTITD-----------------
------TFGAAI--WFNAIVVLTH----------------------ASSAPPDGPNGLPL
SYEMFVAQR-------------SHVVQQTIRQAAGDMRLMNP------------------
VSLVENHSACRTNRSGERVLPNGQVWKPQ-------------------------LLLLCF
ASKILAEANSLLKLQESTPGKPFM-RSKVPPLPFLLSSLLQSRPPLKHSDENAVGEDDTD
DDIEDVED---SDEEDYDELPPFR------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------R
LTRDELDQLDKSSRDEYFEELQMREKLFQKKQWKEEIRRRREMKKRAASSDSAEEYPAPV
DDGYDDDNKSAPV-PVPLPDMQLPPTFDSDNPVHRYRYLETAS-----------------
------------------------------------------------------------
----QWLVRPVMDLHGWDRDSGYDGFNMERMFTYGK-IPA-SLSGQVTKDKKEANVTLEC
AAS-MKHGEGKVSQAGFDVQTVGKDFSYTLRSETRFSNFKKNKTIAGLAMTMIGDTLAYG
MKIEDRLMIGRRVKVVMNGGALTGKGDTAYG-----------GTVEISLRDKDFPLGRSL
STCGLSVMNWHG-DMALGGNLQSQFMVG-KTMVVARGNLNNRGAGQITIRLSSSEQLQIA
LIGVMPLIKALF------------NSKFG-------------------------------
------------------------------------------------------------
------------------------------TGQQA
>gnl|BL_ORD_ID|12035 @Selaginella_moellendorffii@_60423|PACid:15413313
T-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----QGNTEEKTRILCEKLQDIRVKFVRLVHRLGQSADNGIAAQVLYRFALAEQLKGGK-
-MRNSTSGYD-------------------------KACAVAMEEEASSRDEELDFCC---
---------TVLLL---------GKSGVGKSA----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------TVNSIFGK---------------PMASTS----------------------
------------------------------AFSSGTNKVEVIDGTMK-GIRMRVIDTP--
----------------GLSA-SMADRRY---------------NERVVASIKRCIRRN--
---------P--------PDIVLY------------------------------------
---------------------VDRLDSQSK---DAALMRYIGD-----------------
------RFGPAI--WFNAIIVLTH----------------------GASSPPDGPDGFPL
RYDSYVGQR-------------TRMFQQTVRSAVGDTRLLNP------------------
VTLIENHPACRTNRAGERVLPNGMVWRPE-------------------------LLLLCF
SARILAEANTYLKLPESMPLTRLCERRSGSPMPVLLASMLQARSEVQQPDEEEYGEVDPD
EDE--------DGEAEFDQLPPFR------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------R
LLQDELDALDEDNRQSYFEELALREKLFKRKLWKTQCRRWREMKNRG------------V
EDGEDEQQQHRDMAPGISPDFALPTSFSSDDPSHRYRYVDDAS-----------------
------------------------------------------------------------
-----WNVRPVLD-SRWDHENGFNSANLDRSFHLAKNIPV-SVSGQIVMDKKEYHVTFDG
SAA-IKHGPNRVSTGGLDIQTVGRDVCYSLWGGTTFKNHECNKTLAGMGVTMVGENAVVG
VRLEDKVVIGKRAKILMSGATSLTRGDKAYG-----------AIMEATVVGPDYPVDRTN
CTLGLSVMNWTAKDIAYGINLHSQIHLG-GTAMVVRGNANNRGTGQISIKVNSTDRIQLA
LLGLLPVIRSL-------------------------------------------------
------------------------------------------------------------
-----------------------------------
