>Aquilegia_coerulea_gnl|BL_ORD_ID|13906 _006_00073.1|PACid:22036942
MVDDSIFKFQNRM---------KAFKDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------ISSQAVSKSLL-SSRPLLGGGNIFEEET
I-----------------------------------------------------------
-----------NENNEIQGSTATGMQERPVSANNLLQS-------SID-NEESRRA----
-----SADDLGLSGNMDRNRMDPLAKIE----SLQIKFMRLVHRLGQSHDNILV------
---------AKVLYRLHLATLIRVGE------KTSL--RNDRARAMAAELEAAGR-PDLN
FSLRILVLGKTGVGKSATINSIFDQ-MKAATDAFQPATNHIREVIGTSKGIKLTFIDTPG
LLPSSTRNVRRNRKILRSVKNFIRNT-PPD---------IVLYFERLDHINMGYSDFPLL
KLITDTFGSAIWLNTILVMTHSSGALPEGPNGYPVSYEPFVAQCTNLVQHYIHQAVSDLK
IE-----NPVLMVENHPQCKK-NISGEKVL---PNGQAWRSQF------LLLCICMKVLG
------DANTLLKFRDGFQIGPS------------------ASNRLPSLPHLLSTLLRPR
ST------E------R--ENDELDDQDT--DDEDEYDQLPPIRILTKAQFEKLTKSQKNA
YLDELDY-RETLYLKKQLRADIQKRRNN---LL------PKDGNSANDEDYDNHEGN-PE
--AVQLPD-IAVPPSFD-SDWPVHRYRCVVT-SDQWL-ARPVLDPQGWDHDVGFDGINLE
NVVEMK-----KNLHLSVLGQLSKDKQDFSVQTECNALFT-DL-------KGSSASASLD
VQ-T-AGK-DLVCTARGDTKLRNL--KH-NTTGCGVSVTSFGN-------KYFVGAKIED
TISVGR------RVELDL---NVGRMGGLGQVAY---------GGSFEATVRGRDYPVRN
EKIGLTMTV-LSFD-KEMVFGGNILSDFRIGHSSKISLNANLN-SRRMGQICVKTSSSDH
VEIGLIAVISICR----------AIFRRRA--IEDRTVD---------------------
-------------------------------------
>Citrus_clementina_gnl|BL_ORD_ID|10791 _0.9_002789m|PACid:19261909
------------M---------KSVRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFSQLLA-----SSRQLSGNGNFFHGGP
T-----------------------------------------------------------
-----------GEEFDDQ--ARTSSLVAPPVLADAGCS-------SDV-NQDNRRYST--
SQQVPVEDPSPHNQNTDDKMMDPLVKIE----DLQVKFLRLLQRFGQSQDNILA------
---------VKVLYRLHLATLIRAGE--SDMKMVNL--RSDRTRAIAREQEAAGI-PDLD
FSIRILVLGKTGVGKSATINSIFDQ-TKTETDAFQPATDCIREVKGSVNGIKVTFIDTPG
FLPSCVRNVKRNRKIMLSVKKFIRRS-PPD---------IVLYFERLDLISMGFSDFPLL
KLMTEVFGTAIWFNTILVMTHSSSTLPEGSSGYPFSYESYVTQCTDLVQQRIHQAVSDAR
LE-----NQVLLVENHPQCRR-NVKGEQIL---PNGQIWKSRF------LLLCICTKVLG
------DANALLGFRDSIELGPL------------------GNTRVPSMPHLLSSFLRHR
SLSSPSEAE------N--EIDEILASEI--DEEDEYDQLPPIKILKKSQFERLSKSQKKS
YLDELDY-REILYFKKQLKEESRRRKEN---KL------SKEECLPN-DSTPDEQTS-SE
--AVMLPD-MVVPPSFD-PDCLAYRYRCLVT-SDQWL-VRPVLDLQGWDHDVGFDGINLE
TAVEIK-----SNVFASIAGQITKDKHDFNIHSESAAAYV-DP-------EGPTYCIGLD
VQ-S-SGK-DMIYTVHGNTKLRNF--KH-NVTDCGVSLTSFGN-------KNYVGAKLED
SLLVGK------RLKLVM---NAGRMGGSGQVAY---------GGSFEAILRGADYPVRN
DNISLTMTA-LSFN-KEVVLTGGFQSEFRPIRGLNMSVNANLN-SRKMGQVCIKLNSSAH
MEIALLAVFSIFR----------GLLRRKA--AENKSTEALETG----------------
-------------------------------------
>Citrus_sinensis_gnl|BL_ORD_ID|33002 _1.1g003845m|PACid:18125948
------------M---------KSVRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFSQLLA-----SSRQLSGNGNFFHGGP
T-----------------------------------------------------------
-----------GEEFDDQ--ARTSSLVAPPVLADAGCS-------SDV-NQDNRRYST--
SQQVPVEDPSPHNQNTDDKMMDPLVKIE----DLQVKFLRLLQRFGQSQDNILA------
---------VKVLYRLHLATLIRAGE--SDMKMVNL--RSDRTRAIAREQEATGI-PDLD
FSIRILVLGKTGVGKSATINSIFDQ-TKTETDAFQPATDCIREVKGSVNGIKVTFIDTPG
FLPSCVRNVKRNRKIMLSVKKFIRRS-PPD---------IVLYFERLDLISMGFSDFPLL
KLMTEVFGTAIWFNTILVMTHSSSTLPEGSSGYPFSYESYVTQCTDLVQQRIHQAVSDAR
LE-----NQVLLVENHPQCRR-NVKGEQIL---PNGQIWKSRF------LLLCICTKVLG
------DANALLGFRDSIELGPL------------------GNTRVPSMPHLLSSFLRHR
SLSSPSEAE------N--EIDEILASEI--DEEDEYDQLPPIKILKKSQFERLSKSQKKS
YLDELDY-REILYFKKQLKEESRRRKEN---KL------SKEECLPN-DSTPDEQTS-SE
--AVMLPD-MVVPPSFD-PDCLAYRYRCLVT-SDQWL-VRPVLDLQGWDHDVGFDGINLE
TAVEIK-----SNVFASIAGQITKDKHDFNIHSESAAAYV-DP-------EGPTYCIGLD
VQ-S-SGK-DMIYTVHGNTKLRNF--KH-NVTDCGVSLTSFGN-------KNYVGAKLED
SLLVGK------RLKLVM---NAGRMGGSGQVAY---------GGSFEAILRGADYPVRN
DNISLTMTA-LSFN-KEVVLTGGFQSEFRPIRGLNMSVNANLN-SRKMGQVCIKLNSSAH
MEIALLAVFSIFR----------GLLRRKA--AENRSTEALETG----------------
-------------------------------------
>Manihot_esculenta_gnl|BL_ORD_ID|26569 _4.1_002049m|PACid:17986541
------------M---------KGIRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------AFAQLLSKSLA-SARLLSSSGSFFSEGP
V-----------------------------------------------------------
-----------NEDSNDP--AHMACPEVTVLLPDTLCS-------SDN-THENGPHPS--
LQE----DANRTNH-----ASDPLAKIE----DLQVKFFRLLQRLGYSNDNVLV------
---------AKVLYRIRLAISIRGRE--LDLK---------RARKVAEEQEAIDT-PELD
FSVRILVLGKTGVGKSATINSIFDQ-RKMITDAFEPATNHIEEIAGTVNGFRITFIDTPG
FFPSSASNMRRNRKIMLSVKRFIRKS-PPH---------IVLFFERLDLVNMGYYDFPLM
KLMTEVFGSAIWFNTILVMTHASSTLPEGPSGFPVNYESYVTRCTDLIQHFIHQAVSDTK
LE-----NPVLLAENHTQCKK-NFMGENVL---PNGQAWRSQF------LLLCMCTKVLG
------DANILLEFQDSIELGS-------------------SSPRVPSLSHLLLSLLRHR
-LSSPNGAE------Y--DVNEILLSDA--DEEDEYDQLPPIRILTKSQIERLTKSQKRD
YLDELDY-RETLYLKKQLKEDISRKREK---KL------AESETSGEDNNHEDQQPP-PD
--NVLLPD-MAVPPTFD-SDCPVHRYHCVAT-SDQWL-VRPVLDPQGWDHDVSFDGINLE
TAMEIK-----RNIYASITGQMSKDKQNFSIQSECVAAYT-DP-------RGPTYSLGFD
VQ-S-AGK-DLIYTVHSNTKLKTL--KH-HITECAMSLTCFGE-------NYYVGTKLED
TILIGK------RLKFIM---NAGQMRSSGQVAY---------GGTFEATLRGRDYPVRN
DIISLSMTA-LSFK-KETVLGVGFQSEFQPVRGMRMAVNANLN-SQKTGQVSLKMSSSEC
TEIALVAIFSILR----------ALFHRKD--EGNGRKEVLEM-----------------
-------------------------------------
>Manihot_esculenta_gnl|BL_ORD_ID|15640 _4.1_002111m|PACid:17975485
------------M---------KSIRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFTRLLS-----SSRSLSGSGSFFSEGP
A-----------------------------------------------------------
-----------DEDSN--------APEVAPVLPDTSYF-------SGN-TEGNEPHPS--
L----PGDLNRSNNVNDCEKADSLAKIE----DLEVKFFRLLRRLGHSSDNLLV------
---------AKVLYRIHLATSIRGRE--SDLK---------RARKIAAEQEAIDK-PKLN
FSIRILVLGKTGVGKSATINSIFDQ-RKTTTDAFEAATKHIQEIVGTVSGVKVTFIDTPG
FLPASANNVRRNRKIMLSVKRFIRKS-PPD---------IVLFCERLDLVNMGYSDFPLV
KLMTEVLGSAIWFNTILVMTHASSMLPEGPNGFSVNYESYVTKCTDLMQQFIHQAVLDRK
LE-----NPVLLVENHPQCKK-NFAGENIL---PNGQAWKSQF------LLLCICTKILG
------DVSKLLEFQGSIELGS-------------------SSPRVPSLPHLLSSLLRHH
-VSNPNEVD------D--DVYEILLSDA--EEEDEYDQLPPIRILTKSQFERLTKSQKRD
YLDELDY-RETLYLKKQLKEDARSKREK---KL------AEAERLGE-DNSDDQQTP-TE
--AVLLPD-MAVPPTFD-SDCPVHRYRCLAT-SDQWL-MRPVLDPRGWDHDVGFDGINLE
TAVEIK-----RNISASIAGQMCKDKQNFSIQSECAAAYT-DP-------RGPTYSVGFD
VQ-S-AGK-DIIYTVHGNTKLATL--KH-NNADCAVSLTSFGK-------KYYVGAKIED
NILIGK------RLKFVM---NAGQMRGRGQVAY---------GGTFEATLRGQDFPVRN
DIISLSLTA-LSFK-KEMVLSGGFQSEFRPVRNMRVAVNANLN-SQKMGQVSIKMSSAEH
IEIALAAIFSIFR----------VMLYRKE--SKNGSRETLEM-----------------
-------------------------------------
>Ricinus_communis_gnl|BL_ORD_ID|60 _27394.m000352|PACid:16798225
------------M-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------NVIEAASVSPDTSFS-------SNN-TLENGHHPC--
LQQD-SEESNRFSHGGDHKRMDPLAKIE----ALQIKFFRLLQRLGHSHDNLLA------
---------AKVLYRLHLAASIRAGE--TDSK---------RVRKVAAEQEAIDI-PKLN
YSMRILVLGKTGVGKSATINSVFDQ-TKTMTNAFEPATSRIQEIVGTVKGIKVTFIDTPG
FLPSSTSTVRRNRKMMLSVKKFISKY-PPD---------IVLFFERLDLVNLGYSDFPLL
TLMTEVFGSAIWFNTVLVMTHAAPTLPEGPNGYPVNYESYVTRCTDVLQHYIHQAVSDAK
LE-----NPVLLVENHPQCKK-NFMGESIL---PNGQAWKSQV------LLLCICNKILG
------DASTLLEFQDSIKLGSS------------------NSQRMPSLPHLLSSVLQHR
SVSSPNESE------H--EVDGILLSDA--DEEDEYDQLPPIRILTKSQFERLTKSQKRD
YLDELDY-RETLYLKKQLKEDARRRREK---QL------SDAENFGEDNTYDDQQAS-PE
--AVLLPD-MAVPPSFD-SDCPVHRYRCLAT-SDQWL-VRPVLDPQGWDHDVGFDGINLE
TAIEVK-----RNIHASIVGQMTKDKQHFSIQSECAAAYK-DP-------KGPTYSVGFD
VQ-S-SGK-DLIYTVHSDTKLRIL--RH-NIADCAVSLTSFGN-------KYYVGAKLED
AILIGK------RLKFVM---NAGQMRGPGQVAY---------GGTLEATLKGRDYPVRN
DSTSLSMTA-LSFK-KEMVLGGGFQSQFRPILGMTMAVNANLN-SQKMGKVSIKLSSSEH
TEIALIAIFSIFR----------GLLHRKE--AENGSKEALEM-----------------
-------------------------------------
>Populus_trichocarpa_gnl|BL_ORD_ID|6388 _POPTR_0006s06230.1|PACid:18212433
------------M---------KGIRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFGQLLSKSLA-STGPLSGSGSFFSEEP
V-----------------------------------------------------------
-----------NEESDDP-----EMLESSSPTSDTSCS-------SNC-NQETGSPQS--
LEQV-AADSYQPNHEVEVKKADSLTKIE----DLRINFFRLLLRFGRSHDNLLV------
---------AKVLHRLHLAAAIRAGE--SNLKRV----KADGARTVAAEQEASGT-PELN
FSLRILVLGKTGVGKSATINSVFDQ-PKAPTDAFRPATEHIKEVVGSINGVKVTFIDTPG
FLPSSTSNLRRNRKIMLSVRRFIRKS-PPD---------IVLFFERLDLINMGYCDFPLL
KLMTEVFGNAVWFNTILVMTHGSST-PEGPTGYPISYESYVTQCTGLMQHYINQAVSDSK
LE-----NPVVLVENNPHCKK-NLMGESVL---PNGQVWKSHF------LLFCICTKVLG
------DANTLLEFEGGIELGPL------------------ITPRVPSLPHLLSSFLKHR
STPCPSESE------P--EVDEILLSDA--DEEDDYDQLPPIRIMTKSQFEKLTKSLKKD
YLDELDY-RETLYLKKQLKDESRRRRER---KL------SGEENFGEDSNSDPQQAS-PE
--AVLLPD-MAVPPSFD-SDCTIHRYRCLVT-SDQWL-VRPVLDPQGWDHDVGFDGVNME
TAIEIR-----KNVHASITGQMSKDKQDFSIQSECAAAYA-DP-------RGRTYSVGLD
VQ-S-SGK-GTIYTVHSNTKLKNL--KQ-NVTECGVSLTSFGN-------KYYVGTKLED
TMLVGK------QLKFVV---NAGQMRCSEQVAY---------GGSLEATLRGGDYPVRD
DRISLSMSA-LSFK-KEMVLGGGFQSEFRPVRGMRMAVNANLN-SQNMGQVNIKISSSEH
IEIALVSVFSIFK----------AILHKKM--TENKSREVLEMG----------------
-------------------------------------
>Populus_trichocarpa_gnl|BL_ORD_ID|44952 _POPTR_0025s00620.1|PACid:18251457
------------M---------KGVRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFGQLLSKSLA-STRPLSGSGSFLSEEP
V-----------------------------------------------------------
-----------NEDSDDP--GHMARSESSSPTSDTSCS-------SSC-NQETGSPQS--
LQQV-AEDSCQSIQGVEVKKADPLTKIE----DLRINFFRLLLRFGQSHDNLLV------
---------AKVLHRLQLAASIRAEE--MNLIRV----KVDRARAVAAEQEASGI-PELN
SSLRILVLGKTGVGKSATINSVFDQ-TKALTDAFRPATIHIKEVVGSINGVKVTFIDTPG
FLPSSTSNLRRNRKIMFSVRRFIRKS-PPD---------IVLFFERLDLINMGYCDFPLL
KLMTEVFGNAFWFNTILVMTHGSAT-PEGPSGFPITYESYVTQCADLMQHYINQAVSDSK
LE-----NPVVLVENDPHCKK-NFMGESVL---PNGQVWKSHF------LLLCICTKVLG
------DANTLLDFEGSIELGPL------------------ITPRVPSLPHLLSSLLKHR
STTDSTGVE------Q--DADEILLSDA--EEEDDYNQLPPIRILTKSQFEKLTKSQKKD
YLDELDY-RETLYLKKQLKEESQRRRER---RL------SREEDCGVGDNSDHQQAS-PE
--AVLLPD-MAVPPSFD-SDCTIHKYRCLVT-SDQWL-VRPVLDPHGWDHDVGFDGVNLE
TAIEIR-----RNVYASITGQMSKDKQDFSIHSECAAAYA-DP-------RGQTYSAALD
VQTS-SGK-GMIYTVHSNTKLRNL--KQ-NVIECGVSLTSYDN-------KYYVGAKLED
TILVGK------RLKVVV---NAGQMRGPEQVAY---------GGTLEATLKGGDYPVRD
DRISLSMSA-LSFK-NEMVLGGGFQSEFRPIRGMRMAVNANLN-SQNMGQVNIKISSSVH
IEIALVAVFSIFK----------AILRKKV--TENKSRELLKMG----------------
-------------------------------------
>Malus_domestica_gnl|BL_ORD_ID|22931 _0000612047|PACid:22642907
------------M-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------PLV-SPRPLSGSDSFFREEP
S-----------------------------------------------------------
-----------NEEFDDQGAAHSNTLVTPRIRPAPSAS-------FNX-DRENQSDQS--
LQHVVVXNSDHSHNRSDKKKMDPLVRID----DLXVKFLRXLLRLGLSQNNVLV------
---------AKVLYRIHLATLIRAEE--SDLKRVNL--RSDRARAVAAEQEASGL-PEMD
FSLRILVLGKTGVGKSATINSIFDQ-TKTETNPFRPGTDRIXEVVGTVNGIRVTIIDTPG
FLXSCTGNFRRNKKIMLSVKKFIRKS-PPD---------IVLFFERLDLMSXNYNDFSLL
KQITEVFGPAVWFNTXLVMTHSSLVLPEGPDGYPVNYESYVRQSTDMVQHYIHQAVSDSR
LE-----NPVLLVENHPQCRK-NIAGEKIL---PNGQVWKSQF------LLLCICTKVLS
------DVNXLMKFQDSIHLGPS------------------NATHMPSLPHLLSSLLRHR
TAIGPXGGD------V--GVDESLVSDA--EDEDEYDQLPPIRILTKSQFERLTKSQKKD
YLDELDY-RETLYLKKQLKEEYRRQMEI---KL------SKEKXTXSDDNSNSQQASQEE
--AVLLPD-MEVPPSFG-SDWPAHRYRCLLT-SDQWI-MRPVLDSHGWDNDVGLDGVSLE
TAMQVN-----RNVFTSVAGQMSKDKQDFSIQSECAAAYL-DP-------NGTAYSVGLD
VQ-S-AGR-DTIYTLHGNTKLRKL--WH-NVAESGFSLTSFGN-------KYYIGGKLED
TISVGK------RLKFVM---NVGQMMGPEQVAY---------GGGVEATLRGRDYPVRN
DNVSLMMTI-LSFN-KEMVLGGNLQSESRLGRNMSVSVNANLN-SRRMGKISIKASSTDH
LQFSMVAAFTIFW----------ALLRKKD--VKSTSDE---------------------
-------------------------------------
>Malus_domestica_gnl|BL_ORD_ID|48467 _0000285199|PACid:22668452
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------MDPLVRID----DLXVKFLRXLLRLGLSQNNVLV------
---------AKVLYRIHLATLIRAEE--SDLKRVNL--RSDRARAVAAEQEASGL-PEMD
FSLRILVLGKTGVGKSATINSIFDQ-TKTETNPFRPGTDRIXEVVGTVNGIRVTIIDTPG
FLXSCTGNFRRNKKIMLSVKKFIRKS-PPD---------IVLFFERLDLMSXNYNDFSLL
KQITEVFGPAVWFNTXLVMTHSSLVLPEGPDGYPVNYESYVRQSTDMVQHYIHQAVSDSR
LE-----NPVLLVENHPQCRK-NIAGEKIL---PNGQVWKSQF------LLLCICTKVLS
------DVNXLMKFQDSIHLGPS------------------NATHMPSLPHLLSSLLRHR
TAIGPXGGD------V--GVDESLVSDA--EDEDEYDQLPPIRILTKSQFERLTKSQKKD
YLDELDY-RETLYLKKQLKEEYRRQMEI---KL------SKEKXTXSDDNSNSQQASQEE
--AVLLPD-MEVPPSFG-SDWPAHRYRCLLT-SDQWI-MRPVLDSHGWDNDVGLDGVSLE
TAMQVN-----RNVFTSVAGQMSKDKQDFSIQSECAAAYL-DP-------NGTAYSVGLD
VQ-S-AGR-DTIYTLHGNTKLRKL--WH-NVAESGFSLTSFGN-------KYYIGGKLED
TISVGK------RLKFVM---NVGQMMGPEQVAY---------GGGVEATLRGRDYPVRN
DNVSLMMTI-LSFN-KEMVLGGNLQSESRLGRNMSVSVNANLN-SRRMGKISIKASSTDH
LQFSMVAAFTIFW----------ALLRKKD--VKSTSDE---------------------
-------------------------------------
>Malus_domestica_gnl|BL_ORD_ID|43752 _0000491236|PACid:22663736
------------M-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------PLV-LPRPLSGSDNFFREES
S-----------------------------------------------------------
-----------NEEFDDQGAAHSNTLVTPRIHPAASTS-------FNS-DQENQSGPS--
LQHAVVENLDHSHNRSGKKKMDPLVRID----DLQVKFLRLLLRLGLSQNNVLV------
---------AKVLYRIHLATLIRAEE--SDLKRVNL--RSDRARTVAAEQEASGL-PEMD
FSLRILVLGKTGVGKSATINSIFDQ-TMTETNAFRPGTNRIREVVGTVNGIRVXIIDTPG
FLPSCTGNFXRNKKIMLSVKKFIRKS-PPD---------IVLFFERLDLMSTSYNDFSLL
KQITEVFGPAVWFNTILVMTHSSLALPEGLDGNPVNYESYVRQSTDMVQHYIHQAVFDSR
IE-----NPVLLVENHLQCRK-NIAGEKIL---PNGQVWKSQF------LLLCICTKVLS
------DVNILMKFQDSIHLGPS------------------NATHVPSLPHLLSSLLRHR
STISPSGGD------V--EVDESLVSYT--QEEDEYDQLPPIRILTKSQFERLTKSQKKD
YLDELDY-RETLYLKKQLKEEYRRQMEV---KL------SKEKNMASGDNSDSQQASQEE
--AVLLPE-MEVPPSFG-SNCPAHRYRCLVT-SDQWI-MRPVLDSHGWDNDVGLDGVSLE
AAMQVN-----RNVFTSVAGQMSKDKQDFSIQSECAAAYL-DH-------SGTTYSVGLD
VQ-S-AGK-DTIYTLHSNTKLRKL--WH-NVAESGFSLTSFGN-------KYYIGGKLED
TISVGK------RLKLVM---NVGQMMGPEQVAY---------GGSVEATLRGRDYPVRN
DNVSLMMTI-LSFN-KEMVLGGNLQSESRLGRDMRVSVNANMN-NRRMGKISIKTSSTDH
LQFSMVAAFTIFW----------ALLRKKD--VKSTVHE---------------------
-------------------------------------
>Prunus_persica_gnl|BL_ORD_ID|27646 _ppa001605m|PACid:17668321
------------M---------GSLKDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------ISSQLVSMSLV-SSRPLSGSDSFFREEP
S-----------------------------------------------------------
-----------HEGFDGQGAAHSNTSLTSPIIPDTSPS-------VGS-DQENQSNPS--
RQHVVVENSDQSRNGSDKKKMDPLVRID----DLQVKFLRLILRLGLSQNNLLV------
---------AKVLYRIHLATLIRAEE--SDLKRVNL--RSDRARAVAAEQEASGL-PEMD
FSLRILVLGKTGVGKSATINSIFDQ-RKTVTNAFRPGTDHIREVVGTINGVRVTIIDTPG
FLPSSTGNFRRNKKIMLSVKRFIRKC-PPD---------IVLFFERLDLINASYNDFSLL
KLITEVFGPAIWFNTILVMTHSSSALPEGPDGYPVSYESYVRQSTDMVQHYIHQAVSDSR
LE-----NPVLLVENHPQCKK-NIIGEKIL---PNGQVWKSQF------LLLCLCTKVLG
------DVNTLMKFEDSIQLGPS------------------SASHMPSLPHLLSSLLRHR
SVVSPSGVD------I--EVDESLLSDT--EEEDEYDQLPPIRILTKSQFERLTKSQKKD
YLDELDY-RETLYLKKQLKEEYRRRMEI---KL------SKEKIFASNDNSDRQQASQES
--AVLLPD-MEVPPSFG-SDCTAHRYRCLVT-GDQWI-MRPVLDPHGWDNDVCFDGISLE
TAMQIN-----SNVFTTVTGQMSKDKQDFSIQSECAAAYS-DP-------SGTTYTVGLD
VQ-S-AGK-DTIYTFHSNTKLKKV--WR-NTADCGVSLTSFGN-------KCYIGAKLED
TISVGK------RLKFVM---NAGQMVGPEQVAY---------GGGIEATLRGRDYPVSN
DNVSLTMTL-LSFN-EEMVLGGNLQSESRLGRNLRVSVNANLN-SRKMGKICIKTSSTDH
LQFSMAAAFTIFW----------ALLQKKA--VKSTSHE---------------------
-------------------------------------
>Glycine_max_gnl|BL_ORD_ID|36196 _13g23110.1|PACid:16291257
------------M---------KGVRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFSQILSKSLV-SPSPLSGSNSLYAGEH
R-----------------------------------------------------------
-----------NENFNEQGH-HLRLVVGLTILRSCREHCDMIHHLAYG------GTGT--
VELVSDTEIYQYQHNTNGRRKDTLAKVE----ELQVKFFRLLQRLGQSQENLLV------
---------AKVLYRMHLATLIRAKE--LDLKRVNH--ISSSARAIASEQEATGM-PQLD
FSCRILVLGKTGVGKSATINSIFGQ-AKTTTGAFQPATNCIQEVVGNVNGLNIAFIDTPG
FLPSSTNNMKRNKRIMLSIKRFIRKS-PPD---------IVLYFERLDFINAGYVDFPLL
KLVTEVFGSAIWFNTIIVMTHSSSAIPEGPDGYTFNYESYVSYCTNMIQLHIQQVVFDSK
VE-----SPVLLVENHSQCPQ-NIMGEKIL---PNGQVWRSQL------LLFCICTKVLG
------DVNSLLKFQNSVGLGPS------------------NSARIPSMPHLLSSLLRHR
PVSNVSGID------D--EIEEILLSD---KEEDEYDQLPSIRVLTKSQFKKLPEPLKKD
YLDEMDY-RETLYLKKQLKEDCRRRKEK---LL------LTDKKFLNSDNPDDQQAP-PE
--PVLLPD-MAVPPSFD-LDCHSHRYRCLVS-DDRLL-VRPVLDPQGWDHDVGFDGINLE
TTTEIK-----KNVYASVVGQMNKNKQDFSIQSECVAAYV-DP-------SGPTYSMGVD
VQ-S-SGK-DFICTVHSNTKLKNI--KH-NIADCGVSLTSFAK-------KYYVGAKLED
TVFVGK------RLKFVL---NAGRMEGAGQMAY---------GGSFEANLRGEDYPVRN
DNVSLTMTV-LSFN-KEMVLSGSLQSEFRLSRSSKASVSANLN-SRKMGQICIKISSSEH
LQIASVAVFSILK----------FLSRRKE--TKNVVRDVMD------------------
-------------------------------------
>Glycine_max_gnl|BL_ORD_ID|46717 _17g11770.1|PACid:16305250
------------M---------KGVRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFSQILSKSLV-SPSPLSASNSLYAGEH
R-----------------------------------------------------------
-----------NGDVNEQGSDHSASSVSSPIPSDSSNS-------SYG-DQSNQHSSS--
LQLVSDTEIYQYQHNTNGRRKDTLAKVE----ELQVKFFRLLQRLGQSRENFLV------
---------AKVLYRMHLASLIRAKE--SDLKRVNH--SSSRARAIASEQEATGM-PQLD
FCCRILVLGKTGVGKSATINSIFGQ-AKTTTGAFQPATNCIQEVVGNVNGLNLTFIDTPG
FLPSSTNNMKRNKRVMLSIKRFIRKS-SPD---------IVLFFERLDFINAGYVDFPLL
KLVTEVFGSAIWFNTIIVMTHSSSAIPEGPDGYTFNYESYISYCTNIVQQHIQQAVFDSK
VE-----NPVLLVENHSRCPQ-NIMGEKIL---PNGQVWRSQL------LLFCICTKVLG
------DVNSLLKFQNSVELGPL------------------NSPRIPSMPHLLSSLLRHR
LVSNLSGTD------D--EIEEILLSDK--KEEDEYDQLPSIRVLTKSQFEKLPEPLKKD
YLDEMDY-RETLYLKKQLKEDYQRRKEK---LL------STDKKFLNGDNPDDQQAP-TE
--PVLLPD-MAVPASFD-SDCHSHRYRCLVS-DDQLL-VRPVLDLQGWDHDVGFDGINLE
TTTEIK-----KNVYASVVGQMNKNKQDFSIQSECTAAYV-DP-------LGPTYSMGVD
VQ-S-SGK-DFICTVHSNTKLKNI--KH-NIADCGVSLTSFVK-------KYYVGAKLED
TVFVGK------RLKFVL---NAGRMEGAGQMAY---------GGSFEANLRGEDYPVRN
DNVSLTMTV-LSFN-KEMVLSGSLQSEFRLSRSSKASVSANLN-SRKMGQICIKISSSEH
LQIASVAILSIWK----------FLSRRKE--TKNLVKEVMD------------------
-------------------------------------
>Phaseolus_vulgaris_gnl|BL_ORD_ID|30638 _091029429m|PACid:23561633
------------M---------KGVRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFSQVLSKSLA-SPSSLSGGNNFYAEEH
RIQ---------------------------------------------------------
-----------NENFNEQGSDHSA---SSAIPSDSSNS-------SNG-DQSNHHSSS--
LQLVSDTEVDHYQDNTNGRRKDTLAKVE----DLQVKFFRLLQRLGQTQENLLV------
---------AKVLYRMHLATLIRTKE--SDLKRVNH--SSSRARAVASEQEAIGV-PQLD
FSCRILVLGKTGVGKSATINSIFGQ-EKTTTGAFQPATNCIQEVVGNVNGINITFIDTPG
FLPSSTNNMKRNKRIMLAIKRFIRKS-PPD---------IVLYFERLDFINAGYVDFPLL
KLVTEVFGSAIWFNTIIVMTHSSSAIPEGPDGYTINYESYISHCTNIIQQHIHQAVFDSR
LE-----NPVLLVENHSQCPK-NIMGEKIL---PNGLVWRSQL------LFFCVCTKVLG
------DVNILLKFQNSVDLGPT------------------SSTRIPSMPHLLSSLLRHH
PISNLSGID------D--EIEEILLSD---NEEEEYDQLPPIRVLTKSQFEMLSEPLQKD
YLDEMDY-RETLFLKKHLKEDYRKRKEK---LL------LTEQKFLNSDNPDDQQAP-PE
--PVLLPD-MAVPASFD-SDCQSHRYRCVVS-DDQWL-LRPVLDPQGWDHDVGFDGINLE
TTTEIK-----KNVNASVVGQMNKNKQDFSIQSECAAAYV-DP-------RAPTYSVGVD
VQ-S-TGK-DFICTVRSNTKLKNI--KH-NIADCGVSLTSFAK-------KYYVGAKLED
TVFVGK------RLKFVL---NAGRMEGAGQMAY---------GGSFEANLLGEDYPVRN
DNVSLTMTV-LSFN-KEMVLSGNLQSEFRLSRSSRASVSANLN-SRKMGQICIKISTSEH
LQFASFAIFSILK----------FLSRRKA--TRNVVKEGMD------------------
-------------------------------------
>Medicago_truncatula_gnl|BL_ORD_ID|51704 _Medtr8g121750.1|PACid:17483355
------------MNMWLCCDAEKGR-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------DKVELLSSTQLCCDEE
K-----------------------------------------------------------
----------------EEMKLSHTHSVALPIPSGTSN--------SSA-NQSNQSSST--
LQQASDAEIYQSQHSGNGRRKDTLAKVE----DLQVKFFRLLQRLGQSKENLLV------
---------AKVLYRMHLATLIRAEE--TDLQRVNL--SSSGAREIANQHEAADM-PQLD
FSCRILVLGKTGVGKSATINSIFDQ-EKATTNAFQPATDCIQEIVGTVNGLNITFIDTPG
FLPSSTNNVKRNKRIMLSVKRFIRKS-PPD---------IVLYFERLDLINSGYSDFPLL
KLITEVFGAAIWFNTILVMTHSSSSIPEGPNGYTVNYDSYTSQCTNLIQQYIHQAILDSR
LE-----NPALFVENHPQCPR-NILGEKIL---PNGQIWRSQL------LLFCICTKVLG
------DVNSLLKFQNGVELGPT------------------NSARVPSLPHLLSSLLRHR
SVSNQSGID------D--EIEEILLSDK--EEGDEYDQLPSIRILTKSQFEKLSKSQKED
YLDELEY-RETLYLKKQMKEEYRRRKEK---LL------LEEQKFSDIDNSDDQQGP-PE
--PVQLPD-MAVPLSFD-SDCAIHRYRCLVD-NDQLL-VRPVLDPQGWDHDVGFDGINLE
TTTEVK-----KNVYASVVGQMHKNKQDFNIQSECAAAYV-NP-------MGPSYSIGVD
VQ-SVGGK-DMVCTVHSNTKLKNI--KH-NIADCGVSLTSFGK-------KYYVGAKLED
TLLIGK------RLKFVI---NAGRMEGQGQVAH---------GGSFEACLRGEDYPIRN
DNLSLTMTV-LSFN-KETVLSGNLQSEFRLSRSLKATVSANLN-SRKMGQICIKTSSSEH
LQIALVAVFSILK----------VLLHRKE--I---------------------------
-------------------------------------
>Cucumis_sativus_gnl|BL_ORD_ID|11606 _132440.1|PACid:16962561
------------M---------KGVRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------LFSQLVSKSVV-SSRPLLGSDGFFGEEN
KEHM--------------------------------------------------------
-----------DENQDDE--VAQATNIVAPTTPHTSD--------SNG-NLENQDDLS--
LAQV-GGDSSQSQHDSNGVKKDVLTKIE----DLQVQFFRLLLRIGQTQNNLLV------
---------EKVLYRIHLATLIQVGE--SDLKRVNL--ERIKARAKAAEQEAAGI-PELN
FTFRILVLGKTGVGKSATINSLFDQ-AKTPTNAFQPATGHIHEIVGTINGIKVSIIDTPG
LSQSSSGNMKRNKKIMFSVKRYIRKS-PPD---------IVLYFDRLDLVNKHHGDYLLM
KLMNEVFGSAIWFNTILVLTHCSSALPEGPDGYPVSFESYVAHCSDVLQQNIYQALSDSK
LD-----NPILLVENHPQCKK-NIMGEKVL---PNGQVWRSHF------LLLCICTKILG
------SINTLLKFQNCIELGPS------------------AISRLPSLPHLLSSFLRHR
SMANTLGVD------N--DFEAILLNDI---DEDDYDDLPSFRILTKSQFKKLSNSLKKE
YLDELDY-RETLYLKKQLREEYQKRKEI---KL------LKDRDLVHNDNNGDLQAM-PE
ADAVLLPD-MAVPPSFD-PDCPVHRYRCIAV-DDQWI-VRPVLDPQGWDHDVGFDGINLE
TAMEMN-----KNVFTSVAGQVSKDKNVFNIQSECAASYM-DS-------RRTSYTLGLD
VQ-S-AGT-DKMYTVHSNAKLGSI--KH-NLPGIGVSLTSFKK-------NCYYGAKLED
TISLGK------RVKFVI---NGGRIEGAGQMAY---------GGSIDATLRGRDYPVRN
DHLRVTMTV-LSFD-KETILGGNVESEFRLSRSMRLSVNTNLN-TRKMGQICIKASSCEH
LQIALVSAFTILR----------ALMRRKE--INTS------------------------
-------------------------------------
>Eucalyptus_grandis_gnl|BL_ORD_ID|8347 _C00581.1|PACid:23570068
------------M---------KSVREW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFSQLLTNSLS-SSRPLSGSDSYFGEAA
------------------------------------------------------------
-----------NEGPHEQ--AHADSLEVSQASIDQSAS-------SNG-TLESQHYPS--
QRQGLVENCSQSHSSSDRGKSNPMSKIN----DLQIKFLRILQRLGHQQDNLLA------
---------AKVLYRVQLATLIQSGE--ADPKVLKH--MHDKARAQAAQEEAAGV-PELD
FSFKVLVLGRTGVGKSATINSIFDQ-TKVVTNAFQPATDSIREVTGTVGGMKITFVDTPG
LCPSSTANMRRNRKILLSVKKYIRKS-PPD---------IVLFFERLDLINVNYSDFPLL
KLLSEVFGNAIWFNTILVMTHASCSLPEGPNGYPVVYESYVGQCANLIQSYIHLAVSDSK
IE-----NPVLLVENHSQCRK-NLLGEKVL---PNGQVWKSHF------LLLCVCMKVLS
------DANKFLEFRDSIALGPP------------------NAKRQPSLPHLLSSLLRHR
PSPSTGGAD------Y--EMDDSILSDT--EEEDEYDQLPPIKILSRSQFEKLTKSQKKD
YLDELDY-RETLYMKKQLREELQRQRELREDKL------LRKENSDYNDSSDNQETS-SE
--PFLLPD-MAVPPSFD-SDCPLHRYRGLVT-GEQLI-VRPVLDPHGWDHDVGFDGINLE
TSIETK-----SNVYALVTGQMSKEKNDFSIHSECSAVYN-ST-------SGPSYTLGLD
VQ-S-AGK-DLMYTMHSNTRLNNL--KH-NIAECGLSLTRFGD-------KCYTGAKIED
TMHIGR------RVKLVV---NAGRLGAAEQVAY---------GGSFEATVRGRDYPVRT
DSISLSMTV-LSFD-KETVLSGGLQSEFRLSRDTKVMINGNLN-SRKMGQLFLKTSSSEH
MEIALIALVSIIR----------GLFRRKN--TENVGTGSLESG----------------
-------------------------------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|24265 _910069|PACid:16058012
------------M---------KGFKDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFA--LSNSMA-SSRPLLGSDPFFRD--
------------------------------------------------------------
-----------SQEQDNQ--SQVPAAPEPVTSLEAPCS-------TSG-DVEIQPPLS--
QQQVPLESLYQSSIDLNGKKHNPLAKIG----DLQVQFLRLVQRFGQSQNNILV------
---------SKVLYRVHLALLIRAEE--SELKTVKL--RQDRAKALAREQELSGT-PELD
FSLRILILGKTGVGKSATINSIFGQ-SKSETDAFRPATDRIEEVMGTVNGVKVTFIDTPG
FHPLSSSSTRKNRKILLSIKRYVKKR-PPD---------VVLYLDRLDMIDMRYSDFSLL
QLISEILGAAIWLNTILVMTHSSTT-TEGRNGQSVNYESYVGQRMDVVQHYIHQAVSDTK
LE-----NPVLLVENHPSCKK-NLAGEYVL---PNGLVWKPQF------MFLCVCTKVLG
------DVQSLLRFRDSIGLGQP------------------SSTRTASLPHLLSVFLRRR
LSAGADEAE------K--EIDELLNLDL--EEEVEYDQLPTIRILGKSRFEKLSKSQKKE
YLDELDY-RETLYLKKQLKEECRRRRDE---KL------IDEENL-----NDTEQSD-QA
--AVPLPD-MAGPDSFD-SDFPAHRYRCVAA-GDQWL-VRPVYDPQGWDRDVGFDGINIE
TAAKIK-----RNLFASATGQVSRDKQRFTIQSETNAAYTRNS-------REQTFSVAVD
LQ-S-SGE-DLVYSFQGGTKLQTF--KH-NTTDLGVGLTSFGG-------KYYVGGKLED
TLLVGK------RVKLTV---NAGQMRGSGQTAH---------GGSFEACIRGRDYPVRN
EQICLTMTA-LSFN-RELVLNYGLQTQLRPARGTNIDVNINMN-NRKMGKINVKLNSAEH
WEIALISALTMFK----------ALVRRRK--SEMTKENEEEEL----------------
-------------------------------------
>Toc90_gi|75291915|sp|Q6S5G3.1|TOC90_ARATH RecName: Full=Translocase of chloroplast 90, chloroplastic; Short=AtToc90; AltName: Full=90 kDa chloroplast outer envelope protein; AltName: Full=Plastid protein import 4
------------M---------KGFKDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFA--LSNSMA-SSRPLLGSDPFFRDP-
------------------------------------------------------------
-----------HQEQDNH--SQAPAAPQPVTLSEPPCS-------TSS-DLEILPPLS--
QQQVPLESLYQSSIDLNGKKHNPLAKIG----GLQVQFLRLVQRFGQSQNNILV------
---------SKVLYRVHLAMLIRAEE--SELKNVKL--RQDRAKALAREQESSGI-PELD
FSLRILVLGKTGVGKSATINSIFGQ-PKSETDAFRPGTDRIEEVMGTVSGVKVTFIDTPG
FHPLSSSSTRKNRKILLSIKRYVKKR-PPD---------VVLYLDRLDMIDMRYSDFSLL
QLITEIFGAAIWLNTILVMTHSAAT-TEGRNGQSVNYESYVGQRMDVVQHYIHQAVSDTK
LE-----NPVLLVENHPSCKK-NLAGEYVL---PNGVVWKPQF------MFLCVCTKVLG
------DVQSLLRFRDSIGLGQP------------------SSTRTASLPHLLSVFLRRR
LSSGADETE------K--EIDKLLNLDL--EEEDEYDQLPTIRILGKSRFEKLSKSQKKE
YLDELDY-RETLYLKKQLKEECRRRRDE---KL------VEEENL-----EDTEQRD-QA
--AVPLPD-MAGPDSFD-SDFPAHRYRCVSA-GDQWL-VRPVYDPQGWDRDVGFDGINIE
TAAKIN-----RNLFASATGQVSRDKQRFTIQSETNAAYTRNF-------REQTFSVAVD
LQ-S-SGE-DLVYSFQGGTKLQTF--KH-NTTDVGVGLTSFGG-------KYYVGGKLED
TLLVGK------RVKLTA---NAGQMRGSGQTAN---------GGSFEACIRGRDYPVRN
EQIGLTMTA-LSFK-RELVLNYGLQTQFRPARGTNIDVNINMN-NRKMGKINVKLNSSEH
WEIALISALTMFK----------ALVRRSK--TEMTEENEEEKIVNFLVS----------
-------------------------------------
>Capsella_rubella_gnl|BL_ORD_ID|24005 _v10000266m|PACid:20909811
------------M---------KGFKDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFA--LSNSMA-SSRPLLGSDPFFRD--
------------------------------------------------------------
-----------RQEQDNQ--SQEPAVPEPVTRSETPCS-------TTA-DVETPPPLS--
QQQIPLESLYQSSIDLNGKKHNPLAKIG----DLQVQFFRLVQRFGQSQNNILV------
---------SKVLYRVHLAMLIRAEE--SELKTVKL--RQDRAKALAREQESSGI-PELD
FSLRILVLGKTGVGKSATINSIFGQ-PKSETDAFRPATDRIEEVMGTVNGVNVTFIDTPG
FHPLSSSSTRKNRKILLSIKRYVKKR-PPD---------VVLYLDRLDMIDIRYSDFSLL
QLITEILGAAIWLNTILVMTHCSTP-TEGRNGQSMNYESYVGQRMDVVQHYIHQAVSDTK
LE-----NPVLLVENHLSCKK-NLAGEYVL---PNGLVWKPQF------MFLCVCTKVLG
------DVQSLLRFRDGSGLGQP------------------SSTRTASLPHLLSIFLRRR
LSSGVDEAE------K--EIDELLNSDV--EEEDEYDQLPTIRILGKSRFEKLSKTQKKD
YLDELDY-RETLYLKKQLKEEFRRRRDE---KL------TEEENP-----NDTEQND-QA
--AVPLPD-MAGPDSFD-SDFPAHRYRCVAA-GDQWL-VRPVYDPQGWDRDVGFDGINIE
TAAKIE-----KKLFASATGQVSRDKHHFTIQSETNAGYTRRS-------GEQAFSVAVD
LQ-S-SGE-DLVYSFQGGTKLQTF--KH-NTTDLGFGLTSFGG-------KYYLGGKLED
TLLVGK------RVKLTV---NAGQMRGSGQTAH---------GGSLEACIRGRDYPVRN
EQIGLTMTA-LSFN-QELVLNWGLQTQLRPARGTNIDVNINMN-NRKMGKIHVKLNSSEH
WEIALISALTMFK----------ALLRRRK--SEMTKENEEEES----------------
-------------------------------------
>Thellungiella_halophila_gnl|BL_ORD_ID|25456 _Thhalv10012730m|PACid:20205134
------------M---------KGFKDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFA--LTNSMA-SSRPLMGSDPFFRE--
------------------------------------------------------------
-----------NEEQDNQ--SQAPVLPEPVARSETPCS-------TSG-DVEIQLPLS--
QQQVPLESLYQSSFDLNEKKHNPLARIG----DLQVQFLRLVQRFGQSQSNILV------
---------SKVLYRVHLAMLIRAEE--SELKTVKL--RQDRAKALAREQESRGI-PELD
FSLRILVLGKTGVGKSATINSIFGQ-SKSETDAFRPTTDRIEEVMGTVSGVKVTFIDTPG
FQPPSASSTRKNRKILLSIKRYVKKR-PPD---------VVLYLDRLDMIDMRYSDFPLL
KLISEILGAAIWLNTILVMTHSSIA-SEGRNGQSVNYETYVGQRMDVVQHYIHQAVSDTK
LE-----NPVLLVENHPSCKK-NPAGEHVL---PNGLVWKPQF------MFLCVCTKVLG
------DVQSLLRFRDSIGLGQP------------------ISTRTASLPHLLTLFLRRR
LSSGADEAE------K--EIDELLSSEL--EEEDEYDQLPAIRILGKSRFEKLSKSQKKE
YLDELDY-RETLYLKKQLKEECRRRRDE---KL------VEEENV----NNDTEQSD-QA
--AVPLPD-MAGPDSFD-SDFPAHRYRCIVT-SDQWL-VRPVYDPQGWDRDVGFDGINIE
TAAKVK-----RNLFASATGQVSRDKQRFTIQSETNAAYTTDS-------REQTFSVAVD
LQ-S-SGE-DLVYSFQGGTKLKTF--KH-NTTDLGVALTSFGG-------KYYMGGKLED
TLLVGK------RVKLTV---NAGQMKGSGQTAH---------GGSFEACIRGSDYPVRN
EQIGLTMTA-LSFN-QELVLNWGLQTQLRPNRDTNIDVNINMN-NRKMGKINVKLNSSEH
WEIALISAFTIFK----------ALLRRKKVVSEITKENEEEL-----------------
-------------------------------------
>Brassica_rapa_gnl|BL_ORD_ID|8882 _002291|PACid:22692392
------------M---------KGFIDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFD--LSNSMASSSRPLLGTAPFSRH--
------------------------------------------------------------
-----------HEPHDSH--SQAPALPEPVARSEPPCS-------TSV-DVEAHPPIS--
QQQTPLESLHQSSLDLNDKKHNPLAKIG----DLQVQFLRLVHRFGQSQNNILV------
---------SKVLYRVHLAMLIRAEE--SELKTVKL--KQDKAKTLAKEQESSGV-PELD
FSLRILVLGKTGVGKSATINSILGQ-SKSETDAFQPATDRIEEVNGTVSGVKVTFIDTPG
LHQPSPSSARKNRKTLLSIKRYVKKR-PPD---------VVLYLDRLDTIDLRYSDYPLL
SLITEVLGAALWLNTILVMTHSSVA-SEGRN---MNYESYVGQRVDVVQHYIHQAVSDTK
LE-----NPVLLVENHPSCRK-NHAGECVL---PNGLVWKPQF------MFLCVCTKVLG
------DVQSLLRFRDSIGLGQA------------------SGTRTASLPHLLSVFLRRR
LSSGGDEAE------R--EIDELMDSELEEEEEDEYDQLPAIRILGKARFEKLSKSQKRE
YLDELDY-RETLYLKKQLKEECRRRKDE---KL------NEEEE---------EKSD-QA
--AVPLPE-MAGPDSFD-SDFPSHRYRSIAT-SDQWL-VRPVYDPQGWDHDVGFDGINIE
TAVKVK-----KNLFASANGQVSRDKQRFTIHSETNAAYTTDS-------RIQTFSVAAD
VQ-S-SGD-DLVYTFHGGTKLKTF--KQ-NTTDLGVGLTSFGG-------KYYLAGKIED
SLLVGK------RVKLTV---NAGQMKGSGETAH---------GGSFEACIRGRDYPVRN
EQIGVTVTA-LSFK-KELVLNWGLQTQVRPTRDTNVDVSVNMN-NRKMGKINVKLNSSEH
WEIALISAFTLFK----------ALVRRKKAVSEITNENEEEL-----------------
-------------------------------------
>Mimulus_guttatus_gnl|BL_ORD_ID|666 _mgv1a001816m|PACid:17670058
------------M---------TSIKDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFSQVISNSIG-STRPLSASDSFLSQEP
Q-----------------------------------------------------------
-----------NEELGNRVSTEIPSP-------------------SSD-NQITQNPLP--
PQ---VENSSGSNVITEEKHTDPLAKVE----ALQITFLRLLRRFALFQDDLTV------
---------AKVLYRIHLATLIRAGE--SDLKRANL--KIGRARVIAAEQEETGV-PQLD
FSLKILV----------------------TTNAFRPATDRVQEIVGLVNGIKISFIDTPG
LFPSSTNSDRKNRKILHSVKRFIQKS-HPD---------VILYFERLDLISMGNHDFPLL
KLITDVLGPAIWFSTNIVMTHSSAALPEGQNGYPVSFDSYVSHCTQVLQHHIHQSILDTK
LE-----NPVILVENHRHCKM-DNSGKKVL---RNGQLWMSQF------MLFCICTKILG
------DVNTLLELEDSMQLGPS------------------RNSRLPSLPHLLSSFLKHR
VKLSSNGAD------N--ETDELSFSDT--EEEDEYDQLPPIRILTKSQFKKLSPSQEKD
YLDELDY-RETLYMKKQLKQEYMARKEK-----------------APDDNIESQEGP-PE
--PIMLPD-MSVPPSFD-SDNPVHRFRCLVT-SDRWL-ARPVLDPHGWDHDVGFDGINLE
IAAQLG-----KDIITCVAGQMSKDKQDFNIQCESTAAYV-AP-------SGPTYSVGLD
VQ-S-AGK-ELICSVRSNAKVKTH--KY-NVAECGVSVMSFGN-------QYYYCGKIED
SISIKK------RVDLKT---NGGVISGSGQFGY---------SGSFEATLKGKDYPVRE
DKTSLSVSL-LSFK-KETVLGGNIQSDFRLGRGTRMSINANLN-SRNMGQVCVRMNSSEH
MEIALVAVVSLLR----------ALFRKKS--NNNFSSSETTETG---------------
-------------------------------------
>Carica_papaya_gnl|BL_ORD_ID|16307 _evm.model.supercontig_46.61|PACid:16420529
------------M---------KGVRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VFSQMVSKSVA-SSRPLSGSGSYFHEGP
P-----------------------------------------------------------
-----------DVESDSQSPTQTASMIASSMPRNTLYS-------SSS-NRENQTHPP--
LQEVPPEQS--SRDGVVERKMDPLAKIE----DLQVKFLRLVQRLGQSEGNLLV------
---------AKVLYRIHLATLIRAGE--SDLKSVSI--RSDRARAIAREKEATGV-PDLN
FPFRILVLGKTGVGKSATINSIFDQ-IKTETDAFQPATDCIQEVVGTVSGIRITFIDTPG
FLPPCTSNMKRNRKIMLSVKKFIRRS-PPD---------LVLYFERLDLVSMGYSDLHLL
KLMTEVFGTAIWFNTILVMTHSSSTPPERTK-----------------------------
--------------------------------------WIS-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------SLN
VQ-S-AES-DLIYTVHSNTKWKNL--KY-NITDCGVSLTSFRD-------KYYVGTKLED
TVLAGK------RLKFMM---NVGQMVGHGQAAY---------GGSFEATLRGKDYPVRN
DYVSLTTTA-LSLD-KEMVLGGGFQSEFCPFRGTRLSVNANLN-SRKMGQICVKVSSSEH
LEIAFFAAISLLK----------ALFRRKG--IEDRSIEALEQ-----------------
-------------------------------------
>Linum_usitatissimum_gnl|BL_ORD_ID|32806 _10006471|PACid:23171986
------------M-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------PSFSLA-----------------
------------------------------------------------------------
---------------DLP---------------------------ANS-EAASAPDAS--
PQQVVEASSQPSTHHIKERDTHPLENVE----HLKINFFRLLRRFGLPMESALV------
---------AKVLYRIHIATSIRGEL----PKRV----RNINAKTIAAAQEGSGV-PELN
FSVRILVLGKTGVGKSATINSILDQ-RATITSAFQPATNRVQEVTGTLNGVRVTFIDTPG
FLPHSGSGIRQNLKIMRSVKRFIRKS-PPD---------IVLFVERLDHLNTGYSDFLLL
QLMTDVFGDAIWFNTMIIMTHASSSLPEGSTGGPVSYESYVSRCSQMMQHYIHEAVSDTT
LQ-----NLVVVVENHPQCEK-NSNGDAIL---PNGQVWRSQF------LLFCICTKVLG
------DASNILELKNCVELGPK------------------TRPQVLSLPRLLSWLIKNK
AVSGPTPDG------H--DLDEIVVVDE--DEEDEYDQLPPIRILTKSQVAKLSKSQKND
YLDELDY-REMVYMKKQLKEESRSRREN---ML------FGKASYEEFDNSEATNAS-PE
--TVLLPD-MAVPPSFD-SDCPVHRYRCLVAIGDQLL-TRPVLDPRGWDHDVGFDTVDLE
TAIEMK-----KNLCASVSGQINKDKNNFSIQSECAVTYA-DL-------KGPTYSAGLN
VQ-S-AGK-DLVYTIHGNTRSKIF--AHNNVADCGVSLTSSCR-------KCYLGAKLEN
SVLVGK------RLKLLI---NGGQMRGAGEVAN---------GGSVEATILGTDYPMRN
DKASLSLTA-LSFN-KETVVSGGVESEFQLIRGTRVAVNANLN-SLNMGKVGIKVSSSEH
LEIAVIAALTIFS----------AIFRKRV--ANTSPDVSETGEFPVVS-----------
-------------------------------------
>Linum_usitatissimum_gnl|BL_ORD_ID|12132 _10027712|PACid:23151312
------------M-------------DW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------SLPNWFSKSLA-SLSPVTFYESPPSDHH
S-----------------------------------------------------------
-----------DDDRDLT---------------------------ANS-EALSPPDAS--
PQQVVEASSQPSTHHTEERDTHPLENIE----HLKINFFRLLRRFGLPMDSPLV------
---------AKVLYRLHIAISIRGEL----PKRV----RNINALTITAAQEGSGV-PELD
FSVRILVLGKTGVGKSATINSILDQ-RATVTSAFQPATDRVQEVIGTLYGVRVTFIDTPG
FLPHSGSGIRRNLKIMRSVKRFIRES-PPD---------IVLFVERLDHLNTGYSDFPLL
QLMTDVFGDAIWFNTMIIMTHASSSLPEGSIGGPVSYESHVSRCSQMMQHYIHEAVSDTT
LQ-----NLVVVVENHPQCDK-NSNGDAIL---PNGQVWRSQF------LLSCICTKVLG
------DASNILELKNSIELGPK------------------TRPQVLSLPRLLSWLIKNK
AVSGPTPDG------H--DLDEIILVDE--DEEDEYDHLPPIRILTKSQFAKLSKSQKND
YLDELDY-REMVYMKKQLKEESRSRREK---ML------LGKASYEEFDKSEATNAP-PE
--TVLLPD-MAVPPSFD-SDCPVHRYRCLIEIGDQLL-TRPVLDPRGWDHDVGFDTIDLE
TAIEMK-----KNLCASYSGQINKDKNNFSIQSECAVTYA-DL-------KGPTYSAGLN
VQ-K-AGKDDLVYTIHGNTRSKIF--TNNNVADCGVSVTSSCN-------KCYLGAKLEN
SVLVGK------RLKLLI---NGGQMRGPGQVVN---------GGSLEATILGTDYPMRN
DKVSLSLTA-LSFN-KETVVSGGVESEFQLMRGTRVAVNANLN-SLHMGKVGIKASSSEH
LEIAVIAALTIFS----------AIFRKRV--ANTSPDVSETR-----------------
-------------------------------------
>Linum_usitatissimum_gnl|BL_ORD_ID|37184 _10004619|PACid:23176364
------------M-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------PSFSLA-----------------
------------------------------------------------------------
---------------DLP---------------------------ANS-EAASAPDAS--
PQQVVEASSQPSTHHIKERDTHPLENVE----HLKINFFRLLRRIGLPMESALV------
---------AKVLYRIHIATSIRGEL----PKRV----RNINAKTIAAAQEGSGA-PELD
FSVRILVLGKTGVGKSATINS-------TITSAFQPATNRVQEVTGTLNGVRVTFVDTPG
FLPHSGSGIRRNLKIMRSVKRFISESPPPD---------IVLFVERLDHLNTGYSDSLLL
QLMTDVFGDAIWFNTMIIMTHASSSLPEGSTGGPVSYESYVSRCSQMM------------
---------------------------------LFGLMFRSY------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------KH--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>Brachypodium_distachyon_gnl|BL_ORD_ID|8838 _4g40530.1|PACid:21811608
-----------MM---------LNFRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ISYRLGSSLL-SARPFAISGPGAG---
A-----------------------------------------------------------
-----------SEGGVNDGTTESEFVETVSANRFP----------SND-SHAASAVTS--
NSQDGAVSSGPLHPDHDNSKPDPLMQVE----ALQIKFLRLVHRTGVPPNTNVV------
---------AQVLYRLQLANLIKAGE--SDARRTNL--AMNKARVIAAEHEAPGG-PDLD
LPLRVLLLGKTGVGKSATVNSIFDE-TKVATDALAPATNRIKMVDGTIKGVRVTVIDTPG
LTP-HYHSQRRNRKILHAVKRFIKRS-PPD---------IVLYFERIDHINSKYSDYPLL
KLITDILGSSIWFNTVLVMTHCSSSPPEGPDGYPLEYDAYTRYCKNVVQRQIQVAASNTQ
LE-----NPIVLVDNHPLCRR-NTRGERVL---PNGQVWVSEL------LLFCGATKLLA
------DANSLLKFQDSFLLSH-------------------ANTRLPSLPHLLSSLLKPY
PSSSYDSID------N--EMTDLS------DEEDEYDQLPPFRVLKKSEYEKLTKEQKTA
YLDELDY-RETSYLKHQWKEGIRRQKLA---EA------QSTEASYGVADDYEESTA-PE
--VVHMSD-MEIPLNFD-SDYPAHRYRHLIT-NDQ-L-FRPVLDPQGWDHDIGFDGINFE
SSHELK-----RNISSSIAGQMRKDKEDMYIQSECSVSYT-DQ-------RGYSLMGGMD
MQ-T-ASK-DLVCTVHGDAKYRNF--PW-NTTGGGISVTKFGS-------KYFSGAKLED
SIIIGK------RVQLVA---NAGRMVGCGQVAD---------GGGLEVTVRGKDYPVRE
GSTTIAATA-LSFE-KDTVISANLQSVFRVGRGSKLSVSANIN-NRKLGRLSVKTSTSDH
VEIALLAAVSLIQ----------FLLRRRS--PPTDKGDQQFDTDSLEE-----------
-------------------------------------
>Panucum_virgatum_gnl|BL_ORD_ID|1972 _Pavirv00014117m|PACid:23757692
------------M---------MNFRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------LSFRLGSSLL-SARPFALS-AGDDDR-
A-----------------------------------------------------------
------------SDGDADGTTQNEFVETVSANRFP----------SND-TR-VSEVTT--
---SGAVYPAPVQQDNDNKKSDPLMKVE----ALQIKFLRLVHRTGVPPSTDVV------
---------VQVLYRLQLANLIKAGE--SGARRTNL--AINKARVIAAQQEAPGG-PDLD
LPLRILLLGKTGVGKSATINSIFDE-RKVSTDALVPATHRINKTEGIIKGIRVTVIDTPG
LMP-HYLGQRRNKKILNSVKRYIKRS-PPD---------IVLYFERLDHINSRYSDYPLL
KLMTDILGSSMWFNTVLVMTHCSSSPPEGPDGYPLEYDAYTRYCKNVVQRHIQAVVSNTQ
LD-----NPVVLVDNHPMCRR-NTKGERVL---PNGQVWVSEL------LLLCGATKLLA
------EANSLLKFQDSFVLSQ-------------------ANNRLPSLPHLLSSLLKPN
SSSSSDSID------S--ELTEMS------DEEDEYDQLPPFRILKKSEYENLTNDQKSA
YLDELDY-RETLYLKKQWKEGIRRQKLT---EV------QNDE----VADDYEEGAS-PE
--VVHMSD-MEIPLSFD-SDYPVHRYRHIIT-DDQ-M-FRPVLDPQGWDHDIGFDAINFE
ASQELK-----KNVSAGIVGQMRKDKEDMYVNSECSVSYS-DQ-------RGCSLIGGMD
MQ-T-ASK-DLLCTVHGDAKFRNL--PW-NTTGGGISVTKFGN-------KYFAGAKLED
SVTIGK------RVKLVA---NAGRMAGCGQVAH---------GGGMEIIAWGKDYPVRE
ESIAFSVTA-LSFE-KDTVIGANVQSDFRVGRGSKMSVGANLN-SRNLGKLSIKTSTSDH
AEIALIAVVSLIQ----------F-FRRRS--GAADKGDQQFDTN-QDD-----------
-------------------------------------
>Panucum_virgatum_gnl|BL_ORD_ID|31706 _Pavirv00001536m|PACid:23787757
------------M---------MNFRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ISFRLGSSLL-SARPFALS-SGDDDG-
A-----------------------------------------------------------
------------SQGDADGTTQNEFVETVSANRFP----------SND-TR-MSEVTT--
NFNGGAVYPAPVQQDNDNKKSDPLMKVE----ALQIKFLRLVHRTGVPPSTDVV------
---------VQVLYRLQLANLIKAGE--SGARRTNL--AINKARVIAAQQEAPGG-PDLD
LPLRILLLGKTGVGKSATINSIFDE-RKVPTDALVPATHRIKKIEGTIKGIRVTVIDTPG
LMP-HYLGQRRNRKILNSVQRYIKRS-PPD---------IVLYFERLDHINSRYSDYPQL
KLMTDILGSSMWFNTVLVMTHCSSSPPEGPDGYPLEYDTYTRYCKSVVQQHIQAAVSNTQ
LD-----NPVVLVDNHPMCRR-NTKGERVL---PNGQVWVSEL------LLLCGATKLLA
------EANSLLKFQDSFVLSQ-------------------ANNRLPSLPHLLSSLLKPN
SSSSSDGID------S--ELTEMS------DEEDEYDQLPPFRILKKSEYENLTNEQKSA
YLDELDY-RETLYLKKQWKEGIRRQKLT---EV------QNDE----VADDYEEGAS-PE
--VVHMSD-MEIPLSFD-SDYHVHRYRHIIT-DDQ-L-FRPVLDPQGWDHDIGFDAINFE
ASQELK-----KNVSAGIAGQMRKDKEDMYINSECSVSYS-DQ-------RGCSLIGGMD
MQ-T-ASR-DFLCTVHGDAKFRNL--PW-NTTGGVISVTKFGN-------KYFAGAKLED
SVTIGK------RVQLVA---NAGRIAGCGQVAH---------GGGMEITARGKDYPVRE
ESVTFSVTA-LSFE-KETVIGANLQSDFRVGRGSKMSVGANLN-SRYLGKLSIKTSTSDH
AEIALIAVVSLIQ----------F-FRRGS--GAADKGDQQFDTY-LDD-----------
-------------------------------------
>Setaria_italica_gnl|BL_ORD_ID|21382 _Si009414m|PACid:19694856
------------M---------MNFRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ISYRLGSSLL-SARPFALS-SGADAA-
A-----------------------------------------------------------
------------SEGDADG-AHNEVVETVSANRFP----------SND-SR-ASEVTT--
--GSGATYPGLVQQDEDNKKSDPLMKVE----ALQIKFLRLVYRTGVPPTTDVV------
---------AQVLYRLQLANLIKAGE--SDARRTNL--AINKARVIAAQQEAPGG-PDLD
LSLRILLLGKTGVGKSATINSIFDE-RKVATDALVPATHRIKKIEGTIKGIRVTVIDTPG
LIP-HYHGQRRNRKILNSVKRFIKRS-PPD---------IVLYFERLDHINSRYSDYPLL
KLMTDILGSSMWFNTVLVMTHCSSSPPEGPDGYPLEYDAYTRYCKNVVQRHIQAAVSNTQ
LD-----NPVVLVDNHPMCRR-NTKGERVL---PNGQVWVSEL------LLLCGATKLLA
------EANSLLKFQDSFLLSP-------------------ANNRLPSLPHLLSTLLKPN
SSSSSDRID------G--ELTETS------DEEDEYDQLPPFRILKKSEYEKLTNEQKSA
YLDELDY-RETLYLKKQWKEGIRRQRLT---EA------QNDE----VADDYEESAS-PE
--VVHMSD-MEIPLTFD-SDYPVHRYRHIIT-DDQ-L-FRPVLDPQGWDHDIGFDAINFE
ASQELK-----KNVSATIAGQMRKDKEDMYIHSECSVSYS-DQ-------KGCSLMGGMD
MQ-T-ASR-DLVCTVHGDAKFRNL--RW-NTTGGGISVTKFGN-------KYFAGAKLED
SVTIGK------RVQLIA---NAGRMAGCGQVAH---------GGGVEITARGKDYPVRE
ESITVSVTA-LSFD-KETVIGANLHSDFRLGRGSKMSVGAKLN-SSNLGKLSIRTSTSDH
AEIALIAVVSLIQ----------F-FRRRS--GAADKGEQQFDTY-LDD-----------
-------------------------------------
>Sorghum_bicolor_gnl|BL_ORD_ID|23631 _Sb08g006190.1|PACid:1977861
-----------ML---------MNFRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ISYRLGSSLL-SARPFALS-PGADDAV
A-----------------------------------------------------------
------------SEGDAHGTTHNDYVDTVTASPFS----------SND-TR-VSDVTT--
NSNGGAIYSGTVQQDDDNKKSDPLMKVE----ALQIKFLRLVYRTGVSPSADVV------
---------AQVLYRLQLANLIKAGE--SVARRPNL--AINKARVIAAQQEAPGG-PDLD
VSLRILLLGKTGVGKSAMINSIFDE-RKVATDALVPATHRIKKIEGTIKGIRVTVIDTPG
LMP-HYHGERRNRKILSSVKRFIKRS-PPD---------IVLYFERLDHINSRYNDYPLL
KLMTDILGSSMWFDTVLVMTHCSSSPPEGPDGYPLEYDNYTRYCKNVVQRHIQAAVSNMQ
LD-----NPFVLTDNHPMCRR-NTKGERVL---PNGQVWVSEL------LLLCGATKLLT
------EANSLLKFQDSFLLSQ-------------------ANTRLPSLPHLLSSLLKPH
SSSSSDAID------S--EFTEMS------DEEDEYDQLPPFRILKKSEYENLTNEQKSA
YLDELDY-RETLYLKKQWKEGIRKQKLT---EA------QNDE----VGDDYEESAS-PE
--VVHMSD-MDIPLCFD-SDYPVHRYRHIIT-DDQ-L-FRPVLDPQGWDHDIGFDAINFE
ASKELK-----KNVSGAITGQMRKDKEDMYIHSECSVSYN-AH-------RGCSLMGGMD
MQ-M-ASR-DLVCTVHGDAQFRNL--PW-NTTGGGISVTKFGN-------KYFAGAKLED
SVTIGK------RVKLVA---NAGRMAGCGQVAH---------GGGVQITARGKDYPVRE
ESVTAAVSA-LSFE-KETVIGANLQSDFRVGRGSKISVSANLN-SRNLGKLSVRTSTSDH
AEIALIAVVSLIQ----------FILRRRS--AAADKGEQEIDDTYLDD-----------
-------------------------------------
>Zea_mays_gnl|BL_ORD_ID|3368 _GRMZM2G100579_T02|PACid:20823094
-----------ML---------MNFRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ISYRLGSSLL-SARPFALS-PGADDG-
A-----------------------------------------------------------
------------SEGDAHGTAHNDFVDTVTANTFS----------SND-MR-ASEVTA--
NSGSGAIYSGIVQQDDDNKKSDPLMKVE----ALQIKFLRLVYRTGVSPSADVV------
---------AQVLYRLQLANLIKASE--SDARRTNL--AINKARVIAAQQEAPGG-PDLD
VSMQILLLGKSGVGKSATINSIFDE-RKVATDALVPATHRIKKIEGTIKGIRVTVIDTPG
LVS-HYHGQRRNMKILNSVKHFIKRS-PPD---------IILYFERLDHINSRYSDYPLL
KLMTDILGSPMWFNTVLVMTHCSSSPPEGPDGYPLEYDTYTRYCKNVVQRHIQAAVSNTQ
LD-----NPFVLIDNHPMCRR-NTKGERVL---PNGQVWVSEL------LLLCGATKLLT
------EANSLLKFQDSFLLSQ-------------------ANTRLPSLPHLLSSLLKPH
SSSSSDAID------S--QLTEMS------DEEDEYDQLPPFRILKKSEYENLTNEQKSA
YLDELDY-RETLYLKKQWKEGIRRKKLT---EA------QSDE----VGDDYDESAS-PE
--IVHMSD-MDIPLSFD-SDYPVHRYRHIIT-DDQ-L-FRPVLDPQGWDHDIGFDAINFE
ASQELK-----KNVSAAITGQMRKDKEDMYIHSECSVSYN-AQ-------RGCSLMGGMD
MQ-T-ASK-DLVCTVHGDAKFHNL--PW-NSIGGGISVTKFGN-------KYFAGAKLED
SVTIGR------RVKLVA---NAGRMSGCGQVAH---------GGGVEITARGKDYPVRE
GSVTAAVSA-LSFE-KETVIGANLQSDFRVGRGSKISVSANLN-SRNLGNLSVRTSTSDH
AEIALITVVSLIQ----------FILRRRS--AADNKDEQQIGTN-LDD-----------
-------------------------------------
>Oryza_sativa_gnl|BL_ORD_ID|55936 _LOC_Os12g09570.2|PACid:21938408
------------M---------MSFRDW--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ISYRLGSSVL-SARPFSLS-AHHDGAA
A-----------------------------------------------------------
-----------QPGGDGDGVMQNEIVETVSANRFP----------SND-IR-ASDSEV--
TS------SPSYEPDHDSTKSDPLKHVE----ALQIKFLRLVHRTGVPPTTDVV------
---------AQVLYRLHLANLIKAGE--SDSKRTNL--AINKARVIAAEQEAPGG-PDLD
LPLRILLLGKTGVGKSATINSIFDE-PKVATNALAPATERIRRIDGTIKGIRVTVIDTPG
LLP-HYHRQRKNRKILHAVKRFIKRS-PPD---------IVLYFERLDHINSRYCEYPLL
KLITDILGSSMWFNTVLVMTHCSSSPPEGPDGYPLEYDSYARYCKNVVQRHIQVAASNTQ
ME-----NPVVLVDNHPMCRR-NTKGERVL---PNGKVWVSEL------LLLCGATKLLA
------EANSLLKFQDSFLLSQ-------------------ANTRLPSLPHLLSSLLKPN
PSSRSEDVG------I--DMTEVS------DDEDESDQLPPFRVLKKSEYEKLSKEQRSA
YLDELDY-RETLYLKKQWKEGIRRQKLV---EA------QNVDASNAVGDDYEESVS-PE
--VVHMSD-MEIPSSFD-SDYPVHRYRYLIT-DDM-V-FRPVLDPQGWDHDIGFDGINFE
VSQDLE-----KNTTASIAGQMRKDKEDLYIQSECSVSYS-GK-------NGRSLIGSMN
MQ-T-ANK-DLVCTVNGDARFHNL--PW-NTTGGGISITKFGS-------KYFTGAKLED
SITVGR------RVQLVG---NAGRMVGCGQVAH---------GGGLEMTFRGKDYPVRE
ESITVAATA-LSFE-KETVISTNLQSDFRMGRGSKVSVSANLN-SRNLGRFCVKTSTSDH
SEIALVAAVTLFQ----------FFLRRRT--ASTDKGEQQFEFDTYSDE----------
-------------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|13091 _Pp1s123_63V6.1|PACid:18049626
------------MDALRKLSSLGRNQDK---ILDTASSSSYTEASVAEIPKASVETGGKD
EASPSGLAPIKVRVSNDVGAEIEEKRGGDEESVGSGESFDSALERLAASSVTSFEPPSPV
GSVGEQSQFAGGVSEDLEERGQEEYLY---------------------------------
-----------------YDDYGDDGEVEKDGSEKDSTSSSSSSSSSECSSSAS-------
--------------------------------------NTEDEMDISEYGASS-------
----------------------------------------------------------ER
AMPLANPSGVTDEEEEDGKEEETGIEEKFEEVYDGGVDS---------------------
-------------------PLEEIDVASAGNVTAREFRDEPEAWVSSRDSTEDSGKFIVT
VS------------------------------------------VTELKYNVERAVT---
-----------------------------------------AEENMPNGLK-----LGSE
ARGIASSSRGAELGNAFKDSREDHEVQEELTERSVKVAVENYDQEGE-------------
-----DADSTEIKKEFPRELTQSRTVIESPAYRFTS-EPVD---PALLELKSEKAQPNTQ
SFAR--------------IAEGESDADA-DADADDEDVESGDEHEDGYTEIN-------I
RQAAGKSESENESGNNPSLGPAGPSLISVLVRKTARRPASTAATD------TQSSNAA--
SSTQVAGTTDVNPSIEVNEVNETREKLQ----NIRVKFLRLVHRLGQSPQNVVV------
---------AQVLYRLGLAESLRGGS--TRNHTRAF--DFDRANAIAEEQEADNQEEELD
FACTILVLGKTGVGKSATINSIFDE-HKSVTNAYNPSTTNVYEVVGTMLGVKVRFVDTPG
LLF-SVADQRHNERIMGRVKKYIKKA-SPD---------IVLYFDRMDMQTREFGDVPLL
RTITNVFGTAVWFNTIVVLTHASTAPPDGPNGTPMGYELFVAQRSHSVQQSIRQVAGDMR
LQ-----NPVSLVENHPACRA-NRNGQRVL---PNGQIWKPHL------MLLCFASKILA
------EANTLLKLQDTAAPGRPFG----------------QRSRVPPLPFLLSSLLQSR
AQLKLPDEQLDESDESDDDEEDE-------EEGDEYDDLPPFRSLSKEELEELSKDQRQE
YAEELAV-RERLFQKKQHREQLQRRKEM---KKRATAM-RKEGLSHPADEADDEAGQ-PA
AVPVPMPD-MALPPSFD-SDNPTHRYRYLET-ANQWL-VRPVLETHGWDHDAGYDGFNVE
KMFVVK-----NKIPASISGQVTKDKKESQVNFEAAASLK-HG-------EGKVTLTGFD
VQ-T-IGK-DLAYTLRAETRFNNF--KR-NKTTAGVTATYLND-------TIAAGVKLED
RILIGK------RVKMVV---NGGVLTGKGDKAF---------GGSLEATLRGKEYPLSR
TLSTLGLSV-MDWH-GDLAIGGNLQSQFMVGK-TMMVGRANLN-NRGSGQVSIRASSSEQ
LQMVLIGIVPILR----------SLINCRFGFGGGQSSQ---------------------
-------------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|232 _Pp1s136_59V6.1|PACid:18036766
------------MDALRKLGSLGRRRDE----VDTASSPLKNEASAAEIPRDPVQISGKD
EASPSGLTPIRVRVPEDVRSESEVKRDGDEESVGSGESFDSALERMEASSITSFEPPSPM
ESIDGRFQFEDGVREDLAESGLDGNFS---------------------------------
-----------------YDDDDDDEEEEEDGSEE-GESTSSSIINSEYSSSAS-------
--------------------------------------NTEDEMDISGYGASS-------
----------------------------------------------------------AR
TMLVSNDASKSDEEA---------------------------------------------
------------------------------------------------------------
--------------------------------------------IDEPKYKLRNVVT---
-----------------------------------------GEENMSGGLS-----VENE
ARGVALSSWKSELEDFYEASLEDNDVQEELAEKIIKVASEQNDEEDE-------------
-----EVHFPVIANELPGRITRNRTMIDSPAHLYSAVKAVD---STLPALKSESTKSITQ
GFVE--------------AEEAESDVFTEGEDGYD------DEDEDGDIQMD-------V
SQATEKSGTPDESESNPSMGAGGPRLPSLPQRSSARRSAATTATG------VPRPNTA--
SSTQSAATSDASISSESSEANEIREKLQ----NIRIKFLRLARRLNQSPQNVVV------
---------AQVLYRLGLAESLRGGS--SLNRTRAF--SFDHANALAEEQEAAKY-EDLD
FACTILVLGKTGVGKSATINSIFDE-CKTVTSAYYPSTTKVHEVSGTVLGVKVRFIDTPG
LLP-STADQRHNKNIMRQVKKYIKKV-SPD---------IVLYFDRMDMQTRDSGDVPLL
RTITDVFGAAVWFNATVVLTHASKAPPDGSNGTPMSYDYFVAQRSHFVQQTIRQAAGDAR
LQ-----NPVSLVENHPACRI-NRSGQRVL---PNGQPWKQQL------LLLCFASKILA
------EANTLLKLQEASTPGKPFG----------------QRSRVPPLPYLLSSLLQSR
AQLKMPDEQHGESEDSDDDSDEEDE-----EEGDEYDDLPPFRPLSKQELEDLSKEQRQE
YAEELAD-RERLFQKKQYREQIRRRRER---KKQASVM-SKEEPSIPGDGAEDESGQ-PA
TVAVPMPD-MALPPSFD-SDNPTHRYRYLET-ANQWL-VRPVLETHGWDHDAGYDGFNVE
KMFVVK-----EKIPASVSGQVTKDKKEAQVNFEAAASLR-HG-------EGKVTLTGFD
VQ-T-IGK-DLAYTVRAETRFNNF--KR-NKTTAGVTATYLND-------TIAAGVKLED
RVLIGK------RVKLVV---NGGVLTGKGDKAY---------GGSLEATLRGKEYPLSR
TLSTLGLSV-MDWH-GDLAIGGNLQSQFMVGK-TMMVGRANLN-NRGSGQVSIRASSSEQ
LQMVLIGIVPILR----------SLINCRFGF-GGQPQQ---------------------
-------------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|251 _Pp1s136_62V6.1|PACid:18036785
------------METLRNVSSTEKSKESSEAVRGASETSSIPERNSGGGP-DVEESGGRI
N-SYAGPSPPRAPVTDDTEDEVEEV-----DETEDDDNDDSAVE--NTSSLVDSAASRPL
GSYADALT----------------------------------------------------
SMPVAKVTTEDEEQDDDDDDADKADEEEVD-DEEYEEADDQASVEDLYGNSSALSRGSEG
SLPRSIPRIIARESGDDISEEPSEDEYNDISEEEYNEEAVEEAVEPEEKEQVTMEVEEKE
QFESPVAAEESTVKELNATPAVVPPADADVGDVSRTDNSNAEESPMNADADVGDVLKKEN
SNAEESPMNSDACREEDIVAEKVEKELS-QAVMTEDSQEVGSAQSQEEVTELMQAVSSLA
AESESTDQGVKQEVAPEVVPLATSEIKQGELEEIEQATTLPKTDVETRGCSLDLAEELQK
LSVSRSLSNDVLKSDEAERAAIIENAPAESTIDESV---VNVETVTESGYIVKRAASNDL
MAELEKLAAARLEKEASNNTVNPVREVSEDDVKDVSGETTVVTTSISEGANESLSKKEDE
PALIGSNVPEELEGN----SLE---VQSAITTDLEKVSSTPTPSNAEKESPEATEVRIVE
EGKLEKADPSVVNEELSKEILEDPEVVPSPAKMYTALKAVD---GDMPVLKSENGNVAGD
ENVE-SESRVLPAVDFAGKDG-DTDANTADEDNENDEDDVDEDEDEDDADMDTAKALAEL
AMTAGKSGDVSESGTKPSMGAAGPSLPSLPQRPAVRKPIAATASDSPG-RNTQRPNGA--
LSTQITSTTDESASSDAAEGDETREKLQ----NIRVKFLRLAHRLGQSPQNVVV------
---------AQVLYRLGLAESLRGGS--APNRSGAF--SFDRANALAEEQEAANQEEELD
FACTILVLGKTGVGKSSTINSIFDE-RKSVTSAFKPSTNKVQEVIGTVHGIKVRVIDTPG
LLP-SVADQQHNERIMGQVKKYIKKA-SPD---------IVLYFDRLDMQSRDFGDLPLL
RTITDLFGAAVWFNAIVVLTHASSAPPDGPNGVPLSYEMFVAQRSHVVQQTIRQAAGDMR
LM-----NPVSLVENHPACRT-NRTGQRVL---PNGQIWKPQL------LLLCFASKILA
------EANSLLKLQETTAPGRPFG----------------QRSRVPPLPFLLSSLLQSR
AQLKLPDEQAGESDESDDDEEEED------SDADDYDELPPFRPLSKEELEDLTKEQRED
YMEELAD-RERMFQKKQYREEIRRRKEA---KKRQAQM-SKEELA-EAEEAEDEAGN-AA
AVPVPMPD-MALPPSFD-SDNPTHRYRYLET-ANQWL-VRPVLETHGWDHDAGYDGFNVE
KMFVVK-----EKIPASVSGQVTKDKKEAQVNFEAAASLR-HG-------EGKVTLTGFD
VQ-T-IGK-DLAYTVRAETRFNNF--KR-NKTTAGVTATYLND-------TIAAGVKLED
RVLIGK------RVKLVV---NGGVLTGKGDKAY---------GGSLEATLRGKEYPLSR
TLSTLGLSV-MDWH-GDLAIGGNLQSQFMVGK-TMMVGRANLN-NRGSGQVSIRASSSEQ
LQMVLIGIVPILR----------SLINCRFGF-GGQSQQ---------------------
-------------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|13071 _Pp1s123_61V6.1|PACid:18049606
------------MDTSSKVSSMEGNKETTE------DASVAVERSNGGGP-NGVEIEGRG
D-SYVGPSPPRAPVTDDTEDEVEEV-----DGSGDNDSFDSAVERFGASSAASVEPSSPV
SSYADALKTKDTAPEVKEEESVEKDESNKVKENGGGSSAKDEARARNSEGEEEFSEVPIR
TMPVAKVTTVDEDQ---DGDVEEDDEEEVDNEEEFEEANDQVFGEEEYATSTAFRQEYEG
SLPRSMPRIIARESGDDISDE--------FSEEEFNEEETEDEAEQEEGGAVT-EATGKE
EF-----GKETTSKEVTDIPLVEQP----------------------AETEVGDRLKSDD
SSNVENFVNTQGSGREDVSEEQRGLEVSLQAAKIEEAQVVESEQPHEEEKELTRAVSSLV
AEPENFDVGVKEVVASEVVPLATVDVKEGELETTDEATTAPKMDVENRECSADLAEELRK
LSASRSLSEEVFTNEEAEPAVGTENASTDSKPDEVKEFDVDSFPVTESNYVVRRAASNDL
VAELEKLAAARLENESSDNATIPVEEDSKADVKDTSQDITVATASSSEGAN-----KEDE
PASTESSSPKEPEVDDGEGSVE---VQSSIIEDLEKVGNDFTPSNAEKGSSEA---QIVE
ENKV-GVDPALVSEGAPEGVIEGPAVVSSPAKMYTALKAVD---DEMPPLKSENKAVVET
EKVE-SKPRGFSAIDFAEEDG-DSDADAEDEDDEDDEDDDEDDDDEDDKDMVTAKALAEL
ANAVGKSGDGAESGKKSSMGAAGPSLPSLPQRPAVRKTAAATALDTAG-RITQRPNGA--
PSTQLTATTEENANSDTAEGNETREKLQ----NIRVKFLRLAHRLGQSPQNVVV------
---------AQVLYRLGLAESLRGGN--TSNRAGAF--SFDRANALAEEQEAANQEEELD
FACTILVLGKTGVGKSATINSIFDD-RKSVTSAFKPSTNKVQEIVGTVHGIKVRVIDTPG
LLP-SVADQQHNERIMGQVKKHIKKA-SPD---------IVLYFDRLDMQSRDFGDLPLL
KTITDLFGAAVWFNAIVVLTHASSAPPDGPNGVPLSYEMFVAQRSHVVQQTIRQAAGDMR
LM-----NPVSLVENHPACRT-NRNGQRVL---PNGQIWKPQL------LLLCFASKILA
------EANSLLKLQETATPGRPFG----------------QRSRVPPLPFLLSSLLQSR
AQLKLPDEQLDESDESDDDEEEED------SEADDYDELPPFRPLSKEELEELTKEQRQD
YMDELAD-RERLFQKKQYREEMRRRKEM---KKRQAQM-SKEELA-QPDEADDEAGQ-PA
AVPVPMPD-MALPPSFD-SDNPTHRYRYLET-ANQWL-VRPVLETHGWDHDAGYDGFNVE
KMFVVK-----NKIPASISGQVTKDKKESQVNFEAAASLK-HG-------EGKVTLTGFD
VQ-T-IGK-DLAYTLRAETRFNNF--KR-NKTTAGVTATYLND-------TIAAGVKLED
RILIGK------RVKMVV---NGGVLTGKGDKAF---------GGSLEATLRGKEYPLSR
TLSTLGLSV-MDWH-GDLAIGGNLQSQFMVGK-TMMVGRANLN-NRGSGQVSIRASSSEQ
LQMVLIGIVPILR----------SLINCRFGFGGGQSSQ---------------------
-------------------------------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|6113 _170624|PACid:15407391
------------M-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------DYFPDKKPEDDENEKH
EEVDYKKPEEAGNEKHGEADVIGSAAEAVRSQEEREPVPETDSDEEEEEEVD-------T
SAALRAFAQAAAATETPSLGSAGPSLPAKPT--ATRLLSSIEGARNTQ-VAAHNPSGG--
SETTTAVEAADTNGEPNDENVETREKLQ----MIRVKFLRLAQRLGQSANNAVV------
---------AQVLYRLGLAEQLRGGR--SSSRNSAF--RFERASAIAEEQEAAGQ-EELD
FTCTIMVLGKSGVGKSATINSLFDE-AKTETNAFAYSTKKVQEITGTVHGIKLRVIDTPG
LLP-AVADQRHNEKIMASVKRFIKKS-PPD---------IVLYFDRLDMQSRDYGDLPLL
RTITDTFGAAIWFNAIVVLTHASSAPPDGPNGLPLSYEMFVAQRSHVVQQTIRQAAGDMR
LM-----NPVSLVENHSACRT-NRSGERVL---PNGQVWKPQL------LLLCFASKILA
------EANSLLKLQES-TPGKPF-----------------MRSKVPPLPFLLSSLLQSR
PPLKHSDENAVGEDDTDDDIEDVED-----SDEEDYDELPPFRRLTRDELDQLDKSSRDE
YFEELQM-REKLFQKKQWKEEIRRRREM---KKRAASSDSAEEYPAPVDDGYDDDNK-SA
PVPVPLPD-MQLPPTFD-SDNPVHRYRYLET-ASQWL-VRPVMDLHGWDRDSGYDGFNME
RMFTY------GKIPASLSGQVTKDKKEANVTLECAASMK-HG-------EGKVSQAGFD
VQ-T-VGK-DFSYTLRSETRFSNF--KK-NKTIAGLAMTMIGD-------TLAYGMKIED
RLMIGR------RVKVVM---NGGALTGKGDTAY---------GGTVEISLRDKDFPLGR
SLSTCGLSV-MNWH-GDMALGGNLQSQFMVGK-TMVVARGNLN-NRGAGQITIRLSSSEQ
LQIALIGVMPLIK----------ALFNSKFGT-GQQA-----------------------
-------------------------------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|12035 _60423|PACid:15413313
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------TQGNTEEKTRILCEKLQ----DIRVKFVRLVHRLGQSADNGIA------
---------AQVLYRFALAEQLKGGK----MRNSTS--GYDKACAVAMEEEASSRDEELD
FCCTVLLLGKSGVGKSATVNSIFGK-PMASTSAFSSGTNKVEVIDGTMKGIRMRVIDTPG
LSA-SMADRRYNERVVASIKRCIRRN-PPD---------IVLYVDRLDSQSK---DAALM
RYIGDRFGPAIWFNAIIVLTHGASSPPDGPDGFPLRYDSYVGQRTRMFQQTVRSAVGDTR
LL-----NPVTLIENHPACRT-NRAGERVL---PNGMVWRPEL------LLLCFSARILA
------EANTYLKLPESMPLTRLC-----------------ERRSGSPMPVLLASMLQAR
SEVQQPDEEEYGEVDPDEDE----------DGEAEFDQLPPFRRLLQDELDALDEDNRQS
YFEELAL-REKLFKRKLWKTQCRRWREM---KNRGV------------EDGEDEQQQHRD
MAPGISPD-FALPTSFS-SDDPSHRYRYVDD-AS-WN-VRPVLDSR-WDHENGFNSANLD
RSFHLA-----KNIPVSVSGQIVMDKKEYHVTFDGSAAIK-HG-------PNRVSTGGLD
IQ-T-VGR-DVCYSLWGGTTFKNH--EC-NKTLAGMGVTMVGE-------NAVVGVRLED
KVVIGK------RAKILM---SGATSLTRGDKAY---------GAIMEATVVGPDYPVDR
TNCTLGLSV-MNWTAKDIAYGINLHSQIHLGG-TAMVVRGNAN-NRGTGQISIKVNSTDR
IQLALLGLLPVIR----------SL-----------------------------------
-------------------------------------
>Vitis_vinifera_gnl|BL_ORD_ID|15727 _GSVIVT01024062001|PACid:17832352
------------M-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------YTPVDEGV
SASGTGRSPSVEDSAIEKSEMEQCAIEDSTIEKSE-------------------------
----------------------------TKQGVTSELAAADNI-SPQPERAVENVAEVKN
KYVV-----------------------FEEQETKEPNMEKEDQKIQGNRE----------
-REIRPAEQVASSSGRSSNPGPPPAHPAGLGRAAPLLEPASRV------VQQPRVNGT--
TSQVQAQLIEDAGNGEAEENDETREKLQ----MIRVKFLRLAHRLGQTPHNVVV------
---------AQVLYRLGLAEQLRGRN---GGRVGAF--SFDRASAMAEQLEAAGQ-EPLD
FSCTIMVLGKTGVGKSATINSIFDE-VKFSTDAFQVGTKKVQDVVGTVQGIKVRVIDTPG
LLP-SWSDQRQNEKILHSVKRFIKKT-PPD---------IVLYLDRLDMQSRDFGDMPLL
RTITEIFGPSIWFNAIVVLTHAASAPPDGPNGTASSYDMFVTQRSHVVQQAIRQAAGDMR
LM-----NPVSLVENHSACRT-NRAGQRVL---PN-------------------------
-------ANTLLKLQDS-PPGKPFT----------------TRSRSPPLPFLLSSLLQSR
PQVRLPEEQ---------------------------------------------------
---------------------KERRKMM---KKMAA-S-SKDLPSDYSENAEEESGG-AA
SVPVPMPD-WALPASFD-SDNPTHRYRYLDS-SNQWL-VRPVLETHGWDHDVGYEGINVE
RVFAIK-----DKIPVSFSGQVTKDKKDANLQMEIASSVK-HG-------EGKATSVGFD
MQ-T-VGK-DMAYTLRSETRFCNF--RK-NKATAGLSITALGD-------AITAGLKLED
KLIVNK------RIRLVM---TGGAMTGRGDVAY---------GGSLEATLRDKDHPLGR
SLSTLGLSI-MDWH-GDLAIGCNIQSQIPIGRFTNMIGRVNLN-NRGAGQVSIRLNSSEQ
LQIALIGLVPLLR----------KLLGYSQ---QGQSSCFLIVYAFGMNCKIPGMYQKGL
SFFLYLYSWITSAGANETLGSMLLGYVNICNTYESFS
>Vitis_vinifera_gnl|BL_ORD_ID|11234 _GSVIVT01017736001|PACid:17827859
------------M---------------ESRPRVSLSAAQVTSSTSAGYPHDQPSEFMVS
QQTLPGFLPIRAPLSLDSDFDIYVRSDDNVISTSGSESGRNMSEEDEFEFETASERPFVG
FPDEETSVGSDDVEEYVLASPFLAVPDEETLEAPLQDEQNDAIGHYALTFVPVVVDDSNS
KYSMPTARLSMDDDCDNG-------------SGEEELSEVEDGGF--SGADRI-------
------------------------------------------------------------
------------------------------------------------------------
--------------TGIRVLEEIDNVPK--------------------FKVLGIEEDD--
-LQPRI--KVNPDVFIGVGNEVLGSEKAKSLVEQSVDDLVEQ-----RDFDNTEEAIS-E
ASAVNREDIAEETLKLNENVKCPSTESQVLRKLDN---QETGLKGRDVGEQSSSEFNNND
AVYVKLVGSRVDVKEPTEVVEESLIMVDSADVVEEYGDFKSD-ESMGNST------GKNE
IESVNRSKISILNPTHETKYLGNGDLPGATEDVMLEDQIYGKSSNSVSRIPSSYLDPDFE
VNDVANNVSEDVEGEGTISDGDAGGLVFRSSDTAKQIVNEEKQ-SLAPTSGSGAQIPQHH
L------------------------QTTEGQTLKDSEEKLEEDGDDEDHKIFDSEVLTSL
LKAATSAGLDGDSGNGVFTSVDDSRVFSL------KRHAGLGS---SL-RPVPQSNGLNI
SASSDLMAGAESKDSISEEEKKKLEKIQ----LLRVRFLRLVQRLGHSPEDSIV------
---------SQVLYQLAIDAGKHSNE--------AF--SLESAKGMAMKLEAEGK-GDIE
FSLNILVLGKTGVGKSATINSIFCE-EKAMTNAFEPTTSAVNEIIGTIDGVKIRVLDTPG
L-RSSLMEQAFNRKILSSIKKFMKKF-PPD---------VVLYVDRLDTEDKDLNDLPLL
KSITSSLGSSIWRNAIVTLTHGASSPPDKPSGSPLSYDLFVSQRSHSVQQSIRQTVGDLR
LMNPNLINPVSLVENHPLCRK-NGNGQKKV-------IWLS-------------------
-------------------------------------------APFPTLPYLLSSLLQSF
THPKLSTDQGGENVDSDIELGNMTDTDE--ENDDVYDQLPAFKPLRRSDIAKLSKEQRKA
YFEEYDY-RVKLLRKKEWRQELKRLREM---KKKCK-D-GGNDNVHVGEDGDQESGS-PA
TVPVPLPD-MVLPPSFD-ADNPAYRYRSLDA-MSRHL-ARPVLITRCWDHDCGYDGVSLE
ENLAIA-----GMFPTEISVQVTKGKNEFNIHFDSSVSAK-HG-------ENGSTMAGFN
IQ-T-IGR-QVAYILRGETKIKNF--QT-NKTAAGVSITFSGK-------NVAAGLKIED
QIAVGR------RLVFVG---STGAILSQNDAAY---------GANFEIRLKENDFPIGQ
DQATLGLSL-MKWR-NDFALMGNLQCHFSVGQSSKMAFHVGLN-NKLSGQITVRTSSLEQ
LQIALMGFLPIAI----------TIFRSLC------------------------------
-----------PGSVLFHCTDVVIHLSRSDSKL----
>Vitis_vinifera_gnl|BL_ORD_ID|18594 _GSVIVT01027981001|PACid:17835219
------------MGGWFGKSWVGGQFRHFSENGGFVSGEEDFETASEPIMEDPDEEIVEK
GIGGEGIDSPFVGSSE--------------------------------------------
--------------------------------------------------------FFVP
KMVMPVARVSTDDEEEEGGDDVVGGPRARVLGGEEETGETESIGVGADGSKRI-------
------------------------------------------------------------
------------------------------------------------------------
---GLDPGVENCENEGKGVSVQMDSMEKPVVRELVEGSSIGGAAQGNSIEALGADNGDST
FETPKFDDRIKEDAFLGGGTDLVGPLIAEAAAAADNKPVATESVNIAREGDSVVDAIHVS
VSGSGSAIVGDEGFRQNADGESDQVSPLIAEPADNKFLEEDGVKLNGGGDSVVEAMHTNF
SGSGPTIAGDEEENKDSEIEGKEMMVDDSVKLDKRFDQISGDLEEPVNSK------SVGV
DTDFDKSIKPVTNLNVETSELGEKTDGGVEKDQELNVGA-------------VVPIKLDE
TNHHSDEDDEEGEIEGSVTDEESKGMVFEGSEAAKHFLEELEQVSGGAATSASS------
------------------------------------------------------------
-----------DSGSITITSPDGSRLFSV------DRPAGLGSANRSL-KPAPRPNRSNL
FTPSNLAIGGDSENTLSEEDKRKQEKIQ----LIRVKFLRLVQRLGR-------------
----------------------QTGE--------EF--SLDTAKRRAMQLEAEGK-DDLN
FSLNILVLGKSGVGKSATINSIFGE-QKALINAFEPATTTVREIIGTIDGVKIRVFDTPG
LKS-SFLEQGVNRKILSSIQKFTKKC-PPD---------IVLYVDRLDAQTRDLNDLPLL
RTITSSLGPSIWRSAIVTLTHGASAPPDGPSGAPLSYETYVSQRSHVVQQYY--------
------------------------------------------------------------
-------------------------------------------------------LKQSR
THPKLSAEQ----------------------DEDEYDQLPPFKPLRKSQIAKLSKEQRKA
YFEEYDY-R--------------------------------------------DNGG-PA
AVPVPLPD-MVLPPSFD-CDNPAYRYRFLEP-TSQFL-ARPVLDTHGWDHDCGYDGVNLE
QSLAIL-----GQFPAAVSVQVTKDKKEFNIHLDSSAAAK-HG-------ENGSSMAGFD
IQ-N-IGK-QLAYILRGETKFKIL--KK-NKTAAGFSVTFLGE-------NVATGFKVED
Q-----------------------------------------------------------
---------------GDLALGANLQSQFSIGRSSKMAVRVGLN-NKLSGQITVKTSSSEQ
LQIALVGIIPVVM----------AIYKAIWPGVNSILPCLHLFQALVI------------
-------------------------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|9231 _17.g734300.t1.2|PACid:19867537
------------M-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GGGLPPK---------RSEVAESQPASSASSSAAAPAPAAETAG------PKLPPR---P
AGLGLG-GAGLLPSRGAAAAPSAGSATGTPAAAASSSLQQQQQQPAPPATQPAAHAAPAA
P---------------------------------------AGL-----GGAGLKPMLPPR
PAAAAGAGAAGAAAAKPTPAPAPAAAPVPAAAPPPR--PAMPNPAAGM-SLPPRPVVAAA
PPVLAAAGSDA---VVDPSEDRRVQRVQRIAHDTRVRLIRAASRLGLAPRTDQV------
---------AQFLQAIERSERMVGAQHYKGSRRVDLLAAAEREARLAEEREGAAAEAVAG
LRVKILVLGMTGTGKTELINSLLNRPAGSRTNAFREATRRVRVVRGDHNGIPLTFIDTPG
LHA-SASRTADNRAILRAVRAAYRWH-KPD---------YVFYVDRLDATRPGFGEMGLL
GLITESLGAGVWRNTMAVLTHAHAA----RTAFGGQYDVNSRQRRNIVSQLLRQAAGDQQ
SR-----NPVFLADCHPACPT-NSLGQPVILEGPTAVPWKQQL------LVQLVGYKSYN
------VATSAFKDLAKAKAGKAAAGAAGGARGPQDIFKQMMRSRLPPMTFFVEQMSEGV
LKP------------------------------EGWATMETVAGLG----EEVTEDEGAE
SFNHVYY-RQMYELAVAGDPWAQREYAAMLRAY--D-K-GCESYRASYEEADVDANVEYG
VESYVVDP-IDFGPSFDPEDMYSHRHAYAEA-ADAGVTVIPSQDYYGPEHDDPLNGIVFQ
YEAQPFSRHGWGGVPFDLTVCCEKDKTSLCLQGETHVSLV-HSVPPFGPRHITQVTGSWE
VL-RPNIK-DVMYQLEVDTFKDGLLGKS-DHAGCGLMLARLGEGGDPRKGPTAVGVRLQD
TLRVGPFKLEACASKVAVQGPTGGKEEGWGARAFVGYDWLPGLGMAFDFIQERTPEEGGK
RLRGYGANFTYDWE-A---LGAAFGMEVDYVAASESVF------------VSVNAFSGND
YRLGWLLLLPAVNYFK---ETVSSLWARLRGAGGGEGEEGEELEEEGEGEEGD----DEE
AMMMMAQEGDL--------------------------
>Volvox_carteri_gnl|BL_ORD_ID|9830 _Vocar20012343m|PACid:23133716
------------M-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------PSLPARPKGG
LGGLPPRGLPALSSKSASPQSSSPPAPSAGPSAAQPAAAASGSAPPIASMPKLPPRPGAP
SGLGLGLGLGARPAAGAPRPPSEGVPAAAATPAAAETAPAAAAAAAPPGVQQPAAAAAAG
P---------------------------------------AGLGLGLGGAAAQRPTLPPR
PATAGTATSSAAAAAQPRPAGAQSVGGAAAAAGGVRAMPGLPPRPAGLGGAPPAPAAAAA
ATAGAAAAATPSMDVVDRTEDRRVQRVQRTAHEIRVRLIRAATRLGLSPRSDQV------
---------AQFLQAIERSERMVGAQHYKGTRRVDLIAAAEREARELDSRE-PPHSPIAG
LRLKILVLGMTGTGKSELINSLLDRPASSRTSPFREATRRVRVIRGHHNGIPLTFIDTPG
LHA-SVSCTAENKAILRSIKAAYNCF-KPD---------YVFYVDRLDAPRPGLGELGVL
SLIAEALGPGVWRNTMAVLTHAHAA----RAAFGGQYDINSRQRRNIITQLLRQVAGDQQ
SR-----NPVFLVDCHPSCPT-NSLGQQVIQEGPSAVPWKQQL------LGQTVGYKSYN
------AAAAVFKELAKSKAGKSA--AAGGARGPQDIFKQLMRSRLPPMTFFVEQMTEGV
LKP------------------------------EGWATMESVAGLG----DEVTEDEEAE
SFGHMYY-QHMYDLAMSGDPWAQREYAAMLRSY--D-K-AQETFKASYEEADLDHAIEYG
IESYVVDP-IDFGPSFDPEDLYSYRHAYAEA-ADSAITVIPSQDYYGPEHEDPLNGFVMQ
YESQPFARHGWGGVPFDLSVCVEKDKTSLCLQGETHLTVV-HSVPPFGPRQVTQLTGSWE
ML-RPNIK-DVMYQLEVDTFKDGLLGRN-DHAGCGMMLARLGEGGNPRKGPVAVGVRVQD
TFRLGAFKVEACASKVAVQGPTGGKEEGWGARAFVMYDWLPGVGIALDAIQEKGSEESGK
RQRGYGINVTYDWE-M---LGAAFGAEFDYVAASKSLY------------VSVNAFSGND
YRLAWVLLLPALGSDEIEWETLGSVWARLRAAGGGAGQEEEAGEEEAGEEEYDEEDEDEG
VAAMMAQAADM--------------------------
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|3128 Cyanidioschyzon_merolae_cds_gnl|CMER|CMP284C similar to chloroplast outer membrane protein Toc34
------------M-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----DSETPTKNEAEQRASPDRTGQVT----QRPVSLFRKNGTFAYPLEDSDVYEEQVL
ALEDVPEPTAQAILRLALAA------------------------------ERQGV-PRL-
---RFLVVGAPGVGKSSLINTLLNE-NLCSVSAWERGTKNAQVCARQVDSVVIEFIDTPG
IAPCRRSGLEASRRQVQRLRKLLDAR-GADEHPYLRSFHAILYVMRLDDTRPDLVDYHNW
KVLMEFFGAEVLRHMMVVFTHGQSLPPDS-----LSYPEYVRGRRDYVYLLIERLTGPLK
AVR----FPVFVAENSSKCPVIEETGERKL---PDDTPWITQLYDGIRRFVFPLEADLFG
METGPEDTQVLVYIYDKRRSR--------------------ADERYPRSP--LQALIRN-
----------------------------------------------------------PW
FLRAVQFCGAMLLRSYMIRQEHERFNPK----------------PHHPEPIIRDANNAFA
VASRRANDHRLFTPSIDEDEESFFRMNGNDDFVSRLR-NRP-------------------
-------------------GEVDLDE--------------------------------LD
VE----------------------------------------------------------
------------RIESPD-------------------------GRFVEYWYTEKDNP---
----------------------------EMVRMYRLEIRDDPNEERESRQDRIPISKDQH
------------------------------------------------------------
-------------------------------------
