>Amborella_trichopoda_gnl|BL_ORD_ID|8412 evm_15.model.AmTr_v1.0_scaffold00041.111 EVM_15_evm_15.TU.AmTr_v1.0_scaffold00041.111   AmTr_v1.0_scaffold00041:2858431-2865733(+)
M-----------------------------------------------------------
-----AENGVKV-----------EDIHVSNREDVVVKEF---------------------
---------------------------QLKPGEAKD--------------SEGDEVFEEA
MEAQPDDGQS-------------------RSLEPHGVAENGEREKKDDASEGNGDDKT--
-----------------KGDDRFDVKDNKRAEVDEVFGE---NGEKEN------------
-----------EDDGFEE--------SHENRERFYEAIGLSKEENNVE-ERS--------
-----ESKEGSKPSLENGHIGQADIVSSDTTLYENHANNE-----PVVEEADGGKLAAEI
TEPLAKSAIQDALKVDVNQ-DGIPE------LKN-------------GDADFDLNEAEGT
DFVIGSNNDPGTLGPSLIDVNVKEKGSPSTEMDIDID----EVDYKCEDVNMDNMIIDEA
SLLPESEAPAKNAHEFSLLASYE-------------------------TSDIQEDTQALL
IEDA----GDIPRGDTQVALDMETADWSGILPENEGHEQSTHESPPLVSHETSDIQEETQ
GSQAEDIGDVTVPNLNSASVTSQSMGTGEGDS----------------------------
-----------------------------------------ISAIDNDDAQES-------
HIPEPTIVIPVELESNKAEAQDG-------------------------------------
----PITNKLLGKGSSS---STKWDQLGSSSSSSSSDDDNNEHDSIQ--------SMAAS
RISAPSQST-TTSTLPPPPAR---------PAG-----LGSSGSLLEP--APRTQQQSRV
NGSAPLRQSQLVEEVANGETDENSETREKLQMIRVKFLRLAHRLGQTPHNSVVAQVLYRL
GLAEQLRRRRDTNRAGAFSFDTASAMAEQLEAA---------------------------
-----GQ--EPLD-FSCTIMVLGKSGVGKSATINSIFD-------E----VKFSTDA---
----------------------------------------FELGTKK-VQDIVGTVQGIK
VRV--IDTPG----LLP-SFADQRQNEKTLQS--VKRFIKKTPPD-----------IVLY
LDRLDMQSRD-YGDLP-LLRTITEIFGP-----AIWFNAIVVLTHAG-------------
--SAPPDG------------------------PNGSPLSYEMFVAQRSHVV---------
---------QQAIRQAAGDMR------LMNPVSLVENHSAC-RTNRAGQRVLPNGQVWKP
QLLLLS------------------FASKI--------LAEANTLLKLQDVPN-ERP-FSG
RSRVPPLPFLLSSLLQSRPQLRLPEEQYSDEDAFDEDIDESSHSD----DGSDYDNLPPF
KRLTQNHLAKFSKEQKKAYYEELDYREKLFIKKQLKEEKKRRKILKKMASS--VEDWSSE
YN-ESTEEESSSAESVPVTIPDVTLPASFDSDNPTHRYNCLDLPNQWLVRPVLEVHGWDR
DVGYEGLNVERLFVVKNKIPISVSGQITKDKKETNLQMECTGSLKHG-EGKSTSLGFDAQ
TVGKEVAYTLRSDTRFANFRYNKTAAGLSVALFGDAITAGVKLEDKLLVKKWFTVVMTGG
AMVGRGDVAYGGSLEATLRDKDYPLGRFLSTLGLSVMDWHGDLAIGCNLQTQFPVGRWFN
MIARGNLNNRGAGQYQVSTDAFFGEKTEDAMVRSPDLV-----------------QRGHG
I---
>atToc120_gi|332642323|gb|AEE75844.1| translocase of chloroplast 120 [Arabidopsis thaliana]
M-----------------------------------------------------------
-----GDGAEIVTRLYGDEKKLAEDGRIS---------E---------------------
---------------------------LVGSDEVK---------------DNEEEVFEEA
IGSQ--EGLK--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------PESLKTDVLQ-EDFPL------AS--------------NDEVCDLEET---
-----SRNERGVENLKVNYSEIGESHGEVNEQCITTK----EADSDLVTLKMNDY--DHG
EVADADISYGKMASSLDVVENSE-------------------------KAT------SNL
ATED----VNLENGNTH------SSSENGVVSPDENKELVAE----VISVSACSVETGSN
GIDDEKWEEEI--DVSAGMVTEQ-------------------------------------
----------------------------RNGKTGAEFNS--VKIVSGDKSLND-------
SIEVAAGTLSPLEKSSSEEKGETES-----------------------------------
------QNSNGGHDIQS---NKEIVKQQDSSVNIGPEIKESQHMERE--------SEVLS
SVSPTESRS-DTAAL--PPAR---------PAG-----LGRAAPLLEP--APRVTQQPRV
NGNVSHNQPQQAEDSTTAETDEHDETREKLQFIRVKFLRLSHRLGQTPHNVVVAQVLYRL
GLAEQL-RGRNGSRVGAFSFDRASAMAEQLEAA---------------------------
-----AQ--DPLD-FSCTIMVLGKSGVGKSATINSIFD-------E----LKISTDA---
----------------------------------------FQVGTKK-VQDIEGFVQGIK
VRV--IDTPG----LLP-SWSDQHKNEKILKS--VRAFIKKSPPD-----------IVLY
LDRLDMQSRD-SGDMP-LLRTITDVFGP-----SIWFNAIVGLTHAA-------------
--SAPPDG------------------------PNGTASSYDMFVTQRSHVI---------
---------QQAIRQAAGDMR------LMNPVSLVENHSAC-RTNRAGQRVLPNGQVWKP
HLLLLS------------------FASKI--------LAEANALLKLQDNIP-GGQ-FAT
RSKAPPLPLLLSSLLQSRPQAKLPEQQYDDEDD-EDDLDESSDSE----EESEYDELPPF
KRLTKAEMTKLSKSQKKEYLDEMEYREKLFMKRQMKEERKRRKLLKKFAAE--IKDMPNG
YS-ENVEEERSEPASVPVPMPDLSLPASFDSDNPTHRYRYLDTSNQWLVRPVLETHGWDH
DIGYEGVNAERLFVVKDKIPVSFSGQVTKDKKDAHVQLELASSVKHG-EGRSTSLGFDMQ
NAGKELAYTIRSETRFNKFRKNKAAAGLSVTLLGDSVSAGLKVEDKLIANKRFRMVMSGG
AMTSRGDVAYGGTLEAQFRDKDYPLGRFLSTLGLSVMDWHGDLAIGGNIQSQVPIGRSSN
LIARANLNNRGAGQVSIRVNS--SEQLQLAVVALVPLFKKLL-TY--Y----SPEQMQYG
H---
>gnl|BL_ORD_ID|26585 Arabidopsis_thaliana AT3G16620.1|PACid:19664532
M-----------------------------------------------------------
-----GDGAEIVTRLYGDEKKLAEDGRIS---------E---------------------
---------------------------LVGSDEVK---------------DNEEEVFEEA
IGSQ--EGLK--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------PESLKTDVLQ-EDFPL------AS--------------NDEVCDLEET---
-----SRNERGVENLKVNYSEIGESHGEVNEQCITTK----EADSDLVTLKMNDY--DHG
EVADADISYGKMASSLDVVENSE-------------------------KAT------SNL
ATED----VNLENGNTH------SSSENGVVSPDENKELVAE----VISVSACSVETGSN
GIDDEKWEEEI--DVSAGMVTEQ-------------------------------------
----------------------------RNGKTGAEFNS--VKIVSGDKSLND-------
SIEVAAGTLSPLEKSSSEEKGETES-----------------------------------
------QNSNGGHDIQS---NKEIVKQQDSSVNIGPEIKESQHMERE--------SEVLS
SVSPTESRS-DTAAL--PPAR---------PAG-----LGRAAPLLEP--APRVTQQPRV
NGNVSHNQPQQAEDSTTAETDEHDETREKLQFIRVKFLRLSHRLGQTPHNVVVAQVLYRL
GLAEQL-RGRNGSRVGAFSFDRASAMAEQLEAA---------------------------
-----AQ--DPLD-FSCTIMVLGKSGVGKSATINSIFD-------E----LKISTDA---
----------------------------------------FQVGTKK-VQDIEGFVQGIK
VRV--IDTPG----LLP-SWSDQHKNEKILKS--VRAFIKKSPPD-----------IVLY
LDRLDMQSRD-SGDMP-LLRTITDVFGP-----SIWFNAIVGLTHAA-------------
--SAPPDG------------------------PNGTASSYDMFVTQRSHVI---------
---------QQAIRQAAGDMR------LMNPVSLVENHSAC-RTNRAGQRVLPNGQVWKP
HLLLLS------------------FASKI--------LAEANALLKLQDNIP-GGQ-FAT
RSKAPPLPLLLSSLLQSRPQAKLPEQQYDDEDD-EDDLDESSDSE----EESEYDELPPF
KRLTKAEMTKLSKSQKKEYLDEMEYREKLFMKRQMKEERKRRKLLKKFAAE--IKDMPNG
YS-ENVEEERSEPASVPVPMPDLSLPASFDSDNPTHRYRYLDTSNQWLVRPVLETHGWDH
DIGYEGVNAERLFVVKDKIPVSFSGQVTKDKKDAHVQLELASSVKHG-EGRSTSLGFDMQ
NAGKELAYTIRSETRFNKFRKNKAAAGLSVTLLGDSVSAGLKVEDKLIANKRFRMVMSGG
AMTSRGDVAYGGTLEAQFRDKDYPLGRFLSTLGLSVMDWHGDLAIGGNIQSQVPIGRSSN
LIARANLNNRGAGQVSIRVNS--SEQLQLAVVALVPLFKKLL-TY--Y----SPEQMQYG
H---
>atToc132_gi|330251427|gb|AEC06521.1| translocase of chloroplast 132 [Arabidopsis thaliana]
M-----------------------------------------------------------
-----GDGTEFVVRSDREDKKLAED-RISDEQ--VVKNE---------------------
---------------------------LVRSDEVRD--------------DNEDEVFEEA
IGSENDEQEE--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------EEDPKRELFESDDLPL------VETLKSSMVEHEVEDFEEAVGDLDET---
-----SSNEGGVK----DFTAVGESHG--------AG----EAEFDVLATKMNG---DKG
EGGGGG-SYDKVESSLDVVDTTE-------------------------NATSTNTNGSNL
AAEH----VGIENGKTH------SFLGNGIASP-KNKEVVAE----VIPKDDGIEEPWND
GIEVDNWEERV--D---GIQTEQEVEEGEGTTENQFEKRTEEEVVEGEGTSKNLFEKQTE
QDVVEGEGTSKDLFENGSVCMDSESEAERNGETGAAYTSNIVTNASGDNEVSS-------
AV-----TSSPLEESSSGEKGETEGDSTCLKPEQHLASSPHSYPESTEVHSNSGSPGVTS
REHKPVQSANGGHDVQSPQPNKELEKQQSSRVHVDPEITENSHVETE--------PEVVS
SVSPTESRS-NPAAL--PPAR---------PAG-----LGRASPLLEP--ASRAPQQSRV
NGNGSHNQFQQAEDSTTTEADEHDETREKLQLIRVKFLRLAHRLGQTPHNVVVAQVLYRL
GLAEQL-RGRNGSRVGAFSFDRASAMAEQLEAA---------------------------
-----GQ--DPLD-FSCTIMVLGKSGVGKSATINSIFD-------E----VKFCTDA---
----------------------------------------FQMGTKR-VQDVEGLVQGIK
VRV--IDTPG----LLP-SWSDQAKNEKILNS--VKAFIKKNPPD-----------IVLY
LDRLDMQSRD-SGDMP-LLRTISDVFGP-----SIWFNAIVGLTHAA-------------
--SVPPDG------------------------PNGTASSYDMFVTQRSHVI---------
---------QQAIRQAAGDMR------LMNPVSLVENHSAC-RTNRAGQRVLPNGQVWKP
HLLLLS------------------FASKI--------LAEANALLKLQDNIP-GRP-FAA
RSKAPPLPFLLSSLLQSRPQPKLPEQQYGDEED-EDDLEESSDSD----EESEYDQLPPF
KSLTKAQMATLSKSQKKQYLDEMEYREKLLMKKQMKEERKRRKMFKKFAAE--IKDLPDG
YS-ENVEEESGGPASVPVPMPDLSLPASFDSDNPTHRYRYLDSSNQWLVRPVLETHGWDH
DIGYEGVNAERLFVVKEKIPISVSGQVTKDKKDANVQLEMASSVKHG-EGKSTSLGFDMQ
TVGKELAYTLRSETRFNNFRRNKAAAGLSVTHLGDSVSAGLKVEDKFIASKWFRIVMSGG
AMTSRGDFAYGGTLEAQLRDKDYPLGRFLTTLGLSVMDWHGDLAIGGNIQSQVPIGRSSN
LIARANLNNRGAGQVSVRVNS--SEQLQLAMVAIVPLFKKLL-SY--Y----YP-QTQYG
Q---
>Marchathia_polymorpha_gnl|BL_ORD_ID|5297 T20061:6708  (A)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------KRRREAKRRMADSPRGDQPQL
AD-EGADDDLGRSAAVPVPMPDMALPPSFDSDNPSHRYRYLETANQWVVRPVLETHGWDH
DSGYDGFSVEKMFVVSEKIPASVSGQITKDKKEANLTMECAASVKHG-EGKVTLAGLDLQ
TIGKDLAYTLRSETRFSNFKGNKTTGGLALTLLGDTIAAGMKIEDRLIVGKRLKLVLNGG
AITGRGDVAYGGSLEATLRDKDYPLSRTLSTL----------------------------
------------------------------------------------------------
----
>Amborella_trichopoda_gnl|BL_ORD_ID|8792 evm_15.model.AmTr_v1.0_scaffold00045.239 EVM_15_evm_15.TU.AmTr_v1.0_scaffold00045.239   AmTr_v1.0_scaffold00045:4019320-4023603(-)
MEAQGLPPLSKPKGTLTATSGSS----YPIRAPPSLDSDIDENIIEDSNDNSNNSTNALM
MGNKIGNSNVNNGGSSDSGDDIEEDSFLSGEDDFDTASERPFVADPDDETLELEMEDEEF
ETPFLGDSGEEKVRAGVVPSGSKNPGVLMPVAQVSG--------------EDEDEGLGEG
-ESEEDDGYS-------------------SSVRVPKVAEV---DREKGVSDSLVSDEV--
-----------------TGKRQLGSSPLASETIDEPKTG---VPEVENSTVLGPSSQKEV
EPGKTEVSAIGSDEQSQF--------EDNEKSETSESVGLAPKATVQEVDRT--------
-----GGSTTSNESNVKSDVGDNSVVEVSGLEATEQKTGD-----GEAEKAVGSSTVSGG
VAELEKSPVVESSQPEVSQLETGVEEGRSNGVLTGGSDRKLEVEVDSKTGTVDSGEADDK
TDVAEVNNEPCENPVTEAKPQVITLVSESNEMKAKNEEPSVESSVEAESKNCDAIVRGNA
SKTGVTLNPDAQEETIDTEPNHE-------------------------KGTICPILEAIN
SENSNASVAEVIHKTKAVDLSL-TAREGGFGDTEAEGEKSVSESKLKSSRSNEHSYSDVD
EVEASEASEPLVQNMEEE------------------------------------------
-----------------------------------------IKMILLKDYINS-------
EYQNPT-LPPNTLAAETAQQ----------------------------------------
-----IVNEMEKNSSMY---LQKMDDRVVSESDEEVETDEEEQDGKEELFDSAALAALLK
AASSGGTSD-NTITI--SPSDAPRLFSSDPPAG-----LGSSMPSLRP--TPR---QNRP
NI-FTQAEVAALGDQDTTMDEEEKKLHEKIQNIRVKFLRLVHRLGHSSEDVVAAQVLYRL
GLAEGIKRGWHGRR--GVGLEAAKQEAKQLETD---------------------------
-----GG--SPLD-FSCTILVLGKTGVGKSATINSIFG-------E----TKARTNA---
----------------------------------------FEPSTPT-VREINGVLNGVK
VKI--IDSPG----LMP-SVMDQSANKKVLLS--IKKFTKRCPPD-----------IVLY
VDRLDTQSRD-YNDLP-LLRSITSTLGA-----SIWFNAIVALTHAA-------------
--CAPPDG------------------------ANGAPLSYEVFVAQRSHVV---------
---------QHSIRQAAGDMR------LMNPVSLVENHPSC-RKNREGHKVLPNGQAWRP
QLLVLC------------------YSSKI--------LSEANALLKLQDSSP-GKL-FGL
RIRSPPLPFLLSSLLQSRPHPKLATDQGGDNGDSDIDLDDISDSDQE-GDEDEYDQLPPF
KPLKKAQLAKLSKDQRKAYFEEFDYRVRLLQRRQWKEELQQIKKAKKRASA--GESIVSE
FP-N--EDYDVGPAAVPVPLPDMVLPPSFDGDNAGYRYRFLEPSSHLLSRPVLDTHGWDH
DCGYDGVSLEETLAILNKFPAALSVQITKDKREFNIHLDSSVSAKHG-EHGSSMAGFDIQ
TVGKQLAYIFRGETRFKNFYKNRTGAGFSVTILGDTIATGLKIEDRLPIGKRLNLVGSAG
GVQAGSDLACGANLEVRLREGDYPIGQDQATLGLSLMRWRGDLALGANLQSQFSIGRNTK
MAARVGLNNKMTGQITIRTSS--SEQVQIALFGIIPLAALLFRSL--W----GGRESQFG
R---
>atToc159_AT4G02510.1|PACid:19644015
MDSKSVTP--EPTNPFYASSGQSGKTYASVVAAAAAAAADKEDGGAVSSAKELDSSSEAV
SGNSDKVGADDLSDSEKEKPNLVGDGKVSDEVDGSLKED---------------------
-----------STTPEATPKPEVVSGETIGVDDVSSLSPKPEAVSDGVGVVEENKKVKED
VEDIKDDGESKIENGSVDVDVKQASTDGESESKVKDVEEEDVGTKKDDEGESELGGKVDV
DDKSDNVIEEEGVELTDKGDVIVNSSPVESVHVDVAKPGVVVVGDAEGSEELKINADAET
LEVANKFDQIGDDDSGEFEPVSDKAIEEVEEKFTSESDSIADSSKLESVDTSAVEPEVVA
AESGSEPKDVEKANGLEKGMTYAEVIKAASAVADNGTKEEESVLGGIVDDAEEGVKLNNK
GDFVVDSSAIEAVNVDVAK-PGVVVVGDVEVSEVLETDGNIPDVHNKFDPIGQGEGGEVE
LESDKATEEGGGKLVSEGDSMVDSSVVDSVDADINVA----EPGVVVVGAAKEAVIKEDD
KDDEVDKTISNIEEPDDLTAAYDGNFELAVKEISEAAKVEPDEPKVGVEVEELPVSESLK
VGSVDAEEDSIPAAESQF-----EVRKVVEGDSAEEDENKLPVEDIVSSREFSFGGKEVD
QEPSGEG-----------------------------------------------------
-----------------------------------------VTRVDGSESEEETEEMIFG
SSEAAKQFLAELEKASSGIEAHSDEAN---------------------------------
-----ISNNM----------SDRIDGQIVTDSDEDVDTEDE---GEEKMFDTAALAALLK
AATGGGSSEGGNFTI--TSQDGTKLFSMDRPAG-----LSSSLRPLKPAAAPR---ANRS
NI-FSNSNVTMADETEINLSEEEKQKLEKLQSLRVKFLRLLQRLGHSAEDSIAAQVLYRL
ALL----AGRQAGQ--LFSLDAAKKKAVESEAE---------------------------
-----GN--EELI-FSLNILVLGKAGVGKSATINSILG-------N----QIASIDA---
----------------------------------------FGLSTTS-VREISGTVNGVK
ITF--IDTPG----LKS-AAMDQSTNAKMLSS--VKKVMKKCPPD-----------IVLY
VDRLDTQTRD-LNNLP-LLRTITASLGT-----SIWKNAIVTLTHAA-------------
--SAPPDG------------------------PSGTPLSYDVFVAQCSHIV---------
---------QQSIGQAVGDLRLM-NPSLMNPVSLVENHPLC-RKNREGVKVLPNGQTWRS
QLLLLC------------------YSLKV--------LSETNSLLRPQEPLD-HRKVFGF
RVRSPPLPYLLSWLLQSRAHPKLPGDQGGDSVDSDIEIDDVSDSEQEDGEDDEYDQLPPF
KPLRKTQLAKLSNEQRKAYFEEYDYRVKLLQKKQWREELKRMKEMKKNGKK--LGESEFG
YPGEEDDPENGAPAAVPVPLPDMVLPPSFDSDNSAYRYRYLEPTSQLLTRPVLDTHGWDH
DCGYDGVNAEHSLALASRFPATATVQVTKDKKEFNIHLDSSVSAKHG-ENGSTMAGFDIQ
NVGKQLAYVVRGETKFKNLRKNKTTVGGSVTFLGENIATGVKLEDQIALGKRLVLVGSTG
TMRSQGDSAYGANLEVRLREADFPIGQDQSSFGLSLVKWRGDLALGANLQSQVSVGRNSK
IALRAGLNNKMSGQITVRTSS--SDQLQIALTAILPIAMSIYKSIRPE----ATNDKYSM
Y---
>Amborella_trichopoda_gnl|BL_ORD_ID|12687 evm_15.model.AmTr_v1.0_scaffold00072.35 EVM_15_evm_15.TU.AmTr_v1.0_scaffold00072.35   AmTr_v1.0_scaffold00072:1761957-1764089(+)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MED--
-----------CHSSHHYPDGKSSDILEKLDALQVNFLRLVHRLGQSSQNLVVAQVLYRL
ELTKQIRASNSNAKRVGLSIDRAKAIAREQETA---------------------------
-----GQGGSELD-FSIKVLLLGKTGVGKSATINSIFN-------Q----AKVFTDA---
----------------------------------------FQPATEK-IEEIAGTVMGVK
VKV--IDTPG----LLP-SPSDQRLNRRTLRT--VERFIRKSLPD-----------IVLY
FDRLDIINMG-YSDFP-LLKLITETFGS-----AIWFNTTIVLTHSS-------------
--SALPEG------------------------PDGTSLVYEAFVAQCKNIM---------
---------QHHIHQAAADTR------LRNPLLLVENHPLC-VRNREGEKVLPNGQAWRS
QFLLLC------------------ISSKV--------LNDANALLKFQD-VH-GKQ---N
NQRRPSLPHLLSSFLQPCSAPNASDLMLIDEVGEEVT-----DLE----SEDEYDKLPPI
RILSKGQFKRLSKAQKEDYLDELDYQETLYLKKQLKEELRKCRDGLSIN-----------
---DTDGHNEGEPPPDTLPLPDMAMPLSFDSACPTYRYRFLEYSNKWLVRPVLDPHGWDQ
EIGFNGVNLEASFPIEKNLNTSLNSQLSKDKQDCNFQMECAATHIKE-KGPSYYTGLDVQ
NLGRGLACTARGHMQLKTHKYNKAGCGFLMGSIGSNVFVGAKLEDT-IAKKRWKLVVDTG
VMASQGNMTFGGRLEASLRGKDYPVRRDQASVSLTMLSCNKEVLLEGGLSVQFRPARGTN
MAIQANVNHKKSGQICVKGNS--SEHIQIASIAIIPIVRALFRRREIQHGHPVTD-----
----
>Amborella_trichopoda_gnl|BL_ORD_ID|7457 evm_15.model.AmTr_v1.0_scaffold00036.127 EVM_15_evm_15.TU.AmTr_v1.0_scaffold00036.127   AmTr_v1.0_scaffold00036:4818376-4824545(-)
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------KTFKDW
I--SW-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------KSLLSARPLSGSDSFLEEDETRRHEDVDVAGTP-------
-----------------PGSSGTASTTSACPANGIQ--SSASCPYFPP-----VVMED--
-----------CHSSPHYPDGKSSDILEKLDALQVNFLRLVHRLGQSSQNLVVAQVLYRL
ELTKQIRASDSNARSVGLSIDRVKTIAREQETA---------------------------
-----GQGGSELD-FSINVLLLGKTGVGKSATINSIFN-------Q----AKVFTDA---
----------------------------------------FQPATEE-IQEIIGTVMGVK
VKV--IDTPG----LLP-SPSDQRLNRRNMHT--VKRFIRNSPPD-----------IVLY
FDRLDVINMG-YSDVP-LLKLITETFGS-----AIWFNTIIVLTHSS-------------
--SALPEG------------------------PDGTSLGYEAFVTQCKNIM---------
---------QHHIHQAAADMR------LRNPLLLVENHPLC-IRNREREKVLPNGQAWRS
QFLLLC------------------ISSKV--------LNDANALLKFQDVVH-GKQ---N
NQRRPSLPHLLSFFLQPCSAPNASDLMLIDEVGEEVS-----YLE----SEDEYDKLPPI
RILSKGQFKRLSKAQKEDYLDELDYRETLYLKKQLKEELGKCRDGSSIN-----------
---GKDGHNEGEPPPDTVPLPDMAMPLSFDSACPTYRYRSLEYGNKWLVRPVLDPHGWDQ
EIGFDGVNLEASFPIVKNLNTSLNSQLSKDKQDCNFQMECAATHIDE-KGPSYYTGLDVQ
NLGRGLACTARGHMQLKTHKYNKAGCGFLMGSIGSNVYVGAKLEDT-IAKKRWKLVVDTG
GMASQGDMTFGGRLEGSLRGKDYPVRRDQASVSLTMLSCNKEVLLEGGLLVRFRPARGTN
MAIQANVNHKKSGQICIKANS--SEHIQIALIAIIPIVRALFRRRAIQHDPPVTDR----
----
>Toc90_gi|75291915|sp|Q6S5G3.1|TOC90_ARATH RecName: Full=Translocase of chloroplast 90, chloroplastic; Short=AtToc90; AltName: Full=90 kDa chloroplast outer envelope protein; AltName: Full=Plastid protein import 4
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------KGFKDWVFALSNSMASSRPLLGSDPFFRDPHQEQDNHSQ------------
-----------------APAAPQPVTLSEPPCS-----TSSDLEILPPLSQQQVPLES--
-----------LYQSSIDLNGKKHNPLAKIGGLQVQFLRLVQRFGQSQNNILVSKVLYRV
HLAMLIRAEESELKNVKLRQDRAKALAREQESS---------------------------
-----GI--PELD-FSLRILVLGKTGVGKSATINSIFG-------Q----PKSETDA---
----------------------------------------FRPGTDR-IEEVMGTVSGVK
VTF--IDTPG----FHPLSSSSTRKNRKILLS--IKRYVKKRPPD-----------VVLY
LDRLDMIDMR-YSDFS-LLQLITEIFGA-----AIWLNTILVMTHSA-------------
---ATTEG------------------------RNGQSVNYESYVGQRMDVV---------
---------QHYIHQAVSDTK------LENPVLLVENHPSC-KKNLAGEYVLPNGVVWKP
QFMFLC------------------VCTKV--------LGDVQSLLRFRDSIGLGQP---S
STRTASLPHLLSVFLRRRLSSGA------DETEKEIDKLLNLDLE----EEDEYDQLPTI
RILGKSRFEKLSKSQKKEYLDELDYRETLYLKKQLKEECRRRRDEKLVE-----------
---EENLEDTEQRDQAAVPLPDMAGPDSFDSDFPAHRYRCVSAGDQWLVRPVYDPQGWDR
DVGFDGINIETAAKINRNLFASATGQVSRDKQRFTIQSETNAAYTRNFREQTFSVAVDLQ
SSGEDLVYSFQGGTKLQTFKHNTTDVGVGLTSFGGKYYVGGKLEDTLLVGKRVKLTANAG
QMRGSGQTANGGSFEACIRGRDYPVRNEQIGLTMTALSFKRELVLNYGLQTQFRPARGTN
IDVNINMNNRKMGKINVKLNS--SEHWEIALISALTMFKALVRRSKTEMTEENEEEKIVN
FLVS
>Amborella_trichopoda_gnl|BL_ORD_ID|10104 evm_15.model.AmTr_v1.0_scaffold00056.107 EVM_15_evm_15.TU.AmTr_v1.0_scaffold00056.107   AmTr_v1.0_scaffold00056:2387752-2412981(+)
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------AAQLIREWSGIQQFPTATQTKLLELL---------------------------
-----GKLKEENV-STVTILVMGKGGVGKSSTVNSLLG-------E----RVAAVSA---
----------------------------------------FQSEAMRPIICSRAR-AGFT
LNI--IDTPG----LVE----GGFVNEHALEI--IKRFLLNKTID-----------ILLY
VDRLDGYRVD-NLDRQ-VIKAITDSFGK-----GIWQRGLVVLTHAQ-------------
--LSPPDG-----------------------------LSYDEFFSRRSEAL---------
---------LKVV-RLGGQIRRQELEARPVPFVLVENSGRC-NTNDIGEKILPNGTAWLP
ELVKT-------------------ITEVV--------LNGSKPILVDQKLIEGPDPNSKG
RFLIPFILAFQYFLVVKPIKGAIKGDIARESKPLWELRDLGLAKRQF-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Marchathia_polymorpha_gnl|BL_ORD_ID|3862 T20061:5109  (A)
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------ATTQVREWTGLQQFPAQTQTALHALL---------------------------
-----GRLRLESM-ESLTVLVLGKGGVGKSSTVNSLVG-------E----RVAVVSA---
----------------------------------------FQSETLRPIQCSRSR-AGFT
LNI--IDTPG----LVE----GGCVNDQALDI--IRRFLLNKTID-----------AVLY
VDRLDGYRVD-NLDKQ-VIRAIARSFGP-----EIWRLGLVVLTHAQ-------------
--LSPPDG-----------------------------VEYSDFVARRSAAL---------
---------TAAIRQEAG------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanophora_paradoxa_gnl|BL_ORD_ID|516 _ConsensusfromContig10710-snap_masked-ConsensusfromContig10710-abinit-gene-0.1-mRNA-1:cds:3832/1722-1917:0:+
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------PLRTPRYLDPVESMWDRLC---------------------------
-----TSAKLERA-EVLTVLVIGRSGVGKTALVNTLFA-------DEPS-KIKPTSP---
----------------------------------------FEHKPSEGFARVRSAYHGVS
IQF--VEE------TLPMGEPGDPQEEAMARR--VQKLYRRAGAEGEIF-------LLVF
VDRLDGARELNS-----ALAVVTDTLGT-----AAWARSMVVLTHGQ-------------
--TLPPPD-----------------------------STFADFVKQRRETA---------
---------TLALRRAAR------NKQLSVNVVVVDNAREG-LRSAEGHRVLPFGVPAWA
NIGPCVPALLEA------------AAESV--------ANSMPEA----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|3128 _gnl|CMER|CMP284C similar to chloroplast outer membrane protein Toc34
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------DSETPTKNEAEQRASPDRTGQVTQRPVSLFRKNGTFAYPLEDSDV----
----------YEEQVLALEDVPEPTAQAILRLA---------------------------
-----LAAERQGV-PRLRFLVVGAPGVGKSSLINTLLN-------E----NLCSVSA---
----------------------------------------WERGTKNAQVCARQV-DSVV
IEF--IDTPG----IAPCRRSGLEASRRQVQR--LRKLLDARGADEHPYLRSFH--AILY
VMRLDDTRPD-LVDYH-NWKVLMEFFGA-----EVLRHMMVVFTHGQ-------------
--SLPPDS-----------------------------LSYPEYVRGRRDYV---------
---------YLLIERLTG-----PLKAVRFPVFVAENSSKCPVIEETGERKLPDDTPWIT
QLYDGIRRFVFPLEADLFGMETGPEDTQV--------LVYIYDKRRSRADERYPRSPLQA
LIRNPW------------------------------------------------------
------------------FLRAVQFCGAMLLRSYMIRQEHERFNPKPHHPEPIIRDANNA
FAVASRRANDHRLFTPSIDEDEESFFRMNGNDDFVSRLRNRPGEVDLDELDVERIESPDG
RFVEYWYTEKDNPEMVRMYRLEIRDDPNEERESRQDRIPISKDQH---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|3286 _gnl|CMER|CMQ137C similar to chloroplast outer membrane protein Toc34
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------TESFT
SPQTREQVRLDFAERVEPRGDDAAERRDVSGRRTADSDKTTRGSRPSTGRTRSRRRQLFR
RNLLPGVLSQSRKGTESEGHGAENAADGEFFISDERHLYNMGIHVKQELNLSRLAALVVT
SPAPYSKDLKESGSSWQQGPSPTLSDKPSLSEVCGEQPWGAIPDATEKALERLCLLWIAR
KTGASESSSNGLRAVLSDPNVFLHIAGIDAPCS-----------------------GDAR
NLDSMRRCIQLFLDSARNAGLDANALFEPEDVIEGKNLHLACKVLCAYAEKTDSEAFTAC
MKQVGLQRRNYEEIIRGFGNDSRPGCATVNQLV---------------------------
-----DVVRAHSPFRDATILFAGTIGAGKSATINRILG-------S----PVARTNHTMA
LILSDDEILERDPEHGLEVIEERSYEREREQRAHPNRKTEFVPSPNENVLIYPVEKEGMS
LRL--IEIPSSEKYFYDEAGEDSKKWSRAGTCESVAAALRGLEID-----------IVCI
IERLDSYRSHCFRL---VLEELKSLFDG-----GVWERCILVFTHGY-------------
--ALPPEG-----------------------------LTFEENLARRMHLA---------
---------QEEVHRVSG------RRDIFIPVCVVENSESC-PRDSAGNLILPNGISFLD
RFVTIGENVFLRNRDRPRLKVRSLVPSHVRVRHIGFILSSVLILQMLRNGPQDGRANPLA
RDKAFLPAF---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|4539 _gnl|CMER|CMT043C GTP-binding protein of Nug1 family
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------APHRHSKRETLKHKYKVQRKVAEHNRRMRRLARKQRQEGIIKGQRKA
QRELGVPNLYPYKKQLLEQAARRLALRSTVTAEAGSLGESPVSAPALSGANALGKTPVFR
EVARS-------------------------------------------------------
-----RRSFAAALRRVVELSDVVVEVLDARNPLESRSSALELLVRHEGARAAGGKRLILV
LSKADLVPREALQAWLCRLRAEYPTLAMHEGLDQTGQHRGPRQPGSAVQPKQLSQLVQLL
KLYAKRRADKQSSSSTITVGIVGKPNVGKSSLLNALCR-------E----QGAVATG---
----------------------------------------ARPGITKTLQEVRLDS---N
IRL--LDSPGVVLDDVQEIDPAPVVEVEQTKAAGSPEPVANATSG---------------
--SRDESRMALAGFL--AVEELSDPVAA----------ARLVLERCQ-------------
---YNADGALSLLYEMPAFSMCDMVAANEATREESFATQFLALFAKRRGLL---------
--------------------------------------------RKAGVLDLEAAARVLV
QDWATGRIPYYTLPKHVGLPSSQQLGAQI--------VSNWDNAFDLDVCEPSPSAEEVV
MDENPA------------------------------------------------------
------------------------------------------------------------
------------TDAAPLSVADVDDEVVFHVWKHKTRRERQTFALPLSPGAAVENVAADA
DLEDFEFSTTS-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|635 _gnl|CMER|CME151C GTP-binding protein of Nug1 family
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------HVKRNFQVTHTSPGSQQARAERLEFLPQKRST
GNSPRARGPAFTDSARVSSRVQVFHTALAFCSVQGWLAGRPVWSATRQCSQRPARERGMR
YLRVQRTRGIALNLYGNQALPSDEALPPGMPPPVSSWFPGHIAKAMRELRDRLSLIDVVI
EVVDARIPRTTFPQFVHDIL------------------GTKSRVIALNRTDMVPVAASRH
WLAAFRRGALDRASAASQVEHQANAPCYPTDGKLGTGIPQLRRACIAAGKTVNERRARRG
LLS---------------------------------------------------------
--------------RPIRVAVIGYPNVGKSAVINRLCN------------RRAAVSA---
----------------------------------------ARPGVTRQLQWVRI---AQD
LEL--LDTPGVIPPKLEEQDAASRLA----------------------------------
-----------------MCDDIGETAYDVERIASLLIDTLLTLDGSS-------------
------------------------------------WIEHPSLPANERHAV---------
---------RSILQHRYGFTDFQNGEDFLYLAARQCTQRDVDK-----------------
------------------------MARRL--------LTDFRQLHLGRICLEPCKTD---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanophora_paradoxa_gnl|BL_ORD_ID|7261 _ConsensusfromContig38626-snap_masked-ConsensusfromContig38626-abinit-gene-0.1-mRNA-1:cds:8427/102-119:0:+
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------KTVDGLAPDAETLEFFANAVIRDVRFVKGATNEQQLITD-
------------------------------------------------------------
--------------GTAEVSVI-LSNVGKSSLVNTLVG-------R----KDLARSS---
----------------------------------------KKPGKTREFNYFAV--NGKS
LYL--VDLPGLY------ASVSQAQREDWFRF--IDDYLRLPPPH-----------ELLY
PGEKVDVPGP-------LDLHVMDIASG-----RIGITKYVVLSEHG-------------
------------------------------------------------------------
------------------------HDAEATPVVVCSSSEKWGRDEARSG-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|103 _gnl|CMER|CMB003C similar to GTP-binding protein
MGLSHVRAAVVLAGRPNVGKSVLFNRLVGKASSLVDPRAGCTRDVRSAYGRLVDLRFRLF
DTPGLEWLPERVQRGRLPAANSLPNSKAAFGD----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------SGPNLMQQFAHSLEY
SVAYESLYARVLQLTERFLRTLSSRAKDRTLALFLVDASQGVVAADHQIASLLRRLALPT
VLVLNKCDMRAADSGTVASFAELGFPSSVPISALQGEGFSDLYHAMQPLVDHMNSDETVE
ACRANAHICDIPRKRDAECAANTHPVQPEREFACGH--AASTLSHDGTTSHAGLVWNTNG
AALIASQDTRLAPSAQRLALESSPSSIDETTTCAADARSVHQTSPHDPQGTLPARYLT--
----------------STDTAPVSGDPMMDEID---------------------------
-----SPAVAANS-HQIRLTIVGRPNVGKSTLANALLG------------YERFLTA---
----------------------------------------PFPGVTRDAVTVASSRYG-G
FLV--TDTAGARRRTAVAGSRAADAAPDPLETGAYAQMLTSIATATACGLVLDAAEIALA
LQQSKDPRRLLTSMEHSLIQEATELQGK---------PLLLVLNKTD-------------
--LLENKE----------------------------------------------------
---------QQRNVERAIRTRLQSSAPEARHAPIIGLSAACLSEDDAGSLFCTVRELVHL
WSGSWSRGELSQWLFQATRRYSPPVHAKF-------------------------------
------------------------------------------------AYMIQTGRRPPV
FTIFGVAEHYLSPVYRRTLLNALKLDFGLQKVPVKLCFRSH-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|1830 _gnl|CMER|CMK223C similar to mitochondrial GTP binding protein trmE
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----QRTRSLAASVQSLARSLRSKQLRPYQKVTQHANRVETVSLGSLSYCASVVTRYLCS
AAQKAAGAAGTRPTIYALATAPGTGAIAVFRISGPETRQVLQAVLHVPAQKLPQPRQLVP
RTLYDPQRNYAFDRGMVVWFPAPASYTGEDMAELQVHGAPAVIRAALVALAGYPGLVPAT
AGAFTKRALTNGKMDRSQVEALAHIIQADSLDGL----ALAVNNLQGALRSQHHSWRAHL
HAAMAIMEAVLEFGEEHLAHEIDAQLEQAAQRIRAVQAEMRMQIRLASPEGQRPELS---
------------------------------------------------------------
--------------LTPRIVLYGRVNAGKSSLFNLIGQ------------REASIVH---
----------------------------------------ETPGTTRDVVEQRAYIDGLA
ATI--MDTAG----LRETPQTASAIEAEGIRR--ARKVIEQTPLR------------VLV
VDASTEEECSLEHDPT-----------------AAWLPSAVVLHKAD-------------
--LVPDHQQREALRNRFSRCYRESDLFFVSSRTGEGVDAFLNWLGERLRARFECAKDTDQ
RRCLIQTQRQHALLRVVHDLLDGALQHLIVPELAVEHLRSSLQ-----------------
------------------------HLAEI--------SGEGDRRFDAEDTLEHIFSRFCI
GK----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|2550 _gnl|CMER|CMN201C GTP-binding protein of Era family
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MFLQASGLLLGFPYRQSKNKFLCISRVVPV
RGSRFLRPQRHPGGVLKVRGEGRSDLEASETRR---------------------------
-----GDLSVAPESRCCFVSILGPSNTGKSTLVNAMVG-------S----KVAIVSP---
----------------------------------------KVQTTRFQVRGIAIE-ETLH
AQIVFIDTPGVFLPKRKFDQAMVKSAWEASRG------------------------ADIV
LVMLDGNRYHHFRKLSHAETSIAERLSRIDKEELAKTPILLAVNKID-------------
--LIPRKD----------------------------------LDAVRDGLL---------
-------------HEMGGPERIREVHQIS-------------ARTGEGVFELRRRIAELA
PLGPWHYDREQLTDIPERLLAAEVVREQL-------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------YLQLRQELPYECAVETERWES
KEDGSVVIGCVIYVKRQSQKAIVTGAGGVRIKSIGVKARMELERLLGRRVHLLTLIKCRK
WDENPVLYRQMGLDFRA-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|215 _gnl|CMER|CMB146C conserved GTP-binding protein of unknown function (Nucleolar GTP-binding protein)
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------TVGGLKHIQVVPEALDLIDIVL
SQTQRKTPTVVHPGYAITRIRTFYIRKVRYAQSCFHERLTKILSDFPILEELHPFYADIL
NVLYDRDHYKLALGQV-----------SRIRSLVDSFARDYVRQLKYADSLYRAKCLKRA
ALGRMCTTVKHLRPALAYLEQVRQHMARLPSID---------------------------
------------P-MTRTLLIAGYPNVGKSSFLNCVTN-------A-----KVDVQP---
----------------------------------------Y-AFTTKSLFVGHMDYQYLR
WQV--IDTPG----LLD--HALDERNTIEMQS--ITALAHLQAA------------ILFF
VDPSETCGYAIAQQLA-LLRSLQPLFAD--------KPLFVVCNKTD-------------
--LGWEQQ-----------------------------LDPATWTAIRETAE---------
---------QVGAELMTA-----------STMGDDGYASVFAVRNRACERLLALRVSLKV
SGRQTDSVLNRLHVAEPKLVRTPQIPASV--------LERRQALRDADDALNQNTA----
-------PELACTLSTSRAGRKTERELERDHGGAGVYSMDWRKHYDLTDPAWRYDYIPEI
VDGKNIADYVDPEIHQRLLALEQEETMRQSMLSDAVGDEPRADVPVDQPS----------
---------------------DTDVALIREKARNQRRLRQQQAARDRTQRPKLSRKALLK
------VRKTSQAVAKRPWGRAVDPSTTKQQTRKAAHSAPVVYRTRAVSDQSLVPAGLRD
VVQARHAQKLVQRTLRRAFSGREHRQGESDRFIGTRKPHHLFAGKMSLGTRSHR------
------------------------------------------------------------
------------------------------------------------------------
----
>Marchathia_polymorpha_gnl|BL_ORD_ID|6944 T20061:8541  (A)
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------G-PRGDVWVIGAQNVGKSSLINALGKITTEEKEKEK-KKVFLTEA---
----------------------------------------AVPGTTVGVVKLEGILPG-R
ARV--LDTPG----LLHPHQITTRLTREEQKMVQIRKVLKPRTFRVKVGHAISVGG----
-----------LMRMT-VVKAPADSIYA-----TIWASAFIPCHMGQAEKSAELFERHVG
DKLTPPSS-------------------------KDRVEELGRWVSRTVQIS---------
---------GEKWDQSSVDIAVAGVGWIAFALSGAATLEVC-------------------
------------------------TWEGV--------AVTVREAMVFDMAAVFXRPGFTA
L-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanophora_paradoxa_gnl|BL_ORD_ID|5720 _ConsensusfromContig36989-maker-ConsensusfromContig36989-snap-gene-0.1-mRNA-1:cds:4839/4192-4222:0:+
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------NPEYD-YLFKLLLIGDSGVGKSCLLLRFAD-------D----TYTESYI---
----------------------------------------STIGVDFKIRTIELDGKTIK
LQI--WDTAG----------------QERFRT--ITSSYYRGAHG-----------IIIV
YDVTDQES---FNNVK-QWLQEIDRYAC------EGVSKLLVGNKSD-------------
--LTTKKVVQYEVAKEFADSLGIPFLETSAKNSTNVEAAFM-------------------
--------------------------------TMAAEIKAMTKNDVTAGGDKKKGVELGK
SKPVEKGGPLAVFCAYCILQDYALLSRDLRIRTWLHRVISIIQSYIAKLPVKFRTSAKAL
MSSLLASSRPADWRHASIPE----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Marchathia_polymorpha_gnl|BL_ORD_ID|1630 T20061:1707 K07910 Ras-related protein Rab-18 (A)
S-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------GAEID-HIFKLLLIGDSGVGKSSLLLRFTA-------D----TFDDLSP---
----------------------------------------T-IGVDFKLKLLTMSGKRLK
LTI--WDTAG----------------QERFRT--LTSSYYRSAQG-----------VILV
YDVTRRDT---FTDLSDVWLKEVELYST-----NPDCIKMLVGNKVD-------------
--RDAERVVSKQEGIAFARQYGCLFLECSAKTRANVQLCFEELVQKILDTP---------
--------------------------------SLIADTKAFKKNLLRPDEPYTPQSAPGA
GNCTC-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanophora_paradoxa_gnl|BL_ORD_ID|23928 _ConsensusfromContig39250-snap_masked-ConsensusfromContig39250-abinit-gene-0.1-mRNA-1:cds:8596/888-1117:1:-
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------QVEGGVFSGVC
VPDRSFFGSAPYLRRRAHASLRSTWESRSGVVRAQKPEPDQNQEELERPSTPALDIQRGI
IHQEHDPESSQVDFALLWQNFKTIALPYWNQDKWKARGSLAGLIALGLMQSGISVTYSFV
GRDFWNALAAKDSDLFFKQLAIYACFTVGTPIVVMYGYFRDSVSIAWREWLTKEFLAYLE
GRSYYNLGALSRGAGAEEIDNPDQRICEDVLQFADASLAFFLVLLNSVVDLVSFSGILWS
IYPPLWVVLLFYSAFTGVTTLFGRRLVNLNFAQLKREADLRFSLIRVRENAESIAFFGGE
GQEGRVLGTRLEAIILPAAVVAPLYFAGRFEIGVVQQAYSAFNHVLGDLSVIVNQVKALS
AFSAGVSRLGEFDAALAAASSAAPSTLPAASAPVPAAPSRAPLLASIAAPTQLPEIPAAA
SAAGP-------------------------------------------------------
----------------------------------------------SAAAAAAGPSRIEM
RYNGVHAGDGGAGPVLAMRGVGLQTPDRAKYLV---------------------------
-----RELSLELE-RGGRLLIVGDSGSGKSSLLRAVAGLPQRPYMTVGSLRAQLLYP---
----------------------------------------FDDGTEAAGAAGEAGSSR--
-----TEAAGGSRTEADVAEAHRSVSDDELLA----------------------------
-----------------------------------------ILQQAR-------------
--PAPPPA----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Cyanophora_paradoxa_gnl|BL_ORD_ID|15552 _ConsensusfromContig9504-snap_masked-ConsensusfromContig9504-abinit-gene-0.0-mRNA-1:cds:2478/440-548:0:+
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------VAMEAV
QHVLSPVGESVQSSEAAVERAYECPICHEVPDLLQPNAELRAAVARDCPNAYDERARA--
------------------------------------------------------------
--------------NASSVLFVGSTGSGKSAAINYLCG-------E----RVCGTNA---
----------------------------------------FERETQDVAWHARTLPAAGT
EDG--LDTG---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
