>atToc120_gi|332642323|gb|AEE75844.1| translocase of chloroplast 120 [Arabidopsis thaliana]
------------------------------------------------------------
---------------RVNGNVSHNQP-QQAEDSTTAETDEHDETREKLQFIRVKFLRLSH
RLGQTPHNVVVAQVLYRLGLAEQLR-GRNGSRVGAFSF----DRASAM--------AEQL
EAAAQ-DPLDFSCTIMVLGKSGVGKSATINS-IFDELK-ISTDA---------------F
QVGTKKVQD----IEGFV------QGIKVRVIDTPGLLP-SWSDQHKNEKILKSVRAFIK
KS----------------PPD---------IVLYLDRLDMQSRDSGDMPLLRTITDVFGP
SIWFNAIVGLTHAAS-APPDGPNGTASSYDMFVTQRSHVIQQAI--RQAAGDMR-----L
M----------------------------------------------------NPVSLVE
NHSACRTNRA-GQRVL---PNGQ-VW---------------KPHLLLLSFASKILAEANA
L-LKLQDN-IPGGQF----------------ATRSKAPPLPLLLSSLLQSRPQAKLPEQQ
Y-DDEDD-ED----DLDESSDSE-EESEYDELPPFKRLTKAEMTKLSKSQKKEYLDEMEY
REKLFMKRQMKEERKRRKLLKKFAAEI-KDMPNGYS-ENV-EEERSEPASVPVPMPDLSL
PASFD-SDNPTHRYRYLDTSNQWL-VRPVLETHGWDHDIGYEGVNAERLFVVKDK-----
IPVSFSGQVTKDKKDAHVQLELASSVKHG-E-------GRSTSLGFDMQNAGKELAYTIR
SETRFNKF--RKNKAAAGLSVTLLGD-------SVSAGLKVEDKLIAN---------KRF
RMVMSGGAMTSRGDVAY---------GGTLEAQFRDKDYPLGRFLSTLGLSVMDWHGDLA
IGGNIQSQVPIGRSSNLIARANLNNRGAGQVSIRVNSSEQLQLAVVALVPLFK---KLLT
YYSP-EQMQYGH---------------------------------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|12951 _479127|PACid:16046698
------------------------------------------------------------
---------------RVNGNVSHNQP-QQAEDSTTGETDEHDETREKLQFIRVKFLRLSH
RLGQTPHNVVVAQVLYRLGLAEQLR-GRNGSRVGAFSF----DRASAM--------AEQL
EAAGQ-DPLDFSCTIMVLGKSGVGKSATINS-IFDELK-ISTDA---------------F
QMGTKRVQD----IEGFV------QGIKVRVIDTPGLLP-SWSDQHKNEKILKSVRAFIK
KN----------------PPD---------IVLYLDRLDMQSRDSGDMPLLRTITDVFGP
SIWFNAIVGLTHAAS-APPDGPNGTASSYDMFVTQRSHVIQQAI--RQAAGDMR-----L
M----------------------------------------------------NPVSLVE
NHSACRTNRA-GQRVL---PNGQ-VW---------------KPHLLLLSFASKILAEANA
L-LKLQDN-IPGEQF----------------AARSKAPPLPLLLSSLLQSRPQAKLPEQQ
Y-DDEED-ED----DLDESSDSD-EESEYDELPPFKRLTKAEMAKLSKSQKKEYLDEMEY
REKLFMKRQMKEERKRRKLLKKFAAEI-KDMPNGYS-ENV-EEERSEPAAVPVPMPDLSL
PASFD-SDNPTHRYRYLDSSNQWL-VRPVLETHGWDHDIGYEGVNAERLFVVKDK-----
IPVSFSGQVTKDKKDANVQLELASSVKHG-D-------GRSTSLGFDMQNAGKELAYTVR
SETKFNSF--RKNKAAAGLSVTLLGD-------SVSAGLKVEDKLIAN---------KRF
RMVMSGGAMTSRGDVAY---------GGTLEAQFRDKDYPLGRFLSTLGLSVMDWHGDLA
IGGNIQSQVPIGRSSNLIARANLNNRGAGQVTIRVNSSEQLQLAVVALVPLFK---KLLS
YYYSPEQMQYGH---------------------------------------
>atToc132_gi|330251427|gb|AEC06521.1| translocase of chloroplast 132 [Arabidopsis thaliana]
------------------------------------------------------------
---------------RVNGNGSHNQF-QQAEDSTTTEADEHDETREKLQLIRVKFLRLAH
RLGQTPHNVVVAQVLYRLGLAEQLR-GRNGSRVGAFSF----DRASAM--------AEQL
EAAGQ-DPLDFSCTIMVLGKSGVGKSATINS-IFDEVK-FCTDA---------------F
QMGTKRVQD----VEGLV------QGIKVRVIDTPGLLP-SWSDQAKNEKILNSVKAFIK
KN----------------PPD---------IVLYLDRLDMQSRDSGDMPLLRTISDVFGP
SIWFNAIVGLTHAAS-VPPDGPNGTASSYDMFVTQRSHVIQQAI--RQAAGDMR-----L
M----------------------------------------------------NPVSLVE
NHSACRTNRA-GQRVL---PNGQ-VW---------------KPHLLLLSFASKILAEANA
L-LKLQDN-IPGRPF----------------AARSKAPPLPFLLSSLLQSRPQPKLPEQQ
Y-GDEED-ED----DLEESSDSD-EESEYDQLPPFKSLTKAQMATLSKSQKKQYLDEMEY
REKLLMKKQMKEERKRRKMFKKFAAEI-KDLPDGYS-ENV-EEESGGPASVPVPMPDLSL
PASFD-SDNPTHRYRYLDSSNQWL-VRPVLETHGWDHDIGYEGVNAERLFVVKEK-----
IPISVSGQVTKDKKDANVQLEMASSVKHG-E-------GKSTSLGFDMQTVGKELAYTLR
SETRFNNF--RRNKAAAGLSVTHLGD-------SVSAGLKVEDKFIAS---------KWF
RIVMSGGAMTSRGDFAY---------GGTLEAQLRDKDYPLGRFLTTLGLSVMDWHGDLA
IGGNIQSQVPIGRSSNLIARANLNNRGAGQVSVRVNSSEQLQLAMVAIVPLFK---KLLS
YYYP--QTQYGQ---------------------------------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|7943 _480549|PACid:16041690
------------------------------------------------------------
---------------RVNGNGSHNQS-QQAEDSTTVETDEHDETREKLQLIRVKFLRLAH
RLGQTPHNVVVAQVLYRLGLAEQLR-GRNGSRVGAFSF----DRASAM--------AEQL
EAAGQ-DPLDFSCTIMVLGKSGVGKSATINS-IFDEVK-FCTDA---------------F
QMGTKRVQD----VDGLV------QGIKVRVIDTPGLLP-SWSDQAKNEKILNSVKAFIK
KN----------------PPD---------IVLYLDRLDMQSRDSGDMPLLRTISDVFGP
SIWFNAIVGLTHAAS-VPPDGPNGTASSYDMFVTQRSHVIQQAI--RQAAGDMR-----L
M----------------------------------------------------NPVSLVE
NHSACRTNRA-GQRVL---PNGQ-VW---------------KPHLLLLSFASKILAEANA
L-LKLQDN-IPGRPF----------------AARSKAPPLPFLLSSLLQSRPQPKLPEQQ
Y-GDEED-ED----DLDESSDSD-EESEYDQLPPFKSLTKAQMATLSKSQKKQYLDEMEY
REKLLMKKQMKEERKRRKMFKKFAAEI-KDLPDGFS-ENV-EDESGGPASVPVPMPDLSL
PASFD-SDNPTHRYRYLDSSNQWL-VRPVLETHGWDHDIGYEGVNAERLFVVKDK-----
IPISVSGQVTKDKKDANVQLEMASSVKHG-E-------GKSTSLGFDMQTVGKELAYTLR
SETRFNNF--RRNKAAAGLSVTLLGD-------SVSAGLKVEDKLIAS---------KWF
RMVMSGGAMTSRGDFAY---------GGTLEAQLRDKDYPLGRFLTTLGLSVMDWHGDLA
IGGNIQSQVPIGRSSNLIARANLNNRGAGQVSVRVNSSEQLQLAMVAIVPLFK---KLLS
YCYP--QTQYGQ---------------------------------------
>Oryza_sativa_gnl|BL_ORD_ID|2601 _LOC_Os10g40110.1|PACid:21885073
------------------------------------------------------------
---------------RANGPVAVDRETRQDVESP-EDGDENDEIREKLQMIRVKFLRLAN
RFGQTPNNMVVSQVLYRLGLAEQLRRN---TGQGVFSF----DRAQDM--------AERL
EAAGN-EPLDFSCTILVLGKTGVGKSATINS-IFDDVR-LETNA---------------F
DTSTRKVQE----VVGAV------EGIKVKVIDTPGLSC-SSSDQHHNQKILNSVKRLIS
RN----------------PPD---------IVLYFDRLDMQTRDYGDVPLLQTITRVFGA
SIWFNAIVVLTHAAS-APPDGLNGIPLSYEMFVTQRSHVVQQAI--RQAAGDVR-----L
M----------------------------------------------------NPVSLVE
NHSACRTNRA-GQRVL---PNGH-VW---------------KPQLLLLCFASKVLAEANA
L-LKLQDN-PAGKP-------------------RMRIPPLPFLLSSLLQSRAPLKLPEEQ
F-GDDDDIED----DLADDSDSD-DGSDYDDLPPFKRLTKAQLAKLNHAQRKAYLEELDY
REKLFYKKQLKEERMRRKIMKKMAAEA-SARTDDFSNSNL-EDDGSAPTNVAVPMPDMVL
PSSFD-SDHPSHRYRFLDTPSEWL-VRPVLETQGWDHDVGYEGLNVERLFAVKGK-----
VPLSVSGQLSKDKKDCSLQMEVASSLKHG-E-------GKTTSLGLDLQSVGKDMAYTLR
GESRFKNF--RRNNTAAGISATLLGD-------SVSAGVKVEDKLVVN---------KQL
RVLVSGGAMSGRGDVAY---------GGRLEATLKDKDYPIGRMLSTIALSVVDWHGDLA
VGCNIQSQIPAGRASNLIGHANLSNKGTGQVGIRLNSSEHLEIALIALVPIYQNIKKLLQ
S--------------------------------------------------
>Zea_mays_gnl|BL_ORD_ID|19098 _GRMZM5G861756_T01|PACid:20838824
------------------------------------------------------------
---------------RASRPAAVDKGTQEATESAEDDRDENDDIHEKLQMIRVKFLRLAG
RLGQTSHNMVVSQVLYRLGLAEQLRR----TANGTFSI----DRAREM--------AERL
EAAGN-EPLDFSCTILVLGKTGVGKSATINS-IFDDIR-LDTNA---------------F
DSSTMKVQ-----VVGTV------EGIKVKVIDTPGLSC-SSFEQHHNQKVLNSVKRLIS
RN----------------PPD---------IVLYFDRLDMQSRDNGDVPLLQTITKVFGA
SVWFNAIVVLTHAAS-APPDGQNGIPLSYEMFVTQRSHVVQQAI--RQAAGDGR-----L
M----------------------------------------------------NPVSLVE
NHSACRTNRA-GQRVL---PNGQ-VW---------------KPQLLLLCFASKVLAEANV
L-LKLQDS-PIGKL------------------SHTRIPPLPFLLSSLLQSRAPLKLPEEQ
FGGDDDDLED----DLADDSDSD-DGSDCDDLPPFKRLTKAQLAKLNNEQRKAYLEELDY
REKLFYRKQLKEESKHRKLMKKMAAEA-SARGTDFSNSNL-EDDSNTPTNVSVPMPDMVL
PSSFD-SDYPTHRYRFLDTPSEWL-IRPVLETQGWDHDVGYEGLNVERLFAVKGK-----
VPLSVSGQLTKDKKDCSLQMEVASSIKHA-E-------GKTTSFGLDLQSVGKDMAYTIR
GESRFKNF--RRNNTAAGISATLLGD-------SVSAGLKIEDKLIVN---------KQL
RVLVSSGAMSGRGDVAY---------GGRLEA-IRDKNYPIGRLLSTIALSVVDWHGDLA
IGCNIQSQIPAGRASNLVGHANLSNKGTGQVGIRLNSSEHLEIALVALVPIFQNIMKLLQ
NYLESG---------------------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|13071 _Pp1s123_61V6.1|PACid:18049606
------------------------------------------------------------
---------------RPNGAPSTQLT-ATTEENANSDTAEGNETREKLQNIRVKFLRLAH
RLGQSPQNVVVAQVLYRLGLAESLRGGNTSNRAGAFSF----DRANAL--------AEEQ
EAANQEEELDFACTILVLGKTGVGKSATINS-IFDDRK-SVTSA---------------F
KPSTNKVQE----IVGTV------HGIKVRVIDTPGLLP-SVADQQHNERIMGQVKKHIK
KA----------------SPD---------IVLYFDRLDMQSRDFGDLPLLKTITDLFGA
AVWFNAIVVLTHASS-APPDGPNGVPLSYEMFVAQRSHVVQQTI--RQAAGDMR-----L
M----------------------------------------------------NPVSLVE
NHPACRTNRN-GQRVL---PNGQ-IW---------------KPQLLLLCFASKILAEANS
L-LKLQETATPGRPF----------------GQRSRVPPLPFLLSSLLQSRAQLKLPDEQ
L-DESDE-SD----DDEEEED-S-EADDYDELPPFRPLSKEELEELTKEQRQDYMDELAD
RERLFQKKQYREEMRRRKEMKKRQAQM-SKEELAQP-DEA-DDEAGQPAAVPVPMPDMAL
PPSFD-SDNPTHRYRYLETANQWL-VRPVLETHGWDHDAGYDGFNVEKMFVVKNK-----
IPASISGQVTKDKKESQVNFEAAASLKHG-E-------GKVTLTGFDVQTIGKDLAYTLR
AETRFNNF--KRNKTTAGVTATYLND-------TIAAGVKLEDRILIG---------KRV
KMVVNGGVLTGKGDKAF---------GGSLEATLRGKEYPLSRTLSTLGLSVMDWHGDLA
IGGNLQSQFMVGK-TMMVGRANLNNRGSGQVSIRASSSEQLQMVLIGIVPILR---SLIN
CRFGFGGGQSSQ---------------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|251 _Pp1s136_62V6.1|PACid:18036785
------------------------------------------------------------
---------------RPNGALSTQIT-STTDESASSDAAEGDETREKLQNIRVKFLRLAH
RLGQSPQNVVVAQVLYRLGLAESLRGGSAPNRSGAFSF----DRANAL--------AEEQ
EAANQEEELDFACTILVLGKTGVGKSSTINS-IFDERK-SVTSA---------------F
KPSTNKVQE----VIGTV------HGIKVRVIDTPGLLP-SVADQQHNERIMGQVKKYIK
KA----------------SPD---------IVLYFDRLDMQSRDFGDLPLLRTITDLFGA
AVWFNAIVVLTHASS-APPDGPNGVPLSYEMFVAQRSHVVQQTI--RQAAGDMR-----L
M----------------------------------------------------NPVSLVE
NHPACRTNRT-GQRVL---PNGQ-IW---------------KPQLLLLCFASKILAEANS
L-LKLQETTAPGRPF----------------GQRSRVPPLPFLLSSLLQSRAQLKLPDEQ
A-GESDE-SD----DDEEEED-S-DADDYDELPPFRPLSKEELEDLTKEQREDYMEELAD
RERMFQKKQYREEIRRRKEAKKRQAQM-SKEELAEA-EEA-EDEAGNAAAVPVPMPDMAL
PPSFD-SDNPTHRYRYLETANQWL-VRPVLETHGWDHDAGYDGFNVEKMFVVKEK-----
IPASVSGQVTKDKKEAQVNFEAAASLRHG-E-------GKVTLTGFDVQTIGKDLAYTVR
AETRFNNF--KRNKTTAGVTATYLND-------TIAAGVKLEDRVLIG---------KRV
KLVVNGGVLTGKGDKAY---------GGSLEATLRGKEYPLSRTLSTLGLSVMDWHGDLA
IGGNLQSQFMVGK-TMMVGRANLNNRGSGQVSIRASSSEQLQMVLIGIVPILR---SLIN
CRFGF-GGQSQQ---------------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|13091 _Pp1s123_63V6.1|PACid:18049626
------------------------------------------------------------
---------------SSNAASSTQVA-GTTDVNPSIEVNEVNETREKLQNIRVKFLRLVH
RLGQSPQNVVVAQVLYRLGLAESLRGGSTRNHTRAFDF----DRANAI--------AEEQ
EADNQEEELDFACTILVLGKTGVGKSATINS-IFDEHK-SVTNA---------------Y
NPSTTNVYE----VVGTM------LGVKVRFVDTPGLLF-SVADQRHNERIMGRVKKYIK
KA----------------SPD---------IVLYFDRMDMQTREFGDVPLLRTITNVFGT
AVWFNTIVVLTHAST-APPDGPNGTPMGYELFVAQRSHSVQQSI--RQVAGDMR-----L
Q----------------------------------------------------NPVSLVE
NHPACRANRN-GQRVL---PNGQ-IW---------------KPHLMLLCFASKILAEANT
L-LKLQDTAAPGRPF----------------GQRSRVPPLPFLLSSLLQSRAQLKLPDEQ
L-DESDE-SD----DDEEDEE---EGDEYDDLPPFRSLSKEELEELSKDQRQEYAEELAV
RERLFQKKQHREQLQRRKEMKKRATAM-RKEGLSHPADEA-DDEAGQPAAVPVPMPDMAL
PPSFD-SDNPTHRYRYLETANQWL-VRPVLETHGWDHDAGYDGFNVEKMFVVKNK-----
IPASISGQVTKDKKESQVNFEAAASLKHG-E-------GKVTLTGFDVQTIGKDLAYTLR
AETRFNNF--KRNKTTAGVTATYLND-------TIAAGVKLEDRILIG---------KRV
KMVVNGGVLTGKGDKAF---------GGSLEATLRGKEYPLSRTLSTLGLSVMDWHGDLA
IGGNLQSQFMVGK-TMMVGRANLNNRGSGQVSIRASSSEQLQMVLIGIVPILR---SLIN
CRFGFGGGQSSQ---------------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|232 _Pp1s136_59V6.1|PACid:18036766
------------------------------------------------------------
---------------RPNTASSTQSA-ATSDASISSESSEANEIREKLQNIRIKFLRLAR
RLNQSPQNVVVAQVLYRLGLAESLRGGSSLNRTRAFSF----DHANAL--------AEEQ
EAAKY-EDLDFACTILVLGKTGVGKSATINS-IFDECK-TVTSA---------------Y
YPSTTKVHE----VSGTV------LGVKVRFIDTPGLLP-STADQRHNKNIMRQVKKYIK
KV----------------SPD---------IVLYFDRMDMQTRDSGDVPLLRTITDVFGA
AVWFNATVVLTHASK-APPDGSNGTPMSYDYFVAQRSHFVQQTI--RQAAGDAR-----L
Q----------------------------------------------------NPVSLVE
NHPACRINRS-GQRVL---PNGQ-PW---------------KQQLLLLCFASKILAEANT
L-LKLQEASTPGKPF----------------GQRSRVPPLPYLLSSLLQSRAQLKMPDEQ
H-GESED-SD----DDSDEEDEE-EGDEYDDLPPFRPLSKQELEDLSKEQRQEYAEELAD
RERLFQKKQYREQIRRRRERKKQASVM-SKEEPSIPGDGA-EDESGQPATVAVPMPDMAL
PPSFD-SDNPTHRYRYLETANQWL-VRPVLETHGWDHDAGYDGFNVEKMFVVKEK-----
IPASVSGQVTKDKKEAQVNFEAAASLRHG-E-------GKVTLTGFDVQTIGKDLAYTVR
AETRFNNF--KRNKTTAGVTATYLND-------TIAAGVKLEDRVLIG---------KRV
KLVVNGGVLTGKGDKAY---------GGSLEATLRGKEYPLSRTLSTLGLSVMDWHGDLA
IGGNLQSQFMVGK-TMMVGRANLNNRGSGQVSIRASSSEQLQMVLIGIVPILR---SLIN
CRFGF-GGQPQQ---------------------------------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|6113 _170624|PACid:15407391
------------------------------------------------------------
---------------NPSGGSETTTA-VEAADTNGEPNDENVETREKLQMIRVKFLRLAQ
RLGQSANNAVVAQVLYRLGLAEQLRGGRSSSRNSAFRF----ERASAI--------AEEQ
EAAGQ-EELDFTCTIMVLGKSGVGKSATINS-LFDEAK-TETNA---------------F
AYSTKKVQE----ITGTV------HGIKLRVIDTPGLLP-AVADQRHNEKIMASVKRFIK
KS----------------PPD---------IVLYFDRLDMQSRDYGDLPLLRTITDTFGA
AIWFNAIVVLTHASS-APPDGPNGLPLSYEMFVAQRSHVVQQTI--RQAAGDMR-----L
M----------------------------------------------------NPVSLVE
NHSACRTNRS-GERVL---PNGQ-VW---------------KPQLLLLCFASKILAEANS
L-LKLQE-STPGKPF-----------------MRSKVPPLPFLLSSLLQSRPPLKHSDEN
A-VGEDD-TD----DDIEDVEDS-DEEDYDELPPFRRLTRDELDQLDKSSRDEYFEELQM
REKLFQKKQWKEEIRRRREMKKRAASSDSAEEYPAPVDDG-YDDDNKSAPVPVPLPDMQL
PPTFD-SDNPVHRYRYLETASQWL-VRPVMDLHGWDRDSGYDGFNMERMFTYG-K-----
IPASLSGQVTKDKKEANVTLECAASMKHG-E-------GKVSQAGFDVQTVGKDFSYTLR
SETRFSNF--KKNKTIAGLAMTMIGD-------TLAYGMKIEDRLMIG---------RRV
KVVMNGGALTGKGDTAY---------GGTVEISLRDKDFPLGRSLSTCGLSVMNWHGDMA
LGGNLQSQFMVGK-TMVVARGNLNNRGAGQITIRLSSSEQLQIALIGVMPLIK---ALFN
SKFGT-GQQA-----------------------------------------
>atToc159_AT4G02510.1|PACid:19644015
------------------------------------------------------------
---------------RSNIFSNSNV--TMADETEINLSEEEKQKLEKLQSLRVKFLRLLQ
RLGHSAEDSIAAQVLYRLALLAGR------QAGQLFSL----DAAKKK--------AVES
EAEGN-EELIFSLNILVLGKAGVGKSATINS-ILGNQI-ASIDA---------------F
GLSTTSVRE----ISGTV------NGVKITFIDTPGLKS-AAMDQSTNAKMLSSVKKVMK
KC----------------PPD---------IVLYVDRLDTQTRDLNNLPLLRTITASLGT
SIWKNAIVTLTHAAS-APPDGPSGTPLSYDVFVAQCSHIVQQSI--GQAVGDLRLMNPSL
M----------------------------------------------------NPVSLVE
NHPLCRKNRE-GVKVL---PNGQ-TW---------------RSQLLLLCYSLKVLSETNS
L-LRPQEPLDHRKVF----------------GFRVRSPPLPYLLSWLLQSRAHPKLPGDQ
G-GDSVD-SDIEIDDVSDSEQEDGEDDEYDQLPPFKPLRKTQLAKLSNEQRKAYFEEYDY
RVKLLQKKQWREELKRMKEMKKNGKKL-GESEFGYPGEED-DPENGAPAAVPVPLPDMVL
PPSFD-SDNSAYRYRYLEPTSQLL-TRPVLDTHGWDHDCGYDGVNAEHSLALASR-----
FPATATVQVTKDKKEFNIHLDSSVSAKHG-E-------NGSTMAGFDIQNVGKQLAYVVR
GETKFKNL--RKNKTTVGGSVTFLGE-------NIATGVKLEDQIALG---------KRL
VLVGSTGTMRSQGDSAY---------GANLEVRLREADFPIGQDQSSFGLSLVKWRGDLA
LGANLQSQVSVGRNSKIALRAGLNNKMSGQITVRTSSSDQLQIALTAILPIAM---SIYK
SIRPEATNDKYSMY-------------------------------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|433 _911963|PACid:16034180
------------------------------------------------------------
---------------RSNIFSNPNV--TMADETEVNLSEEEKEKLEKLQSLRVKFLRLLQ
KLGHSAEDSIAAQVLYRLALLAGR------QTGQFFSL----DAAKKK--------AVES
EAEGN-EDLNFSLNILVLGKAGVGKSATINS-ILGNQK-ASIDA---------------F
GLSTTSVRE----ISETV------GGVKITFIDTPGLKS-AAMDQSANAKMLSSVKKVMK
KC----------------PPD---------IVLYVDRLDTQTRDLNNMPLLRTITASLGT
SIWKNAIVTLTHAAS-APPDGPSGTPLSYDVFVAQCSHIVQQSI--GQAVGDLRLMNPSL
M----------------------------------------------------NPVSLVE
NHPLCRKNRE-GVKVL---PNGQ-TW---------------RPQLLLLCYSLKVLSEANS
L-LKPQEPLDHRKVF----------------GFRVRSPPLPYLLSWLLQSRAHPKLPGDQ
G-GDSVD-SDIEIDDVSDSEQEDGEDDEYDQLPPFKPLRKTQLAKLSKEQRKAYFEEYDY
RVKLLQKKQWREELKRMKEMKKNGKKV-GESEFGYPGEED-DPENGAPAAVPVPLPDMVL
PPSFD-SDNSAYRYRFLEPTSQLL-TRPVLDTHGWDHDCGYDGVNAELSLAVASR-----
FPATATVQVTKDKKEFNIHLDSSVSAKHG-E-------NGSTMAGFDIQNVGKQLAYVVR
GETKFKNL--RKNKTTVGGSVTFLGE-------NIATGVKLEDQIALG---------KRF
VLVGSTGTMRSQGDSAY---------GANLEVRLREADFPIGQDQSSFGLSLVKWRGDLA
LGANLQSQLSVGRNSKIALRAGLNNKMSGQITVRTSSSDQLQIALTAILPIAM---SIYK
SIRPDATNDKYSMY-------------------------------------
>Zea_mays_gnl|BL_ORD_ID|56215 _GRMZM2G351125_T01|PACid:20876031
------------------------------------------------------------
---------------RSNLFSPSEL--AVTADPTEEMTEEEKKLHDKVELIRVKFLRLVY
RLGATPEETVAAQVLYRLSLAEGIRHGR--QTNRAFSL----DNARRK--------ALLL
EAEGK-EDLNFSCNILVLGKTGVGKSATINS-VFGEEK-SKTDA---------------F
SSATTNVRE----IIGDV------DGVKIRIIDTPGLRP-NVMDQGSNRKILAAVKKYTK
KC----------------PPD---------IVLYVDRLDSLSRDLNDLPLLKTITSVLGS
SIWFNAIVALTHAAS-APPEGLNGAPMTYEVLMAQRSHIIQQSI--RQAAGDMR-----L
M----------------------------------------------------NPVALVE
NHPSCRKNRE-GQKVL---PNGQ-SW---------------RHQMLLLCYSSKILSEANS
L-LKLQDP-NPGKLF----------------GFRFRSPPLPFLLSSLLQSRAHPKLSAEQ
G-GNEGD-SDIELDDYSDVEQDD-EEEEYDQLPPFKPLTKAQLARLTKEQKNAYFDEYDY
RVKLLQKKQWKDEIRRLKEMKKRGKT--DLDDYGYANITGEDDQDPPPENVSVPLPDMVL
PPSFD-CDNPTYRYRFLEPTSTVL-ARPVLDAHGWDHDCGYDGVSVEETLAILSR-----
FPANVAVQVTKDKKEFSIHLDSSIAAKHG-E-------NTSSLAGFDIQTVGRQLAYILR
GETKIKNI--KKNKTTGGFSVTFLGD-------IVATGLKIEDQLSLG---------KRL
SLVASTGAMRAQGDTAY---------GANLEARLKDKDYPIAQSLSTLGLSLMKWRRDLA
LGANLQSQFSIGRGSKMAVRLGLNNKLSGQITVRTSTSEQVQIALLGLVPVAA---SIYR
SFRPSEPSFAY----------------------------------------
>Oryza_sativa_gnl|BL_ORD_ID|57949 _LOC_Os05g05950.1|PACid:21940421
------------------------------------------------------------
---------------RSNLFSPSEL--AVTAEPTEEMTEEEKKLHDKVELIRVKFLRLVY
RLGATPEETVAAQVLYRLSLAEGIRHGR--QTNRAFSL----DNARKK--------AMLL
EAEGK-EELNFSCNILVLGKIGVGKSATINS-IFGEEK-SKTDA---------------F
SSATNSVRE----IVGNV------DGVQIRIIDTPGLRP-NVMDQGSNRKILASVKKYTK
RC----------------PPD---------IVLYVDRLDSLSRDLNDLPLLKTITSVLGS
SIWFNAIVALTHAAS-APPEGLNGAPMTYEVLMAQRSHIIQQSI--RQAAGDMR-----L
M----------------------------------------------------NPVALVE
NHPSCRRNRE-GQKVL---PNGQ-SW---------------RHQMLLLCYSSKILSEANS
L-LKLQDP-NPGKLF----------------GFRFRSPPLPFLLSSLLQSRAHPKLSPDQ
G-GNEGD-SDIDLDDYSDIEQDE-DEEEYDQLPPFKPLTKSQLARLTKEQKNAYFDEYDY
RVKLLQKKQWKDEIRRLKEMKKRGKT--DMDAYGYANIAGENDLDPPPENVSVPLPDMVL
PPSFD-CDNPTYRYRFLEPTSTVL-ARPVLDAHGWDHDCGYDGVSVEETLALLNK-----
FPANMAVQVTKDKKEFSIHLDSSISAKLG-E-------DASSLAGFDIQTVGRQLAYILR
GETKFKNI--KKNKTTGGFSVTFLGD-------IVATGLKVEDQLSLG---------KRL
ALVASTGAMRAQGDTAY---------GANLEARLKDKDYPIGQSLSTLGLSLMKWRRDLA
LGANLQSQFSIGRGSKMVVRLGLNNKLSGQITVRTSTSEQVQIALLGLIPVAA---SIYR
SFRPSEPSFAY----------------------------------------
>Oryza_sativa_gnl|BL_ORD_ID|30676 _LOC_Os03g61890.1|PACid:21913148
------------------------------------------------------------
---------------RKNVASSPVL--EVAPNPDNEMTEEERKLYRKVDVARIKYLRLIH
RLGYDTEHHIAIQVLYRLSLVEGFRRIK--VANHSSEL----ESAWKK--------ALQL
EAEGT-EDLEFSCNVLVLGKTGVGKSATINS-IFGEDK-SKTSA---------------F
LPATTAVKE----ISGVV------GGVKFRVVDTPGLGT-THMDEKSNRKVLNSVKKYIK
RC----------------PPD---------VVLYVDRIDTQRQDANNLSLLQCITSVLGS
SIWSKTIITLTHSAA-APPEGPSGIPLNYEMFVTQRTHAIQQSI--RQATNDPR-----F
E----------------------------------------------------NTSALVE
NHHLCRRNTE-GEKVL---PNGL-IW---------------RRLLLLLCYSVKTV-ETNS
LSARVA---SPANLF----------------SLRFRMPPLPHFLSSLLQSREHPRCAADQ
DVGDI---------DPDELINED-EEDDYDQLPPFKPLSKSQVAKLSKEQQKLYFDEYDY
RTKLLEKKQLKEQLRRLKEMKIEGNNHDVLGDNDNP-----DDEYETERSV---MPDWAL
PSSFD-SDDPAYRYRCLDPKPNFL-VRAITNPDGWDHDCGFDGVSLQYSLDAANA-----
FPASLWVQVNKDKRESTIHLVSSISAKHR-E-------NVSSLAGFDIQTIMDQLAYTLR
GESKFKNS--KKNTTTGGLSMTFLGD-------TMVTGAKFEDKLSVG---------DRL
TLLANTGAVSIRGDTAY---------GVNMEATLREKDYLMGQDLAILGASLVRWHKEWS
MAAKLDSQFSMGRASNVAVHVDLTNKLTGRVSIKANTSEQLKIALLGVCSMTM---YLWN
RMHPFIDRNY-----------------------------------------
>Toc90_gi|75291915|sp|Q6S5G3.1|TOC90_ARATH RecName: Full=Translocase of chloroplast 90, chloroplastic; Short=AtToc90; AltName: Full=90 kDa chloroplast outer envelope protein; AltName: Full=Plastid protein import 4
------------------------------------------------------------
---------------ILPPLSQQQVPLESLYQSSIDLNGKKHNPLAKIGGLQVQFLRLVQ
RFGQSQNNILVSKVLYRVHLAMLIRAEESELKNVKLRQ----DRAKAL--------AREQ
ESSGI-PELDFSLRILVLGKTGVGKSATINS-IFGQPK-SETDA---------------F
RPGTDRIEE----VMGTV------SGVKVTFIDTPGFHPLSSSSTRKNRKILLSIKRYVK
KR----------------PPD---------VVLYLDRLDMIDMRYSDFSLLQLITEIFGA
AIWLNTILVMTH-SA-ATTEGRNGQSVNYESYVGQRMDVVQHYI--HQAVSDTK-----L
E----------------------------------------------------NPVLLVE
NHPSCKKNLA-GEYVL---PNGV-VW---------------KPQFMFLCVCTKVLGDVQS
L-LRFRDSIGLGQP------------------SSTRTASLPHLLSVFLRRRLSSG-----
--ADETE-KEI---DKLLNLDLE-EEDEYDQLPTIRILGKSRFEKLSKSQKKEYLDELDY
RETLYLKKQLKEECRRRRDEKLVEEENL-------------EDTEQR-DQAAVPLPDMAG
PDSFD-SDFPAHRYRCVSAGDQWL-VRPVYDPQGWDRDVGFDGINIETAAKINRN-----
LFASATGQVSRDKQRFTIQSETNAAYTRNFR-------EQTFSVAVDLQSSGEDLVYSFQ
GGTKLQTF--KHNTTDVGVGLTSFGG-------KYYVGGKLEDTLLVG---------KRV
KLTANAGQMRGSGQTAN---------GGSFEACIRGRDYPVRNEQIGLTMTALSFKRELV
LNYGLQTQFRPARGTNIDVNINMNNRKMGKINVKLNSSEHWEIALISALTMFK---ALVR
RSKTEMT------------------------------EENEEEKIVNFLVS
>Arabidopsis_lyrata_gnl|BL_ORD_ID|24265 _910069|PACid:16058012
------------------------------------------------------------
-----------------PPLSQQQVPLESLYQSSIDLNGKKHNPLAKIGDLQVQFLRLVQ
RFGQSQNNILVSKVLYRVHLALLIRAEESELKTVKLRQ----DRAKAL--------AREQ
ELSGT-PELDFSLRILILGKTGVGKSATINS-IFGQSK-SETDA---------------F
RPATDRIEE----VMGTV------NGVKVTFIDTPGFHPLSSSSTRKNRKILLSIKRYVK
KR----------------PPD---------VVLYLDRLDMIDMRYSDFSLLQLISEILGA
AIWLNTILVMTH-SS-TTTEGRNGQSVNYESYVGQRMDVVQHYI--HQAVSDTK-----L
E----------------------------------------------------NPVLLVE
NHPSCKKNLA-GEYVL---PNGL-VW---------------KPQFMFLCVCTKVLGDVQS
L-LRFRDSIGLGQP------------------SSTRTASLPHLLSVFLRRRLSAG-----
--ADEAE-KEI---DELLNLDLE-EEVEYDQLPTIRILGKSRFEKLSKSQKKEYLDELDY
RETLYLKKQLKEECRRRRDEKLIDEENL-------------NDTEQS-DQAAVPLPDMAG
PDSFD-SDFPAHRYRCVAAGDQWL-VRPVYDPQGWDRDVGFDGINIETAAKIKRN-----
LFASATGQVSRDKQRFTIQSETNAAYTRNSR-------EQTFSVAVDLQSSGEDLVYSFQ
GGTKLQTF--KHNTTDLGVGLTSFGG-------KYYVGGKLEDTLLVG---------KRV
KLTVNAGQMRGSGQTAH---------GGSFEACIRGRDYPVRNEQICLTMTALSFNRELV
LNYGLQTQLRPARGTNIDVNINMNNRKMGKINVKLNSAEHWEIALISALTMFK---ALVR
RRKSEMT------------------------------KENEEEEL------
>Zea_mays_gnl|BL_ORD_ID|3368 _GRMZM2G100579_T02|PACid:20823094
------------------------------------------------------------
---------------EVTANSGSGAIYSGIVQQ--DDDNKKSDPLMKVEALQIKFLRLVY
RTGVSPSADVVAQVLYRLQLANLIKASESDARRTNLAI----NKARVI--------AAQQ
EAPGG-PDLDVSMQILLLGKSGVGKSATINS-IFDERK-VATDA---------------L
VPATHRIKK----IEGTI------KGIRVTVIDTPGLVS-HYHGQRRNMKILNSVKHFIK
RS----------------PPD---------IILYFERLDHINSRYSDYPLLKLMTDILGS
PMWFNTVLVMTHCSS-SPPEGPDGYPLEYDTYTRYCKNVVQRHI--QAAVSNTQ-----L
D----------------------------------------------------NPFVLID
NHPMCRRNTK-GERVL---PNGQ-VW---------------VSELLLLCGATKLLTEANS
L-LKFQDSFLLSQ-------------------ANTRLPSLPHLLSSLLKPHSSSS-----
--SDAID-SQL---TEM----SD-EEDEYDQLPPFRILKKSEYENLTNEQKSAYLDELDY
RETLYLKKQWKEGIRRK---KLTEAQ----------SDEVGDDYDESASPEIVHMSDMDI
PLSFD-SDYPVHRYRHIITDDQ-L-FRPVLDPQGWDHDIGFDAINFEASQELKKN-----
VSAAITGQMRKDKEDMYIHSECSVSYNAQ-R-------GCSLMGGMDMQTASKDLVCTVH
GDAKFHNL--PWNSIGGGISVTKFGN-------KYFAGAKLEDSVTIG---------RRV
KLVANAGRMSGCGQVAH---------GGGVEITARGKDYPVREGSVTAAVSALSFEKETV
IGANLQSDFRVGRGSKISVSANLNSRNLGNLSVRTSTSDHAEIALITVVSLIQ---FILR
RRSAADN------------------------------KDEQQI--GTNLDD
>Oryza_sativa_gnl|BL_ORD_ID|55936 _LOC_Os12g09570.2|PACid:21938408
------------------------------------------------------------
---------------D------SEVTSSPSYEP--DHDSTKSDPLKHVEALQIKFLRLVH
RTGVPPTTDVVAQVLYRLHLANLIKAGESDSKRTNLAI----NKARVI--------AAEQ
EAPGG-PDLDLPLRILLLGKTGVGKSATINS-IFDEPK-VATNA---------------L
APATERIRR----IDGTI------KGIRVTVIDTPGLLP-HYHRQRKNRKILHAVKRFIK
RS----------------PPD---------IVLYFERLDHINSRYCEYPLLKLITDILGS
SMWFNTVLVMTHCSS-SPPEGPDGYPLEYDSYARYCKNVVQRHI--QVAASNTQ-----M
E----------------------------------------------------NPVVLVD
NHPMCRRNTK-GERVL---PNGK-VW---------------VSELLLLCGATKLLAEANS
L-LKFQDSFLLSQ-------------------ANTRLPSLPHLLSSLLKPNPSSR-----
--SEDVG-IDM---TEV----SD-DEDESDQLPPFRVLKKSEYEKLSKEQRSAYLDELDY
RETLYLKKQWKEGIRRQ---KLVEAQNVDA------SNAVGDDYEESVSPEVVHMSDMEI
PSSFD-SDYPVHRYRYLITDDM-V-FRPVLDPQGWDHDIGFDGINFEVSQDLEKN-----
TTASIAGQMRKDKEDLYIQSECSVSYSGK-N-------GRSLIGSMNMQTANKDLVCTVN
GDARFHNL--PWNTTGGGISITKFGS-------KYFTGAKLEDSITVG---------RRV
QLVGNAGRMVGCGQVAH---------GGGLEMTFRGKDYPVREESITVAATALSFEKETV
ISTNLQSDFRMGRGSKVSVSANLNSRNLGRFCVKTSTSDHSEIALVAAVTLFQ---FFLR
RRTASTD------------------------------KGEQQFEFDTYSDE
>TOC100
------------------------------------------------------------
---------------LTGSSFQNSSELLSSNHSVELISERVKERVEKTQLLKEKLQRIIR
RTCLSRENSTVTKVASKMSLAGG-------EHPTSLGLDHMFDGTKIV--------LPEQ
EFP---ADLDFSINVLVIGKTGVGKSATVNS-IFGETK-SAVGA---------------F
GVTTNSANY----VVGNV------GGIQISILDTPGLLS-SATEEQFNQEVLIA------
------------------------------------------------------------
-----------------------------------RC-----------------------
-----------------------------------------------------LGIVLAE
NNMSFFSANKSSESTCS-------DW---------------RLNLLILCCSVKIRSKAGS
LQKQNTDVEKAG-------------------VFGSQLSSFTLFCSLWNVLL---NSGHTS
HSHDDLEEKKRKLLD---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|25057 _355185|PACid:16058804
------------------------------------------------------------
---------------LSESSFQNYSEVLCSDHSVQLISEKVKERVEKTQLLKEKLQRIIR
RTDLCSENLTVTEVESKLSIAGG-------EHQTTLGLDNVSDRTKIM--------LPEH
EFP---DDLDFSINVLVIGKTGVGKSATINS-IFGETK-SLVGA---------------F
GVTTKSANY----VVGNV------GGILIRILDTPGLMS-SATEERFNQKVLMSIKKSMR
KF----------------PVD---------VILYIDRLDEH----PDIHLLRIITNSLGS
SVWRNAIVVLTHAAS-NIPDS-----SSYKDFIAQRCSLMHQSI--RQAVPELSCVGQSK
M----------------------------------------------------PGIVLAE
NNMSSFSTNKRSESTCP-------DW---------------RLNLLILCCSVKIRSKAGL
LQKQITVVEKAD-------------------VFGNQLHSFTLFCSLWNVLLLGANSGHTS
HSHDDLDEKKRQLLD---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>atToc34CDS
------------------------------------------------------------
------------------------------------------------------------
---------------------------------EWIGIQQFPPATQSK--------LLEI
LGKYK-EEDVSSLTVLVMGKGGVGKSSTVNS-VIGEKA-AAVST---------------F
QSEGLRPTL----VSRTR------SGFTLNIIDTPGLIE----GGYVNDQAINIIKRFLL
NM----------------TID---------VLLYVDRLDVYRVDDLDRQVVGAITDAFGK
EIWKKSALVLTHAQF-SPPDG-----LNYNHFVSKRSNALLKVI--QTGAQLKKQDLQGF
S----------------------------------------------------IPVILVE
NSGRCHKNES-DEKIL---PCGT-SW---------------IPNLFNKITEISFNGNKAI
HVDKKLVEGPNPNERGK-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Oryza_sativa_gnl|BL_ORD_ID|33217 _LOC_Os03g13730.1|PACid:21915689
------------------------------------------------------------
------------------------------------------------------------
---------------------------------EWVGLQQFPAATQTK--------LHEL
LGKLK-EENVSTLTILVMGKGGVGKSSTVNS-IVGERV-ATVSA---------------F
QSEGLRPMM----CSRTR------AGFTLNIIDTPGLIE----GGYINEQAVEIIKRFLL
GK----------------TID---------VLLYVDRLDAYRMDTLDDQVIRAVTNSFGK
AIWRRTLVVLTHAQL-SPPDG-----LDYNDFFTKRSESLLRYI--RAGAGVSKRELGDF
P----------------------------------------------------LPIALVE
NSGRCKTNEN-GEKVL---PDGT-PW---------------IPNLMKEITTVVSNGSKSI
HVDQKLIDGPNPNNRWK-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Zea_mays_gnl|BL_ORD_ID|49367 _GRMZM2G157157_T02|PACid:20869183
------------------------------------------------------------
------------------------------------------------------------
---------------------------------EWVGLQQFPAATQTK--------LHEL
LGKLK-EEDVSTLTILVMGKGGVGKSSTVNS-IVGERV-ASVSA---------------F
QSEGLRPMM----CSRTR------AGFTLNIIDTPGLIE----GGYINEQAVDIIKRFLL
GK----------------TID---------VLLYVDRLDAYRMDTLDEQVIRAITNSFGK
DIWRRSLVVLTHAQL-SPPDG-----IDYNDFFTRRSEALLRYI--HSGAGINKREYGDF
P----------------------------------------------------LPIALVE
NSGRCKTNEH-GEKIL---PDGT-LW---------------VPNLMKEITVVISNGSSPT
HVDQKLIDGPNPNNRRK-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|30599 _311338|PACid:16064346
------------------------------------------------------------
------------------------------------------------------------
---------------------------------EWVGFQQFPAATQEK--------LIEF
FGKLK-QKDMNSMTVLVLGKGGVGKSSTVNS-LIGEQV-VRVSP---------------F
QAEGLRPVM----VSRTM------GGFTINIIDTPGLVE----AGYVNHQALELIKGFLV
NK----------------TID---------VLLYVDRLDVYRVDELDKQVVKAITQTFGK
EIWFKTLLVLTHAQF-SPPDE-----LSYETFSSKRSDSLLKTI--RAGSKMRKQEFEDS
A----------------------------------------------------IAVVYAE
NSGRCSKNDK-DEKAL---PNGE-AW---------------IPNLVKAITDVATNQRKAI
HVDKKMVDGSYSDDKGK-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>atToc33
------------------------------------------------------------
------------------------------------------------------------
---------------------------------EWVGFQQFPAATQEK--------LIEF
FGKLK-QKDMNSMTVLVLGKGGVGKSSTVNS-LIGEQV-VRVSP---------------F
QAEGLRPVM----VSRTM------GGFTINIIDTPGLVE----AGYVNHQALELIKGFLV
NR----------------TID---------VLLYVDRLDVYRVDELDKQVVIAITQTFGK
EIWCKTLLVLTHAQF-SPPDE-----LSYETFSSKRSDSLLKTI--RAGSKMRKQEFEDS
A----------------------------------------------------IAVVYAE
NSGRCSKNDK-DEKAL---PNGE-AW---------------IPNLVKAITDVATNQRKAI
HVDKKMVDGSYSDDKGK-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|31223 _Pp1s54_12V6.1|PACid:18067760
------------------------------------------------------------
------------------------------------------------------------
---------------------------------EWTGLLQFPVATQTA--------LHNI
LGKLR-QQKKESLTVLVVGKGGVGKSSTVNS-IIGERV-TVVSA---------------F
QSETLRPLQ----CARTR------AGFTLNVIDTPGLIE----GGCINDQALDIIKRFLL
NK----------------TID---------VVLYVDRLDGYRVDNLDKQVIRALARSFGP
NFWRIAIIALTHAQL-SPPDG-----VDYTEFVNNRSAALRAAI--RQEAGFKKSEGE--
-----------------------------------------------------ISYMLVE
NSGRCNTNSE-GEKVL---PNGS-VW---------------LPALVDRIAEVATGATPSI
HVDQKLIDGPNANGKGK-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|6422 _178526|PACid:15407700
------------------------------------------------------------
------------------------------------------------------------
---------------------------------EWSGINQFPVATQTA--------LHGL
LGKVR-QQNVDSMTVLVLGKGGVGKSSTVNS-IIGERV-AAVSA---------------F
QSETLRPLF----VSRSR------AGFTLNIIDTPGLIE----GGWVNDQALEIIKRFLM
DK----------------TID---------VVLYVDRLDGYRVDSLDKQVIRAITRSFGP
QIWKLCLLVLTHAQL-PPPDG-----ASYDDYVQQRSEGLLAAI--RHEAGFKKTDPD--
-----------------------------------------------------IPYALVE
NSGRCSTNAG-GEKIL---PNGT-VW---------------VPNLVGRLVQVVTNEHPSL
LVDKKLIEGPNANNRGK-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|2394 _Pp1s6_441V6.1|PACid:18038928
------------------------------------------------------------
------------------------------------------------------------
---------------------------------EWTGFQGLPAATQII--------LHTL
LAKLR-KQKVDKITIVLLGKGGVGKSSIVNS-LFSERV-AAVSA---------------F
RSETLRPRQ----YSRSK------DGFKLTVIDTPGFVE----AGRV-DAALNSIRRYLL
GK----------------TIN---------VVLYVDRLDGPREDKVDVKISRAISQAFGP
QIWPHVIVVFTHAEI-HLED------VTYSEFVSRRSAALRNII--LKESRFKTVNTK--
-----------------------------------------------------VPFVLVE
NCSRCSENGE-HEKIL---PDGT-VW---------------LPVLFEALVDLVLGSKKPI
LIDEKMIGISKGNPLGS-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|5312 _06.g252200.t1.1|PACid:19863610
------------------------------------------------------------
------------------------------------------------------------
---------------------------------PWAGLNRLPE--RDD--------MLDI
LNELR-AEGRKQLTVLLLGKSSVGKSSLINS-LLGEAV-VRVQA------FKLQADTDIT
TTVVRQVAV----GNSEV------DGFRLKLIDTCGLED-PEAGDTVNLGALSKIAEDVR
GV----------------GID---------VVLYCDRLDLYRVDPLDKAIIDAISSTFGR
GIWRRTVVALTHANLVQTPPG-----TDYDSFVNGRVRLIRGAV--RGPLFFRPS-----
-----------------------------------------------------LPVALVE
NSETCPVSSESGFRVL---PDGE-PW---------------LVALVSQLVDMAAARRRPY
KYHPRLSSKPSHRFR---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Volvox_carteri_gnl|BL_ORD_ID|4108 _Vocar20003545m|PACid:23127977
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------MPTTGWWIAQVPHPPLASNGI-CRVDSGITPFLVGSQADAEAT
MTIVRHISV----GDPEI------DGLRIKLIDTCGLED-PEAGDTVNWGALSKIAEDIR
GV----------------SID---------VVLYVDRLDLYRVDPLDKAIIAAVTHTFGR
QIWCRTILALTHSALMQVPPG-----TSYDSFVDGRIRLLRGVI-PRGPLPFLR-----S
P----------------------------------------------------LPAVLVE
NSETCPINKDNGHRML---PDDT-EW---------------LVGMVSEVVDLVLARRQAY
KYNPRMTSKPSQRFR---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|3128 _gnl|CMER|CMP284C similar to chloroplast outer membrane protein Toc34
------------------------------------------------------------
------------------------------------------------------------
---------------------------------QVLALEDVPEPTAQA--------ILRL
ALAAE-RQGVPRLRFLVVGAPGVGKSSLINT-LLNENL-CSVSA---------------W
ERGTKNAQV----CARQV------DSVVIEFIDTPGIAPCRRSGLEASRRQVQRLRKLLD
AR----------------GADEHPYLRSFHAILYVMRLDDTRPDLVDYHNWKVLMEFFGA
EVLRHMMVVFTHGQS-LPPDS-----LSYPEYVRGRRDYVYLLI--ERLTGPLKA----V
R----------------------------------------------------FPVFVAE
NSSKCPVIEETGERKL---PDDT-PW---------------ITQLYDGIRRFVFPLEADL
FGMETGPEDTQ-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Cyanophora_paradoxa_gnl|BL_ORD_ID|516 _ConsensusfromContig10710-snap_masked-ConsensusfromContig10710-abinit-gene-0.1-mRNA-1:cds:3832/1722-1917:0:+
------------------------------------------------------------
---------------MP--------------------------------------LRTPR
YL----------------------------------------DPVESM--------WDRL
CTSAK-LERAEVLTVLVIGRSGVGKTALVNT-LFADEP-SKIKP---------------T
SPFEHKPSEGFARVRSAY------HGVSIQFVEET--LPMGEPGDPQEEAMARRVQKLYR
RA----------------GAEGE-----IFLLVFVDRLDGARELN---SALAVVTDTLGT
AAWARSMVVLTHGQT-LPPPD-----STFADFVKQRRETATLAL--RRAARNKQ-----L
S----------------------------------------------------VNVVVVD
NAREGLRSAE-GHRVL---PFGVPAWANIG---------PCVPALLEAAAESVANSMPE-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|9231 _17.g734300.t1.2|PACid:19867537
------------------------------------------------------------
-------------------APPVLAAAGSDAVVDPSEDRRVQRVQRIAHDTRVRLIRAAS
RLGLAPRTDQVAQFLQAIERSERMVGAQHYKGSRRVDLLAAAEREARL--------AEER
EGAAAEAVAGLRVKILVLGMTGTGKTELINS-LLNRPAGSRTNA---------------F
REATRRVRV----VRGDH------NGIPLTFIDTPGLHA-SASRTADNRAILRAVRAAYR
WH----------------KPD---------YVFYVDRLDATRPGFGEMGLLGLITESLGA
GVWRNTMAVLTHAHAARTAFG-----GQYDVNSRQRRNIVSQLL--RQAAGDQQ-----S
R----------------------------------------------------NPVFLAD
CHPACPTNSL-GQPVILEGPTAV-PW---------------KQQLLVQLVGYKSYNVATS
A-FKDLAKAKAGKAAAGAAGGARGPQDIFKQMMRSRLPPMTFFVEQMSEGVLKPEGWATM
ETVAGLG----------------EEVTEDEGAESFNHVYYRQMYELAVAGDPWAQREYAA
MLRAYDKGCESYRAS---------------------YEEADVDANVEYGVESYVVDPIDF
GPSFDPEDMYSHRHAYAEAADAGVTVIPSQDYYGPEHDDPLNGIVFQYEAQPFSRHGWGG
VPFDLTVCCEKDKTSLCLQGETHVSLVHSVPPFGPRHITQVTGSWEVLRPNIKDVMYQLE
VDTFKDGLLGKSDHAGCGLMLARLGEGGDPRKGPTAVGVRLQDTLRVGPFKLEACASKVA
VQGPTGGKEEGWGARAFVGYDWLPGLGMAFDFIQERTPEEGGKRLRGYGANFTYDWEALG
AAFGMEVDY-------------VAASESVFVSVNAFSGNDYRLGWLLLLPAVNYFK---E
TVSSLWARLRGAGGGEGEEGEELEEEGEGEEGD----DEEAMMMMAQEGDL
>Volvox_carteri_gnl|BL_ORD_ID|9830 _Vocar20012343m|PACid:23133716
------------------------------------------------------------
----------------AATAGAAAAATPSMDVVDRTEDRRVQRVQRTAHEIRVRLIRAAT
RLGLSPRSDQVAQFLQAIERSERMVGAQHYKGTRRVDLIAAAEREARE--------LDSR
E-PPHSPIAGLRLKILVLGMTGTGKSELINS-LLDRPASSRTSP---------------F
REATRRVRV----IRGHH------NGIPLTFIDTPGLHA-SVSCTAENKAILRSIKAAYN
CF----------------KPD---------YVFYVDRLDAPRPGLGELGVLSLIAEALGP
GVWRNTMAVLTHAHAARAAFG-----GQYDINSRQRRNIITQLL--RQVAGDQQ-----S
R----------------------------------------------------NPVFLVD
CHPSCPTNSL-GQQVIQEGPSAV-PW---------------KQQLLGQTVGYKSYNAAAA
V-FKELAKSKAGKSA--AAGGARGPQDIFKQLMRSRLPPMTFFVEQMTEGVLKPEGWATM
ESVAGLG----------------DEVTEDEEAESFGHMYYQHMYDLAMSGDPWAQREYAA
MLRSYDKAQETFKAS---------------------YEEADLDHAIEYGIESYVVDPIDF
GPSFDPEDLYSYRHAYAEAADSAITVIPSQDYYGPEHEDPLNGFVMQYESQPFARHGWGG
VPFDLSVCVEKDKTSLCLQGETHLTVVHSVPPFGPRQVTQLTGSWEMLRPNIKDVMYQLE
VDTFKDGLLGRNDHAGCGMMLARLGEGGNPRKGPVAVGVRVQDTFRLGAFKVEACASKVA
VQGPTGGKEEGWGARAFVMYDWLPGVGIALDAIQEKGSEESGKRQRGYGINVTYDWEMLG
AAFGAEFDY-------------VAASKSLYVSVNAFSGNDYRLAWVLLLPALGSDEIEWE
TLGSVWARLRAAGGGAGQEEEAGEEEAGEEEYDEEDEDEGVAAMMAQAADM
>Homo_sapiens_gnl|BL_ORD_ID|12914 gi|313760638|ref|NP_001186506.1| GIMAP1-GIMAP5 protein [Homo sapiens]
------------------------------------------------------------
----------------------------------------------------------RA
SVTATLEDRAQQPFLERMGGFQRGKYGTMAEGRSEDNL----------------------
------SATPPALRIILVGKTGCGKSATGNS-ILGQPV-FESKL--------------RA
QSVTRTCQV----KTGTW------NGRKVLVVDTPSIFE-SQADTQEL---YKNIGDCYL
LS----------------APG-------PHVLLLVIQLGR--FTAQDTVAIRKVKEVFGT
GAMRHVVILFTHKEDLGG--------QALDDYVANTDNCSLKDL--VRECE---------
-----------------------------------------------------RRYCAFN
NWGSVEEQRQQ------------------------------QAELLAVIERLGREREGS-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Homo_sapiens_gnl|BL_ORD_ID|12910 gi|23397516|ref|NP_694968.1| GTPase IMAP family member 7 [Homo sapiens]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----MAESEDRSLRIVLVGKTGSGKSATANT-ILGEEI-FDSRI--------------AA
QAVTKNCQK----ASREW------QGRDLLVVDTPGLFD-TKESLDTT---CKEISRCII
SS----------------CPG-------PHAIVLVLLLGR--YTEEEQKTVALIKAVFGK
SAMKHMVILFTRKEELEG--------QSFHDFIADAD-VGLKSI--VKECG---------
-----------------------------------------------------NRCCAFS
NSKKTSKAEKESQ----------------------------VQELVELIEKMVQCNEGA-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Takifugu_rubripes_gnl|BL_ORD_ID|6856 jgi|Takru4|708219|fgh5_pm.C_scaffold_7000026
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MMLIGKTGSGKSATGNT-ILGQKH-FESRV--------------GI
NSVTRQCQT----ASGVI------DGYRVALVDTPGLFD-TSFSNEDT---KRELVKCMS
LL----------------APG-------PHVFLLVLRIGR--FTWEEKIIVALTTTFFGE
KSKDFIIIIFTWGDELKG--------QSIDSYLAQDKEGSLQTL--ITQCG---------
-----------------------------------------------------GRYVVFN
NKDQHNRSQ--------------------------------VSQLLVKVEEMIKKNGKG-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Takifugu_rubripes_gnl|BL_ORD_ID|15866 jgi|Takru4|562427|e_gw2.15.404.1
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------EKILQLVRENGNRAF
ETERQ-LRHVTDIRIVLLGAKGSGKTSALNT-ILNRPS-SQVPG----------------
--RTAQCVL----GRGLV------FGRRLTVVDTPGWWM-NYFSAETSIFDRDQLIRSLS
LC----------------PPG-------PHVFLLTVRVDRA-FTETYRRAVQEHLQLLGR
SVWTRVILLFTFGDWLGG--------TSIERCIESEGPPLTWLV---ESCG---------
-----------------------------------------------------NRYHVVD
NRTR-------GDGFQ-------------------------VRELILRIEEMLAGCADA-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Anabaena_variabilis_ATCC_29413_gnl|BL_ORD_ID|3501 gi|75909106|ref|YP_323402.1| engA gene product [Anabaena variabilis ATCC 29413]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------HGNGTGELLDEL---------------IKHL
PPTTE-LEENNEIKIAIIGRPNVGKSSLLNA-FAGEER-VIVSP---------------I
SGTTRDAID----TFIER------NGQNYRLIDTAGIRKKKSIDYGTEFFSINRAFKAIR
------------------RAD--------VVLLVIDALDG--VTEQDQKLAGRILDE---
--GKACVVVVNKWDA-VEKDS-----YTIYDYEKNLE-----------------------
-----------------------------------------------------ARLHFTE
WADTIYVSAVTGQRVEK------------------------ILELVTKANEEHKRR----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Nostoc_sp_PCC_7120_gnl|BL_ORD_ID|793 637230843 alr0483 GTP-binding protein EngA [Nostoc sp. PCC 7120]
MGLPIVAIIGRPNVGKSTLVNRLAGEQTAIVHDEPGVTRDRTYLPAYWSDREFQVVDTGG
LVFNDDTEFLPLIRQQALAALHEASAAIFVVNGQTGPNSADEEIAEWLRQQPVPVFLAVN
KCESPDQGSIQASEFWELGLGEPYPISAIHGNGTGELLDEL---------------IKHL
PPVTE-LEENNEIKIAIIGRPNVGKSSLLNA-FAGEER-VIVSP---------------I
SGTTRDAID----TFIER------DGQNYRLIDTAGIRKKKSIDYGTEFFSINRAFKAIR
------------------RAD--------VVLLVIDALDG--VTEQDQKLAGRILDE---
--GKACVVVVNKWDA-VEKDS-----YTIYDYEKNLE-----------------------
-----------------------------------------------------ARLHFTE
WADTIYVSAVTGQRVEK------------------------ILELVTKANEEHKRRVSTS
VINE-----VLEDAVRWHSPPTSRGGRQGRIYYGTQVSTQPPTIALFVNEAKRFNDNYRR
YIERQFRQQLGFKGTPIRLLWRSKKVRDVESGSANRATRV--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Microcystis_aeruginosa_NIES_843_gnl|BL_ORD_ID|80 641534060 MAE_00810 GTP binding protein [Microcystis aeruginosa NIES-843]
MKLPVVAIIGRPNVGKSTLVNRIAGDQQAIVFDQPGITRDRTYQPAFWCDRDFQIVDTGG
LVFNDDSEFLPLIREQALIALAEASVAIFVVDGQGGITAGDREIAAWLRQQNVPILLAVN
KCESVEQGILQATEFWELAIGEPFPISAIHGSGTGELLDAV---------------IKYL
PPAAE-IPENEEIKVAIIGRPNVGKSSLLNA-LTGQQR-AIVSP---------------I
SGTTRDSID----TLIER------EGQVYRLIDTAGIRRKKNVDYGAEFFSINRAFKAIR
------------------RSD--------VVLFVIDVLDG--VTEQDLKLAGRIIEE---
--GRAVVLVVNKWDA-VEKDT-----YTINTYTKMLQ-----------------------
-----------------------------------------------------DRLYFMD
WAEMIFVSAMTGQRVTK------------------------ILELVDIAAESHRRRVSTS
VIND-----VIEEAVKWHNPPTTRGGKQGKLYYGTQVSSQPPTIALFVNDPQRFNDNYRR
YIEGQFRQQLGFKGTPIRLIWRGKPAREVEK-TVNRATKV--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|1764 637617446 syc1763_c GTP-binding protein EngA [Synechococcus elongatus PCC 6301]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------HGSGTGELLDRV---------------LELL
PPADEAAGDETEIGVAIVGRPNVGKSSLLNS-FLGEQR-AIVSP---------------I
AGTTRDAID----TVIER------NDQRYRLVDTAGIRRKRGVDYGPEFFGINRSFKAIR
------------------RAD--------VCLLVIDVLDG--VTDQDQKLAGRIEED---
--GRACVIVVNKWDA-HEKDS-----STIYEVERQLR-----------------------
-----------------------------------------------------DRLYFLD
WAPMIFVSALTGQRVEK------------------------ILDQVNTVVEQHRRR----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|1764 637617446 syc1763_c GTP-binding protein EngA [Synechococcus elongatus PCC 6301]
MPLPIVAILGRPNVGKSTLVNRLAGSREAIVHDEPGVTRDRTYQEAFWCDRDFTVVDTGG
LVFDDDTEFLPLIREQAELALAEAALAVLVVDGQAGLTAADNEIADWLRHQNRPIVVAVN
KCESPDKGAAQAAEFWSLGFGEPLPISSIHGSGTGELLDRV---------------LELL
PPADEAAGDETEIGVAIVGRPNVGKSSLLNS-FLGEQR-AIVSP---------------I
AGTTRDAID----TVIER------NDQRYRLVDTAGIRRKRGVDYGPEFFGINRSFKAIR
------------------RAD--------VCLLVIDVLDG--VTDQDQKLAGRIEED---
--GRACVIVVNKWDA-HEKDS-----STIYEVERQLR-----------------------
-----------------------------------------------------DRLYFLD
WAPMIFVSALTGQRVEK------------------------ILDQVNTVVEQHRRRVGTS
VINE-----VLGDAIAWRTPPTTRQGRQGRIYYGTQVTTQPPSFTLFVNDPKLFGESYRR
YIERQFRESLGFSGTPIRLFWRGKKSRELER-GANRATRV--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Anabaena_variabilis_ATCC_29413_gnl|BL_ORD_ID|5110 gi|75910714|ref|YP_325010.1| era gene product [Anabaena variabilis ATCC 29413]
------------------------------------------------------------
------------------------------------------------------------
---------------------------------AELKVASIDNHISSL--------SGEV
SIPQA-PPEFKSGFIGIIGRPNVGKSTLMNQ-LVGQKI-AITSP---------------V
AQTTRNRLR----GIVTT------PEAQLIFVDTPGIHK---PHHQLGEVLVKNAKLAIE
------------------SVD---------VVLFVVDGTVA-CGAGDRFIADLLIHS---
--KTPVILGINKVDQ-QPSDS-----QNIDDSYQQLASAYQWPT----------------
------------------------------------------------------------
----VKFSAKTGAELPQ------------------------LQELLVEHLEHGPYY----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Microcoleus_chthonoplastes_PCC_7420_gnl|BL_ORD_ID|1669 647566030 MC7420_506 GTP-binding protein Era [Microcoleus chthonoplastes PCC 7420]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------MEDSNNFTLIPDADTV
MIPQA-PEGFKSGFVGIIGRPNVGKSTLMNE-LVGQKI-AITSP---------------V
AQTTRNRLQ----GILTT------DNAQLIFVDTPGIHK---PHHQLGKVLVQNAKIAIE
------------------AVD---------VVLFVVDGATP-AGGGDRYISNLLSQT---
--STPVILGINKSDL-QSPG------KGLDEGYHQLADPHNWQV----------------
------------------------------------------------------------
----TKFSALTGDGLAT------------------------LQEQLIDRLEQGPYYYPPN
LVTDQPERFIMGELIREQILLLTRQEVPHSVAITIDAVEEEPKITRILATIHVERESQKG
ILIGKKGSMLKSIGSAARQQIQKLIAGKVYLELFVKVQPKWRQSRLRLAELGYRLEE---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|3480 641252663 AM1_3580 GTP-binding protein Era-like protein [Acaryochloris marina MBIC11017]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------MSDL--------SSLT
SIPQA-SPEFKSGFVAIVGRPNVGKSTLMNQ-LIGQKI-AITSP---------------V
AQTTRNRLR----GILTT------PTAQMIFVDTPGIHK---PHHQLGEILVKNARMAIH
------------------AVD---------VVLFVVDCSEP-LGGGDRFIAQLLAQT---
--NTPVILGLNKLDI-QRKTAQQA--LTLDQAYKALAKEHHWPV----------------
------------------------------------------------------------
----CKFSALTTAKLKS------------------------LQRQLIEKLVPGPYYYPPD
LVTDQPERFIMGELIREQILLLTRQEVPHSVAIVIERVDESPKITRILATIHVERPSQKQ
ILIGKKGSMLKAIGTEARQQIQKLIAGKVYLELFVKVQPKWRQSRMQLAELGYQVESN--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Arthrospira_platensis_Paraca_gnl|BL_ORD_ID|4015 646131753 AplaP_010100020559 GTP-binding protein Era [Arthrospira platensis Paraca]
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------MDS--------IFPV
SIPVA-PEGYKSGFVGIIGRPNVGKSTLMNK-LVGQKI-AITSP---------------I
AQTTRNRLR----GILTT------DSAQIIFVDTPGIHK---PHHQLGKVLVKNAKLAIA
------------------SVD---------VLVFVVDASVM-SGGGDRYIVDLLTHT---
--KFPVILGLNKWDL-QPDQY-----EAIDQSYQQFAEAHKWQM----------------
------------------------------------------------------------
----VKFSAVTGAGVET------------------------LQNLLINSLDPGPYYYPPD
LVTDQPERFIMGELIREQILLHTREEVPHSVAIAI-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Drosophila_melanogaster_gnl|BL_ORD_ID|9955 gi|17137038|ref|NP_477064.1| peanut, isoform A [Drosophila melanogaster]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GYVGFA--------NLPN
QVYRKAVKRGFEFTLMVVGASGLGKSTLINS-MFLSDI-YNAEQ---------------Y
PGPSLRKKKTVAVEATKVMLKENGVNLTLTVVDTPGFGD-----AVDNSNCWVPILEYVD
SKYEEYLTAESRVYRKT-ISDSR-----VHCCLYFIAPSGHGLLPLDIACMQSLSDKV--
----NLVPVIAKADTMTPDEVHLFKKQILNEIAQHKIKIYDFPAT-LEDAAEEAKTTQNL
R--------------------------------------------------SRVPFAVVG
ANTIIEQD---GKKVR----GRRYPWGLVEVENLTHCDFIALRNMVIRTHLQDLKDVTNN
VH----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Takifugu_rubripes_gnl|BL_ORD_ID|17846 jgi|Takru4|295838|estExt_Genewise2.C_710121
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------EYVGFA--------TLPN
QVNRKAVKKGFMFTIMVAGKSGLGKSTLVNS-LFLTDL-YKDRK---------------V
PSAQDRINQTVKIIKHTVGIEEKGIRLRLNIIDTPGFGD-----AINNTKCWQSIEDYID
QQFEQYFRDESGLNRRN-IQDNR-----VHCCLYFISPFSHGLRPLDVECMTALHGKV--
----NIVPVLAKADCMTPAEVSIKKQKIKGELKKFGIKIYQFPECDPEDNEEIRMHDQML
K--------------------------------------------------ENFPFAVIG
SNLHVESK---GRMVR----GRAYPWGVVEAEDPLHSDSLLLRNMLVRTYMQDLKDVTQE
TH----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Homo_sapiens_gnl|BL_ORD_ID|25723 gi|164698496|ref|NP_001106964.1| septin-9 isoform e [Homo sapiens]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GYVGID--------SILE
QMRRKAMKQGFEFNIMVVGQSGLGKSTLINT-LFKSKI-SRKSV---------------Q
PTSEERIPKTIEIKSITHDIEEKGVRMKLTVIDTPGFGD-----HINNENCWQPIMKFIN
DQYEKYLQEEVNINRKKRIPDTR-----VHCCLYFIPATGHSLRPLDIEFMKRLSKVV--
----NIVPVIAKADTLTLEERVHFKQRITADLLSNGIDVYPQKE--FDEDSEDRLVNEKF
R--------------------------------------------------EMIPFAVVG
SDHEYQVN---GKRIL----GRKTKWGTIEVENTTHCEFAYLRDLLIRTHMQNIKDITSS
IH----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Takifugu_rubripes_gnl|BL_ORD_ID|20737 jgi|Takru4|160954|gw2.141.141.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------SYVGID--------AILE
QMRRKAMKQGFELNIMVVGQSGLGKSTLMNT-LFKSKV-SRKSV---------------L
ATAQEKIPKTVEIKSISHDIEEKGVRMKLTVIDTPGFGD-----QINNENCWQPIMKFIN
DQYEAYLQEEININRKKRIPDSR-----VHCCIYFIPPTGHCLRPLDVEFMRRLSKVV--
----NIVPVIAKADTLTLEERDFFKKKIREELRANGIDVYPQKE--FDEDAEDRMINEKI
RVRIMFKFWXLKDIYGCCGDDHAXVVARSTIVPDAWSNGGIKLPRXSTVEQEMIPFAVVG
SDQEYQVN---GRRLL----GRKTKWGTIEVENIAHCEFAYLRDLLIRTHMQNIKDITSS
IH----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
