>gnl|BL_ORD_ID|13734 @Aquilegia_coerulea@_006_00193.1|PACid:22036769
M-----------------------------------------------------------
-------------------------------------ENGVEKPISEVETKTADGAVSQF
NLVDKTVQVFHDDGEMNKEEEVKEEEAELPLADDETKT----------------------
-------ADGAVSQLKLVDNVVQVFH-----------QPKDSEGDDVFEEAVM-------
------------------------------------------------------------
----------------EDYTEDDNEHIPSLPDLEGAE--SVQSNGESIEVYEADKFEEAV
DTDLPNEDRNVGEEIFET-------ARAVEPVDEVKDA---KEAVMEDLPEDMPNGVVFN
AEG----DKKED--------SAVVVEEDTRLLTAGDVMSNRESENGDDDDNNPVESSDGV
VCNGEEEEDESKISALIVNGGTKLPTDAKVEANGN----CDAVVDEKSDNAGLKESELE-
VKPVILAKASDVTRA--------ISEHSELISSEDDHC----------------------
---------------------------K-SGSFDGNVHGQIDNGK-TENGCL-----ENL
EV--DEKSSVPEN---------------LLEVDKVGS------DEIAPE-GND-----PV
EKIFSDEDNQTTVVRYTVVNADALMSEDIHTPEIENAYNNPGASVDERIYEQKENSDTMI
NKSSKAVAAESEDENSVSVQPQYTESIENDSVNNARTKEPEL---QEMQDEHNKQDHTRV
-----------EESRSSGLAREPEIRQVVEP------------VQA-------PPRRPAG
LGGAAPLFEPASRAVQQPRVNGAGPQRQAQVLEDP------VNGEAEEND-ETREKLQMI
RVKFLRLAHRLG-----QTPHNVVVAQVLYRLGLAEQLRGRNAGRVGAFSFDRASAMAEQ
LESA--GQEPLDFSCTI-------------------MVLGK-------------------
---------------------------------------TGVGKSATINSIFDESKF---
------------------------------ITDAFQMGTKKVQDVV-GTV--QGIKVRVI
DTPGLLP-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------CW
S-DQRQNEKI--------------------------------------LHSVKRFIKKTP
PDI-------------------------------VLY-----------------------
---------------------------------------LDRLDMQTRDFGDLPLLRTIT
EIFGPSIWFNAIVVLTHAAS----------------------------------------
-------------------APPDGPNGISSSYEMFVSQR------S--------------
-------------------HVVQQAIRQAAGDMR------------LMNPVSLVENHSAC
RTN-----------------------RAGQRVLPNGQVW---------------------
----KPHLL------LLSFASKILAEANTLLKLQDNPPGKP-FATRARVPPLPFLLS---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------SLLQSRPQLKLPE----------------------------------
-------------EQFGDEDGLDEDLD---------------------------------
-----------ESSDSD---DESEYDELPPFKRLTKAQLAKLSKLQKKAYFDEL------
-EYREKL-FMRKQLRED-------------------------------------------
--------------------------------------------KRRRKLLKKMAVSA--
-------------KEVPTDYTESAEDESGGGASVPV-------------PMPDFALPASF
DSDNPSHRYRFLDTSNAWLVRPVLETHGWDHDVGYEGINVERLFVVKDKIPVSFSGQATK
DKKESNLQVELATSIKHNEGKATSVGFDMQTVGKDMSYTLRSETKFSNFRHNKAAAGLSV
TLLGDALTAGVKLEDKLIVNKRFRLVLTGGAMTGRGDVAYGGSLEATLRDKDYPLGRMLS
TLGLSIMDWHGDLAIGCNVQSQIPIGRNSNLIARANL-----------------------
----NNRGSGQVSIRVNSSEQLQLALVGLLPLFRKALS-LYQ---QT-------------
------------RYGE
