>gnl|BL_ORD_ID|7943 @Arabidopsis_lyrata@_480549|PACid:16041690
M------------------------------GDGTEVVVRS---------DRISDEQVAK
TELLGSVEVKDEKEDDV-------------------------------------------
-------FEEAIGSENDEQ--EEDPKRELLETDDLP----LEETRQSSKDENEVEDFEEA
VGDLDET-----------------------------------------------------
--SSNEGGVKDLHVDYSVVGESHG--------AGEAGFDVVAPKMNGDKGEGGAGDSYGK
V--ESNLDVVENTEMA---DTNGLKLAAEDVSIENGKTHSFLGN------GIVSPNNKEV
VAEVIPKDDGIEEPWNDGIVVENWEERVDGVQTEQDVEDGEGTTKNLFEERTEEEVVDGA
GTGKNLFENGS-------------------------------------------------
------------------------------------------------------------
GSVCIDNESEAKTNGETGAAYTSDIETNASGDKSVNDSTEVASAETSSPLDKSSSGEKGE
TEGDSTCLKPEQQLASSPNSNPESTEIRSNSGSPGVTSRENETVRNSNGGHDVQQRPQPN
KELEKQRSSRVN-----------------VDPEIKENSHVETEAEVVSSVSPTESRSNPT
ALPPAR-------------------------PAGLGRASPLLEPASRAP----QQSRVNG
NG-SHNQSQQAEDSTTVETD----------------------------------------
------------------------------------------EHDETREKLQLIRVKFLR
LAHRLGQTPHNVVVAQVLY----------RLGLAEQLRGRNGS-RVGAFSFDRASAMAEQ
LEAAGQDPLD------------------------------------F-------------
-SCTIMVLGKSGV---GKSA--------------------TIN------------SIFD-
-----------------------------------------------------------E
VKFCTDAFQ-----------MGT---KRVQDVDGLV--QGIKVRVIDTP-----------
-G------------------LLP-SWSDQA--KNEKI---------------LNSVKA--
FIK---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---KNPPDIV-------------------------------------------LYLD---
--------R----LDMQSRDSGDMPLL---RTISDVF-----------------------
------------------------------------------------------------
-----GP---SIWFNAIVGLTHA----------------------------ASVPPDGPN
GTASSYDMFVTQRSHVIQQ-----AIRQAAGDMRLMNP-----VS-LVENH-SACRTNRA
GQRVLPNGQV-WKPH---------------------------------------------
------------------------------------------------------------
-----------LLLLSFASKILAEANALLKLQ--DNIP-GRPFAARSKAPPLPFLLSSLL
QSRPQPKLPEQQYGDEEDED-DLDE--SSDSDEE----SEYDQLPPFKSLTKAQMATLSK
SQKKQYLDEMEYREKLLMKKQMKEERKRRKMFK----------------------KFAAE
IKDLPDGFSENVEDESGG----PASVPVPMPDLSLPASFDSDNPTHRYRYLDSSNQWLVR
PVLETHGWDHDIGYEGVNAERLFVVKDKIPISVSGQVTKDKKDANVQLEM-ASSVKHGEG
KSTSLGFDMQTVGKELAYTLRSETRFNNFRRNKAAAGLSVTLLGDSVSAGLKVEDKLIAS
KWFRMVMSGGAMTSRGDFAYGGTLEAQLRDKDYPLGRFLTTL------------------
------------------------------------------------------------
-----------------------------------------GLSVMDWHGDLAIGGNIQS
QVPIGRSSNLIARANLNNRGAGQVSVRVNSSEQLQLAMVAIVPLFKKLL---SYCYP--Q
TQYGQ--------
