>gnl|BL_ORD_ID|1693 @Brachypodium_distachyon@_2g06810.1|PACid:21804463
M-----------------------------------------------------------
------------------------------------------------------------
----DNREKPLPEAGHRGGPGGVAEEEAAAAQVGVDPAP---------------------
---DV----------------------------------TAANEGGGGR----ILG-GEK
GDAAEGVVQADVKRPPGVGAAQKGGGDEVGKGDIKSEPDSVRSEFNSSADGSMDPSAGHG
----------------HQVTQNR---------A-----GNGTPTAAESDEDADLF-----
----------------------VEVEQ--QELAGSDQSEEFFD--NAEALVAGESV----
---DVEGDAIEDGSHAELRVEDDT--MHDEHRERLE-----------EEAMLTAIRQCVT
DAVLAEHMEEHPEKGGEDVPAC------VGNPDIPVSSSGEPEHIK--------EVKLAD
QSTEQPE----YSEGDIPTRDSKLEVPAQFGG--------EPDVVVEELADSNSSDDE--
NKGSSASARPS-------------SAAAGHSNGSSL-PS------------------RPA
GLGSSTSLLQPPARPVQQVRANGPVGVG---------RDTRQDIESAGDDGDENDEIRE-
---KLQMIRVKFLRFANRFGQTPHNMVVSQVLYRLGLAEQI-------------------
-------------------------------------------R-SNTN----TGHG---
--------------------------------------VFSFDRAQEMAERLEAAGNEP-
-LDLS-----------------------CTILVLGKT-----------------------
--G--VGKS-------ATIN---SIFDDV-------KLETD-AFESSTRKVQEVVGM---
--------------------------------------------V-EG---IKVKVIDTP
--------G-LSCSSSDQHY--NQKILNSVK-RLVSKSPPDIVLYFDRLDMQSRD-----
-------------------YGDVPLL--QTISKIFGASV--------WFNAIVVLTHAAS
APPDGPNGIPLSYEMFVTQRSHVVQQAIRQAAG-------DVRLMNPVSL----------
VENH-SACRTNRAG----QRVLPNGQV----WKPQLLLLCFASKVLAEANVLLKLEDSPT
GKPSNAR--IPPLPFFLSSLLQSRAPVKLPEEQFG---D-DDDLEDVVDDCGSDDGSDYD
DLPPFKRLAKSQLSKLN---------------------HAQRKAYLEELD----------
------------------------------------YREKLFYKKQLREERLRRKMMKKM
AAEAR-ARTDDFSNSNVDGDDSTPT--NVAV------PMPDMVLPSTFDSDYPSHRYRFL
DTPS---EWLVRPVLETQGWDHDVGYEGLNIERLFAVKGKVPLSVSGQLTKDKK------
------------------------------------------------------------
----------------------------------------DSSLQMEVASSVKHSEGKTT
SLGLDLQSVG----KDMAYTIRGESRFKNFRRNNTAAGISATLLGDS-------------
------------------------------------------------------------
------------------------------------------------------------
----------------------VSAGVKIED--------------------------RLI
VNKQLRLLVSGGAMSGKGDAAYGGRLEATLRDKDYPIGRMLSTLAISVVDWHGD------
----------------------------------LAVGCNVQSQIPAGRSSSLIANANLS
NKGTGQVGIRLNSSEHLQIALIAFVPIYQNIRKLLE------------------------
------------------------------------------------------------
---------------------KY----S--------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------ES----------A
