>gnl|BL_ORD_ID|1598 @Brassica_rapa@_022170|PACid:22685108
M-----------------------------------------------------------
-----------------------------------------------------GEDGRQE
VYSVGLQEYEVSDVQIVRRKNDDANELPGKVVGKSTFIDLAGSEIGADTTDNDRQTSFGS
LNAEYECKLGIFLTILVNCAYLARICFRACMEEKKLADDRVIDDQVEKIELVVSDVDARD
TED---EEAIDSS----------KPESLQADDLP----------SEEVKDP---------
----------------------------KEIIGE----SHGEANLQHIT-------TGEA
VPGF--GTSRMNGDEGEAG-----------------AENVHET-----------------
ATHSFSENGTVSLEKKQPVADVI----------G------------------ETRNGGIE
EE----------------------------------------------------------
-IKEEIVDVSGAQRN------------GERASGERSFNDSI-------------------
------------------------QVASAGTSSPLEKSSSEENGE---T---EGH-----
---------------------------ISREHDTVQ--NGGLGVEHT-------------
-SQPNKEFEKQRGSRVNMSPEIKER-----KSEVASSVSPTESTSNIAAS----------
-----------------PPPARPA-GHGRDASLLEPTPRV--PHQPRVNGNA------SQ
NQSEQA-EDPTPAETDEHDETREKLQLIRVKFLRLSHRLGQTP-HNVVVAQV--------
-------------LYRLGLAEQLRGRNGS-RVGAFSFDRASSMAEQLEAAGQDPLDFSC-
----------------------TVMVLG-----KSGVGKSA-----TI------------
-----------------NSIF-----DE----VKIC-TDAFQM----------GTKR---
----------------VQEVEGFV--Q----------GIKVRVIDT----PG--------
----------L-LPSWSDQHKNEKMLKSVKVF--IKK----NPPDIVLYLDRLDMQSRDS
---------GD--TPLLRTITDVFGPSIWFNAIVGLTHAASAPPDG--------------
---PN-GTAS-----------------SY-----------------DMFVTQRSHVIQ--
----QAIRQAAG--------------------------------------DMR-----LM
NPVS-LVENHSACRTN--RAGQRVLPNGQV-----------------WKPHLLLLSFASK
ILAEAN-----ALLKLQD--NNTPGRPFVARSKAPPLPLLLSS----FLQSRPQAKLPE-
--------------E-----------------QYGDEEDED-DLDESSGS------DEES
EYDQLPPFKRLTKAE-----------------------------------MARLSKSQKK
QYLDEME-----------YREKLFMKRQMKEERKRRKMMKKFAA----------------
----EIKDMAEEH-SENVEEERSEPAS----------------------VPVPMPDLSLP
ASFDSDNPTHRYRSLDSSNQ---------------WLVRPVLETQGWDHDVGYEGVNAER
LFVVKEKIPISFSGQVTKDK----------------------------------------
------------------------------------------------------------
------KDANVQLEMAGSVKHGE--GRST--------SL---------------------
------------------------------------VEDKLIANKRFRMVMC-GGAMTSR
GDVAYGGSLEAQLR--------------DKDYPLGR-FLSTLGLSVMDWH-GDLAIGGNI
QSQVPIGRSSNLI---------------------------ARANLNNRGAGQVSVRVNSS
EQLQLAMVALVPLFKKLF------SYYSPQ-QM---------------------------
------------------------------------------------------------
----QY
