>gnl|BL_ORD_ID|26953 @Citrus_clementina@_0.9_001850m|PACid:19278112
-M----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------ENGVNKP-VVDAFVDE------------------KVEEKVMVS----------
-SDEPKDV-------EDV---------------FE-EAVDTPDH-------LNDEGTKDE
SG----------------------------------------------------DDASVG
D--LG-----SVVVDGGSNVGGE--MDSFDETEGVPSEGGNDVVGEGEGKVGDLAGAESV
IEVVLCWKRSSTQVTGECNVQP----------LPQPASSAAKSTMPVN----PPA-----
--------------------RPAGLGRAAPLLEPAPRVVQHPRVNG--------------
-------------------------------------------------AISHTQTQPIE
DPGNGEAEEYDETREKLQMIRVKFLRLAHRLGQTPHNVVVAQVLY--RLGLAEQLR-GRN
GGRVGAFSFDRASAMAEQLEAAGQEPLDFSCT----------------------------
----------------------IMVLGKT-----GVGKSA-----TINSIFD--------
EVKFGTDAFQM-------------------------------------------------
-----GTKKVQDVV-GTV--QGIKV--RV--IDTP---G---------------------
--------------L--LPSWSDQ-RQNEKILHSVKRFIKKTPPDIVLYLDR--------
--LD----------MQNRDFSDMPLLRTITDIF--GPS----------------------
----------------------------------------------IWFNAIVVLTHAAS
APPD--GPNGTASSYDMFVTQRSHVVQQAIRQAAGD-----MRLMN-----PVSLVEN--
-------------------------HSACRTNRAGQRVLPNGQV----WKPHLLLLSFAS
KILAEANTLLKLQDTPP-GKPFSARSRAPPLPFLLSSLLQS-------------------
--------------------RPQVKLPEEQFGDEDSLDDDLDDSSES---EDESEFDELP
PFKRLTKAQVAKLTKAQKRAYFDELEYREKLFMKKQLKEEKKRRKMMKKMAAAAKDLPSD
NSENVEEESGGAASVPVPMPDLALPASFDSDNPTHRYRYLDSSNQWLVRPVLETHGWDHD
VGYEGINAERLFVVKNKIPISFSGQVTKDKKDANVQMEVVSSLKHGEGKATSLGFDMQTV
GKDLAYTLRSETRFSNFRKNKAMAGLSVTHLGDSLSAGVKVE--DKLIVNKRFRVVMTGG
AMTSRSDVAYGGSLEAQLRDADYPLGRSLTTLGLSVMDWHGDLAIGCNIQSQVPIGRSTN
MIGRANLNNRGAGQVSIRVNSSEQLQLALIGLIPLLKKLLG-YSQQMQLGQ--------
