>gnl|BL_ORD_ID|25604 @Eucalyptus_grandis@_G01765.1|PACid:23587325
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------EYAAR-DVDGPPRVE
EEVNGEAGVLEERVEERVGSAAGDDSKVVEGEEVFEEAVVDAHDDSSREEGLKVVSVAGV
PGPDTDDVAGVDPSSEVSNENASAGHEDEKFEEAIGTPAKIENNE---EIVKEVDV----
---EEKVEGLVGGESIGGALVADGVDEGGTHEKVPVK-----EDDGLMSN--GEDAV---
---REIAELHVDEEMHND--------------------VDGSSPT----HGV--ALKK--
--------LDNGTED------ELENGNVSMEGLLDTE--HKGTSSVEVLYAGDQHEELVD
TDLATEGKLIIDRELEIAPAANHPDDL-DEGNATLATENKGDVKVE-----TKSVTASFE
SVYHDADGEVKKSFSSTDTEYQNDVNKEVKDATNGPDSSQGKISEQD----PTSIDRPSS
TSDEPV-----THESG---ILTTSEELKSE-KDEQITA-----------------GTIEI
DQEDVTSRTQQPVE--------NVQENHHKHT---------------SA-------EKLE
KKDSDSGGDGKKVIRENGI------PAAKEVASS-----GRLMNHASVPAR---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------PAGLGRA
APLLEPAPRVSQQSRVNGAVSH----AQAQHIEESANGESEDHDETR----EQLQMIRVK
FLR----LAHRLGQTPHNVVVAQVLYR---------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------LGLAEQ----------
-------------------IR-GRNGGRVGAFSFDRASAMAEQAEASGQEP---------
---------------LDFSCT--IMVLGKTGVGKSATINSI-------F----DEVKFST
DAFDTGTKKV--QDVVGTVQGIKVRII---------------DTPG--------------
----LLPSLT-DQRQNEKILHSIKR-FIKKTPPDIV-----LYLDRLDMQTRDLGD---M
PLLRTIT----------------------------------EIFGPSIWFNAIVVLTHAA
SAPPDGPN--------------------------------------GTASSYD-------
-----------------------------------------------MFVTQRSHVVQQA
IRQAAGDMR---------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------LMN
---PVSLVENHSACRTNRAGQR-VLPNGQVWKPHL------LLLS---------------
---------------------------FA-SKILAEANALLKLQDSPPGKP-FASRSRAP
PLPFLLSTLLQPRPQPKLPEEQYGDD--DGMDDDLDESSDS---DDESEYDELPPFKRLT
KAQVSKLTRAQKKAYFDELEYREKLFMKKQLKEERRRRRMMKKMAAAAKDQPSEYVENAE
EESGGAASVPVPMPDLALPASFDSDNPTHRYRYLDNSTQWLVRPVLDTHGWDHDVGYEGI
NLERLFVVKDKIPISFSGQVSKDKKDANVQMEVASSLKHGEGKSTSLGFDMQTVGKDLAY
TVRSETRFSNFRKNKATAGLSFTLLNDALTAGLKVEDKLIVNKWLRLVMTGGAITARGDV
AYGGSLDATLRDKDYPLGRSLFTLGLSVMDWHGDLAVGGNIQSQLPIGRFTNLIARANLN
NRGAGQVSLRVNSSEQLQIALLGLIPLFKRLLE-FPQQWQLGQ------
