>gnl|BL_ORD_ID|12853 @Malus_domestica@_0000744418|PACid:22632826
------------------------------------------------------------
------------------------------------------------------------
--------------MENG----------DKVAGGSEVGENKSVEVEVVEGSNGL------
-----------KDDAEDEVFEEAI------------------------------------
------------------------------------------------------------
------------------ETQENLQEQGSKNDLV--DAAAVGEERKAEMVGGLGLDSLIE
SPNVENFEEAI-------------EFHDEVGKSDGDDGE-----EAIVAGEVKVENMVGK
NSAD--EGGGPGGIDDGQTIKEVVSEETNGLTDDELVGS-QEDGVKEVTQVGAGGGIAGL
TGGDEADVKSVVLENVKFEKVNFESNGLADDGLVGSQDVEVKEVSEIITGAEVAGLTDVD
EVDSKPNAVLKNEEPERNDIECSTSEPVPA------DEKLDTEDLDSPQVTEFTKEILKE
AXNSQELEDNSLSIENQDEK-TVDLASASDGVPLKLQDDNXVELHDRNMDTVHQEGHSA-
--ES--------------------NDATLSIEEKQEEDNKTEKPKDTLTVTDAEHQGFSN
GEVKDSFTVPGS-----EHHEEKSEPKSVSSAKQLSGEGGEERIVTSEREISALSKT---
SATEKTEKIQDGATNLRTESNKVXQPQRAGEIACEVR----DN--IAKENIPGEKGITKV
NKEQEIRPAPALSSSLNSTQRSP-----PPARPAGLG-----------------------
----RAAPLLEPSPRVV--------QHPRV--NGTISHVQNQQIEDPVNGEAEESDETRE
KLQMIRVK----------------------------------------------------
------------------------------FLRLAHRLGQTXHNVV-----VAQVLYR--
------------------------------------------LGLAEQLRGRNG--GRVG
A----------------------FSFDRASAMAEQLEASG-----------NEPLDFAC-
-----TIMVL--------------------------------------------------
----GKSGVG---KSATINSIFDEKKF----------TTDAF------------------
QMGTKKVQDVVGTV--QGIKVRVID---TPGLLPSWSDQ-GQNEKTLLNVK---------
---------------------RFIKKTPPD---------IVLYFDRLDMQSRDFSDMPL-
--------------LRTITDIFGASIWFN-------------------------------
-------------------------------------AIVVLTHAGSAPPEGPNGAASSY
DMFV--------------------------------------------------------
---------------------------------------TSRSHVVQQAI----RQAAGD
MR---------------------------------------LMN----------------
-------------------PVSLVENHSAC------------------------------
---------RTNRAGQ-------RV-----------------------------------
-LPNGQVWKPH-------------------------------------------------
------------------------------------------------------------
----------------------L-------------------------------------
---------------------------LLLSFASKILAEANALLKLQDSP-PGKPFATRT
RAPPLP-FLLSSLLQSRP---QLKLPEEQFGEDDSLDDDLDESSDSD---DESEFDELPP
----------------------------------FRRLTKAQV-----------------
----------EK-L-------------------------------------SKAQKK---
----------------AYFDELEYREKLFMKKQLKEEKXRRKLMKKX-------AAAAKE
LPSDYVENVEEESSGAASVPIPMPDLALPASFDSDNPTHRYRYLDSSNQWLVRPVLEQHG
WDHDVGYEGINAERLFVVKEKIPLSFSGQVTKDKKDANVQMEIATSIKHGE-GKATSFGF
DMQ----------------TVGKDLAYTLRSDTRISNFRKNKATAGLSVTLLG-------
---------DALSAGMKVEDK-----FIANKRFQLV------------------------
---------------------------------------MTGGAMTARGDAAYG-GSLEA
QLRDKDH-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--PLGRSLSTLGLSVMDWHGDLAIGCNIQSQIPVG-------------------------
-------------------------RHTNLIAR--------ANLNNRGAGQLSLRLNSSE
QLQLALIGLVPLLRKFFT-FPQQLQYG---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------Q
