>gnl|BL_ORD_ID|20932 @Populus_trichocarpa@_POPTR_0009s13380.1|PACid:18227174
-ME---------------------------------------------------------
-------------------------------------------------------NGIDR
VVDATQLENNINVNTEVSRDKVEDKYEVLGGAVEGTNELLGDKV-EEKVA----VASSES
K-DLEDEVFVEALESTEKLH--------E----------EGVK-----------------
----FESDGGV---ESVGDSSLVVGNANLDVGNEMEKFEAHESEGGDSGSVVVIEKSDVG
SMMDKFEEPVFVP--------------------------AEPGNPEGLTEVVGE------
-----------EKVVDSVGGESVRKIDEGGT-----------VVEVEGSVLNGGEVV---
-----------------------------------------------------SVELQDR
KGEGLHENPVKVDTEDQDDKSGELIGDS--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----AGLDSEDGIHKGGHPKGISATVDTEHGDTSNGDLKDT---IASVDPEHHEETPELT
ATSAVPHTALEESTVVAETGS---LNSLDKFVNEKN--EDIQADTANLRAEDNKDSEPEH
AAEKGNDAGQNNIVSGHPERIAETYPE-KQNTPVNKE-----------------------
---AGLGRA------------------APLL---------EPATRAMQQLRA--------
------------------------------------------------------------
----------------------------------------------NGAMSHMRPQQLDD
PTNGE-SEEHDE--THEKLKMIRVKF----------------------------------
-----LRLVHRLGLAPNETVVAQVLYRLGIVEQLRGRNRGRI------------------
---------------GTLSFDPASAMAGQLEADGQEPLDF--SCTI--------------
---------MVLGKTGVGKSATINSIFDEAKL-----PTNAFQSGTKMVQDVVGTV--QG
I-------------KLRVIDTPGLLP-SGSDQRQNEKI--LLSVKNFI--KKTP----PD
IVLYFDRL--------------------------DMQSKDFGDL-PLLR---TVTKIFG-
----------PSIWQNAIVVLSHAASAPPDSPQGTVSSYEMFVTQRS-----HVVQQTIR
QAAGDMWLV-----NPV----------------SLVENHSACRRNRAGHRVLPNGQVWKP
QL-----LLL----SFASKILAEANAILKVQDGPP-RKQFATRSRAPPLPYLLSSLLRSR
PQVKLPEEQFGDEDGLDDDLD-----------------------------------E--S
LDSEDESEY-DDLPPFKSLTKAQVAKLTKAQKNAYFDE----------LEYREKLFMKKQ
LKEEKRQQRMMK-------KTAVATNPLPGDYSENAEEESEGPASVPV------------
------------------------------------------------------------
------------------------------------------------------PMPDLS
LPASFDSDNPSHRYRYLDNSNQWLVRPVLDTHGWDHDVGYEGINVERLFVVKDKIPVSFS
GQVTKDKKDANVQMELASSIKHGEGKSTSLGFDMQ-TLGKDLGYTLHSETRFINFRKNKA
TAGLSVTLLGDALSAGVKVEDKLIANKRFQMVMSGGAMTGRGDVAYGGSLEAQLRDEDYP
LGRSLSTLGLSVVDWHGVLAIGCNIQSQVPIGRSTNLIARANLNNKGAGQLSIRINSSEH
LQIALAGLIPLLRKLFD-YHEE------MQLGQ
