>gnl|BL_ORD_ID|44520 @Panucum_virgatum@_Pavirv00015881m|PACid:23800695
----------------------------------M-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------ENGGVVGEGRPEDRAGENGG-----VAEAGQSAVKRVAAEEEG-SVDVV-
--VEDGDDAVAAEEVDGDEVGEENQ--------GAGGHAVESGTPVAGDHQPVVTP----
-NTRVVLETGRHAAEKWGEDSPRAEINVEGSVEENAMGQTTKGYCHTKRERPESITRSAA
EPAIIIEELDDLGSSDDENTATSAPPAQSSAASGHSNSPSL-------------------
----------------------------PSRPAGLGSSPSLSQPPARHVQQARANGPISS
DRGS----------------------------------QPSTESAEDDGDENDEVHEKLQ
M----IRVKFLRLAHRFGQT-----------------------PHNMVVSQVMYRLGL--
--------AEQLRR-TTAN--GSLS------FDRAREMAE-HLEAAGNEPLDFSC-----
------------------------------------------------------------
-----------------------------------------------TILVLG-------
--------------------------------------------KTGVGKSATINS----
---------------------------------------IFDDTRLDTNAFDSSTKKVQE
------------------------------------------------------------
-------VVGTV--EG-----I--------------------------RVKVVDT-----
------------PGLSCSSLEQ--------------------------------------
------------------------------------HHNQK------VLNSV--------
-------------------------------KRLISKNPPDIVLYF--------------
------------------DRL--DMQSRDNGDVPLLQTIT--------KVFGAS---VWF
NAI-------VV---LTHAASAP----PDGLNG---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------IPLSYE-MFVT-QRSHVVQQAIRQAAGD
IRLMN------PVSLVENHAACRTN------RAGQRVLPNGQVWKPQLLL----------
-------LC----FASKVLAEANVLLKLQDSPIGK-------L--SRTRIPPLPFLVSS-
----------LLQSRAPLKLPEEQFGDDDDLE---DDSTDDSDSDDGS------------
------------------------------------------------DYDDLPPFKRLT
KA------------------------QLSKLNNA--------------------------
-----------------QRKAYLEELDYR---EKLFYRKQLKEERMRRKLMKKMAVEAST
RTNDFYNSNPEDDSN-TPTNVAVPM-----------------------------------
--------------PDMVLPSS--FD----------SDYPSHRYRFLDTPSEWLVRP---
------------------------------------------------------------
--------------VLETQGWDHDVGY-------EGLNVERLFAV---------KGKVPV
SISGQLTKDKKDCSMQMEVASSVKHAEGKSTSLGLDLQSVGKDMAYTIRGESRFKNFRRN
STAAGISATLLGDSVSTGVKIEDKLIVNKQLRVLIS------------------------
------------------------------------------------------------
---------------------------------GGAMSGRGDVAYGGRLEATLRDKDYPI
GRMLSTLALSVVDWHGDLAIGCNVQSQIPAGRASNLVGHANISNKGTGQVGIRLNSLEHL
ELALIALVPIFQNIRKLLQNFSEST------------
>gnl|BL_ORD_ID|54837 @Panucum_virgatum@_Pavirv00064825m|PACid:23811108
----------------------------------M-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------ENGGVVGWGRPEDREGENGG-----VAEAGESAVKRVAAEEEG-GVDVV-
--VEDGDDAVAVEEADEDEAREENQ--------GAGGDAVESGTPVAGDHQPVVTP----
-NTRVVLETGRHAAEKWGEDSPRAEINVEGSVEENAMGQATRGYCHTKQDRPESVTRFAA
EPAIIVEELDDLRSSDDENTATSAPPARSRAASGRNNSPSL-------------------
----------------------------PSRPAGLGSSSSLSQPPARPVQQARANGSVSS
DIGS----------------------------------QPSTESAEDDGDENDEVHEKLQ
M----IRVKFLRLAHRFGQT-----------------------PHNMVVSQVLYRLGL--
--------AEQLRR-TTAN--GSLS------FDRAREMAE-RLEAAGNEPLDFSC-----
------------------------------------------------------------
-----------------------------------------------TILVLG-------
--------------------------------------------KTGVGKSATINS----
---------------------------------------IFDDTSLDTNAFDSSTRKVQE
------------------------------------------------------------
-------VVGTV--EG-----I--------------------------TVRVIDT-----
------------PGLSCSSLEQ--------------------------------------
------------------------------------HHNQK------VLNSV--------
-------------------------------KRLISKNPPDIVLYF--------------
------------------DRL--DMQNRDNGDIPLLQTIT--------KVFGAS---VWF
NAI-------VV---LTHAASAP----PDGLNG---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------IPLSYE-MFVT-QRSHVVQQAIRQAAGD
IRLMN------PVSLVENHAACRTN------RAGQRVLPNGQVWKPQLLL----------
-------LC----FASKVLAEANALLKLQDSPIGK-------L--SRTRIPPLPFLVSS-
----------LLQSRAPLKLPEEQFGDDDDLE---DDSTDDSDSDDGS------------
------------------------------------------------DYDDLPPFKRLT
KA------------------------QLSKLNNA--------------------------
-----------------QRKAYLEELDYR---EKLFYRKQLKEERMLRKLMKKMAAEAST
RANDFYNSNPEDDSN-TPTNVAVPM-----------------------------------
--------------PDMVLPSS--FD----------SDYPSHRYRFLDTPSEWLVRP---
------------------------------------------------------------
--------------VLETQGWDHDVGY-------EGLNVERLFVV---------KGKVPL
SISGQLTKDKKDCSMQMEVASSVKHAEGKTTSLGLDLQSAGKDMAYTIRGESRFKNFRRN
STAAGISATLLGDSVSTGVKIEDKLIVNKQLRVLIS------------------------
------------------------------------------------------------
---------------------------------GGAMSGRGEVAYGGRLEATLRDKDYPI
GRMLSTLALSVVDWHGDLAIGCNVQSQIPAGRASNLVGHANISNKGTGQVGIRLNSTEHI
ELALVALVPIFQNIRKLLQNYSEST------------
