>gnl|BL_ORD_ID|24605 @Phaseolus_vulgaris@_091015439m|PACid:23555468
M---------------------------DYEAGGF---------------GANGEGESKR
VGEG-VS-EESVVGSDSL---KSLDV------EGD-----FQEAM----EPREQAHDQGS
ELLSEEAVVDKQDDANTAGALTSALVDEKGPDVVQEHDSSEE-----ADSEN--------
-------GKLGETDAIAYQDLERDGPGTHSVHLDGVASGVSGDGGFCDGSNGVVDDNLER
----S-------DGGGGKEDSGLNSDVEVVVKENGVVED-ENSGLMSEKAEEVDDSEFMT
PRQNGVRTL--DDVSTDK-EDDVDGVATEVIIKSESSEVIPAEGTDAGDLKEC----DAD
PELGDDNIEVNLNASADSSGEIQDDTCEEVHGNSAHITLEQQDEVTRDVKDVTLGTDISH
EDIIGEEMSTPGIQNAEVTSYENGD-GEHENSSFLDNP-----STKETLP-IQEASAADP
KEGSNKDDQSQISDENQRDDDN------SFVVEEPERTQEKIIQETETTQETGEQPVQPS
ADISSSTENSSAAGPRPLLPSSENSTGPRPILPSSENSAAAGPTPVLPAGLGRAAPLLEP
ASRLVQQPRANGTVSNTQSQQMEDSSSGEAEEYD--------ETREKLQMIRVKFLRLAH
RLGQTPHNVVVAQVLYRLGLAEQLRGRNG--GRV-------------GAFSFDRASAMAE
QLEAAGQEPL--D-FSCTIMV-----------------------LGKTGVGK--------
------SATINSIF--------DEVKFNTSAFNMGT---K----KVQD------------
---VVGT-----------------------------------------------------
VQGIKVRV----------------------------------------------------
--------------------IDTPGLLPSWSD-------QRS-NEK---------ILLSV
KNFIKKTPPDIVLY----------LDRLD-----------MQSRDFSDMPLLRTITE---
-----------------------------------------------------------I
FGPSIWFNAIVVLT---------HAASAP-------------------------------
-----PEGPNGTASSYDMFVTQRSHVVQQ--------AIRQAAGDMR-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------LMNPVSLVENHSACRI-----------
------------------------------------------------------------
-----------------------------------NRAGQRVLP---NG-----------
------------------------------------------------------------
--------------------------------------------------------QV--
-------------------------WKPHLL------LLSFAS-----------KILAEA
NALLKLQDSPPGKPYIA-R-R----APPLPFLLSTLLQSRPQLKLPQEQFGDEDSLDD--
--DLDEASESD-DENEHDDLPPFKPLTKAQVEKLSKAH----------------------
------------------------------------------------------------
KKAYFDELEYREKLLMKKQLK---------------------------------------
-----EEKKRRKFMKKMAEAA---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------KDLPSDYSENVEEEGGGAASVPVPMPDLALPASFDSDNPTHRYRYLDSSNQW
LVRPVLETHGWDH-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------DVGYEGLNV
ERLFVVKDRVPLSFTGQVTKDKKDANVQMEIAGSVKHGEGKATSLGFDMQTVGKDLAYTL
RSETRFTNFRRNKATAGLSFT---------------------------------------
------------------------------------LLGDALSGGVKIEDKLVASKRFRV
VISGGAMAGRNDIAYGGSLEAQLRDKDYPLGRFLSTLGLSVMDWHGDLAVGCNVQSQIPV
GRHTNLVARAN---------------------------------------------LNNR
GAGQISIRLNSSEQLQIALVALIPLFK---------LNYGQVLVVNERTILYFICHQGRR
QVSSTYAMGFVKHVDVRFQYSKRTSHRPNEGDIVADDEISCGRSKPKSLGDDIPSNRLIL
KFQTLKLVLEFTSYF
