>gnl|BL_ORD_ID|2946 @Sorghum_bicolor@_Sb01g029790.1|PACid:1952668
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------ENENGSVGRPEDRAGENG-----
-----------------GVAEEEESAVKA-ATAA-DEG------------DCDVVVEGVD
----EGDV-----PPGAVAAQDGGGDEVGE----ENRASGEGALESAGVSGDHQPVV--T
PNTRVVLETGQLAADKWDEDETPRVVDVEEMFADDV------NQEQVAAQSGSEYEDVKG
GMYQS--------KNQPGKST-------EEIAS-----------S-HSRPKS--VTHSAA
ESAVAIEELDDSGF--------------------SDDENTTTSA-------------PPA
K--------------------------SSAG----------------------------S
STPAQSSSGASARSTNGPSLL--SRPAGLGSSSSLSQPPVRSVQQVRANRPSAVD--RGT
QEATESAEDDRDENDEIHEKLQMIRVKFLRLADRF-------------------------
-----GQTSHNMVVSQVLYRLGLAEQLR-RT-------------TAN--GTFSIDRARE-
------------------------------------------------------------
-------------------------------MAERLEAAGNEPLD-----------FSCT
ILV---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------LGKTGVGKSATINSIFDDT---RLDTNAFDSSTRK-----------VQEVV
GMV--EG----IKVKVID------TPGLSCSS----------------------------
------------------------------------------------------------
--------------------------------LEQHHN-QKVLNS---------------
------------------VKRIISKNPPDIVLY-------FDRL--DMQSR---------
------------------------------------DNGDVPLLQTIT------------
------------------------------KVFGAS------------------------
----VWFNAIVVLTHAASAPPD--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------GQNGIPLSYEMFVTQRSHV---------
------------VQQAIRQ----------------AAGDVRLMN-----PVSLVENHSAC
R-------------TNRA------------------------------------------
--------GQRVLPNGQVWKPQLL-----LLCFASKVLAEANVLLKL-------------
--------------------------------QDSPMSK--LSRTRIPPLPFLLSSLLQS
RAPLKLPEEQFGGDDD-DLE-DDSADDSDSDDGSDY------------------------
----------------DDLPPFKRLTKAQLAKLNKEQRKAYLEELDYR------------
------------------------------------------------------------
-----------------------------------------------EKLFYRKQLKEES
KRRKLMK-----------------------------------------------------
------------------KMAAEASARANDFGNSNL---EDDSNTPTNVSV---PMPDMV
LPSSFDSGYPSHRYRFLDTPSEWLVRPVLETQGWDHDVGYEGLNVERLFAVKGKVPLS--
-VSGQLTKDKKDCSLQMEAASSIKHAEGKTTSLGLDLQSVGKDMAYTIRGESRFKNF---
------------------------------------------------------------
----------------------------------------RRNNTAAGISATLLGDSVSA
GVKIEDKL-------------------IVNKQLRVLISGGAMSGRGDVAYGGRLEATMRD
KDYPIGRMLSTIALSVVDWHGDLAIGCNIQSQIPAGRASNLVGHANLSNKGTGQFGIRLN
SSEHLEIALVALVPIF--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------QNIMKLLQNYYSES
---G---------
>gnl|BL_ORD_ID|25025 @Sorghum_bicolor@_Sb09g004020.1|PACid:1979795
MATTTDAADPVAPPVEEESAAPAAAEEEPPKKVEEAVATTDAAPVAPAPAPVEDETPAPA
AAAAAAEEESTKKVEAAAAEEVEEDKEAPAKVVAGGGEG---EEEEDVRLE-GESEGLGG
------------------------------------------------------------
------------------------------------------------------------
----------------------------------PEAENGQAEGVGGGHDVGEVKEAEED
DKGGNLGVAEAEKDGGGEELASEDGEAAPSGAEPVPVVESKSENGELGEGDPSLAFHDAL
EGDEKGELQKEEQQEDEEERGAALEVEVVDKVADDAEAPVAAEKLEPE---IEKG-----
--------EEVGSGSGDGGELSDEKEV--EVSPP-SEEV---AEP-QDKVAPEANGELGD
EKEESDDVVALGGEEAP-EESTNKDADGDD----VVALGGEEAPEESTNKDADGDDVVAL
GGDEAPEESTKKDAD--VEDEATKPEPPSEA--SPVVLNDESIEELAPATADSVLEDSPE
K--EQNADAQTTASEVVEDVGVDKPTEVENVAAPSADGILSRELAPESSNENKGADEIEG
VTEVVDREEEAADNDIIEVVPDDEDGVGNEADDDDDGANSDTSPARVAILESSEAAKQIM
KELAEGSSGSVSRDF--TNSMDGQIMLDDSEDDEDDDDNDDSDEKGFDSAALAALLK--A
ATGGSSDGNITVASPDGSRIFTMDRPAGLGSSAPSLRP-TAPRQPARSNLFSPSE----L
AVTADPTEEMTEEEKKLHDKVELIRVKFLRLVYRL-------------------------
-----GATPEETVAAQVLYRLSLAEGIRHGR-------------QTN--RAFSLDNARR-
------------------------------------------------------------
-------------------------------KALLLEAEGKEELN-----------FSCN
ILV---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------LGKTGVGKSATINSIFGEE---KSKTDAFSSATTN-----------VREII
GDV--DG----VKIRIID------TPGLRPNV----------------------------
------------------------------------------------------------
--------------------------------MDQGSN-RKILAA---------------
------------------VKKYTKKCPPDIVLY-------VDRL--DSLSR---------
------------------------------------DLNDLPLLKTIT------------
------------------------------AVLGSS------------------------
----IWFNAIVALTHAASAPPE--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------GLNGAPMTYEVLMAQRSHI---------
------------IQQSIRQ----------------AAGDMRLMN-----PVALVENHPSC
R-------------KNRE------------------------------------------
--------GQKVLPNGQSWRHQML-----LLCYSSKILSEANSLLKL-------------
--------------------------------QDPNPGKLFGFRFRSPPLPFLLSSLLQS
RAHPKLSAEQGGNEGDSDIELDDYSDVEQDDDEEEY------------------------
----------------DQLPPFKPLTKAQLARLTKEQKNAYFDEYDYR------------
------------------------------------------------------------
-----------------------------------------------VKLLQKKQWKDEI
RRLKEMK-----------------------------------------------------
------------------KRG---KTDLDDYGYASIGGENDQDPPPENVSV---PLPDMV
LPPSFDCDNPTYRYRFLEPTSTVLARPVLDAHGWDHDCGYDGVSVEETLAILSRFPAN--
-VAVQVTKDKKEFSIHLDSSIAAKHGENASSLAGFDIQTVGRQLAYILRGETKIKNI---
------------------------------------------------------------
----------------------------------------KKNKTTGGFSVTFLGDIVAT
GLKVEDQL-------------------SLGKRLSLVASTGAMRAQGDTAYGANLEARLKD
KDYPIGQSLSTLGLSLMKWRRDLALGANLQSQFSIGRGSKMAVRLGLNNKLSGQITVRTS
TSEQVQIALLGLIPVA--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------ASIYR--SFRPSEP
SFAY---------
