>gnl|BL_ORD_ID|6262 @Setaria_italica@_Si034092m|PACid:19679642
M-----------------------------------------------------EN----
----------------------------------------------------GGV-----
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------VGGGRPE
DRAGENGGVPE------AEESAVKTVAA-----EEEGGVDVVVEGGDDAVAAQDG-----
----------D--GDEVGEENRG---PGGGAVESGAAGTPLTGDHQ--PVVTPNTRVVLE
TGQRAAEK---WDEAS----------PRAEIDIEESIAS----DVNQESA----------
---------------------------------------------------------DEN
AMGQAIREY--VTAAVLADRTKGKRLEKDMKSSAEPAVVVEELDGLSSSDDENTATSAPP
AQ--STSSSSTPAQSNSAVSGRSNGPSLPS-----------RPAGLGSSS----------
------------------------------------------------------------
------------------------------------------------------------
----------------SLLQPPARPVQQVRFNGSAS-----LATESAEDDGDGNDEIHEK
--------------------LQMIRVKFLR------------------------------
--------------------------------------------LAHRFGQTPHNMVVSQ
VLYRL--------GLAEQLR-RTTAN--GSFSFDRAREMAERLEAAGNEPLDFSCTI---
------------------------------------------------------------
--------------------------------------------LVLG------------
--------------------KTGVGKSATIN---SIFDDTRL------------------
----DTNAFDFSTRKVQEVVGTVEGIRVKVIDTPGLSCSSLEQ-----------------
-----------------------------------------------------------H
HNQKVLNSVKRLISK------------------NPPDIVLYFDRLD--------------
-------------------MQSRDNGDVPLLQTITKVFGASVWFNAIVVLTHAASAPPDG
LN------------GIPLSYEMFVTQRSHVVQQAI-------------------------
------------------------------------------------RQAAGDIRLMNP
VSLVENHAACRTNRAG---------------QRVLPNGQVWKPQLLLL-----CFASKVL
AEANVLLKLQDSNPVGKL-SRTRIPPLPFLLSSLLQSRAPLKLPEEQFGDDDDLE---DD
SAD---------------------------------------------------------
----------------------------------------------DCDSDDDSDYDDLP
PFKRLTKAQLSKLNK----------AQQKAYLEELDYREKLFYRKQLKEERMRRKLMKKM
AAEASTRANDFNNSNSEDDPN-TPTNVAVPMPDMVLPSSFDSDNPSHRYRFLDTPSEWLV
RPVLETQGWDHDVGYEGLNVERLFAVKGKVPLSISGQLTKDKKDCSMQMEVASSVKHAEG
KTTSLGLDLQSVGKDMAYTIRGESRFKNFRRNNTAAGISATLLGDSVSAGVKIEDKLIVN
KQLRVLVGGGAMSGRGDVAYGGRLEATLRDKDYPIGRMLSTLALSVVDWHGDLAIGCNIQ
SQIPAGRASNLVGHANLSNKGTGQVGIRLNSSEHLELALVALVPIFQNIRKLLQNYSEST
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
