>gnl|BL_ORD_ID|6113 @Selaginella_moellendorffii@_170624|PACid:15407391
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------DYF-------------
------------------------------------------------------------
PDKKPEDDENEKHE-----EVDYKKPEEAGNEKHGEADVIGSAAEAVRSQEEREPVPETD
SDEEEEEEVDTSAALRAFAQAAAATETPSLGSAGPSLPAKPTATRLLSSIEGARNTQVAA
HNPSGGSETTTAVEAADTNGEPNDENVETREK-LQMIRVKFLRLAQRLGQSANNAV----
------------------------------------------------------------
------------------------------------------------------------
-------VAQVLYRLGLAEQLRGGRSSS-------------------------RNSAFRF
ERASAIAEEQEAAGQ-EELDF-----------------TCTIMVLGKSGVGK--------
------------------SATINSLF-DEA------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------KTETNAFAYSTKKVQEITGTV
-HGIK--------------------------LRVIDTPG-------------------LL
PAVADQRHNEKIMASVKRFIKKSPPDIV-------L------------------------
-----YFDRLDMQSRDYGDLPLLRTITDTFGAAIWFNAIVVLTHASSAPPDGPNGLPLSY
EMFVAQRSHVVQQTIRQAAGDMRLMN--PVSLVENHSACRTN--RSGE------------
-RVLPNGQVWKPQLLLLCFASKILAEANSLLKLQESTPG---------------KPF-MR
SKVPPLPFLL----SSLLQSRPPLKHSDENAVGED---------------DTDDDIEDVE
DSDEE-DYDELPPFRRLTRDELDQLDKSSRDEYFEELQMREKLFQKKQWKEEIRRRREMK
KRAAS-SDSAEEYPAPVDDGYDDDNKSAPV-PVPLPDMQLPPTFDSDNPVHRYRYLETAS
QWLVRPVMDLHGWDRDSGYDGFNMERMFTYG-KIPASLSGQVTKDKKEANVTLECAASMK
HGE--------------------GK--------VSQAGFDVQTVGKDFSYTLRSETRFSN
FKKNKTIAGLA------------MTMIGDTLAYGMKIEDRLMIGRRVKVVMNGGALT---
------------GKGDTAYGGTVEISLRDKDFPLGRSLSTCGLSVMNWHG-DMALGGNLQ
SQFMVGKTM-V----------VARGNLNNRGAGQ-----------------------ITI
RLSSSEQLQIALIGVMPLIKALFN------------SKFGTGQQA---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
