>gnl|BL_ORD_ID|9830 @Volvox_carteri@_Vocar20012343m|PACid:23133716
MPS---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------LPARPKGGLGGLPPRGLP
ALSSKSASPQSSSPPAPSAGPSAA------------------------------------
------------QPAAAASGSAPPIASMPKLPPRPGAPSGLGL-----------------
--------GLGLGARPAAGAPRP---------------------PSEGVPAAAATPAAAE
TA---PAAAAAAAPPGVQQP--------------------------------------AA
AAAAGPAGLGLGLGGAAAQRPTLPPRPATAGTATSSAAAAAQPRPAGAQSVGGAAAAAGG
V-----RAMPGLPP--RPAGLGGAPPAPAAAAAATAGAAAAATPSMDVVDRTEDRRV---
---QRVQRTAHEIRVRLIRAATRL-GLSPR----SDQVAQFLQAIERSERMVGAQHYKGT
RRVDLIAAAEREARELDSREPPHSPIAGLRLKILVLGMTGTGKSELINSLLDRPASSRTS
PFREATRR-------VRVIRGHHNGIPLTFIDTPGLHA---------SVSCTAENKAILR
SIKAAYNCFKPDYVFYVDRLDAPRPGLG-----------------ELGVLSLIAEALG--
---PGVWRNTMAVLTHAHAARAAF------------GGQYDINSRQRRNIITQLLRQVAG
DQQSR---NPVFLVDCHPS--------------------CPTNS-LGQQVIQEGPSAVPW
KQQLLGQTVGYKSYNAAAAVFKELAKSKAGKSAAAGGARG----------PQDIFKQLMR
SRLPPMTFFVEQMTEGVLKPEGWA-------------TMESVAGLGDEVTEDEEAESFGH
MYYQHMYDLAMSGDPWAQREYAAMLRSYDKAQETFKASYEEADLDHAIE-----------
------------------------------------------------------------
------------------------------------YGIESYVVDP---------IDFGP
SFDPEDLYSYRHA----YAEAADSAITVIPSQDYYGPEHEDPLNG------FVMQYESQP
FARHGWGGVPFDLSVCVEKDKTSLCLQGETHLTVVHSVPPFGPRQVTQLTGSWEMLRPNI
KDVMYQLEVDTFKDGLLGRNDHAGCGMMLAR-----------------------------
---------------------------LGEG-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------GNPRKGPVAVGVRVQDTFRLGAFKVEACASKVAVQGPTGGKEEGWGA
RAFVMYDWLPGVGIALDAIQEKGSEESGKRQRGYGINVTYDWEMLGA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------AFGAEFDYVAASKSL------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------YVSVN
AFSGNDYRLAWVLLLPALGSDEIEWETLGS------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------VWARLRAAGGGAGQEEEAGEEEA--------------------
-------------------------------------------------GEEEYDEEDED
EGVAAMMAQAADM
