>gnl|BL_ORD_ID|15727 @Vitis_vinifera@_GSVIVT01024062001|PACid:17832352
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------YTPVDEGVSASGTGR--------------SPSVEDSAI--------------
------------------------EKSEMEQCAIED----STIEKSETKQGVTSELAAAD
NISPQPERAVENVA-------EVKNKYVVFEEQETKEPNMEKEDQKIQGNR---------
----EREIRPAEQV--ASSSGRSSNPGPPPA------HPAGLGRAAPLLEPASRVVQQPR
VNGTTSQVQAQLIEDAGNGEAEENDETREKLQM----------------IRVKFLRLAHR
LGQTPHNVVVAQVLYRLGLAEQLRGRNGGR-------------VGAFSFD---RASAMAE
QLEAA-----GQEPLDFSCTI----M----------------------------------
--------------------------------------------VLGKTGVG--------
---------------------------------------KSATINSI----FDE-VKFST
DAFQVGTKKVQDVVG---------------------------------------------
---------------------------TV--QGI-------------KVRVIDTP-----
------------------------------------------------------------
------------------------------------------GLLP-SWSDQRQ--NEK-
-ILHSVKRFIKKTPPD---------IVLYL---------------------DRLDMQSRD
FGD---------------MPLLRTITEIFGPSIWFNA-----IVVLTHAASAPPDGPNGT
ASSY---------DMFVTQRSHVVQQAIRQAAGDMRLM-----NPVS-------------
----------------------LVENHSA--CRTNRAGQRVLPN----------------
----ANTLLKLQDSPPGKPFTTRSRSPPLPFLLSSLLQSRPQVRLPEEQ-----------
----------------------------------------------------------KE
RRKMMKKMAASSKDLPSDYSENAEEESGGAASVPVPM-------------PDWALPASFD
SDNPTHRYRYLDSSNQWLVRPVLETHGWDHDVGYEGINVERVFAIKDKIPVSFSGQVTKD
KKDANLQMEIASSVK---------------------------------------------
---------------HGEGKATSVGFDMQTVGKDMAYTLRSETRFCNFRKNKATAGLSIT
ALGDAITAGLKLEDKLIVNKRIRLVMTGGAMTGRGDVAYGGSLEATLRDKDHPLGRSLST
LGLSIMDWHGDLAIGCNIQSQIPIGRFTNMIGRVNLNNRGAGQVSIRLNSSEQLQIALIG
LVPLLRKLLGY----SQQGQSSCFLIVYAFGMNCKIPGMYQKGLSFFLYLYSWITSAGAN
ETLGSMLLGYVNICNTYESFS
